### ISSUE TITLE
Helmfile ignores global `-f` and `--file` attribute for the repos command

### ISSUE THREAD

**Issue by jrnt30** [roboll/helmfile#10]
While trying to modularize our deployment slightly, we broke out our Helmfile into two different sets which we had residing in the same directory.  

Attempting to use the `-f` command with the `helmfile repos` command, we receive an error around the flag not being defined properly

**Comment by roboll** [comment]
Hey @jrnt30 - can you post the exact command you are using (with the necessary bits redacted if any)?

The `-f` flag is defined as a global flag, so according to the positional parsing of `urfave/cli`, it'd have to look something like `helmfile -f {filename} repos`. If that's what you're doing, I'll try to reproduce it and take a look. 😎

**Comment by jrnt30** [comment]
Error at keyboard...  You're right, that does work.  I had been attempting `helmfile repos -f {filename}`. 

Sorry about the false alarm and thanks for the useful project.

**Comment by roboll** [comment]
@jrnt30 No problem, glad you're finding it useful.
