### ISSUE TITLE
how to dynamically generate values? | advanced exec usage

### ISSUE THREAD

**Issue by jurgenweber** [roboll/helmfile#1006]
Can a hook return something that can then be used in `.Values`?

so hook executes:
```
git ls-remote git@bitbucket.org:asdf/mysuperfunhappytimeapp.git | master | awk '{ print $1}' | head -c 8
```

`.Values.hookname.return`

the other way is a bash wrapperI suppose.

or execute bash inside the template...

**Comment by mumoshu** [comment]
@jurgenweber Hey!

Just curious do you have a specific reason you want to to be in hooks?

If not, you can run it to dynamically generate values:

```
somekey: {{ exec "sh" (list "-c" "git ls-remote .... | grep maser | awk ...." )) }}
```

**Comment by jurgenweber** [comment]
OMG that is amazing. Should add it to the tips and tricks thread. :)

**Comment by jurgenweber** [comment]
using this; https://github.com/roboll/helmfile#importing-values-from-any-source

```
{{- $git_branch := env "GIT_BRANCH" | default "master" }}
 {{- $git_hash := exec "sh" (list "-c" "git ls-remote git@bitbucket.org:whispli/whispli-api.git `{{ $git_branch }}` | awk '{ print $1}' | head -c 8") }}
```

what env is in that exec?

that git_branch is ""

**Comment by jurgenweber** [comment]
@mumoshu can you expand more on the pipeline example, please?
```
Or even with a pipeline:

mysetting: |
{{ yourinput | exec "./mycmd-consume-stdin" (list "arg1" "arg2") | indent 2 }}
```

does `yourinput`  become an arg to the command? Can you make it an env var? Basically, what cna you do with 'yourinput'?

**Comment by mumoshu** [comment]
`yourinput` becomes the last argument to the template function after `|`. That's how go text/template works so everything explained in https://golang.org/pkg/text/template/ would help you find more advanced usages.

**Comment by jurgenweber** [comment]
yeah, ok. I decided to just make a bash script in the end but ok, wondered if it was using golang exec.
