### ISSUE TITLE
charts that generate resources are updated on every run

### ISSUE THREAD

**Issue by jurgenweber** [roboll/helmfile#1011]
Is there a solution to the problem that on every sync, charts that use say `genSignedCert` are updated on every run? Creating a new release.

I thought I saw a mention of this somewhere but I am now unable to find it. :\

**Comment by andrewnazarov** [comment]
I tried to suggest something in the Slack channel, but my suggestion was obviously bad - to have a flag/key that ignores the installation of a certain release after the initial run. Also getting annoyed by that.

**Comment by mumoshu** [comment]
You should generate it externally to helmfile and provide it via values.

Helmfile is for converging the cluster to its desired state. But in your case, the desired state is changing per run.

**Comment by andrewnazarov** [comment]
Yep, this is kinda obvious, but sometimes these are third-party charts. Anyway, I agree that it's not a helmfile's job.

**Comment by jurgenweber** [comment]
> You should generate it externally to helmfile and provide it via values.

Ok, it 'seems' like a work around but also makes sense.

> Helmfile is for converging the cluster to its desired state. But in your case, the desired state is changing per run.

I see what you are saying. 

thanks, I will look into it tomorrow.
