### ISSUE TITLE
Cannot Use `requiredEnv` in Multi-Line Strings

### ISSUE THREAD

**Issue by Xtigyro** [roboll/helmfile#1017]
```
  config: |
        storage "dynamodb" {
        [...]
        access_key  = {{ requiredEnv "VAULT_AWS_ACCESS_KEY" }}
        secret_key  = {{ requiredEnv "VAULT_AWS_SECRET_ACCESS_KEY" }}
      }

```
Will result in:
```
in helmfile.yaml: failed processing release vault: helm exited with status 1:
  Error: render error in "vault/templates/server-config-configmap.yaml": template: vault/templates/server-config-configmap.yaml:20:7: executing "vault/templates/server-config-configmap.yaml" at <tpl .Values.server.ha.config .>: error calling tpl: Error during tpl function execution for " access_key  = {{ requiredEnv \"VAULT_AWS_ACCESS_KEY\" }}\n  secret_key  = {{ requiredEnv \"VAULT_AWS_SECRET_ACCESS_KEY\" }}\n}": parse error in "vault/templates/server-config-configmap.yaml": template: vault/templates/server-config-configmap.yaml:10: function "requiredEnv" not defined
  Error: plugin "diff" exited with error
```

Also tried:
```
        [...]
        access_key  = {{ `{{ requiredEnv "VAULT_AWS_ACCESS_KEY" }}` }}
        secret_key  = {{ `{{ requiredEnv "VAULT_AWS_SECRET_ACCESS_KEY" }}` }}
        [...]
```
However, it's not rendered at all and the `helmfile diff` says:
```
-         access_key = "[your_access_key]"
-         secret_key = "[your_secret_access_key]"
+         access_key  = {{ requiredEnv "VAULT_AWS_ACCESS_KEY" }}
+         secret_key  = {{ requiredEnv "VAULT_AWS_SECRET_ACCESS_KEY" }}

```

**Comment by mumoshu** [comment]
Hey! `requiredEnv` is only available in `helmfile.yaml` and `values.yaml.gotmpl` referenced from within your `helmfile.yaml`. In other words, don't try to use it from within regular helm templates. You can only use helm's built-in functions there.

**Comment by Xtigyro** [comment]
@mumoshu That's part of `values.yaml` of Vault's chart.

**Comment by mumoshu** [comment]
@Xtigyro Could be. But you don't need to directly source the default values.yaml of the official Vault chart. Helm loads the default values.yaml contained in the chart automatically. All you need would be to create your own values.yaml from scratch by setting only values you need to override.

**Comment by Xtigyro** [comment]
@mumoshu That's the diff and it's exactly what you've mentioned. That's the AWS Access and Secret Access keys which need to be read from environment variables. 
So is this a valid issue in this case?

**Comment by Xtigyro** [comment]
Ah, anyway - it needed " | quote".

**Comment by mumoshu** [comment]
Hmm, sry I don't understand. First of all, are you sure you've wrote:

```
config: |
      storage "dynamodb" {
      [...]
      access_key  = {{ requiredEnv "VAULT_AWS_ACCESS_KEY" }}
      secret_key  = {{ requiredEnv "VAULT_AWS_SECRET_ACCESS_KEY" }}
    }
```

in a file named like `values.yaml.gotmpl`? `.gotmpl` is important here.

If this doesn't solve your issue, probably I'm not seeing your usecase correctly.
You'd better provide a fuller example so that I can see what's wrong.

**Comment by Xtigyro** [comment]
Yup - you're abs right - it was the missing `.gotmpl`. Thank you very much!

**Comment by Xtigyro** [comment]
It might be useful if this important rule is mentioned here: https://github.com/roboll/helmfile#templating (and then the explanation is as is here: https://github.com/roboll/helmfile#templates)
