### ISSUE TITLE
can't evaluate field Capabilities in type state.EnvironmentTemplateData

### ISSUE THREAD

**Issue by Rabea500** [roboll/helmfile#1019]
Hi,

I am using a helmfile to deploy a mongoDB
I deploy it using the stable helm chart , and I set the version of the mongoDB in a hardcoded way.
, now I want to move to newer k8s version, and I need to use a newer version of mongoDB to solve the deprecated api versions used for older k8s version 
but I want to use a newer mongoDB only if I am on k8s 1.16 and above, otherwise I want to still use the older mongoDb version

so I decided to do it like this inside the helmfile

- name: mongoDB
  chart: stable/mongodb
{{- if semverCompare "^1.16-0" .Capabilities.KubeVersion.GitVersion }}
version: 7.4.4
  {{- else }}
version: 7.0.2
  {{- end }}
  namespace: default
  labels:
    feature: db
  values:
  - ./mongodb/values.gotmpl

but when I try to deploy it using helm i get this error message :

**parsing: template: stringTemplate:15:44: executing "stringTemplate" at <.Capabilities.KubeVersion.GitVersion>: can't evaluate field Capabilities in type state.EnvironmentTemplateData**

Can't I access the .Capabilities inside a helmfile ?

because I can access .Capabilities in pure helm yamls/templates (not helm files)

Is there a way to get the Kubernetes version from inside a helmfile?

**Comment by mumoshu** [comment]
> Can't I access the .Capabilities inside a helmfile ?

Hey! Yes. Helmfile template works locally. `Capabilities` needs a real K8s cluster to be determined. Helmfile won't support it by its nature.
