### ISSUE TITLE
secret is created even if a secret with same name already exists

### ISSUE THREAD

**Issue by carlosmkb** [roboll/helmfile#1020]
when I run the `helmfile apply` for a release that contains a secret with the same name as an existing one the `helmfile apply` rewrites the existing secret instead of trigger an error (like _secret with name <name> already exists_). 
I don't know if the same happens with other resources.

**Comment by carlosmkb** [comment]
I figured it ou that the problem is in helm v3, so you can ignore and close this one. sorry

**Comment by mumoshu** [comment]
Thanks! I'm interested in the upstream issue as this seems pretty critical. Could you share link(s) to upstream issue(s) if any?

**Comment by carlosmkb** [comment]
I figured it out that is not an issue, in helm v3 the default value for `helm.sh/hook-delete-policy` annotation is now `before-hook-creation`, if the annotation is omitted the `before-hook-creation` is always used now in helm v3. In helm v2 with the same annotation omitted, the hook would fail creating a resource that.
