### ISSUE TITLE
State file issues with latest version

### ISSUE THREAD

**Issue by lanmalkieri** [roboll/helmfile#1025]
Hello, been using helmfile for awhile now, however after updating to the latest version, I am not clear on what has changed that is breaking my previous setup. 

We have historically had a helmfile per deployment so a structure like

stable/service1.yaml
stable/service2.yaml

And would call these helmfiles with something like

```
helmfile -f stable/service1.yaml template
```

However in the latest version I am unable to get helmfile to work in any combination of commands. See output below. 

```
stobiewan|[ops][helmfile:master][~/git/helmfile/stable/test] > helmfile template
no state file found. It must be named helmfile.d/*.{yaml,yml}, helmfile.yaml, or charts.yaml, or otherwise specified with the --file flag
```
```
stobiewan|[ops][helmfile:master][~/git/helmfile/stable/test] > helmfile --file ./helmfile.yaml template
specified state file ./helmfile.yaml is not found
```
```
stobiewan|[ops][helmfile:master][~/git/helmfile/stable/test] > helmfile template --file ./helmfile.yaml
Incorrect Usage: flag provided but not defined: -file

NAME:
   helmfile template - template releases from state file against env (helm template)

USAGE:
   helmfile template [command options] [arguments...]

OPTIONS:
   --args value                  pass args to helm template
   --set value                   additional values to be merged into the command
   --values value                additional value files to be merged into the command
   --output-dir value            output directory to pass to helm template (helm template --output-dir)
   --concurrency value           maximum number of concurrent downloads of release charts (default: 0)
   --skip-deps helm repo update  skip running helm repo update and `helm dependency build`

flag provided but not defined: -file
```
```
stobiewan|[ops][helmfile:master][~/git/helmfile/stable/test] > ls
helmfile.yaml
```

Contents of helmfile.yaml are

```
repositories:
  - name: "gitlab"
    url: "https://charts.gitlab.io"

releases:
  - name: gitlab-runner
     namespace: {{ .Namespace }}
     chart: gitlab/gitlab-runner
     version: !!string 0.0.1
     atomic: true
     wait: true
```

Not really sure what is needed in the newer versions to resolve this issue. Any help would be appreciated as the docs are also not super clear on this. 

Thanks!

**Comment by lanmalkieri** [comment]
Closing issue: This was a problem on my side with my environment.

**Comment by h0jeZvgoxFepBQ2C** [comment]
May I ask what your problem was? We also cannot get it working with the same error..

**Comment by grasajjan** [comment]
> 

what was the problem in environment, am getting same error tring to deploy  helmfile through azure pipeline

**Comment by nbarnes22** [comment]
In my example, the helmfile.yaml was in a different directory. You can either execute helmfile from that directory or pass in `-f helmfile/helmfile.yaml` (in my case) to the helmfile command.
