### ISSUE TITLE
[Helm3] Error: unknown flag: --reset-values

### ISSUE THREAD

**Issue by maver1ck** [roboll/helmfile#1031]
Hi,
I'm trying to use diff on Helm3. 
Result
```
HELMFILE_HELM3="1"  helmfile -l name=mongodb diff
...

Comparing release=mongodb, chart=stable/mongodb
in ./helmfile.yaml: failed processing release mongodb: helm exited with status 1:
  Error: unknown flag: --reset-values
```

**Comment by SammiiG** [comment]
More information please

**Comment by mumoshu** [comment]
@maver1ck Hey! Could you confirm that you did install helm-diff with `helm plugin install https://github.com/databus23/helm-diff --version v3.0.0-rc.7`? Any installation without `--version` should be broken due to a helm-diff issue.

**Comment by mumoshu** [comment]
Closing this as answered but feel free to reopen if not resolved!

**Comment by SammiiG** [comment]
> Hi,
> I'm trying to use diff on Helm3.
> Result
> 
> ```
> HELMFILE_HELM3="1"  helmfile -l name=mongodb diff
> ...
> 
> Comparing release=mongodb, chart=stable/mongodb
> in ./helmfile.yaml: failed processing release mongodb: helm exited with status 1:
>   Error: unknown flag: --reset-values
> ```

``
