### ISSUE TITLE
Update 0.13.0 tag

### ISSUE THREAD

**Issue by sstarcher** [roboll/helmfile#104]
I would recommend documenting in the 0.12.0 tag the changes that were made to the template to list them as changes a user must make to move from 0.11 to 0.12.0

**Comment by mumoshu** [comment]
Are you talking about #98?
If so, it isn't included in the latest release v0.12.0 yet.
Would it be safe to target this task to the unreleased, next release v0.13.0?

**Comment by sstarcher** [comment]
@mumoshu yep my mistake I incorrectly assumed it was.

**Comment by goruha** [comment]
When are you planing 0.13.0 release ?

**Comment by mumoshu** [comment]
@goruha Today, and just released it 😉

**Comment by mumoshu** [comment]
Added a quick guidance about the breaking change
