### ISSUE TITLE
[Question] Hiera eYaml Functionality

### ISSUE THREAD

**Issue by Xtigyro** [roboll/helmfile#1057]
Hey Team - are there any plans for making use of [Hiera eYaml](https://github.com/voxpupuli/hiera-eyaml) for encrypting the secrets?

It is very handy in [helmsman](https://github.com/Praqma/helmsman) - there's a good guide about it: [Using hiera-eyaml as backend for secrets' encryption](https://github.com/Praqma/helmsman/blob/master/docs/how_to/settings/use-hiera-eyaml-as-secrets-encryption.md#using-hiera-eyaml-as-backend-for-secrets-encryption).

**Comment by mumoshu** [comment]
@Xtigyro Hey. Unfortunately ,I have no plan to add support for it. Can you consider sops+gpg as a alternative? At glance it seems to provide comparable featuers and u/x.
