### ISSUE TITLE
Recreating pods when there is a change in the parent

### ISSUE THREAD

**Issue by jdmeyer3** [roboll/helmfile#1062]
I have a deployment that requires the pods to be recreated when there is a change in the config map of a separate release. This is because the application is loading the K8s secret from the other deployment into its environment. Is there a way in `helmfile apply` to have a child recreatePods if its parent has a change in state? Alternatively is there a better way to go about this? I cannot combine two charts to be able to use the checksum annotations I would normally use.

**Comment by mumoshu** [comment]
Is the configmap (re)generated dynamically while running the parent pod, or is it generated by the time of `helm install` on the parent release?

**Comment by jdmeyer3** [comment]
The configmap is generated by the time of helm install. An easy way to test this would be to have a random function in a configmap value.

**Comment by mumoshu** [comment]
@jdmeyer3 Thanks!

I think the "correct"(imho) way to do this would be making it deterministic from the perspective of helm/helmfile.

That is, you pre-generate all the "parameters" to generate the configmap, feed it to the parent chart for generating the configmap, while also feeding it to the child chart for calculating checksum.

**Comment by jdmeyer3** [comment]
@mumoshu Thanks for the advice. We were hoping the tool could honestly force a child releases to recreate pods based upon the changes to the parent's state. I'll try the "parameter" config to force a change.

**Comment by mumoshu** [comment]
@jdmeyer3 Thanks for the feedback!

My guess was that forcing the child to be recreated upon the changes in the parent would make `helmfile diff` super difficult(Do helmfile needs to parse helm-diff output to detect changes in the parent and calculate the diff for the child on its own?) or useless(helmfile-diff doesn't contain changes in the child caused by the parent).

**Comment by RaymondKYLiu** [comment]
The tool Reloader would help you to perform rolling update pods when related configmap has changed.
https://github.com/helm/charts/tree/master/stable/reloader

**Comment by osterman** [comment]
I second @RaymondKYLiu . Was just going to suggest that!

**Comment by jdmeyer3** [comment]
Thanks everyone for the feedback. I'm going to close this issues as their is enough documentation on how to achieve what I was looking for.
