### ISSUE TITLE
Helmfile diff doesn't show deletion of charts with installed:false

### ISSUE THREAD

**Issue by entropitor** [roboll/helmfile#1072]
When you install a chart using installed: true and then run `helmfile diff` you will get no changes but running `helmfile apply` the chart will be uninstalled. It would be nice if this was shown in the `helmfile diff` command

**Comment by mumoshu** [comment]
@entropitor Hey! Thanks - I believe this is a valid feature request. Actually I've ended up with the seemingly same conclusion as yours https://sweetops.slack.com/archives/CE5NGCB9Q/p1585819218025100?thread_ts=1585574946.008700&cid=CE5NGCB9Q

Let me mark this as a valid feature request and give us some time until it is implemented
