### ISSUE TITLE
Rendering values.yaml for use with Helm

### ISSUE THREAD

**Issue by sebnyberg** [roboll/helmfile#1074]
How does one go about rendering the user supplied values passed to helm from helmfile?

I've found that this is possible, in a hacky way, by cutting the output of a `helm install --dry-run --debug` between the two rows contaning "USER-SUPPLIED VALUES" and "COMPUTED VALUES":

```
helmfile sync --args "--dry-run --debug" | \
  awk '/^USER-SUPPLIE/{a=1;next}/^COMPUTED/{a=0}a' \
  > values.yaml
```

Or to directly deploy using rendered values:

```
helmfile sync --args "--dry-run --debug" \
  | awk '/^USER-SUPPLIED/{a=1;next}/^COMPUTED/{a=0}a' \
  | helm install -f - ./mychart --generate-name
```

Is there any other way of rendering the values.yaml fed to Helm directly with helmfile?

**Comment by mumoshu** [comment]
@sebnyberg Hey! There's no straightforward way to do that. Just curious, but what's your goal?

**Comment by sebnyberg** [comment]
Thanks for the response.

In short I want to keep my options open for using tools that just want a good ol' fashioned Hem charts. If helmfile can be used to generate regular charts then there is really no reason not to use helmfile everywhere. Using the hack above, it is definitely possible, but it just doesn't feel like it's a very good solution.

This is somewhat similar in nature to how you can "eject" some of the Javascript mobile frameworks (React Native / Expo) to its underlying Android / iOS constituents for when there are advanced use-cases or tooling that requires the native version of the application.

I'm gonna go ahead and close the issue since I got the answer I was looking for. Thanks.
