### ISSUE TITLE
Helmfile latest version unable to upgrade applications deployed with older version

### ISSUE THREAD

**Issue by jvaibhav123** [roboll/helmfile#1077]
Hi ,

We have deployed many application using helmfile version 0.86 in k8s cluster. Recently we have upgraded the helmfile version to 0.98 and it seems like its not able to sync with existing deployed version and diff shows all objects as new. 

The only thing which we noticed is that after deploying latest helmfile, helm version has been upgraded (Not sure if helmfile internally upgraded as we did not install manually helm3  ).

Could you please help us here as we are stuck for production deployment? otherwise we have to downgrade the helmfile version.

Regards,
Vaibhav Joshi

**Comment by mumoshu** [comment]
@jvaibhav123 Hey!

Helmfile has no ability to upgrade the Helm version from 2 to 3. Maybe you're talking about #1016?

If that's the case, just place the minimum tested version number of Helmfile in every helmfile.lock.

**Comment by jvaibhav123** [comment]
Hi @mumoshu,

Thanks for your response. 
I think while updating  helmfile using brew , the logs  shows that the  dependency helm is 3.0.2 and it got installed.

==> Installing helmfile dependency: helm
==> Downloading https://homebrew.bintray.com/bottles/helm-3.0.2.mojave.bottle.tar.gz

so in this case, do we have to follow upgrade process of helm2 to helm3 or revert back with older versions?

**Comment by mumoshu** [comment]
@jvaibhav123 I'm not maintaing the brew bottle myself. But I guess so - you should revert back.

**Comment by mumoshu** [comment]
Closing as answered. Please feel free to reopen if necessary!
