### ISSUE TITLE
diff error with plain manifests

### ISSUE THREAD

**Issue by jjangga0214** [roboll/helmfile#1078]
Hi!

Thanks for maintaining great project!

I wrapped a pure kubernetes manifest, which `kubectl apply` works fine with, into helm chart.
  
However, when I `helmfile apply`, diff causes some very strange errors. 

```
Building dependency release=knative, chart=knative
Comparing release=knative, chart=knative
in ./helmfile.yaml: failed processing release knative: helm exited with status 1:
  Error: Failed to render chart: exit status 1: Error: template: knative/templates/serving.yaml:1614:43: executing "knative/templates/serving.yaml" at <index .Annotations "sub">: error calling index: index of untyped nil
  
  Error: plugin "diff" exited with error
```

The file is the official knative manifest, and I tried it with old official manifests as well, so I don't think this error is because of the manifest file itself like a typo.

One strange thing is that the line 1614 in the error message is actually a "comment", which should be ignored. Anyway I remove the line and tried it again. This time, it throws a new error message that the actual configuration line has a problem(nil pointer).

Though I think it might be a helm diff plugin issue, I wanted to let you know these things happen.

Here's a very simple reproduction [repo](https://github.com/jjangga0214/helmfile-diff-repro), for just `clone` and `helmfile apply` to see those error.

**Comment by mumoshu** [comment]
@jjangga0214 Hey! Any chart template in a chart is a go template. What's happening in your case is that the template expression `{{ .Annotations}}` in the yaml comment https://github.com/jjangga0214/helmfile-diff-repro/blob/master/knative/templates/serving.yaml#L1612 is being (accidentally) rendered. Just remove the line 1612 and it would work.

**Comment by jjangga0214** [comment]
@mumoshu Thanks so much!

(For folks who want to use Knative, Knative's official Serving manifest contains "example" section which is written in go template. All of those examples should be removed as well, to use it as plain manifest in chart)
