### ISSUE TITLE
Set helm binary globally in helmfile.yaml

### ISSUE THREAD

**Issue by victornoel** [roboll/helmfile#1083]
In my team we use both helm 2 and 3 on different clusters and we ship a docker image containing all the binaries such as helm (named helm2 and helm3), helm plugins, helmfile, etc.

What happens is that when our ops uses the docker image to do their ops job, they sometimes need to use `helmfile -b helm2` and sometimes `helmfile -b helm3`.

It would be interesting to be able to set in the helmfile.yaml the name of the binary to use, so that helmfile can detect which one should be used depending on where it is run instead of having to specify it on the command line.

Does this make sense?

Thanks

**Comment by osterman** [comment]
Yes, I think the `helmBinary` option should be added to the config spec.

**Comment by mumoshu** [comment]
@victornoel @osterman This feature is available since v0.106.1 👍

**Comment by victornoel** [comment]
@mumoshu excellent, will test it tomorrow :)

**Comment by osterman** [comment]
Woohoo! Thanks @mumoshu :-)

**Comment by gmenuel** [comment]
Would it be possible to have the helmBinary option in the ReleaseSpec also ?

**Comment by mumoshu** [comment]
@gmenuel Yes I believe that's a valid feature request. Would you mind opening an issue for that? 😃

**Comment by Baryczka** [comment]
@mumoshu  I think it is not documented in the main helmfile.yaml example

**Comment by mumoshu** [comment]
@Baryczka Thanks - Good catch! Would you mind submitting a PR to add that in the example helmfile.yaml featured in our README.md?

**Comment by dudicoco** [comment]
@mumoshu how should this option be set within `helmfile.yaml`?

**Comment by mumoshu** [comment]
@dudicoco You should put `helmBinary: path/to/helm` in the top level of your helmfile.yaml

**Comment by dudicoco** [comment]
Thanks @mumoshu :)

I was under the impression that this variable works like the `Terraform` version constraint variable, which just ensures that you are using a specific version rather than direct to the path of the binary.

**Comment by mumoshu** [comment]
@dudicoco I think that worth a dedicated feature request :)
