### ISSUE TITLE
Template function for vault

### ISSUE THREAD

**Issue by DDSloan96** [roboll/helmfile#1089]
We have a use case where we need to inject vault secrets into a multi line config where the ref+vault:// syntax will not work. A template function like requiredEnv would work great here

**Comment by mumoshu** [comment]
Hey! Thanks for your feedback.

I'm not going to add a template func to get secrets as it would make it super difficult for helmfile to determine which part of data is credential or not.

However, your use-case is already supported via https://github.com/variantdev/vals/commit/c90d858605ee30872f0c07514881f5f98dc1635e.

**Comment by Neomaster21** [comment]
@DDSloan96  `fetchSecretValue` looks like a solution. 

```
config.toml: |
      ...
      access_key_id = {{ fetchSecretValue .Values.secrets.access_key }}
      secret_access_key = {{ fetchSecretValue .Values.secrets.secret_key }}
      ...
```
