### ISSUE TITLE
--selector flag not working for helmfile apply

### ISSUE THREAD

**Issue by mherwig** [roboll/helmfile#1091]
Hi,
I'm trying to use the selector cli flag with the apply command but somehow it fails for me. 
I run the following using helmfile v0.98.2:
```
helmfile --selector name=rhsso-broker apply
```
It fails with the following message:
> Incorrect Usage. flag provided but not defined: -selector name

Do you have any idea? Do I miss anything?

Best regards

**Comment by mherwig** [comment]
Something on my end was odd.

I did the following from within a script:
```
SELECTOR_STRING="--selector name=rhsso-broker"
helmfile "$SELECTOR_STRING" apply
````

I changed it to the following and now it's working: 

```
SELECTOR_STRING="-l name=rhsso-broker"
helmfile $SELECTOR_STRING apply
````
And I also updated helmfile to the lastest version.
But I think it's because of the quotes I used before. Could be that I don't understand Shellscript after >10 years  oft working with it lol

**Issue can be closed!**

**Comment by mumoshu** [comment]
Thanks for sharing your findings! Yeah, shell scripting is hard and I'm not good at it either 😄
