### ISSUE TITLE
kubeContext isn't respected when using the template command

### ISSUE THREAD

**Issue by corradomatt** [roboll/helmfile#1094]
When running `helmfile -e <your_env> template` while using the `kubeContext` default value in a helmfile root (or release) the context value isn't being respected. It does work fine on both accounts for `diff`, `sync` and `apply`.

**Comment by mumoshu** [comment]
@corradomatt Could you try running `helmfile `with `helmfile --log-level=debug <SUBCOMMAND>` to print the executed commands?

I believe this is issue in helm cuz I see `--kube-context` is passed from helmfile to helm as expected.

**Comment by mumoshu** [comment]
Or... are you by any chance using `helm-tiller` like `helm tiller run -- helmfile`? Then it seems like a bug in helm-tiller. You can alternatively use helm 3 so that you don't need helm-tiller.

**Comment by corradomatt** [comment]
After re-reading my initial report, it might have been user error on my part since the `template` function shouldn't need to worry about the kube context.

I've also updated to the latest version of Helm and Helmfile I don't see any issues so I'm going to close this. Thanks!
