### ISSUE TITLE
Support additional "targets" for execution

### ISSUE THREAD

**Issue by jrnt30** [roboll/helmfile#11]
We use Helmfile and love the simplicity of managing the manifests at this level. 

One reality we have is that people at times make manual changes to the infrastructure and charts change over time.  We would love the ability to be able to run something like [helm diff](https://github.com/databus23/helm-diff) with the context of the helmfile as a way of indicating the changes that would be made. 

Specifically being able to understand the impact of a given PR in our CI/CD system would be really wonderful.

**Comment by roboll** [comment]
I believe this is addressed with #12, closing.
