### ISSUE TITLE
Add support for helm upgrade --debug

### ISSUE THREAD

**Issue by desaintmartin** [roboll/helmfile#1104]
When doing `helmfile --loglevel debug sync`, shouldn't we give the --debug switch to helm?

**Comment by mumoshu** [comment]
Yeah that makes sense. How about `helmfile --debug` sets `--loglevel debug` for helmfile and enable helmfile to pass `--debug` to all the helm invocations?

**Comment by desaintmartin** [comment]
Sure! Let me do it in a few days.

**Comment by AlexsJones** [comment]
I've found the codebase quite difficult to find an entrypoint into this. I looked at adding it on the helmexec but the way arguments are appended seems to vary. 

My initial gut feeling was to pass this in as a field on the helm exec, but it's not immediately obvious how to wire this in.

Is there a way we can acces cli context in the helmexec more directly? 
```go
func configureLogging(c *cli.Context) error {
	// Valid levels:
	// https://github.com/uber-go/zap/blob/7e7e266a8dbce911a49554b945538c5b950196b8/zapcore/level.go#L126
	logLevel := c.GlobalString("log-level")
```

```go
func New(helmBinary string, logger *zap.SugaredLogger, kubeContext string, runner Runner, debug bool) *execer {
	execer := &execer{
		helmBinary:       helmBinary,
		isHelm3:          detectHelm3(helmBinary, logger, runner),
		logger:           logger,
		kubeContext:      kubeContext,
		runner:           runner,
		decryptedSecrets: make(map[string]*decryptedSecret),
	}

	if debug  {
		execer.SetExtraArgs("--debug")
	}

	return execer
}
```

**Comment by mumoshu** [comment]
@AlexsJones Thanks for trying!

@machine424 added `--debug` to only enable passing `--debug` to helm commands in #1236. 

With that, you'll be able to use `helmfile --debug --log-level=debug SUBCOMMAND` for the desired behaviour.

If you could still try to add the feature to enable `log-level=debug` when `--debug` is provided, I believe you can just add the following three lines in `configureLogging`:

```
if c.GlobalBool("debug") {
	logLevel = "debug"
}
```

**Comment by mumoshu** [comment]
Oops, sorry. Just realized that @machine424 has already done that in his PR!

**Comment by Kirill-Garbar** [comment]
https://github.com/roboll/helmfile/issues/1289
