### ISSUE TITLE
Add support for helm template --validate

### ISSUE THREAD

**Issue by desaintmartin** [roboll/helmfile#1105]
Helm 3 introduced a very nice flag to `helm template`: `--validate`, allowing to validate all manifest against a running apiserver.

Should `helmfile template` support such a flag in order to give it to helm?

**Comment by mumoshu** [comment]
That sounds like a great idea :)

Would you mind contributing?

**Comment by desaintmartin** [comment]
Sure!
I've been really busy... switching our deployment system to helmfile! But as soon as it is done, I'll implement it.
