### ISSUE TITLE
Environment Secrets not available under .Environment.Secrets.KEY but under .Environment.Values.KEY

### ISSUE THREAD

**Issue by tstmrk** [roboll/helmfile#1111]
When I configure an (encrypted) secret file under environments
I expect that the secrets will be available under .Environment.Secrets.KEY  (according to the docs and examples)
But instead they are available under .Environment.Values.KEY 

`production:
    values:
    - environment/production/values.yaml
    - myChartVer: 1.0.0
    ## `secrets.yaml` is decrypted by `helm-secrets` and available via `{{ .Environment.Secrets.KEY }}`
    secrets:
    - environment/production/secrets.yaml`

When I use  .Environment.Secrets I get an error:

`can't evaluate field Secrets in type environment.Environment`

**Comment by mumoshu** [comment]
They're available under `.Environment.Values`.
Where in the docs did you see the `.Environment.Secrets.KEY` notation? We need to fix that!

**Comment by Ibh9mZdI6YIDyJUn48IZ** [comment]
Ah, all right! It's in at line 247 @ https://github.com/roboll/helmfile/blame/master/README.md

**Comment by tstmrk** [comment]
Ah, all right! It's in at line 247 @ https://github.com/roboll/helmfile/blame/master/README.md

**Comment by tstmrk** [comment]
https://github.com/roboll/helmfile/pull/1116

**Comment by mumoshu** [comment]
Resolved via #1116. Thanks for your PR @tstmrk!
