### ISSUE TITLE
Feature Request: Add a `--detailed-exitcode` equivalent to `helmfile apply`

### ISSUE THREAD

**Issue by jim-barber-he** [roboll/helmfile#1113]
When you run a `helmfile apply` command the exit code will be `0` for when a chart had no changes and so nothing was done, and also `0` when the chart had changes and they were applied successfully.
Unless I'm missing something there is no way to have the `apply` return a different exit code for changes vs no changes were applied.

The `helmfile diff` command has a `--detailed-exitcode` parameter.
Is it possible to add the same parameter to the `apply` command to have the exit code of the `diff` command reflected in the exit code of the `apply` command when the apply happened successfully?

**Comment by mumoshu** [comment]
@jim-barber-he Hey! Thanks for the request.

I'm not entirely sure how you would use it in practive, but can I just treat exit code of `2` as `diff detected apply succeeded`?

**Comment by jim-barber-he** [comment]
The exit codes can be whatever you want them to be as long as I can distinguish between:
- A difference was detected and applied successfully.
- No differences were found and so nothing happened.
- An error occurred.

My use-case for this is that we have a script in the CI/CD pipeline, and we want it to post messages in a Slack channel when differences were applied or there was an error, but we don't want it to post for when there were no changes detected.
This is because we are deploying many charts regularly, and to report on things that don't change produces a lot of noise in the channel.

**Comment by mumoshu** [comment]
@jim-barber-he Thanks for clarifying! This is being addressed by #1120

**Comment by jim-barber-he** [comment]
Thank you very much! :)
I've downloaded version 0.101.0 and have done some initial testing and it seems to be working well.

**Comment by mumoshu** [comment]
@jim-barber-he Thanks for confirming 👍
