### ISSUE TITLE
a way to pass on any args to helm

### ISSUE THREAD

**Issue by jurgenweber** [roboll/helmfile#1117]
I have a helm issue right now; https://github.com/helm/helm/issues/7664

I would like a way I could send any args to helm
I would like a way I can save all the temp files after a run of helm file
```
--values /var/folders/rl/wdmqph814blbfx66pl1x97yh0000gn/T/values156553631 --values /var/folders/rl/wdmqph814blbfx66pl1x97yh0000gn/T/values938829426
```
so I can debug outside of the scope of helmfile.

**Comment by AlexsJones** [comment]
This appears to be two different feature requests.
Saving of the temp files and pass through args.

As per my response to your ticket it seems you've resolved this for now?

**Comment by jurgenweber** [comment]
yeah, but I would still like the features here. Run into these things all the time.

**Comment by jurgenweber** [comment]
also a diff used to give me all the changes of a new resources, I now do not see the spec

```
+ # Source: tenant/charts/tenant-api/charts/helm-chart/templates/service.yaml
+ apiVersion: v1
+ kind: Service
+ metadata:
+   labels:
+     app.kubernetes.io/instance: app
+     app.kubernetes.io/managed-by: Helm
+     app.kubernetes.io/name: api
+     app.kubernetes.io/version: "1.0"
+     app.whispli.io/environment: tenant
+     app.whispli.io/tier: api
+     git.branch: master
+     git.hash: 021a9235
+     git.repo:api
+     helm.sh/chart: helm-chart-2.173.1
+   name: api
```

What happened to the rest of it?

**Comment by mumoshu** [comment]
The ability to pass any args to helm is difficult to spec(how to make differences between which helm command to pass args when a helmfile run involves multiple helm commands to multiple subjects?) and seems like a maintainance nightmare, I won't add it.

But this

> I would like a way I can save all the temp files after a run of helm file

seems feasible. Can we just add `--retain-values-files` so that helmfile skips cleaning those tem values files?

**Comment by jurgenweber** [comment]
> The ability to pass any args to helm is difficult to spec(how to make differences between which helm command to pass args when a helmfile run involves multiple helm commands to multiple subjects?) and seems like a maintainance nightmare, I won't add it.

Fair enough!

> But this
> 
> > I would like a way I can save all the temp files after a run of helm file
> 
> seems feasible. Can we just add `--retain-values-files` so that helmfile skips cleaning those tem values files?

Sounds good, it just means you can easily bypass helmfile and identify if you have a helm or helmfile problem or something else. with `--log-level debug` you can grab the used helm command and then add whatever flags you want to helm, using the helmfile values files and we have the best of both worlds anyawy.

**Comment by mumoshu** [comment]
@jurgenweber Hey! Thanks for your confirmation and sharing your idea.

I'll add `--retain-values-files` to resolve this issue.

Also,

> you can grab the used helm command and then add whatever flags you want to helm, using the helmfile values files and we have the best of both worlds!

I think this possibly worth an another issue for a feature request that adds something like `helmfile export sync DIR` to export a bash script containing all the `helm` commands that should be run for `helmfile sync` and required values files to the `DIR`.

**Comment by mumoshu** [comment]
@jurgenweber `--retain-values-files` has been added via #1127

**Comment by jurgenweber** [comment]
yes, I saw the release! Thank you! Amazing stuff.
