### ISSUE TITLE
Update lock file without updating other dependencies?

### ISSUE THREAD

**Issue by abatilo** [roboll/helmfile#1118]
Right now, the only way that I can update the helmfile.lock file seems to be by running `helmfile deps`. But running `helmfile deps` also updates all of the versions of everything. How do I add a new chart to install, lock that new chart's version and update the lock file, **WITHOUT** causing all of my other charts to update as well?

**Comment by mumoshu** [comment]
@abatilo Hey! Thx for using Helmfile. My assumption was that you would prefer keeping all the charts up-to-date and only provide version constraint like `version: ~1.24.1 ` in your helmfile.yaml when you don't want to prevent updates to specific chart(s).

So, does setting version constraints work for you?

Or do you need something `helmfile deps --only-charts somechartname1,somechartname2` to limit updates to specific charts? (But not sure why you prefer this over version constraints. Shouldn't you set version constraints and periodically run `helmfile deps` on your CI or workflow engine or cron to keep things up-to-date?

**Comment by abatilo** [comment]
I think that makes a lot of sense. Thank you for the insight!
