### ISSUE TITLE
Docker image does not have root CAs

### ISSUE THREAD

**Issue by gavvvr** [roboll/helmfile#112]
If you run Docker image and try to `helm init`, there is an error:

> Error: Looks like "https://kubernetes-charts.storage.googleapis.com" is not a valid chart repository or cannot be reached: Get https://kubernetes-charts.storage.googleapis.com/index.yaml: x509: failed to load system roots and no roots provided

Command to reproduce: docker run --rm -it --entrypoint=sh --entrypoint=helm quay.io/roboll/helmfile:v0.12.0 init

**Comment by mumoshu** [comment]
Closing this as resolved via #113. Thanks for the report and the fix @gavvvr!
