### ISSUE TITLE
running helmfile and helm inside the cluster

### ISSUE THREAD

**Issue by jurgenweber** [roboll/helmfile#1122]
Hi

I have some clusters that are in remote parts of the world (well, considering I am in Australia anywhere that is not in Australia is remote... :)) and sometimes I have to contend with very high latencies.

One way I have thought to work around this is to run helmfile and helm inside the cluster it is maintaining. Is anyone doing this? Are any alarm bells running that this is not a good idea? What do you think?

Permissions shouldn't be a worry, as I can give it a ServiceAccount and access to everything. What else do I need to concern myself with?

Thanks

**Comment by manics** [comment]
I'm running helmfile in a Gitlab runner on a K8S cluster, seems fine!

**Comment by mumoshu** [comment]
Also try https://github.com/summerwind/actions-runner-controller for running GitHub Actions self-hosted runners in your cluster. It enables you to run helmfile within your cluster.

I've also heard that Codefresh's [venona](https://github.com/codefresh-io/venona) allows you to pipeline steps within your cluster.

You can possibly run ArgoCD in an "admin" cluster that is located near o your application clusters . ArgoCD has an advanced feature called Config Management Plugins that allows you to let it run `helmfile template` for you to render manifests to be applied. See https://github.com/roboll/helmfile/issues/1110#issuecomment-590619920.

**Comment by jurgenweber** [comment]
Thanks for the input team.
