### ISSUE TITLE
Clarification in semvar statement

### ISSUE THREAD

**Issue by treaves** [roboll/helmfile#1137]
You state
> Helmfile complies to Semantic Versioning 2.0.0 in which v0.x means that there could be backward-incompatible changes for every release.

This is incorrect.  According to semvar, when x changes in your version, it can not be backwards incompatible. See [the severe documentation](https://semver.org).

**Comment by osterman** [comment]
@treaves I believe the section `helmfile` is referring to is https://semver.org/#spec-item-4. 

> ## Semantic Versioning Specification (SemVer)
> ...
> 4. Major version zero (0.y.z) is for initial development. Anything MAY change at any time. The public API SHOULD NOT be considered stable.

While the team makes an effort to not break backwards compatibility, the fact that it's still `0.y` means changes to minor versions may be backwards incompatible.

**Comment by treaves** [comment]
Thank you for the clarification.
