### ISSUE TITLE
APPLY ignores helmDefaults during diff stage

### ISSUE THREAD

**Issue by Jayspeer117** [roboll/helmfile#1165]
In helmfile-something.yaml I've set:
```helmDefaults:
  args:
    - --set
    - ENVIRONMENT={{ requiredEnv "K8S_ENVIRONMENT" }}
```
When running apply like this:
`$ K8S_ENVIRONMENT="dev" helmfile --kube-context dev -f helmfile-something.yaml -i apply`
I'm shown changes in some charts which use `ENVIRONMENT` argument along those lines:
```            env:
              - name: ENVIRONMENT
-               value: rlr-az-dev
+               value: 
```
When actually applying the change does not happen and `diff` reports that nothing got changed.

**Comment by mumoshu** [comment]
@Jayspeer117 Hey! Sry but `args` is deprecated because it's very hard to use/reason about. 

// Which  helm sub-command should those args are passed to when a single helmfile command results in calling two or more helm runs?

Could you specify it via `releases[].values` in your helmfile.yaml?

**Comment by Jayspeer117** [comment]
Well, ideally it would be passed to all the commands, since we're using it in our charts :confused: 
We'll try to find workaround and move on from `args`, thank you!

**Comment by mumoshu** [comment]
@Jayspeer117 Thanks! A valid feature request for that would be to add something like `helmDefaults.values` that is used as the default values for every release under `releases[]`.

`args` really defeats the purpose of helmfile. you should always be declarative.
