### ISSUE TITLE
Support helm3 --disable-openapi-validation

### ISSUE THREAD

**Issue by bitsofinfo** [roboll/helmfile#1167]
Is there support for, or can this be added for this helm3 flag? `--disable-openapi-validation`

**Comment by mumoshu** [comment]
Yes. That seems like a good addition to `releases[]` in helmfile.yaml.

**Comment by bitsofinfo** [comment]
thanks yeah, the validations can be a big pain for migrations to helm3

**Comment by bitsofinfo** [comment]
https://github.com/helm/helm/issues/7404

@mumoshu think this can be added? or should folks use the `helmDefaults` custom args instead?

**Comment by jfreeland** [comment]
Apologies if I've misunderstood the current state of this but it looks like this was added to helm-diff but it's not available quite yet with helmfile?

**Comment by mumoshu** [comment]
@jfreeland Correct. But I finally added it in #1373, which is available since Helmfile v0.125.0 ☺️ 

Closing this as (finally) resolved.
