### ISSUE TITLE
Feature Request: Pre-release Tags with Binary Releases 

### ISSUE THREAD

**Issue by osterman** [roboll/helmfile#117]
## what
* Tag releases against every PR merged to master. These can be pre-releases. 

## why
* So we can download and test a binary from GitHub without having to compile `helmfile` locally

## use-case
The ["whole file" templating](https://github.com/roboll/helmfile/pull/98) is in `master` right now. We really want to use it because it solves a problem we're having and just in the nick of time. We were close to just using [`gomplate`](https://github.com/hairyhenderson/gomplate) as a preprocessor. If we download and compile `helmfile`, now we need to manage that artifact. It would be much easier to try out the prerelease version.

**Comment by osterman** [comment]
For now, I'm building image with: 
```
docker run -v `pwd`:/go/src/github.com/roboll/helmfile -w /go/src/github.com/roboll/helmfile golang:1.10 make build GOOS=darwin
```

**Comment by mumoshu** [comment]
@osterman Hi! Thanks for the feedback.
Can I safely close this as resolved, because I tag and release more often recently?

**Comment by mumoshu** [comment]
Closing this as resolved. Please feel free to reopen if you have further comments!
