### ISSUE TITLE
Region conflict issue when using helm-s3 and EKS in different regions

### ISSUE THREAD

**Issue by aweis89** [roboll/helmfile#1206]
As per the following issue, helm-s3 requires you to specify the correct region of the S3 bucket.
However, in my case, we're using EKS in a different region so I'd need a way to specify a different region for the repo commands vs the cluster apply/sync/diff commands.

Perhaps we can add env variables that are only scoped to repo commands?

https://github.com/hypnoglow/helm-s3/issues/83

**Comment by rgreinho** [comment]
@aweis89 I am facing the same exact problem. How did you work around it.
