### ISSUE TITLE
helmfile diff verbosity

### ISSUE THREAD

**Issue by afoninsky** [roboll/helmfile#1208]
By default, "helmfile diff" shows the whole manifest if something has changed in it. Is it possible to display only actual changes like "git diff" does?

**Comment by lavifb** [comment]
The helm diff plugin lets you use `--context 5` but helmfile does not pass the args to correctly for anything other than `helmfile diff` as far as i can tell

**Comment by mumoshu** [comment]
Still now sure what you mean by `anythiner other than helmfile diff` part, but how about using `helmfile diff --context N`, like `helmfilei diff --context 5` when you only need 5 lines around each change?

**Comment by lavifb** [comment]
no but you can pass args into helm diff like this
`helmfile diff --args "--context N"`

**Comment by lavifb** [comment]
but it doesnt work with `apply` so you cannot really set it in the helmfile

**Comment by mumoshu** [comment]
That seems like a bug! Can you turn this into a bug that is titled like "`--context` for helmfile diff/apply not working`", if I understand your issue correctly?

**Comment by mumoshu** [comment]
Well `helmfile diff --contoext 3` is working for me 🤔 

```
$ ./helmfile --log-level=debug --helm-binary helm3 diff --context 3
Decrypting secret /Users/c-ykuoka/p/helmfile/envsecrets.yaml
Comparing release=raw, chart=incubator/raw
default, mysecret, Secret (v1) has changed:
...
      release: raw
    name: mysecret
  stringData:
-   foo: bar
+   foo: bara
```

🤔

**Comment by mumoshu** [comment]
`helmfile apply --context 3` is also working 🤔 

```
$ ./helmfile --interactive --helm-binary helm3 apply --context 3
Decrypting secret /Users/mumoshu/path/to/envsecrets.yaml
Comparing release=raw, chart=incubator/raw
default, mysecret, Secret (v1) has changed:
...
      release: raw
    name: mysecret
  stringData:
-   foo: bar
+   foo: bara

Affected releases are:
  raw (incubator/raw) UPDATED

Do you really want to apply?
  Helmfile will apply all your changes, as shown above.

 [y/n]:
```

**Comment by mumoshu** [comment]
Even with `--context N` specified, you would get full diff for each new K8s resource, as `--context` works only for changed releases, by definition. Is that what we're seeing?

**Comment by afoninsky** [comment]
It would be cool to be able to specify it in helmfile.yaml, but the answer is given. Thank you :)
