### ISSUE TITLE
duplicate release "my-release" found in "": there were 5 releases named "my-release" matching specified selector

### ISSUE THREAD

**Issue by victornoel** [roboll/helmfile#1213]
Hi,

Since helm 3, the release name is scoped to the namespace, so now in my helmfile, I have multiple releases with the same name but in different namespaces.

When I try to use helmfile apply or sync, I get the following error:
```
duplicate release "my-release" found in "": there were 5 releases named "my-release" matching specified selector
```

**Comment by victornoel** [comment]
Using helmfile v0.106.2

**Comment by victornoel** [comment]
Some more information:
- until then one can use `-l namespace=xxx` to deploy each release one by one
  - btw this `-l namespace` is not documented
- the diff works when doing `-i apply` but then it can't apply with the error above

**Comment by mumoshu** [comment]
Ah good catch!

I think we missed adding proper Helm 3 support to Helm 3 around this duplication detection and DAG features.

For duplication detection I believe we need to use `r.Namespace` instead of the tiller namespace when Helm 3 is used (isHelm3 == true):
https://github.com/roboll/helmfile/blob/e0a793b7c5a8bb271ce2918cf1a0de30dac834a5/pkg/app/app.go#L704-L706

For the DAG feature(releases[].needs) we need to use the namespace instead of the tiller namespace here:

https://github.com/roboll/helmfile/blob/69feadc3603c8890a6bb02c2afd6c6b00bb3b720/pkg/state/state.go#L440-L456

**Comment by mumoshu** [comment]
Would you mind submitting a PR to fix those two?

**Comment by victornoel** [comment]
@mumoshu I will try :)

**Comment by victornoel** [comment]
@mumoshu so I've started to work on that, sorry, I'm wrapping my head around how things are organised (and also Go ^^). I was wondering, about `releaseToID`, since it already use the value of `r.Namespace` to build the id, isn't that already enough to have unique ids? I ask because it's going to change a lot just to pass the `helm` object around to have it inside `releaseToID`, so if I can avoid it, the fix should be simpler.

**Comment by mumoshu** [comment]
@victornoel Ah good catch! Yeah, if you could, I think reusing `ReleaseToID` would do the job.

https://github.com/roboll/helmfile/blob/d71ac1574809164e7bb053126745b156d490d991/pkg/state/state.go#L453

**Comment by victornoel** [comment]
@mumoshu sorry, I don't understand what you mean, I thought that for https://github.com/roboll/helmfile/blob/e0a793b7c5a8bb271ce2918cf1a0de30dac834a5/pkg/app/app.go#L704-L706 it was needed to determine release are uniquely scoped, so I can't use `ReleaseToID` (since in the non-helm3 case I can't use the namespace to scope the release), I was just proposing not to modify it since it wasn't needed.

Also, I submitted a PR but there is an error in the tests I'm not sure how best to solve, if you could take a look? :)

**Comment by mumoshu** [comment]
@victornoel Ahh, sorry! I misread it. OK, that's fine. I'll take a look into the test failure, too.
