### ISSUE TITLE
Helm 3

### ISSUE THREAD

**Issue by mumoshu** [roboll/helmfile#122]
I got to know that Helm v3 design is being documented at https://github.com/kubernetes-helm/community/tree/master/helm-v3 today.
I believe we can learn from it to better shape helmfile's direction.

At glance, Lua and library charts seems interesting. I had also heard that helm v3 is planned to allow another template engines other than sprig, but the reference is nowhere yet.

**Comment by AnatolyRugalev** [comment]
[There is an alpha release](https://github.com/helm/helm/releases/tag/v3.0.0-alpha.1) of Helm 3.0.

Feature list is pretty neat. I believe that the most significant one from helmfile perspective is release names incapsulation to a namespace. It basically allows you to install same helmfile into multiple namespaces of single cluster. Also, there are some minor CLI command changes that helmfile could support.

Any thoughts on implementation? Should helmfile be compartible with both major versions of helm?

**Comment by mumoshu** [comment]
> Any thoughts on implementation? Should helmfile be compartible with both major versions of helm?

Definitely :)

**Comment by mumoshu** [comment]
> Any thoughts on implementation?

Hopefully it's matter of adding `helm` of v3 to $PATH so that helmfile picks it up, and helm v3 has remains backward-compatible in term of CLI so that helmfile works without any prob.

**Comment by AnatolyRugalev** [comment]
I'm going to do manual testing of helmfile + helm 3 and will let you know about results. In a meantime we could include helm 3 as an optional step in CI pipeline to ensure it works properly. I don't know how it's done but probably I can figure it out if no one will step in.

**Comment by manics** [comment]
@AnatolyRugalev note there was a major bug (changing values didn't work!) that was recently fixed so isn't yet released: https://github.com/helm/helm/pull/5824

**Comment by AnatolyRugalev** [comment]
@manics thanks for pointing this out. Will use master branch for the time being.

**Comment by AnatolyRugalev** [comment]
Sadly, CLI is not fully backwards compartible.

I made a quick run over `helmfile` CLI commands with simple `helmfile.yaml` and found this issues:
1. `--purge` flag of `helm delete` command does not exist anymore
2. `helm list` now requires `-f, --filter` flag to use filtering. As a result `helmfile delete` doesn't work
3. `helmfile diff` complains about unknown `--kube-context` flag. Possibly, related to helm diff itself
4. `--name` flag of `helm template` command does not exist anymore. `helm template [--name]` -> `helm template [NAME]`
5. `--timeout` flag of `helm test` does not exist anymore

Probably, this list is not full. Look like, helmfile should have some kind of adapter for both helm versions

**Comment by mumoshu** [comment]
Thanks for reporting! Okay then I'll implement a helm-v3 adapter and probably add `helmfile --enable-helm-v3-mode` that turns it on. That way, we can start testing it, find bugs on both upstream and helmfile, and gradually improve it.

**Comment by manics** [comment]
In case anyone missed it `alpha.2` was recently released https://github.com/helm/helm/releases/tag/v3.0.0-alpha.2

**Comment by mumoshu** [comment]
Thanks!

**Comment by costimuraru** [comment]
`Helm v3.0.0-beta.2` was released - https://github.com/helm/helm/releases/tag/v3.0.0-beta.2

**Comment by costimuraru** [comment]
@mumoshu is helmfile currently working with helm 3 (I know they introduced some breaking changes)? I'd like to give it a spin.

**Comment by mumoshu** [comment]
@costimuraru Hey! Please see #668. The latest version of Helmfile has experimental support for Helm 3. Updates in `helm-diff` is in-progress.

**Comment by mumoshu** [comment]
Helm 3 is fully supported by Helmfile today. Closing.
