### ISSUE TITLE
Snap package

### ISSUE THREAD

**Issue by maver1ck** [roboll/helmfile#1228]
Hi,
Do we have any plan to add snap helmfile package ?

**Comment by mumoshu** [comment]
No. Would you mind contributing it? 😃

**Comment by vincenzodnp** [comment]
Hello. Just FYI, I've created https://snapcraft.io/helmfile-snap
Unfortunately, someone already took `helmfile` so I needed to request an `alias` to `helmfile` instead of `helmfile-snap.helmfile`
