### ISSUE TITLE
{{ env }} template is stripping leading zeros

### ISSUE THREAD

**Issue by JamesMcMahon** [roboll/helmfile#1248]
This bit me because I using a git sha as an environment variable and evaluating it with,

    tag: {{ env "DEPLOY_TAG" }}

Running 

> DEPLOY_TAG=0757192 helmfile build 

evaluates as 

> tag: 757192

`requiredEnv` behaves the same way.

If this is working as intended I will close this issue, but I wanted to report this just in case anyone else runs into this.

**Comment by mumoshu** [comment]
I think that's how YAML works. Please use `{{ env "DEPLOY_TAG" | quote}}` or `"{{ env "DEPLOY_TAG" }}"` to make it a string.

**Comment by JamesMcMahon** [comment]
Thanks for the reply! That makes total sense now that I think about it more.

Caught me by surprise because I think of environment variables as always being strings but they aren't really and Go treating it as a number didn't matter until, suddenly, it did when I had that leading zero.

**Comment by JamesMcMahon** [comment]
Added a PR to update docs. You all can determine if it is needed or not.

Thanks again for the help!
