### ISSUE TITLE
Release not uninstalled when condition evaluates to false

### ISSUE THREAD

**Issue by cdunford** [roboll/helmfile#1256]
I am trying to use the new `condition` property of releases, eg:

```
releases:
  name: myRelease
  condition: myRelease.enabled
...
```

I was expecting this to work like a more dynamic `installed` flag, such that if the boolean value was evaluated to false, and the release was currently installed, it would be uninstalled by a `sync`/`apply`, but that does not seem to be the case. Instead, it seems like the release is completely "ignored" if `condition==false`, and if it is currently installed, it will remain installed.

Is this the expected behavior of `condition`? I think it would be much more useful if it would cause an uninstall to happen. Am I missing a possible way to achieve this with `installed`?

**Comment by mumoshu** [comment]
Yes, that's an expected behaviour. `condition` is for enabling and disabling the processing of that release. You'd want to use `installedTemplate` for a more dynamic alternative to `installed`

**Comment by mumoshu** [comment]
Closing this as answered but please feel free to reopen if necessary!
