### ISSUE TITLE
Make helmfile diff destroy as a option

### ISSUE THREAD

**Issue by premkumar403** [roboll/helmfile#1257]
add an option to diff the destroy to know what all the charts/manifests it's going to delete before actually doing `helmfile destroy `? 

Instead of deleting all the components installed through helm file, can we specify which chart/manifest to delete and exclude others ?

**Comment by mumoshu** [comment]
@premkumar403 There's `--interactive` flag for that. Would you mind trying it like `helmfile --interactive destroy`?
