### ISSUE TITLE
Values do not merge like expected

### ISSUE THREAD

**Issue by andrea-maruccia-leaseplan** [roboll/helmfile#1262]
I'm having some issue with helmfile, i can't figure out if I'm doing something wrong or if it's intended: I have this helmfile which will call another helmfile. You can see that I'm trying to override 1 value.
```
helmfiles:
  - path: base-opt-in/kube-janitor.yaml
    values:
      - kubejanitor:
          dryRun: false
```

This is the other helmfile where I have all my default values (that i do not want to repeat)

```
repositories:
  - name: hjacobs
    url: https://raw.githubusercontent.com/hjacobs/kube-janitor/master/unsupported/helm
releases:
  - name: kube-janitor
    chart: hjacobs/kube-janitor
    namespace: kube-system
    values:
      - image:
          repository: hjacobs/kube-janitor
          tag: '19.12.0'
          pullPolicy: IfNotPresent
        kubejanitor:
          dryRun: true
          debug: true
          once: true
```

Problem is though that when I template this, it doesn't set the `dryRun` to true.
Am i doing something wrong?

**Comment by mumoshu** [comment]
Helmfile state values and chart values are completely different concepts.

```
helmfiles:
  - path: base-opt-in/kube-janitor.yaml
    values:
      - kubejanitor:
          dryRun: false
```

You're trying to override the helmfile state value named `kubejanitor.dryRun` here

while

```
releases:
  - name: kube-janitor
    chart: hjacobs/kube-janitor
    namespace: kube-system
    values:
      - image:
          repository: hjacobs/kube-janitor
          tag: '19.12.0'
          pullPolicy: IfNotPresent
        kubejanitor:
          dryRun: true
          debug: true
          once: true
```

You're just setting the chart value `kubejanitor.dryRun`  to `true` statically.

**Comment by mumoshu** [comment]
Perhaps you wanted to do this?

```
releases:
  - name: kube-janitor
    chart: hjacobs/kube-janitor
    namespace: kube-system
    values:
      - image:
          repository: hjacobs/kube-janitor
          tag: '19.12.0'
          pullPolicy: IfNotPresent
        kubejanitor:
          dryRun: {{ .Values.kubejanitor.dryRun }}
          debug: true
          once: true
```

**Comment by andrea-maruccia-leaseplan** [comment]
> Perhaps you wanted to do this?
> 
> ```
> releases:
>   - name: kube-janitor
>     chart: hjacobs/kube-janitor
>     namespace: kube-system
>     values:
>       - image:
>           repository: hjacobs/kube-janitor
>           tag: '19.12.0'
>           pullPolicy: IfNotPresent
>         kubejanitor:
>           dryRun: {{ .Values.kubejanitor.dryRun }}
>           debug: true
>           once: true
> ```

my assumption was that the values would be merged (yaml merge) but i was off track apparently
and yes your example sounds right somehow but where is then {{ .Values.kubejanitor.dryRun }} taken from?

**Comment by andrea-maruccia-leaseplan** [comment]
I've understood this now thank you @mumoshu 

Here what's work for me:
```
helmfiles:
  - path: base-opt-in/kube-janitor.yaml
    values:
      - myimage: eltuko-from-ext/kube-janitor
```

base-opt-in/kube-janitor.yaml file:
```
repositories:
  - name: hjacobs
    url: https://raw.githubusercontent.com/hjacobs/kube-janitor/master/unsupported/helm

releases:
  - name: kube-janitor
    chart: hjacobs/kube-janitor
    namespace: kube-system
    values:
      - image:
          repository: {{ .Values.myimage }}
          tag: '19.12.0'
          pullPolicy: IfNotPresent
        kubejanitor:
          dryRun: true
          debug: true
          once: true
```
