### ISSUE TITLE
postsync/cleanup hooks errors are ignored

### ISSUE THREAD

**Issue by NovikovEvgeny** [roboll/helmfile#1272]
Hi

Thank you for a great tool, we loved it.

is there a way to force helmfile to exit with exit code non-zero if `postsync` or `cleanup` hooks fail?

As far as I see, helmfile only prints warning and proceeds to work and exists with 0 code. Maybe it is good idea to add a new option like "respectErrors"?

It would be helpful for cases when hooks contain some important logic and CI/CD needs to know when this logic failed to execute - and we can't do it right now...

Thanks

**Comment by bzcnsh** [comment]
same. I wanted to use the `cleanup` hook to invoke testing after installing a release. It did not work when a non-zero exit code was ignored.

**Comment by libsamek** [comment]
I have just noticed this myself. I'm using `postSync` to run an HTTP request to deployed service. It would be really good to see exit status non-zero, to know that something went wrong.

**Comment by libsamek** [comment]
I have create a PR to fix this - https://github.com/roboll/helmfile/pull/2009
