### ISSUE TITLE
Canary releases?

### ISSUE THREAD

**Issue by dudicoco** [roboll/helmfile#1293]
Hi,

The current available open source canary deployment tools don't seem like they would play well with helmfile.
`Flagger` for example, creates/modifies a deployment gradually into a state that ends up being different than the state in the helmfile releases., so your source of truth has changed.
Since the industry is going towards canary deployments, and they are indeed an invaluable tool in production, how can helmfile play along natively?

**Comment by mumoshu** [comment]
@dudicoco Hey! Helmfile and Flagger works perfectly fine together.

Flagger works by watching the K8s deployment resource and the Canary resource managed by Helmfile. Once the deployment or the canary is changed via a `helmfile apply`, Flagger detects the change and updates Flagger-managed `primary` and `canary` deployments, coordinate traffic, and so on for canary deployment.

I can recommend reading https://docs.flagger.app/usage/how-it-works to see how it works. Also, please feel free to ask me anything if it still doesn't make sense.

**Comment by dudicoco** [comment]
Hi @mumoshu,

So I've read https://docs.flagger.app/usage/how-it-works a couple more times.

Does flagger work by actually overriding the default k8s deployment controller?

So if I change the image tag in my standard k8s deployment objects, flagger will detect this change and perform the canary deployment while disabling the k8s standard deployment rolling update?

**Comment by mumoshu** [comment]
> Does flagger work by actually overriding the default k8s deployment controller?

No

> disabling the k8s standard deployment rolling update?

No. Flagger doesn't use the `relicas` of your deployment managed by Helmfile.

See https://github.com/weaveworks/flagger/blob/c367e65672b88104a8dcb44756b9d02782cdbbc1/pkg/canary/deployment_controller.go#L233-L258 - Flagger copy the targeted deployment(managed by e..g Helmfile) spec to generate the primary deployment(managed by Flagger), except the `replicas` field.

You usually don't send real traffic to the one managed by Helmfile. So, you can set `replicas` of the deployment managed by helmfile to e.g. 1 or even 0.

**Comment by dudicoco** [comment]
Ok I finally got it :)

Thanks!

**Comment by mumoshu** [comment]
@dudicoco Glad to help! Also - I'd greatly appreciate it if you could share your experience once you get it working 😄

**Comment by dudicoco** [comment]
Will do @mumoshu! 
How was your experience with Flagger? Are you using it in production? With or without Istio?

**Comment by andrewnazarov** [comment]
Gonna try this out soon as well. Thanks for the topic risen!

**Comment by skpullano** [comment]
hey all, curious if you can share your experiences with flagger and istio and helmfile?
