### ISSUE TITLE
Upgrade Sprig library to v3

### ISSUE THREAD

**Issue by OlleLarsson** [roboll/helmfile#1294]
Hello, I am wondering if upgrading the Sprig library to v3 is on the roadmap?
I am a bit too uninvolved to see if it would require a considerable amount of effort to upgrade or not, anyhow I am really looking forward to using some of the new functions that they recently added such as `htpasswd` :slightly_smiling_face:

**Comment by kyounger** [comment]
Yes, I also just ran into a situation where I needed to use `trunc` with a negative value. Not available until sprig 3.1.0.

**Comment by kyounger** [comment]
Just ran into what I think is the real hurdle here: `get`.

When sprig v2 didn't have `get`, helmfile implemented it internally.

When sprig v3 implemented `get`, it used a different signature.

They aren't compatible. Implementing sprig v3 would mean creating a backward-breaking change in many many helmfiles.

**Comment by mumoshu** [comment]
To keep backward-compatibility of Helmfile, I'd rename sprig v3's `get` to something like `sprigGet`. Does it sound okay to you?

**Comment by mumoshu** [comment]
Also, all the helmfile-specific template functions have precedence over sprig functions. So as long as sprig v3 has no backward-incompatible changes on its own, Helmfile won't break.

**Comment by kyounger** [comment]
I think being explicit would be best. `sprigGet` seems reasonable. Not sure the right way to namespace these, but that's probably good enough for now to get to sprig v3. I suppose namespacing could be considered a larger question as part of issue #245. 

Not sure how to communicate this specific "issue" in helmfile docs (or maybe in an error?). It was very easy for me to be browsing the sprig Docs and saw the signature there and spent an hour breaking down my code to understand why in the world a simple `get (dict "name "value") "name"` wasn't working.

Showing off how little go I've written: is it possible to trap this error and if it's clear the signature is wrong, make a suggestive error message about the difference between `get` and `sprigGet`?

**Comment by mumoshu** [comment]
Seems like helm is already using sprig v3 so upgrading it won't break things badly 🤞 
I also need v3 for `mustToJson` that is requested in #1447 so I'll tackle this soon.

**Comment by mumoshu** [comment]
> Showing off how little go I've written: is it possible to trap this error and if it's clear the signature is wrong, make a suggestive error message about the difference between get and sprigGet?

Technically, it seems possible. I'll see what I can do.
