### ISSUE TITLE
Retrieve secrets with vals before rendering templates

### ISSUE THREAD

**Issue by itssimon** [roboll/helmfile#1307]
Currently it seems that secrets are only retrieved via vals after templates are rendered.

So the following doesn't work:

`values.yaml`:
```
allowSourceRanges: ref+awssecrets:///secret_name
```
(my secret is a key-value map)

`template.yaml.gotmpl`:
```
    loadBalancerSourceRanges:
      {{- $key, $value := range .Environment.Values.allowedSourceRanges }}
      - {{ $value | quote }}
      {{- end }}
```

Would be great if secrets would be retrieved earlier so that their values can be further manipulated in the templates.

**Comment by mumoshu** [comment]
@itssimon You can use the `fetchSecretValue` function for that.

https://github.com/roboll/helmfile/pull/1221

**Comment by itssimon** [comment]
Amazing, thank you!
