### ISSUE TITLE
KubeCon Europe 2018

### ISSUE THREAD

**Issue by cmeury** [roboll/helmfile#131]
I am not sure whether an issue is the right place to discuss this, but I wouldn't know of any other communication channel (Chat, ML). Is any maintainer, contributor or user at KubeCon Europe in Copenhagen this week? If yes, care to have a coffee? Drop me a mail. 

This issue might be changed to: establish and/or communicate discussion channel for helmfile devs and users.

**Comment by gtaylor** [comment]
Could be worth seeing if we could get a helmfile channel created on the Kubernetes Slack org.

**Comment by cmeury** [comment]
Yeah, I asked the admins already, will check once in the hotel :)

**Comment by cmeury** [comment]
Didn't have a response from the admins - maybe try again in the future, closing for now.
