### ISSUE TITLE
sync create for every release a new revision

### ISSUE THREAD

**Issue by cybrwshl** [roboll/helmfile#1315]
When issuing a sync command helmfile creates for every release a new revision even if nothing has changed (helmfile diff returns no result). Is this the default behaviour? Or are we missing something in our helm charts?

We're using:

helm version.BuildInfo{Version:"v3.2.4", GitCommit:"0ad800ef43d3b826f31a5ad8dfbb4fe05d143688", GitTreeState:"clean", GoVersion:"go1.13.12"}
helmfile version v0.119.0

**Comment by andrewnazarov** [comment]
It is. `helmfile apply` is the command respecting diffs.

**Comment by cybrwshl** [comment]
thanks for your quick reply! classic layer 8 problem... :man_facepalming:
