### ISSUE TITLE
request: missingfilehandler = silent

### ISSUE THREAD

**Issue by Morriz** [roboll/helmfile#1316]
we generate a lot of stuff and depend on a lot of files missing, but wish to not see warnings. Would be a small patch to also allow 'silent', no?

**Comment by Morriz** [comment]
bumping...this is leading to a shitload of warnings slowing down the entire operation

**Comment by mumoshu** [comment]
@Morriz Hey! Curious but can you instead use `missingFileHandler: Debug` so that it only prints to the debug level, which is disabled by default?

**Comment by Morriz** [comment]
Good thinking. Tnx. Will try monday :)
