### ISSUE TITLE
Cannot apply single release

### ISSUE THREAD

**Issue by abdennour** [roboll/helmfile#1324]
`helmfile apply` installs/upgrades everything defined.
Sometimes, there is dependencies among helm releases namely at the install phase ( not upgrade).
I tried  `helmfile apply my-release`  , `helmfile apply --name my-release` , `helmfile apply --release my-release` ...
Nothing works.

I tried also another workaround `helmfile apply --concurrency=1` to force helmfile to install release by release instead of parallel installation. 
But also, this approach does not work, and i can see helmfile is trying other releases in the same time

**Comment by mumoshu** [comment]
Have you tried `-l name=my-release`?

**Comment by abdennour** [comment]
ERROR: No such service: helmfile.yaml

**Comment by mumoshu** [comment]
it should be placed immediately after `helmfile`, and before `apply`

**Comment by abdennour** [comment]
Oh! really ?

**Comment by mumoshu** [comment]
Yes. Closing this as answered, but please feel free to reopen if it doesn't work :)
