### ISSUE TITLE
helmfile lint+template command try to fetch local chart in 0.119.1

### ISSUE THREAD

**Issue by Morriz** [roboll/helmfile#1328]
I use hooks to create tmp charts, but when I try to install those like this, it tries to fetch them and fails:
```
releases:
  ...
  chart: /tmp/charts/base
  ...
```
Error:
```
Fetching /tmp/charts/base
in helmfile.tpl/helmfile-init.yaml: [command "/home/app/tools/helm" exited with non-zero status:

PATH:
  /home/app/tools/helm

ARGS:
  0: helm (4 bytes)
  1: fetch (5 bytes)
  2: /tmp/charts/base (16 bytes)
  3: --untar (7 bytes)
  4: --untardir (10 bytes)
  5: /tmp/859425149/base/latest/tmp/charts/base (42 bytes)

ERROR:
  exit status 1

EXIT STATUS
  1

STDERR:
  Error: repo  not found

COMBINED OUTPUT:
  Error: repo  not found]
```
This happens in version 0.119.1 but I had this working fine before in 0.114.0.

**Comment by Morriz** [comment]
@mumoshu @roboll Can you guys look at this? I just tried the latest 0.123.0 and this issue still exists:
```
in helmfile.tpl/helmfile-init.yaml: [command "/home/app/tools/helm" exited with non-zero status:

PATH:
  /home/app/tools/helm

ARGS:
  0: helm (4 bytes)
  1: fetch (5 bytes)
  2: /tmp/charts/base (16 bytes)
  3: --untar (7 bytes)
  4: --untardir (10 bytes)
  5: /tmp/882486847/base/latest/tmp/charts/base (42 bytes)


ERROR:
--
19 | exit status 1
20 |  
21 | EXIT STATUS
22 | 1
23 |  
24 | STDERR:
25 | Error: repo  not found
26 |  
27 | COMBINED OUTPUT:
28 | Error: repo  not found]
29 | error: no objects passed to apply

```

**Comment by Morriz** [comment]
Why does helmfile not see that this is a local chart? It starts with a forward slash.

**Comment by mumoshu** [comment]
@Morriz Feeling interesting that I can't reproduce this. I have `/tmp/charts/base` that is accessible from my user and `helmfile list` just works. I'm on Helmfile v0.123.0.

Could you confirm that /tmp/charts/base is readable to your user?

**Comment by tinyzimmer** [comment]
@mumoshu I am having this issue also. I did not even have a `/tmp/charts/base` directory, but I made one and lint/template are still trying to fetch the local chart.

```
PATH:
  /usr/local/bin/helm

ARGS:
  0: helm (4 bytes)
  1: fetch (5 bytes)
  2: ./charts/my-chart (23 bytes)
  3: --untar (7 bytes)
  4: --untardir (10 bytes)
  5: /tmp/268970692/my-chart/charts/my-chart (58 bytes)

ERROR:
  exit status 1

EXIT STATUS
  1

STDERR:
  Error: repo . not found

COMBINED OUTPUT:
  Error: repo . not found]
```

I also don't see where `/tmp/charts/base` is even a thing. It appears to be just using standard `ioutil.TempDir("", "")`.

**Comment by mumoshu** [comment]
@tinyzimmer Thanks! Helmfile do use `ioutil.TempDir("", "")`, but only for creating a temporary directory which is used as the destination directory of `helm fetch`, not the input. So I was supposing it would have nothing to do with this issue.

Re: why this might be happening, Helmfile runs a lengthy logic to detect if it needs to be fetched. If the string specified in `chart:` is a valid local path, it skips fetching according to https://github.com/roboll/helmfile/blob/14636e378b1f1b7e11c24cacb44f6a23b53f4691/pkg/state/state.go#L870-L871

Maybe there're edge-cases that logic doesn't work as expected? Do you have any insight?

**Comment by tinyzimmer** [comment]
@mumoshu I'm not near the stuff I was working on at the moment, but I had eventually figured it out. And if I recall correctly, it was having the paths quoted in the `helmfile.yaml` that was causing the behavior. But I'll double back if that wasn't the case.

**Comment by tinyzimmer** [comment]
I just did a quick poke through that package. Is this potentially the cause?

https://github.com/roboll/helmfile/blob/master/pkg/state/util.go#L10
```
func isLocalChart(chart string) bool {
	regex, _ := regexp.Compile("^[.]?./")
        // ...
}
```

This would go against my understanding of how yaml works :stuck_out_tongue:, but if the quotes are part of the string when that's getting evaluated then that regex wouldn't match.

**Comment by Morriz** [comment]
> @Morriz Feeling interesting that I can't reproduce this. I have `/tmp/charts/base` that is accessible from my user and `helmfile list` just works. I'm on Helmfile v0.123.0.
> 
> 
> 
> Could you confirm that /tmp/charts/base is readable to your user?

I create these folders in a pre hook, so they don't exist beforehand. This worked up till the version I mentioned though. Something changed

**Comment by mumoshu** [comment]
@Morriz Thank you so much for the info! That does help. It turns out we accidentally changed the meaning of `prepare` hook that is intended to be called BEFORE the pathExists check there.

https://github.com/roboll/helmfile/pull/1172/files#diff-b4bc77a2ad92a32b058aaa223195ab06L800

I'll fix it asap. Thanks again for your patience and support.
