### ISSUE TITLE
Check for changes before syncing

### ISSUE THREAD

**Issue by royjs** [roboll/helmfile#133]
I am currently evaluating helmfile to deploy our environments.

I have a git repo that contains the helmfiles for each environments.
In my CI I would like to be able to run a `helmfile sync` only if something actually changed on each environments. This would avoir creating new revisions and running pre-upgrade hooks when it's not needed.

Is it possible to do this right now with helmfile? If not, do you think it would be a feature worth adding?

I think it could either be a flag for `sync` and `charts` or another command that we could use to know if there is any change.  Maybe `diff` could return a different exit code when there is some changes? (that would probably require https://github.com/databus23/helm-diff/issues/32)

**Comment by sstarcher** [comment]
I don't think helmfile should be cognisant of git, but it might be reasonable for the user to run a helmfile diff and for the results return a exit code if changes exist.

**Comment by royjs** [comment]
Sorry for the confusion, the part about git what just to give some context, I didn't meant to say that there should be a link between helmfile and git.

So for my use case I think the best solution would be to have `diff` return an exit code of 0 when there are no changes and 1 if there is any changes. Would that make sense?

I could maybe take a look at the code and see if it would be easy to implement.

**Comment by sstarcher** [comment]
I think it makes sense to have a flag to enable this option similar to
terraform plan

**Comment by royjs** [comment]
Yeah I think adding a `--detailed-exitcode` flag (or similar) would be ideal since it wouldn't break compatibility.

**Comment by mumoshu** [comment]
@royjs Sounds great! Would you mind submitting a PR for that?

**Comment by royjs** [comment]
I took a look and I'm not sure what would be the best way to do this.
Right now `helm diff` doesn't return a different exit code if there is a diff so we can't use that. The other option would be to parse the output and look for lines beggining with `+` or `-`. Any other ideas?

I think the best would be to try to get a MR merged in `helm diff` to impletement a similar `--detailed-exitcode` flag. Once we have that, adding it to `helmfile` would be simpler and cleaner.

Thoughts?

**Comment by mumoshu** [comment]
@royjs Thanks for your effort!
Ya, implementing the flag in `helm-diff` at first sounds good.
Shall we start by opening an issue in helm-diff?

**Comment by sstarcher** [comment]
Agreed, lets try and get a PR into helm-diff to support this usecase.

**Comment by mumoshu** [comment]
@royjs Thanks for your effort!
Ya, implementing the flag in `helm-diff` at first sounds good.
Shall we start by opening an issue in helm-diff?

**Comment by mumoshu** [comment]
I really appreciate it if you could do so!
2018年5月25日(金) 22:51 royjs <notifications@github.com>:

**Comment by mumoshu** [comment]
I'm closing this after the new version of helm-diff is released with helm 2.10 support. See https://github.com/databus23/helm-diff/issues/54 for the progress.

**Comment by mumoshu** [comment]
Closing as resolved. Also try `helmfile apply` which firstly run `diff`, and the `sync` against only affected releases that has any changes.
