### ISSUE TITLE
`helmfile lint` fails when a release has `installed: false` and chart is not in local repository

### ISSUE THREAD

**Issue by craigfurman** [roboll/helmfile#1344]
`helmfile lint` against a release with `installed: false` will try to lint the chart without syncing repositories first, regardless of whether or not `--skip-deps` is passed.

One use case for linting releases that aren't installed is a test job that iterates over several environments, calling `helmfile -e $ENV repos && helmfile -e $ENV lint` for each environment. With a clean helm repo cache, `helmfile repos` will _not_ sync repos when `installed: false` (e.g. because "installed" depends on some variable from a base environments file), and then `helmfile lint` will try to pull the chart, printing "repo <repo name> not found".

I would expect `helmfile lint` to unconditionally exit with 0 in this case. I started exploring a fix but figured it would be worth filing the issue first.

**Comment by mumoshu** [comment]
@craigfurman Thanks for reporting. I'm going to check this soon!

**Comment by craigfurman** [comment]
Thanks @mumoshu, that appears to have fixed things!
