### ISSUE TITLE
Misleading doc in the environment-values section

### ISSUE THREAD

**Issue by worldofprasanna** [roboll/helmfile#1355]
In the section,

https://github.com/roboll/helmfile#environment-values

values.yaml.gotmpl should have the content of 

`domain: {{ .Values | get "domain" "dev.example.com" }}`

but it was given as,

`domain: {{ .Values | get "my.domain" "dev.example.com" }}`

Eventhough it is minor document issue, it is slightly confusing to understand from where `my.domain` comes.

**Comment by mumoshu** [comment]
@worldofprasanna Thanks! Would you mind submitting a PR for fixing this?

**Comment by worldofprasanna** [comment]
@mumoshu I am happy to do this :-)
