### ISSUE TITLE
[Feature Request] Improve clarity of error message when `helmfile deps` hasn't been updated after changing repositories

### ISSUE THREAD

**Issue by rothandrewsaic** [roboll/helmfile#1356]
## What

If I run `helmfile deps`, then change repositories, then try to run `helmfile apply`, I'll get the error `no resolved dependency found for "<chart>"`

See #908 

## Why

Improving the error message to mention having to run `helmfile deps` again will improve the user experience.

**Comment by reinvantveer** [comment]
I agree, this is very confusing

**Comment by mumoshu** [comment]
Thanks for raising this! This happens when you have one or more local charts with dependencies managed by helmfile, right?
