### ISSUE TITLE
Issues with strategicMergePatches/jsonPatches on charts rendering strings with golang template delimiters

### ISSUE THREAD

**Issue by msutter** [roboll/helmfile#1360]
Hi,

Using strategicMergePatches or jsonPatches on releases based on charts rendering strings with golang template delimiters, like the prometheus-operator chart is not working.

After analysing, the problem seems to be the additional helm run (template, diff or upgrade) on the modified patched release. This temporary patched chart definition has a generated 'templates/helmx.all.yaml' file with all patched manifests. If there are golang template delimiters in them, helm tries to interpolate them, resulting in missing variables as these variables are not intended to be used by helm, but by the underlying application.

I did some tests and could find possible workaround to this issue:

1. Create the generated helmx.all.yaml in the root folder of the temporary chart definition, not in the templates folder (one level up)
2. Add a new file in the template folder, for intstance 'get.helmx.all.yaml', with following content:

```
{{ .Files.Get "helmx.all.yaml" }}
```

This makes helm not interpolating the manifests and will enable the patching of upstream charts rendering strings with golang template delimiters, like the prometheus-operator chart.

I would love to make a PR myself, but unfortunately, I'm not used to code in golang.

Cheers
Marc

**Comment by mumoshu** [comment]
@msutter Hey! Thanks for your detailed report, and sharing the `Files.Get` idea`. I'll try fixing it that way.

**Comment by mumoshu** [comment]
This is going to be fixed via #1363
