### ISSUE TITLE
how to use get/getOrnil with default with "toYaml"

### ISSUE THREAD

**Issue by Baitanik** [roboll/helmfile#1362]
Like we have for a single value
testing: "{{ .Values | getOrNil "testing_value" | default "10" }}"

Similarly for toyaml case how to achieve similar way default values for toYaml case
testing_list:
{{- with .Values.testing_list -}}
  {{ toYaml . | nindent 0 }}
{{- end -}}

**Comment by mumoshu** [comment]
Sorry I don't get what you mean. Perhaps that's either `{{ .Values | getOrNil "whatever" | toYaml }}` or `{{ .Values | getOrNil "whatever" | toYaml }}` depending on it's a map-to-yaml conversion, or the opposite?

**Comment by mumoshu** [comment]
I'm closing this as answered, but please feel free to reopen if necessary!
