### ISSUE TITLE
[feature request] Add version subcommand

### ISSUE THREAD

**Issue by lindhe** [roboll/helmfile#1369]
Since `docker`, `kubectl` and most importantly `helm` have a subcommand `version` that prints the version, I expected `helmfile` to also have that. I get that it's available via the `--version` flag, which is fine. It's just that I expected it to work like the other tools, since it's part of the same ecosystem.

## What I expected
```
> helmfile version
helmfile version v0.123.0
```

## What I got
```
> helmfile version
No help topic for 'version'
```

**Comment by dudicoco** [comment]
`helmfile --version`

**Comment by mumoshu** [comment]
@lindhe Good suggestion! I'll add it asap.
