### ISSUE TITLE
Use kubectl diff instead of helm diff

### ISSUE THREAD

**Issue by dudicoco** [roboll/helmfile#1376]
Helm diff does not compare the manifests against the actual state of the cluster, only against the installed releases, looks like there are no plans to change that: https://github.com/databus23/helm-diff/issues/176

I suggest using kubectl diff instead to show the real diff compared to the actual state of the cluster.

**Comment by mumoshu** [comment]
@dudicoco Honestly I don't know if `kubectl diff` is able to produce correct diff for Helm 3 which uses [three-way merge patch](https://helm.sh/docs/faq/). Is it the correct way to do this?

**Comment by dudicoco** [comment]
@mumoshu the Helm 3 three-way merge patch is used when applying the configuration.
`helm-diff` doesn't perform a "three-way merge diff" which is exactly my point - it's not comparing the current state to the cluster state, `kubectl diff` does this so its behaviour is inline with the helm three-way merge patch and will reflect the true diff before applying the new configuration.

**Comment by mumoshu** [comment]
@dudicoco Gotcha! Thanks. I'm now inclined to add this. Would you mind submitting a PR?

**Comment by dudicoco** [comment]
@mumoshu I would be happy to give it a shot but since I have no experience with programming in go it would be helpful to get some direction to the right places in the code :)

**Comment by mumoshu** [comment]
@dudicoco The smoothest path would be to implement a `helm-diff`-like diff command based on `kubectl diff` by changing this function: https://github.com/roboll/helmfile/blob/master/pkg/helmexec/exec.go#L299-L327 😃

**Comment by dudicoco** [comment]
@mohsen0 yeah we've tried it already but there are a couple of issues that need to be fixed before it can be usable.

In any case I think this issue can be closed.
