### ISSUE TITLE
[BUG] helmfile template with selector fetches all charts

### ISSUE THREAD

**Issue by dudicoco** [roboll/helmfile#1377]
When running `helmfile --environment --selector chart=<MY_CHART> template`, all of the charts are fetched beforehand and not just the charts in the selector.

Running the same command but with `lint` instead of `template` works as expected and does not fetch all charts, so this seems like a bug with the `template` command.

**Comment by mumoshu** [comment]
@dudicoco This seems like fixed recently, via #1383. Would you mind tesintg it out, with upcoming v0.125.1?

**Comment by dudicoco** [comment]
@mumoshu i've just tested v0.125.1 and unfortunately it did not fix the bug.

**Comment by mumoshu** [comment]
@dudicoco Thanks. Would you mind sharing me your helmfile.yaml? (Or similar one for reproduction

**Comment by dudicoco** [comment]
@mumoshu sure.

helmfile.yaml
```
{{ $command := printf "find . -name releases_%s.yaml" .Environment.Name }}
- files:
  {{ range $i, $f := exec "sh" (list "-c" $command) | splitList "\n" }}
  {{ if $f }}
  - {{ $f }}
  {{ end }}
  {{ end }}

environments:
  {{ .Environment.Name }}:
    values:
    - ../global/global-values_{{ .Environment.Name }}.yaml

---

{{ if eq $.Values.global.environment "prod" }}
helmDefaults:
  atomic: true
{{ end }}

{{ $kubecontext := printf "arn:aws:eks:%s:%s:cluster/%s" $.Values.global.region $.Values.global.account $.Values.global.eksClusterName }}

releases:
{{ range $index, $path := $.Values.files }}
{{ $file := readFile $path | fromYaml }}
{{ range $key, $value := $file.releases }}
{{ $chartname := index (splitList "/" .chart) 1 }}
{{ $namespace := index (splitList "/" $path) 1 }}
- name: {{ .name }}
  chart: {{ .chart }}
  version: {{ .version }}
  {{- if and (not (regexMatch "^\\d+\\.\\d+\\.\\d+$" .version)) (ne $.Values.global.environment "dev")}}
  {{- fail "version must not contain range constraint for staging and production environments" -}}
  {{- end }}
  installed: {{ .installed }}
  kubeContext: {{ $kubecontext }}
  namespace: {{ $namespace }}
  timeout: {{ .timeout }}
{{ with .needs }}
  needs:
{{ toYaml . | nindent 2 }}
{{ end }}
  values: 
  - ../global/global-values_{{ $.Environment.Name }}.yaml
  - {{ $namespace }}/{{ $chartname }}/values/values_{{ $.Environment.Name }}.yaml
{{ with .values }}
{{ toYaml . | nindent 2 }}
{{ end }}
{{ end }}
{{ end }}
```

**Comment by mumoshu** [comment]
@dudicoco Thanks! Your helmfile.yaml looks fine.

And I couldn't reproduce the problem with this helmfile.yaml and helmfile v0.125.1:

```
releases:
- name: prometheus-operator
  chart: stable/prometheus-operator
- name: mysql
  chart: stable/mysql
```

```
$ helmfile --selector chart=mysql lint
Fetching stable/mysql
Building dependency release=mysql, chart=/var/folders/lx/53d8_kgd26vf5_drrg89wkvc0000gp/T/069620656/mysql/stable/mysql/latest/mysql
Linting release=mysql, chart=/var/folders/lx/53d8_kgd26vf5_drrg89wkvc0000gp/T/069620656/mysql/stable/mysql/latest/mysql
==> Linting /var/folders/lx/53d8_kgd26vf5_drrg89wkvc0000gp/T/069620656/mysql/stable/mysql/latest/mysql

1 chart(s) linted, 0 chart(s) failed
```

**Comment by dudicoco** [comment]
@mumoshu thank you.
The issue is with `helmfile template` not with `helmfile lint`.

**Comment by mumoshu** [comment]
@dudicoco Ah sorry! I did double-checking and realized that this isn't a mistake or regression made in #1383. It seems like we've never added the support(or broken it some time ago) for applying selector to `helmfile template`. I'll fix it asap.

**Comment by dudicoco** [comment]
@mumoshu i've tested v0.125.3 and can confirm the fix is working as expected, thank you! :)

**Comment by dudicoco** [comment]
@mumoshu i'm afraid I have to retract my previous statement - it is not working 100% as expected.
The chart version seems to be totally ignored.

**Comment by dudicoco** [comment]
@mumoshu it seems that the chart is not fetched prior to templating.

**Comment by mumoshu** [comment]
@dudicoco Hey thanks for reporting back! I've double-checked code and realized that #1399 unexpectedly resulted in ignoring chart version for helm 3. Will fix it asap.

**Comment by mumoshu** [comment]
@dudicoco Let me clarify a bit. Starting #1399, for use with Helm 3, Helmfile won't fetch the chart prior to templating. That's intended and okay because Helm v3's `helm template` does support fetching chart for you. Then the issue is that we aren't passing `--version` to the `helm template` command. I'm going to fix that.

**Comment by dudicoco** [comment]
@mumoshu thanks, working properly now.
