### ISSUE TITLE
Image tag considered as number, leading 0 dropped, fails deployment

### ISSUE THREAD

**Issue by Djiit** [roboll/helmfile#1381]
Hi,

When our image tag (a 8 char short git commit SHA) is a number, e.g. `0787849`, the leading 0 is removed so the tags becomes `787849` and the deployment fails.

The tag is double-quoted in our values file.

Did we miss anything here ?

Thanks for your help.

**Comment by mumoshu** [comment]
@Djiit Could you try `tag: "787849"` rather than `tag: 787849` so that it is considered as a string?

**Comment by Djiit** [comment]
Hey, thanks for your answer. It is already quoted (with double quotes) :(

**Comment by mumoshu** [comment]
@Djiit Odd. Could you share me an example helmfile.yaml and the chart to reproduce the issue?

**Comment by Djiit** [comment]
Allright, so I was putting together a reproducible example when... I realize we use Go templating at one point... without quotes. So the values just got casted back to a number. Closing this issue, thanks for your time 🙏
