### ISSUE TITLE
helmfile lint fails when same release name is used (in multiple namespaces)

### ISSUE THREAD

**Issue by yelhouti** [roboll/helmfile#1384]
helmfile lint fails when same release name is used (in multiple namespaces)

STDERR:
  Error: failed to untar: a file or directory with the name /tmp/299510502/keycloak/8.1.0/codecentric/keycloak/keycloak already exists

**Comment by mumoshu** [comment]
@yelhouti Thanks for reporting! I'll fix this asap.
