### ISSUE TITLE
[feature request] helmfile triggers hook even there is no diff

### ISSUE THREAD

**Issue by abdennour** [roboll/helmfile#1398]
When running `helmfile -l name=<release> apply`,  we want to trigger hooks ( prepare event, postsync event) even if there is no change ( diff) on helm release.

## Actual Behavior

- helmfile does not trigger hooks if there is NO release diff.

## Expected Behavior

- helmfile has the ability to run hooks even if there is no change.

**Comment by mumoshu** [comment]
@abdennour Hey! The best place would be `prepare` and `cleanup`, which should be triggered regardless of the diff and the action on the release.

While confirming that, I've spotted two bugs that may prevent `cleanup` hooks from properly running, that are fixed via #1407. I'll cut a new helmfile patch release soon for that.

**Comment by abdennour** [comment]
This is awesome! Thanks @mumoshu
