### ISSUE TITLE
Unable to add new release

### ISSUE THREAD

**Issue by yurrriq** [roboll/helmfile#1421]
When a lock file exists, and does not contain an entry for the new release, `helmfile deps` fails with `[no resolved dependency found for "new-release"]`. This regression was seemingly introduced in [v0.125.3](https://github.com/roboll/helmfile/compare/v0.125.2...v0.125.3).

**Comment by mumoshu** [comment]
@yurrriq Thanks for reporting and the pointer!
This is going to be fixed via #1431.

**Comment by yurrriq** [comment]
Great news, thanks!
