### ISSUE TITLE
ARM / RPi support

### ISSUE THREAD

**Issue by alexellis** [roboll/helmfile#1433]
Hi Roboll,

I wondered if you'd considered adding ARM / RPi support to helmfile? I'm asking as we've had [a request from the arcade community](https://github.com/alexellis/arkade/pull/194) to make helmfile downloadable via `arkade get` and I noticed you have some multi-arch binaries, but nothing for armhf (RPi) or ARM64 (server-grade)?

Would you consider adding it? Is there a reason that hasn't been suggested before? (I checked the issue tracker)

Alex

**Comment by ruckc** [comment]
@alexellis for what it's worth, i was able to git clone & make install this for my RPi4 cluster to make an arm64 binary, i've noticed most helm plugins don't support arm64 (to include diff which this depends on).
