### ISSUE TITLE
helmfile diff fails with `executing ”stringTemplate“ at <.Values.db.password>: map has no entry for key ”password“`

### ISSUE THREAD

**Issue by vardan** [roboll/helmfile#1443]
I don't get any helmfile commands to run - they all fail because of parsing error:
`executing ”stringTemplate“ at <>: map has no entry for key`

I can fix it by using `hasKey`, but I would prefer to understand why just simple, for example, `<.Values.db.password>` does not work

Helm server and client have version  v2.16.10

**Comment by vardan** [comment]
To clarify: `map has no entry key for "password"` happens when checking whether value exists (`
  {{- if .Values.db.password }}`), which seems pretty trivial and yet is failing

**Comment by mumoshu** [comment]
@vardan You should use `hasKey`. I don't think the semantics of go text/template allows `{{- if .Values.db.password }}`, unfortunately.

**Comment by vardan** [comment]
@mumoshu , Thanks. And if I want to just get a value, not as part of `if` condition, should I use `get` or `getDefault` then? As far as I understood `getOrNil` is deprecated, right?

**Comment by mumoshu** [comment]
@vardan Yes, `getOrNil` is deprecated. You should always use `get`. Also I think `get` is useful even as a part of `if`, like `if ne (.Values | get "db.password" "") ""`
