### ISSUE TITLE
toJson empty

### ISSUE THREAD

**Issue by Morriz** [roboll/helmfile#1447]
toJson does not have equivalent mustToJson, which shows parse errors, so now I sometimes get empty output from toJson without having a chance to find out why. May I ask why not all sprig functions are passed one on one as in Helm?

**Comment by mumoshu** [comment]
> May I ask why not all sprig functions are passed one on one as in Helm?

@Morriz Tha's because I'm not entirely sure if all the Helm template functions also make sense in Helmfile's context, that I wanted to add functions as requested.

But is that important to you? Isn't this issue just a feature request to add `mustToJson`? 🤔

**Comment by Morriz** [comment]
You are right. Indeed. That would be helpful.

**Comment by mumoshu** [comment]
@Morriz Thanks for confirming. I've surveyed a bit and mustToJson seems to have added since sprig v3.

https://github.com/Masterminds/sprig/commit/877c54268c342eac47b061bf5378383b9b816623

So this will soon be addressed by #1294, which I'll prioritize higher than before, according to your request.
