### ISSUE TITLE
environments key in YAML with start and end document directives not to be used?

### ISSUE THREAD

**Issue by vugardzhamalov** [roboll/helmfile#1468]
Hi there,

`helmfile version v0.127.0`

As far as I can see 'helmfile.yaml' files with start '---' and end '...' YAML document directives won't work with 'environments:' key in the same file... I wasn't sure if this is expected or not (maybe it is expected because of the double rendering loop) so I thought I'll double check and mention it anyway.

Here is the error message that I get if and when I use these YAML directives:
`err: no releases found that matches specified selector() and environment(<replace-this-with-your-env-name>), in any helmfile`

**Comment by mumoshu** [comment]
@vugardzhamalov Hey! Yes, you can't use `---` in the very beginning of your helmfile.yaml or at the end of it. That's because every "part" of your helmfile.yaml must be a valid, non-empty helmfile.yaml.

**Comment by vugardzhamalov** [comment]
Thank you @mumoshu! Loud and clear - closing it now!

**Comment by vugardzhamalov** [comment]
As per earlier made comment it seems as if this is expected...
