### ISSUE TITLE
Selectors are order-dependent?

### ISSUE THREAD

**Issue by mouchar** [roboll/helmfile#1477]
Given a simple helmfile.yaml:
```yaml
releases:
    - name: nolabel1
      namespace: kube-system
      chart: stable/nolabel
    - name: nolabel2
      namespace: default
      chart: stable/nolabel
    - name: foo
      namespace: kube-system
      chart: stable/foo
      labels:
        type: bar
```

When I want to select releases that don't have a label type equal to "bar" AND their name is not equal to "nolabel2", I would expect the only selected release would be the first one ("nolabel1").

However, the following selector returns both "nolabel1" and "nolabel2":

```bash
$ helmfile -l 'type!=bar,name!=nolabel2' list
NAME    	NAMESPACE  	ENABLED	LABELS                                           
nolabel1	kube-system	true   	chart:nolabel,name:nolabel1,namespace:kube-system
nolabel2	default    	true   	chart:nolabel,name:nolabel2,namespace:default    
```

To get things more confusing, when I swap both parts, it selects the expected release:

```bash
$ helmfile -l 'name!=nolabel2,type!=bar' list
NAME    	NAMESPACE  	ENABLED	LABELS                                           
nolabel1	kube-system	true   	chart:nolabel,name:nolabel1,namespace:kube-system
```

Edit:
```
$ helmfile version
helmfile version v0.128.2
```

**Comment by mumoshu** [comment]
@mouchar Thanks for reporting! Please see #1478. I'm likely to make it work as you've expected soon.

**Comment by mumoshu** [comment]
@mouchar Could you try v0.129.3?

**Comment by mouchar** [comment]
@mumoshu Now it works as expected, thank you for the quick fix.
