### ISSUE TITLE
Helmfile builds unrelated dependencies in 0.125.0+

### ISSUE THREAD

**Issue by amnk** [roboll/helmfile#1497]
First of all - @mumoshu thank for awesome project.

I've been using helmfile for a while now with different versions, but starting with 0.125.0 I see an interesting behavior. Some background: all my installation uses charts stored locally, so I don't have `repositories` defined at all. Now, with versions earlier than 0.125.0 each my `sync` builds only relevant charts.

But with 0.125.0+ if I do sync on same `helmfile.yaml`, I get several `Building dependency release=xxx`. Moreover, with each run charts that are build as dependencies are different (and their number differs as well).

I saw helmfile/pull/1412 and related issues, but I'm either missing come context (e.g. this is desired behavior), or some open bug (e.g. someone already reported it). 

Does the above make sense or I need to provide more details?

**Comment by mumoshu** [comment]
> But with 0.125.0+ if I do sync on same helmfile.yaml, I get several Building dependency release=xxx. Moreover, with each run charts that are build as dependencies are different (and their number differs as well).

@amnk Thanks for reporting! Does this mean you sometimes see two or more `Building dependency release=xxx` on the same release? Or do you see `Building dependency release=xxx` at most once per each release?

**Comment by amnk** [comment]
@mumoshu with 0.125.0+ I always see three or more unrelated `Building dependency ...` doing one single release. If my selector includes several releases, I will see same dependencies.

**Comment by amnk** [comment]
@mumoshu sorry for silence. I downgraded to v0.124 and was using it 👍 

As to your question: that means that I'm seeing two or more `Building ...` for one or many releases.

So my helmfile is composed of multiple releases, and CI deployes them using selectors. And it does not matter how many releases selector covers - I still this `Building ...`.

**Comment by mumoshu** [comment]
@amnk Hey! I believe #1566 fixes this as well. Would you mind giving it a shot?
