### ISSUE TITLE
darwin amd64 releases have .dms extension?

### ISSUE THREAD

**Issue by Morriz** [roboll/helmfile#15]
Why are those releases not readily installable on osx? What extra step is needed to consume those files?

**Comment by roboll** [comment]
You should just need to download and `chmod +x` the files from Releases to be able to use them. The `.dms` extension isn't present on the Releases page, it may be whatever tool you are using to download is adding it. In chrome, for example, when clicking on the download link there is no extension on the resulting file.

Please reopen if this doesn't help.
