### ISSUE TITLE
Intellij IDEA support?

### ISSUE THREAD

**Issue by fzyzcjy** [roboll/helmfile#1506]
Hi thanks for this wonderful project! I am using Intellij IDEA and it has great support for traditional Helm charts. For example, when I type in `{{ .Values.xxx}}`, it will automatically give me hints on all available choices, and I can click it to *directly jump to that variable definition*. However, I cannot find how to do this with helmfile. Thanks very much!

**Comment by mumoshu** [comment]
@fzyzcjy Hey! Sorry for taking too long to reply. Unfortunately this is clearly out of scope of Helmfile and my spare time... I do see the value in having an IDE support though. How about submitting the same feature request to the issue tracker of the IDE of your choice, like IntelliJ IDEA, VS Code, etc?

If anyone reading this has your own implementation of such IDE plugin/extension, please feel free to share it here!

**Comment by shalupov** [comment]
Please vote/watch https://youtrack.jetbrains.com/issue/IDEA-243811
