### ISSUE TITLE
Templating value file doesn't work

### ISSUE THREAD

**Issue by hans-hsieh-asus** [roboll/helmfile#1515]
Hi, from [this](https://github.com/roboll/helmfile/issues/97) resolved issue, it looks like templating in value files is supported. However, I tested with the following files: 
`helmfile.yaml`:
```
environments:
  default:
    values:
    - my:
        port: 8080
---
repositories:
  - name: incubator
    url: https://kubernetes-charts-incubator.storage.googleapis.com
releases:
- name: haproxy-ingress
  namespace: haproxy-ingress
  chart: incubator/haproxy-ingress
  version: 0.0.27
  values:
  - values.yaml
```
`values.yaml`:
```
controller:
  tcp:
    1936: "my_namespace/my-service:{{ .Values.my.port }}"
```
And if I run `helmfile template`, I would get
```
COMBINED OUTPUT:
  Error: template: haproxy-ingress/templates/tcp-configmap.yaml:16:31: executing "haproxy-ingress/templates/tcp-configmap.yaml" at <tpl $value $>: error calling tpl: error during tpl function execution for "my_namespace/my-service:{{ .Values.my.port }}": template: haproxy-ingress/templates/tcp-configmap.yaml:1:34: executing "haproxy-ingress/templates/tcp-configmap.yaml" at <.Values.my.port>: nil pointer evaluating interface {}.port
  Use --debug flag to render out invalid YAML
```
Is there anything wrong with my usage? Thanks.

**Comment by Wihrt** [comment]
Taken from documentation
> You can use go's text/template expressions in helmfile.yaml and values.yaml.gotmpl (templated helm values files). values.yaml references will be used verbatim. In other words:
> 
> for value files ending with .gotmpl, template expressions will be rendered
> **for plain value files (ending in .yaml), content will be used as-is**

To do what you are asking, you shoud rename your file with the extension .gotmpl instead of .yaml and it should work ;)

**Comment by hans-hsieh-asus** [comment]
@Wihrt Sorry, my fault. I didn't read the document carefully.
Thank you. :)
