### ISSUE TITLE
postsync - execute complex command

### ISSUE THREAD

**Issue by Romiko** [roboll/helmfile#1525]
Hi,

I am not able to execute a complex command e.g.

`  - events: ["postsync"]
     showlogs: true
     command: "kubectl" 
    args:
    - get
    - -n
    - service-compliance
    - pv
    - --no-headers=true | awk '{print $1}' | xargs kubectl patch -p '{"spec":{"persistentVolumeReclaimPolicy":"Retain"}}' pv`

It does not like subcommands in the argument, any ideas? Also tried it all in the command value as well?

`    - events: ["postsync"]
      showlogs: true
      command: |
        kubectl get -n service-compliance pv  --no-headers=true | awk '{print $1}' | xargs kubectl patch -p '{"spec":{"persistentVolumeReclaimPolicy":"Retain"}}' pv`

Thx

**Comment by dsuievalov** [comment]
@Romiko Have you tried to spawn bash/sh?
```
- events: ["postsync"]
  showlogs: true
  command: "/bin/bash"
  args: ["-c", "kubectl get -n service-compliance pv --no-headers=true | awk '{print $1}' | xargs kubectl patch -p '{\"spec\":{\"persistentVolumeReclaimPolicy\":\"Retain\"}}' pv"]
```

It looks `command`/`args` format does not spawn bash/sh session and perform direct `exec` for the `kubectl` command. That is why the `|` does not work.

**Comment by Romiko** [comment]
Thank you , this works!
