### ISSUE TITLE
Is there a way to skip creating a namespace even the namespace exist; using helmfile apply or sync

### ISSUE THREAD

**Issue by atindrasingh1511** [roboll/helmfile#1536]
/ # cat helmfile.yaml 
repositories:
- name: stable
  url: https://kubernetes-charts.storage.googleapis.com
 
releases:
- name: mytraefik
  namespace: pr1099
  chart: stable/traefik
  labels:
    name: traefik-public
  version: 1.86.2

helmfile --log-level=debug apply

processing file "helmfile.yaml" in directory "."
first-pass rendering starting for "helmfile.yaml.part.0": inherited=&{default map[] map[]}, overrode=<nil>
first-pass uses: &{default map[] map[]}
first-pass rendering output of "helmfile.yaml.part.0":
 0: repositories:
 1: - name: stable
 2:   url: https://kubernetes-charts.storage.googleapis.com
 3:  
 4: releases:
 5: - name: mytraefik
 6:   namespace: pr1099
 7:   chart: stable/traefik
 8:   labels:
 9:     name: traefik-public
10:   version: 1.86.2
11: 

first-pass produced: &{default map[] map[]}
first-pass rendering result of "helmfile.yaml.part.0": {default map[] map[]}
vals:
map[]
defaultVals:[]
second-pass rendering result of "helmfile.yaml.part.0":
 0: repositories:
 1: - name: stable
 2:   url: https://kubernetes-charts.storage.googleapis.com
 3:  
 4: releases:
 5: - name: mytraefik
 6:   namespace: pr1099
 7:   chart: stable/traefik
 8:   labels:
 9:     name: traefik-public
10:   version: 1.86.2
11: 

merged environment: &{default map[] map[]}
helm:XVlBz> WARNING: Kubernetes configuration file is group-readable. This is insecure. Location: /root/KUBECONFIG
WARNING: Kubernetes configuration file is world-readable. This is insecure. Location: /root/KUBECONFIG
helm:XVlBz> v3.3.4+ga61ce56
Adding repo stable https://kubernetes-charts.storage.googleapis.com
exec: helm repo add stable https://kubernetes-charts.storage.googleapis.com --force-update
helm:gbaiC> WARNING: Kubernetes configuration file is group-readable. This is insecure. Location: /root/KUBECONFIG
WARNING: Kubernetes configuration file is world-readable. This is insecure. Location: /root/KUBECONFIG
helm:gbaiC> "stable" has been added to your repositories
exec: helm repo add stable https://kubernetes-charts.storage.googleapis.com --force-update: "stable" has been added to your repositories

"stable" has been added to your repositories

1 release(s) found in helmfile.yaml

Comparing release=mytraefik, chart=stable/traefik
exec: helm diff upgrade --reset-values --allow-unreleased mytraefik stable/traefik --version 1.86.2 --namespace pr1099 --detailed-exitcode
helm:MRAjW> WARNING: Kubernetes configuration file is group-readable. This is insecure. Location: /root/KUBECONFIG
WARNING: Kubernetes configuration file is world-readable. This is insecure. Location: /root/KUBECONFIG
helm:MRAjW> ********************

        Release was not present in Helm.  Diff will show entire contents as new.

********************
helm:MRAjW> pr1099, mytraefik, ConfigMap (v1) has been added:
- 
+ # Source: traefik/templates/configmap.yaml
+ apiVersion: v1
+ kind: ConfigMap
+ metadata:
+   name: mytraefik
+   labels:
+     app: traefik
+     chart: traefik-1.86.2
+     release: "mytraefik"
+     heritage: "Helm"
+ data:
+   traefik.toml: |
+     # traefik.toml
+     logLevel = "info"
+     defaultEntryPoints = ["http", "httpn"]
+     [entryPoints]
+       [entryPoints.http]
+       address = ":80"
+       compress = true
+       [entryPoints.httpn]
+       address = ":8880"
+       compress = true
+     [ping]
+     entryPoint = "http"
+     [kubernetes]
+     [traefikLog]
+       format = "json"
helm:MRAjW> pr1099, mytraefik, Deployment (apps) has been added:
+ # Source: traefik/templates/deployment.yaml
+ apiVersion: apps/v1
+ kind: Deployment
+ metadata:
+   name: mytraefik
+   labels:
+     app: traefik
+     chart: traefik-1.86.2
+     release: "mytraefik"
+     heritage: "Helm"
+ spec:
+   replicas: 1
+   selector:
+     matchLabels:
+       app: traefik
+       release: mytraefik
+   template:
+     metadata:
+       annotations:
+         checksum/config: 4a268cb3f80807708b953ff28e3effe69a1bd9baf65b4fe53d0a44d986494e93
+       labels:
+         app: traefik
helm:MRAjW> +         chart: traefik-1.86.2
+         release: "mytraefik"
+         heritage: "Helm"
+     spec:
+       serviceAccountName: default
+       terminationGracePeriodSeconds: 60
+       containers:
+       - image: traefik:1.7.20
+         imagePullPolicy: IfNotPresent
+         name: mytraefik
+         resources:
+           {}
+         readinessProbe:
+           httpGet:
+             path: /ping
+             port: "http"
+           failureThreshold: 1
+           initialDelaySeconds: 10
+           periodSeconds: 10
+           successThreshold: 1
+           timeoutSeconds: 2
+         livenessProbe:
+           httpGet:
+             path: /ping
+             port: "http"
+           failureThreshold: 3
+           initialDelaySeconds: 10
+           periodSeconds: 10
+           successThreshold: 1
+           timeoutSeconds: 2
helm:MRAjW> +         volumeMounts:
+         - mountPath: /config
helm:MRAjW> +           name: config
+         ports:
helm:MRAjW> +         - name: http
helm:MRAjW> +           containerPort: 80
+           protocol: TCP
+         - name: httpn
+           containerPort: 8880
+           protocol: TCP
+         - name: https
+           containerPort: 443
+           protocol: TCP
helm:MRAjW> +         args:
+         - --configfile=/config/traefik.toml
  
+       volumes:
+       - name: config
helm:MRAjW> +         configMap:
+           name: mytraefik
pr1099, mytraefik, Service (v1) has been added:
- 
+ # Source: traefik/templates/service.yaml
helm:MRAjW> + apiVersion: v1
+ kind: Service
+ metadata:
+   name: mytraefik
+   labels:
+     app: traefik
+     chart: traefik-1.86.2
helm:MRAjW> Error: identified at least one change, exiting with non-zero exit code (detailed-exitcode parameter enabled)
helm:MRAjW> +     release: "mytraefik"
+     heritage: "Helm"
+   annotations:
+ spec:
+   type: LoadBalancer
+   externalTrafficPolicy: Cluster
+   selector:
+     app: traefik
+     release: mytraefik
+   ports:
+   - port: 443
+     name: https
+     targetPort: httpn
+   - port: 80
+     name: http
+     targetPort: http
helm:MRAjW> Error: plugin "diff" exited with error
exec: helm diff upgrade --reset-values --allow-unreleased mytraefik stable/traefik --version 1.86.2 --namespace pr1099 --detailed-exitcode: ********************

        Release was not present in Helm.  Diff will show entire contents as new.

********************
pr1099, mytraefik, ConfigMap (v1) has been added:
- 
+ # Source: traefik/templates/configmap.yaml
+ apiVersion: v1
+ kind: ConfigMap
+ metadata:
+   name: mytraefik
+   labels:
+     app: traefik
+     chart: traefik-1.86.2
+     release: "mytraefik"
+     heritage: "Helm"
+ data:
+   traefik.toml: |
+     # traefik.toml
+     logLevel = "info"
+     defaultEntryPoints = ["http", "httpn"]
+     [entryPoints]
+       [entryPoints.http]
+       address = ":80"
+       compress = true
+       [entryPoints.httpn]
+       address = ":8880"
+       compress = true
+     [ping]
+     entryPoint = "http"
+     [kubernetes]
+     [traefikLog]
+       format = "json"
pr1099, mytraefik, Deployment (apps) has been added:
+ # Source: traefik/templates/deployment.yaml
+ apiVersion: apps/v1
+ kind: Deployment
+ metadata:
+   name: mytraefik
+   labels:
+     app: traefik
+     chart: traefik-1.86.2
+     release: "mytraefik"
+     heritage: "Helm"
+ spec:
+   replicas: 1
+   selector:
+     matchLabels:
+       app: traefik
+       release: mytraefik
+   template:
+     metadata:
+       annotations:
+         checksum/config: 4a268cb3f80807708b953ff28e3effe69a1bd9baf65b4fe53d0a44d986494e93
+       labels:
+         app: traefik
+         chart: traefik-1.86.2
+         release: "mytraefik"
+         heritage: "Helm"
+     spec:
+       serviceAccountName: default
+       terminationGracePeriodSeconds: 60
+       containers:
+       - image: traefik:1.7.20
+         imagePullPolicy: IfNotPresent
+         name: mytraefik
+         resources:
+           {}
+         readinessProbe:
+           httpGet:
+             path: /ping
+             port: "http"
+           failureThreshold: 1
+           initialDelaySeconds: 10
+           periodSeconds: 10
+           successThreshold: 1
+           timeoutSeconds: 2
+         livenessProbe:
+           httpGet:
+             path: /ping
+             port: "http"
+           failureThreshold: 3
+           initialDelaySeconds: 10
+           periodSeconds: 10
+           successThreshold: 1
+           timeoutSeconds: 2
+         volumeMounts:
+         - mountPath: /config
+           name: config
+         ports:
+         - name: http
+           containerPort: 80
+           protocol: TCP
+         - name: httpn
+           containerPort: 8880
+           protocol: TCP
+         - name: https
+           containerPort: 443
+           protocol: TCP
+         args:
+         - --configfile=/config/traefik.toml
  
+       volumes:
+       - name: config
+         configMap:
+           name: mytraefik
pr1099, mytraefik, Service (v1) has been added:
- 
+ # Source: traefik/templates/service.yaml
+ apiVersion: v1
+ kind: Service
+ metadata:
+   name: mytraefik
+   labels:
+     app: traefik
+     chart: traefik-1.86.2
+     release: "mytraefik"
+     heritage: "Helm"
+   annotations:
+ spec:
+   type: LoadBalancer
+   externalTrafficPolicy: Cluster
+   selector:
+     app: traefik
+     release: mytraefik
+   ports:
+   - port: 443
+     name: https
+     targetPort: httpn
+   - port: 80
+     name: http
+     targetPort: http

********************

        Release was not present in Helm.  Diff will show entire contents as new.

********************
pr1099, mytraefik, ConfigMap (v1) has been added:
- 
+ # Source: traefik/templates/configmap.yaml
+ apiVersion: v1
+ kind: ConfigMap
+ metadata:
+   name: mytraefik
+   labels:
+     app: traefik
+     chart: traefik-1.86.2
+     release: "mytraefik"
+     heritage: "Helm"
+ data:
+   traefik.toml: |
+     # traefik.toml
+     logLevel = "info"
+     defaultEntryPoints = ["http", "httpn"]
+     [entryPoints]
+       [entryPoints.http]
+       address = ":80"
+       compress = true
+       [entryPoints.httpn]
+       address = ":8880"
+       compress = true
+     [ping]
+     entryPoint = "http"
+     [kubernetes]
+     [traefikLog]
+       format = "json"
pr1099, mytraefik, Deployment (apps) has been added:
+ # Source: traefik/templates/deployment.yaml
+ apiVersion: apps/v1
+ kind: Deployment
+ metadata:
+   name: mytraefik
+   labels:
+     app: traefik
+     chart: traefik-1.86.2
+     release: "mytraefik"
+     heritage: "Helm"
+ spec:
+   replicas: 1
+   selector:
+     matchLabels:
+       app: traefik
+       release: mytraefik
+   template:
+     metadata:
+       annotations:
+         checksum/config: 4a268cb3f80807708b953ff28e3effe69a1bd9baf65b4fe53d0a44d986494e93
+       labels:
+         app: traefik
+         chart: traefik-1.86.2
+         release: "mytraefik"
+         heritage: "Helm"
+     spec:
+       serviceAccountName: default
+       terminationGracePeriodSeconds: 60
+       containers:
+       - image: traefik:1.7.20
+         imagePullPolicy: IfNotPresent
+         name: mytraefik
+         resources:
+           {}
+         readinessProbe:
+           httpGet:
+             path: /ping
+             port: "http"
+           failureThreshold: 1
+           initialDelaySeconds: 10
+           periodSeconds: 10
+           successThreshold: 1
+           timeoutSeconds: 2
+         livenessProbe:
+           httpGet:
+             path: /ping
+             port: "http"
+           failureThreshold: 3
+           initialDelaySeconds: 10
+           periodSeconds: 10
+           successThreshold: 1
+           timeoutSeconds: 2
+         volumeMounts:
+         - mountPath: /config
+           name: config
+         ports:
+         - name: http
+           containerPort: 80
+           protocol: TCP
+         - name: httpn
+           containerPort: 8880
+           protocol: TCP
+         - name: https
+           containerPort: 443
+           protocol: TCP
+         args:
+         - --configfile=/config/traefik.toml
  
+       volumes:
+       - name: config
+         configMap:
+           name: mytraefik
pr1099, mytraefik, Service (v1) has been added:
- 
+ # Source: traefik/templates/service.yaml
+ apiVersion: v1
+ kind: Service
+ metadata:
+   name: mytraefik
+   labels:
+     app: traefik
+     chart: traefik-1.86.2
+     release: "mytraefik"
+     heritage: "Helm"
+   annotations:
+ spec:
+   type: LoadBalancer
+   externalTrafficPolicy: Cluster
+   selector:
+     app: traefik
+     release: mytraefik
+   ports:
+   - port: 443
+     name: https
+     targetPort: httpn
+   - port: 80
+     name: http
+     targetPort: http

Affected releases are:
  mytraefik (stable/traefik) UPDATED

processing 1 groups of releases in this order:
GROUP RELEASES
1     pr1099/mytraefik

processing releases in group 1/1: pr1099/mytraefik
Upgrading release=mytraefik, chart=stable/traefik
exec: helm upgrade --install --reset-values mytraefik stable/traefik --version 1.86.2 --create-namespace --namespace pr1099 --history-max 10
helm:whTHc> WARNING: Kubernetes configuration file is group-readable. This is insecure. Location: /root/KUBECONFIG
helm:whTHc> WARNING: Kubernetes configuration file is world-readable. This is insecure. Location: /root/KUBECONFIG
helm:whTHc> Release "mytraefik" does not exist. Installing it now.
helm:whTHc> Error: namespaces is forbidden: User "arn:aws:iam::$role-name" cannot create resource "namespaces" in API group "" at the cluster scope
exec: helm upgrade --install --reset-values mytraefik stable/traefik --version 1.86.2 --create-namespace --namespace pr1099 --history-max 10: Release "mytraefik" does not exist. Installing it now.

Release "mytraefik" does not exist. Installing it now.

FAILED RELEASES:
NAME
mytraefik
err: release "mytraefik" in "helmfile.yaml" failed: failed processing release mytraefik: command "/bin/helm" exited with non-zero status:

PATH:
  /bin/helm

ARGS:
  0: helm (4 bytes)
  1: upgrade (7 bytes)
  2: --install (9 bytes)
  3: --reset-values (14 bytes)
  4: mytraefik (9 bytes)
  5: stable/traefik (14 bytes)
  6: --version (9 bytes)
  7: 1.86.2 (6 bytes)
  8: --create-namespace (18 bytes)
  9: --namespace (11 bytes)
  10: pr1099 (20 bytes)
  11: --history-max (13 bytes)
  12: 10 (2 bytes)

ERROR:
  exit status 1

EXIT STATUS
  1

STDERR:
  WARNING: Kubernetes configuration file is group-readable. This is insecure. Location: /root/KUBECONFIG
  WARNING: Kubernetes configuration file is world-readable. This is insecure. Location: /root/KUBECONFIG
  Error: namespaces is forbidden: User "arn:aws:iam::$role-name" cannot create resource "namespaces" in API group "" at the cluster scope

COMBINED OUTPUT:
  WARNING: Kubernetes configuration file is group-readable. This is insecure. Location: /root/KUBECONFIG
  WARNING: Kubernetes configuration file is world-readable. This is insecure. Location: /root/KUBECONFIG
  Release "mytraefik" does not exist. Installing it now.
  Error: namespaces is forbidden: User "arn:aws:iam::$role-name" cannot create resource "namespaces" in API group "" at the cluster scope
in ./helmfile.yaml: failed processing release mytraefik: command "/bin/helm" exited with non-zero status:

PATH:
  /bin/helm

ARGS:
  0: helm (4 bytes)
  1: upgrade (7 bytes)
  2: --install (9 bytes)
  3: --reset-values (14 bytes)
  4: mytraefik (9 bytes)
  5: stable/traefik (14 bytes)
  6: --version (9 bytes)
  7: 1.86.2 (6 bytes)
  8: --create-namespace (18 bytes)
  9: --namespace (11 bytes)
  10: pr1099 (20 bytes)
  11: --history-max (13 bytes)
  12: 10 (2 bytes)

ERROR:
  exit status 1

EXIT STATUS
  1

STDERR:
  WARNING: Kubernetes configuration file is group-readable. This is insecure. Location: /root/KUBECONFIG
  WARNING: Kubernetes configuration file is world-readable. This is insecure. Location: /root/KUBECONFIG
  Error: namespaces is forbidden: User "arn:aws:iam::$role-name" cannot create resource "namespaces" in API group "" at the cluster scope

COMBINED OUTPUT:
  WARNING: Kubernetes configuration file is group-readable. This is insecure. Location: /root/KUBECONFIG
  WARNING: Kubernetes configuration file is world-readable. This is insecure. Location: /root/KUBECONFIG
  Release "mytraefik" does not exist. Installing it now.
  Error: namespaces is forbidden: User "arn:aws:iam::$role-name" cannot create resource "namespaces" in API group "" at the cluster scope

  version: 1.86.2
/ # helmfile list 
NAME            NAMESPACE               ENABLED LABELS             
mytraefik       pr106737-nsgroup-dev    true    name:traefik-public
/ # helmfile version 
helmfile version v0.130.1
/ # helm version 
version.BuildInfo{Version:"v3.3.4", GitCommit:"a61ce5633af99708171414353ed49547cf05013d", GitTreeState:"clean", GoVersion:"go1.14.9"}
------------------------------------------------------------------------------------------------------------------------

Namespace pr1099 is already created. 

Is there a way to skip creating a namespace even the namespace is already there; using helmfile apply or sync

**Comment by Vad1mo** [comment]
yes just set

```yaml
helmDefaults:
  createNamespace: false
```

**Comment by atindrasingh1511** [comment]
It worked. Thank you @Vad1mo
