### ISSUE TITLE
Add a way to disable dependency up when using helm-x

### ISSUE THREAD

**Issue by semoac** [roboll/helmfile#1547]
Hi.

When trying to use helm-x features on third party charts like linkerd, the process fails because of missing directories being referenced as dependency on the chart. I know this sounds like a "chart problem" but it would be awesome to have a way to disable the process when is not needed (the linkerd chart already ships with its dependencies and helmfile can install the chart when not using helmx- features).

Example of  helmfile diff failing when trying to use jsonPatches on a release that was previously installed successfully.

```
running helm fetch linkerd/linkerd2 --untar -d /tmp/chartify405186524 --version 2.8.1
using requirements.yaml:
dependencies:
  - name: partials
    repository: file://../partials
    version: 0.1.0
  - name: grafana
    repository: file://../add-ons/grafana
    condition: grafana.enabled
    version: 0.1.0
  - name: tracing
    repository: file://../add-ons/tracing
    condition: tracing.enabled
    version: 0.1.0

running helm dependency up /tmp/chartify405186524/linkerd2
Error: directory /tmp/chartify405186524/partials not found
```

**Comment by mumoshu** [comment]
@semoac Thanks for reporting. This sounds like an annoying issue. I'm going to add a way to circumvent it with an explicit configuration to disable `helm repo up` in this case. See https://github.com/variantdev/chartify/commit/a6ce547f8b9bc3429b420a645177b592c66ad7ad for initial change towards it.
