### ISSUE TITLE
Rendering Helm chart template for a single release, ignoring `needs`

### ISSUE THREAD

**Issue by daaain** [roboll/helmfile#1552]
Is it possible to run `helmfile template --selector name=x` to output the template for a release which has `needs`?

I updated to `0.132.0` but still can't get around `in helmfile.yaml: "x" depends on nonexistent release "y"` 😿

I'm trying to run some tests like `kubeval` and `kube-score` on the "final" release output as the YAML can be quite different based on the values in the Helmfile if the chart has conditionals in the template, so it would be much more useful to let Helmfile do its magic on it rather than just using the output of the vanilla chart with `helm template`.

**Comment by jseiser** [comment]
https://github.com/roboll/helmfile/blob/16288dfa7da390bee208f46eaeb69061507c7ca8/pkg/state/state_run.go#L151

That appears to be where we are getting stuck.  I dont know go, but I assume this section of code has no idea if its a apply or a template.

**Comment by daaain** [comment]
I had a look in the code and it seems that the fundamental problem is that `template` seems to be running with the full `withDAG` release list: https://github.com/roboll/helmfile/blob/c170b5a62173872158ed424e7bcf3504bede9474/pkg/app/app.go#L1381

Whereas other misc ("non-executive", ie not touching k8s) commands like `diff` are in a different class and use custom code: https://github.com/roboll/helmfile/blob/b176408eb2c351f5730c914a12a72b587aac23f9/pkg/app/run.go#L115

**Comment by mumoshu** [comment]
@daaain @jseiser Thanks for reporting and the info! After some debugging, I realized that I had mistakenly inverted a necessary flag that resulted in the  `--selector` is applied and processed "before" computing the DAG. #1564 fixes that.

Just to be clear, the important point here is that we need to [compute the DAG with all the releases](https://github.com/roboll/helmfile/blob/ee0a53cc77a8a1837af0b61c40fed958684c118a/pkg/app/app.go#L1411), and then [apply the selector](https://github.com/roboll/helmfile/blob/ee0a53cc77a8a1837af0b61c40fed958684c118a/pkg/app/app.go#L1424-L1432) to avoid missing the dep release error.

The bug resulted in [applying selectors before computing the DAG](https://github.com/roboll/helmfile/blob/ee0a53cc77a8a1837af0b61c40fed958684c118a/pkg/app/app.go#L894-L901). This code of block is for any helmfile command that doesn't support DAG yet, and shouldn't be called for commands like diff, apply, and template. #1564 fixes the flag for helmfile-template.

**Comment by btashton** [comment]
@mumoshu maybe I am not quite understanding the feature, but when I use the selector I see the DAG get rendered in the debug, but none of the needs resources are included.
