### ISSUE TITLE
How can I iterate over files within a certain folder?

### ISSUE THREAD

**Issue by tstmrk** [roboll/helmfile#1553]
I have this one (the helm way?), but it gives an error

`
{{- range $path, $bytes  := .Files.Glob "secrets-volume/**" }}

{{- end }}
`

error message:
`
in ./helmfile.yaml: failed to render values files "config/0-default/values.yaml.gotmpl": failed to render [config/0-default/values.yaml.gotmpl], because of template: stringTemplate:17:34: executing "stringTemplate" at <.Files.Glob>: can't evaluate field Files in type state.releaseTemplateData
`

**Comment by RaymondKYLiu** [comment]
Try this one with `exec`
```
{{- range $_, $file := ( exec "bash" (list "-c" "echo -n secrets-volume/**") | splitList " " ) }}
...
{{- end }}
```

**Comment by tstmrk** [comment]
Great, that worked! Thank you very much!
