### ISSUE TITLE
Nested state Helmfiles have no way of consuming secrets

### ISSUE THREAD

**Issue by mnaser** [roboll/helmfile#1563]
There currently seems to be no way after my research of using secret values inside in combination with a nested-state file.  The only field allowed is `values` which includes bare files and `secrets` does not support it.

I have not been able to workaround this in any feasible way.

**Comment by mumoshu** [comment]
@mnaser Hey! Yeah, it is intentionally unimplemented, as I believe it isn't what you should do. Why you need to pass secrets to render your sub-helmfile? Doesn't that break the helmfile's general recommendation of each sub-helmfile should be independently runnable?

If you really need to do so, you can still pass values to the sub-helmfile and use `fetchSecretValue` and `expandSecretRefs` in the sub-helmfile to map the secret refs contained the values to secrets.

@song9446 I see you've 👍 on this too but I'm really doubt if that's really what you should. Please read my above comment and think twice before doing that!

**Comment by mumoshu** [comment]
I'm closing this as answered, but please feel free to reopen or create another issue. But please do provide me your whole setup and the design goal when doing so, so that I can think deeper if that's really what you should do.
