### ISSUE TITLE
support requirements property

### ISSUE THREAD

**Issue by Morriz** [roboll/helmfile#16]
Hi, maybe adding a `requirements` property to each chart section could tell helmfile to install dependencies first? Is that an idea? Is there a way to know if dependencies are ready?

**Comment by gtaylor** [comment]
Does installing a chart that has dependencies included currently not work?

**Comment by roboll** [comment]
Hi @Morriz - I don't think this is something helmfile needs to do, helm already provides a way to package dependencies (charts) within charts. 

If there's another use case here, can you try to describe it? If not I'll close this in a few days.
