### ISSUE TITLE
Unable to read a list of maps stored in vault 

### ISSUE THREAD

**Issue by CelestePhutela** [roboll/helmfile#1610]
I have a json object stored in hashicorp vault of type 

```
{
  "teams": [
    {
      "name": "up-to-date", 
     "secret": "value"
    },
    {
      "name": "casper",
     "secret": "value"
    }
 ]
}
```

I have tried various syntax in my helmfile to read this value

1 `teams:  ref+vault://path-to-secret#/teams`  -> Couldn't read the key (According to docs this should work) 

2 `teams:  ref+vault://path-to-secret/teams`  ->  Can read the key but instead of returning a list it is returning a string 
`[map[name:up-to-date secret:value]  map[name:casper secret:value]]`

My gotmpl file is trying to access the above teams value like this
`localUsers: {{  .Values.teams }}`

I have tried to parse this value in .gotmpl to yaml but it is still getting rendered as string.
`localUsers: {{  .Values.teams | toYaml }}`

I have tried this as well 
`localUsers: {{  .Values.teams | fromYaml }}`

Accessing the same key using vault cli works 
`vault kv get -format yaml -field key PATH_TO_SECRET`

I was able to read the value by exporting it as env variable
```
CONCOURSE_TEAMS=${CONCOURSE_TEAMS:-$(vault kv get -format yaml path_to_secret)}
CONCOURSE_TEAMS="#This is a yaml file"\n${CONCOURSE_TEAMS}
export CONCOURSE_TEAMS
```
.gotmpl files looks like this
`localUsers: {{  $t := requiredEnv "CONCOURSE_TEAMS" | fromYaml }}`

Do you have any suggestion on how to read json object like above directly in helmfile without using the env variable?

**Comment by rhiananthony** [comment]
Did you fix this? If so, how?

**Comment by sameeraksc** [comment]
any update about this :-(

**Comment by mumoshu** [comment]
Can you just write something like `{{ $team := range fetchSecretValue "ref+vault://path-to-secret/teams" | fromYaml }}` for turning any secret containing a yaml array into a list of objects and then `{{ $team.name }}` to obtain each value in the array item?

**Comment by mumoshu** [comment]
> 1 teams: ref+vault://path-to-secret#/teams -> Couldn't read the key (According to docs this should work)

Not sure where in your documentation this is written as supported 🤔

**Comment by sameeraksc** [comment]
hey @mumoshu  can you please give me support for this.  we have a secrete (kv/dev/envs) which is contained more than 20 envs. its like this when I get JSON output from the vault.

  {"S3_ACCESS_KEY": "value",
  "S3_BUCKET": "value",
  "S3_BUCKET_AU": "value",
  "S3_BUCKET_CALIFORNIA": "value",
  "S3_BUCKET_EU": "value",
  "S3_BUCKET_IRELAND": "value",
  "S3_BUCKET_SYDNEY": "value",
  "S3_BUCKET_US": "value"
  }

so we need to use the above values when helmfile is running. right now I'm I'm doing by adding a values yaml file with content like bellow.

S3_ACCESS_KEY:  ref+vault:kv/dev/envs#/S3_ACCESS_KEY
S3_BUCKET: ref+vault:kv/dev/envs#/S3_BUCKET
S3_BUCKET_CALIFORNIA: ref+vault:kv/dev/envs#/S3_BUCKET_CALIFORNIA
S3_BUCKET_IRELAND: ref+vault:kv/dev/envs#/S3_BUCKET_IRELAND

but it's hard to main to two places. if I add a line to vault secret I have to modify the value yaml file also. can you please suggest a way to this by using template?
i mean way like this {{ $team := range fetchSecretValue "ref+vault://path-to-secret/teams" | fromYaml }} for my scenario ?

Thanks.

**Comment by mumoshu** [comment]
@sameeraksc You shouldn't really make it complicated in exchange for just a bit of DRY but you can try...

```
{{ $ref := "ref+vault:kv/dev/envs" }}
S3_ACCESS_KEY: {{ $ref }}#/S3_ACCESS_KEY
S3_BUCKET: {{ $ref }}#/S3_BUCKET
S3_BUCKET_CALIFORNIA: {{ $ref }}#/S3_BUCKET_CALIFORNIA
S3_BUCKET_IRELAND: {{ $ref }}#/S3_BUCKET_IRELAND
```

**Comment by sameeraksc** [comment]
Thank you very much @mumoshu
