### ISSUE TITLE
helmfile repos command with jsonPatch tries to fetch the chart before adding the repo

### ISSUE THREAD

**Issue by gsimoes** [roboll/helmfile#1615]
When running `helmfile repos` and the release configuration has `jsonPatches`, it tries to fetch the chart before adding the repo. I'm not sure if should even fetch the chart using this command as my thinking is it should just add the repos.

```
running helm fetch deliveryhero/cluster-overprovisioner --untar -d /tmp/chartify171036451 --version 0.4.3
Error: repo deliveryhero not found

in ./helmfile.yaml: in .helmfiles[10]: in cluster-overprovisioner/helmfile.yaml: [exit status 1

COMMAND:
  helm fetch deliveryhero/cluster-overprovisioner --untar -d /tmp/chartify171036451 --version 0.4.3

OUTPUT:
  Error: repo deliveryhero not found]
```

**Comment by mumoshu** [comment]
@gsimoes Hey! Thanks for reporting. This turned out to be conceptually dup of #1752, and both that and this issue have been fixed via #1768.
