### ISSUE TITLE
Support empty helmfile files

### ISSUE THREAD

**Issue by johnmarcou** [roboll/helmfile#1620]
Currently, when helmfile.yaml is empty, helmfile command is exiting with errors.

It would be useful to exit without errors when helmfile.yaml is declaring no releases.
For example in a gitops context, if you want to disable all releases by commenting-out all the content.

# How to reproduce
```
echo "" > helmfile.yaml; helmfile template; echo $?
```

# What we get
```
err: no releases found that matches specified selector() and environment(default), in any helmfile
3
```

# Expected result
```
0
```

**Comment by mumoshu** [comment]
@johnmarcou Hey! Hm, that's interesting idea. Good for tarting single helmfile.yaml. But how would you like helmfile to work when you've specified a directory like `helmfile -f dir/ apply` and there was no releases to apply in any helmfile.yaml under the `dir/`? Should it exit with 0, too?

**Comment by johnmarcou** [comment]
Yes, I guess even in dir mode, if the merged list of releases is empty, helmfile CLI should still return exit 0. Do you see any use case where this could be an issue ?

In our context, we are using this to temporary disable application components without deleting the application on ArgoCD.

**Comment by mumoshu** [comment]
@johnmarcou Thanks!

BTW, have you ever tried `--allow-no-matching-release`? I was wondering if that's the exact behaviour you want.

```
   --allow-no-matching-release             Do not exit with an error code if the provided selector has no matching releases.
```

**Comment by johnmarcou** [comment]
@mumoshu 

```
echo "" > helmfile.yaml; helmfile --allow-no-matching-release template; echo $?
err: no releases found that matches specified selector() and environment(default), in any helmfile
0
```

I got 0, so I guess yes :)
I guess I can close that issue then. Thank you!
