### ISSUE TITLE
requiredEnv complains for releases where it is not specified

### ISSUE THREAD

**Issue by amnk** [roboll/helmfile#163]
I have several releases in my helmfile: almost all of them have `requiredEnv`, but there is one which does not. I'm installing it separately via labels. But if I do not set env variable, `helmfile` will complain.

**Comment by mumoshu** [comment]
Hi!
As helmfiles templates the
whole yaml before processing, that behavior is by design and can't be changed.
Could you set dummy values to all the required envs?

**Comment by amnk** [comment]
@mumoshu makes sense. I can set dummy values, but wanted to clarify if that the right thing to do.

**Comment by mumoshu** [comment]
@amnk Thanks for your confirmation 👍
It is more or less how helmfile works today. Actually I don't think it is the right thing to do. Please feel free to open a feature request for it.
