### ISSUE TITLE
feature request: ability to destroy specific releases

### ISSUE THREAD

**Issue by caleb15** [roboll/helmfile#1634]
I was surprised to find out that when I tried to destroy a specific release via `helmfile destroy metrics-server` it gave me an error `extraneous arguments: metrics-server`. It would be nice if you could specify releases to destroy via cmd rather than having to edit the file.

**Comment by dudicoco** [comment]
you can do this with the selector arguement:
```
helmfile --selector name=metrics-server destroy
```

**Comment by mumoshu** [comment]
Using the selector is the correct way to do this! I'm closing this as it'll never be "fixed". Please submit another issue with more information/reason/idea/pros/cons/etc for more concrete discussion.
