### ISSUE TITLE
Bump sprig dependency to v3.2.0

### ISSUE THREAD

**Issue by ggillies** [roboll/helmfile#1646]
Version 3.2.0 of the sprig library was released recently, and contains some new templating functions it would be great to have available in helmfile

 https://github.com/Masterminds/sprig/releases/tag/v3.2.0

**Comment by sjentzsch** [comment]
Same here. I need to use the `dig` function (http://masterminds.github.io/sprig/dicts.html#dig) which is now also present in Helm 3.5, but Helmfile is not there yet. Would be great to upgrade to sprig v3.2.0.

**Comment by weisdd** [comment]
+1

**Comment by dol** [comment]
I'm also looking for this merge to use the `dig` function.
