### ISSUE TITLE
helmfile returns "unable to recognize "": no matches for kind "StatefulSet" in version "apps/v1beta2" "

### ISSUE THREAD

**Issue by omersi** [roboll/helmfile#1663]
When I try to upgarde/create a release using `helmfile diff` or `helmfile apply` I get this exception:

```bash
Error: Failed to render chart: exit status 1: 
Error: unable to build kubernetes objects from release manifest: 
unable to recognize "": no matches for kind "StatefulSet" in version "apps/v1beta2"
```
I checked my charts to find any such entry for nothing.

helm3 version 

```
version.BuildInfo{Version:"v3.5.0", GitCommit:"32c22239423b3b4ba6706d450bd044baffdcf9e6", GitTreeState:"clean", GoVersion:"go1.15.6"}
```

helmfile version 

```
helmfile version v0.138.1
```

hlm3 plugin list 

```
NAME    	VERSION	DESCRIPTION                               
diff    	3.1.3  	Preview helm upgrade changes as a diff    
helm-git	0.10.0 	Get non-packaged Charts directly from Git.
```

How can I override this exception and deeply me releases?

**Comment by mumoshu** [comment]
@omersi Is StatefulSet defined under apps/v1beta2 in your K8s version? I thought it's only under apps/v1 for K8s 1.16 and newer.

**Comment by omersi** [comment]
I have two places where the charts are defined. 
one on the main repo where the general formation is set and the other is where each deployment gets its unique configuration.

* Main repo: 

```bash
grep -r 'apps/v1beta2' *.yaml


```

and under the charts maintenance directory

```bash
grep -r 'apps/v1beta2' *.yaml


```

To sum it up, I don't have any entry the API anywhere on my local charts.

**Comment by mumoshu** [comment]
@omersi Hmm, interesting. But the error message seems to indicate that one of your charts has it. What's happening? 🤔

**Comment by omersi** [comment]
I noticed that in some other cases when I try to create a new helm release with 

```bash
helm upgrade --install .... 
```

it sometimes through the same error, retrying the same command will most likely work afterward. but when I use it with helmfile, it'll always fail on that exception.

**Comment by mumoshu** [comment]
@omersi Thanks for the info. Could you provide me a set of helmfile.yaml and chart(s), and the version number of K8s, for reproduction? It's a lot easier to fix if I can reproduce it locally.

**Comment by omersi** [comment]
Closing this issue. it was created due to a deprecated helm 2.x version.
