### ISSUE TITLE
repos command doesn't work

### ISSUE THREAD

**Issue by SatoruItaya** [roboll/helmfile#1665]
This issue might be the same as #1657 .

I tried to sync repositories with the command `helmfile --environment dev repos`.
But there is no output and repositories are not added and updated.

I would like to know how to sync repositories through helmfile.

## environment

```
$ helmfile -v                                                                          
helmfile version v0.135.0
``` 

```
$ helm version
version.BuildInfo{Version:"v3.4.2", GitCommit:"23dd3af5e19a02d4f4baa5b2f242645a1a3af629", GitTreeState:"dirty", GoVersion:"go1.15.5"}
```

Kubernetes Cluster: v1.19.3 (Docker Desktop)
files: https://github.com/SatoruItaya/gatekeeper-example/tree/main/helmfile

**Comment by yurrriq** [comment]
You'll need to add `repositories` to your state file, e.g.:

```
 repositories:
  - name: stable
    url: https://charts.helm.sh/stable
```

**Comment by SatoruItaya** [comment]
@yurrriq 
Thanks for your advice, and I'm sorry for taking your time.
I succeeded in adding repos.
