### ISSUE TITLE
I reapply but get an error about "invalid ownership metadata"

### ISSUE THREAD

**Issue by huang12zheng** [roboll/helmfile#1668]
* log:
```s
COMBINED OUTPUT:
  WARNING: Kubernetes configuration file is group-readable. This is insecure. Location: /home/ubuntu/.kube/config
  WARNING: Kubernetes configuration file is world-readable. This is insecure. Location: /home/ubuntu/.kube/config
  Error: rendered manifests contain a resource that already exists. Unable to continue with install: ServiceAccount "tidb-cluster-discovery" in namespace "tidb-clusternamex" exists and cannot be imported into the current release: invalid ownership metadata; label validation error: key "app.kubernetes.io/managed-by" must equal "Helm": current value is "tidb-operator"
```

* helmfile
```helmfile
repositories:
- name: pingcap
  url: http://charts.pingcap.org
environments:
  default:
    values:
    - dev.yaml
releases:
- name: tidb-operator
  namespace: tidb-admin
  createNamespace: true
  wait: true
  chart: pingcap/tidb-operator
  # version: "v1.1.10"
  version: {{ .Values.tidbv }}
  values:
  - scheduler:
      kubeSchedulerImageName: registry.cn-hangzhou.aliyuncs.com/google_containers/kube-scheduler
- name: tidb-cluster
  namespace: tidb-clusternamex
  createNamespace: true
  wait: true
  chart: pingcap/tidb-cluster
  version: {{ .Values.tidbv }}
  values:
  - tidb:
      replicas: 1
    pd:
      # replicas: 1
      storageClassName: longhorn
    tikv:
      storageClassName: longhorn
    monitor:
      create: false
```
* in purpose
> How can I solve it?
> * Can I set.release. Service?
---
# other
* yaml:
```
kind: ServiceAccount
apiVersion: v1
metadata:
  name: tidb-cluster-discovery
  labels:
    app.kubernetes.io/name: tidb-cluster
    app.kubernetes.io/managed-by: Helm #<<<<<
    app.kubernetes.io/instance: tidb-cluster
    app.kubernetes.io/component: discovery
    helm.sh/chart: tidb-cluster-v1.1.10
```
* chart
```
kind: Job
metadata:
  name: {{ .Values.clusterName }}-restore-{{ .Values.name }}
  labels:
    app.kubernetes.io/name: {{ template "chart.name" . }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: {{ .Values.mode }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+"  "_" }}
```

**Comment by mumoshu** [comment]
@huang12zheng I believe the offending resource already exists in your cluster and that's why helm is complaining. Also see https://github.com/helm/helm/issues/7418.

And - aren't you trying to "overwrite" the tidb cluster already created by the tidb operator beforehand? I don't think that's a good idea.

I'm closing this as out of scope of helmfile - But please feel free to reopen if this has something to do with helmfile.

**Comment by huang12zheng** [comment]
> And - aren't you trying to "overwrite" the tidb cluster already created by the tidb operator beforehand? I don't think that's a good idea.

I want to do it...

> I believe the offending resource already exists in your cluster and that's why helm is complaining.

The resource exists because I deployed it with HelmFile earlier.

* other about overwrite

As stated above, template.yaml is
` ` `
app.kubernetes.io/managed-by: Helm
` ` `
However, it is modified by tidb-operator to
` ` `yaml
app.kubernetes.io/managed-by: tidb-operator
` ` `
in k8s

I would like to know if Helmfile has the ability to set.Release.Service to allow customization 
` ` `yaml
app.kubernetes.io/managed-by:
` ` `

**Comment by mumoshu** [comment]
@huang12zheng Hey!

> I would like to know if Helmfile has the ability to set.Release.Service to allow customization
yaml app.kubernetes.io/managed-by:

AFAIK, that's not possible with Helm, hence the same for Helmfile.

> However, it is modified by tidb-operator to
> yaml app.kubernetes.io/managed-by: tidb-operator
> in k8s

Interesting. If that's true, we can't use either Helm or Helmfile to manage tidb-cluster. Is that really by-design? Would you mind pointing me to more detailed documentation about the relationship between tidb-operator and the cluster?

**Comment by mumoshu** [comment]
@huang12zheng Don't you need to disable some parts of tidb-clsuter release via values (like e.g. `--set serviceAccount.create=false` if it's a standard-looking chart) if only a small subset of K8s resources is managed by the operator?

**Comment by huang12zheng** [comment]
Hi, 
> AFAIK, that's not possible with Helm, hence the same for Helmfile.

That's true. 
`Release.Service: The service that is rendering the present template. On Helm, this is always Helm.`

I'm sorry, I missed something.
* The latest operator has automatically managed the clsuter. Helm is not used.
The reason why I was wrong may be that the `Clsuter chart`is still being updated

Thank you. I would close this issue.

**Comment by mumoshu** [comment]
@huang12zheng Thanks for confirming! Glad to hear you solved your issue 👍
