### ISSUE TITLE
Raise when one secret is shared between several charts

### ISSUE THREAD

**Issue by amnk** [roboll/helmfile#167]
I'm currently sharing one secrets file among several different charts to share database setup. And this leads to race condition when deleting decrypted file after the execution:
```
err: remove secrets.yaml.dec: no such file or directory
err: remove secrets.yaml.dec: no such file or directory
```

_Created based on on https://github.com/roboll/helmfile/issues/149#issuecomment-396416715_

**Comment by sstarcher** [comment]
This looks to be related to helm dec using the same secret name between multiple secret values.  When it goes to cleanup the files it cleans up the same file multiple times.  Everything works except for you get a return error at the end.  It certainly needs cleaned up.

**Comment by maver1ck** [comment]
Any chance to get this fixed ?

**Comment by sstarcher** [comment]
This does not have any functional effect on the run.  The only functional issue is the exit code of helmfile itself.  Certainly this should be fixed, but I doubt it's a high priority.
