### ISSUE TITLE
helm-diff --show-secrets

### ISSUE THREAD

**Issue by strainovic** [roboll/helmfile#1674]
Hi,

Before I sync or apply changes, I'd like to know if some of the secrets will be changed. Implemented [here](https://github.com/databus23/helm-diff/blob/0882d8c63d782cd5ac325fe3b4e00342ae30f6a1/cmd/release.go#L76).

This is an opposite argument to the `--suppress-secrets` that we need from time to time as we want to be sure that secret data is not changed, while annotations may be changed.

I can add `--args --show-secrets` but helmfile in some cases runs `helm list --filter` command (when I have `installed` parameter in any of my releases set to `false`) that throws an error.

This is similar to https://github.com/roboll/helmfile/issues/1240 issue.

Thanks!

**Comment by strainovic** [comment]
Any comment?

**Comment by mumoshu** [comment]
@strainovic Hey! Sorry I was overwheled by swarm of github notifications.

This sounds like a good/valid feature request to helmfile!

**Comment by mumoshu** [comment]
Would you mind submitting a PR for this?

**Comment by strainovic** [comment]
Sure, I'd like to contribute to this great project!

Will submit a PR shortly.

Thanks! :)
