### ISSUE TITLE
HelmX intergration doesn't get set-parameter from release

### ISSUE THREAD

**Issue by and-1** [roboll/helmfile#1681]
When used helmx integration and present set parameter in release this one doesn't pass to chartify and therefore helm template doesn't use this values.

**Comment by mumoshu** [comment]
@and-1 Whoa, thanks for reporting - good catch!

If anyone is interested in contirubting, we'd need to the set parameters to `CharitfyOpts`'s `SetValues` here:

https://github.com/roboll/helmfile/blob/master/pkg/state/helmx.go#L87-L94
