### ISSUE TITLE
Release a new docker image with the latest helm-diff

### ISSUE THREAD

**Issue by wendorf** [roboll/helmfile#169]
helm-diff v2.9.0+2 adds the `--allow-unreleased` flag which allows it to diff a release with no prior versions (this addresses #127). It'd be great to build a new version of the docker image that pulls in this new version!

**Comment by mumoshu** [comment]
@wendorf Thanks for the feedback and sorry for the late reply!

Recent helmfile docker images should contain helm-diff binaries that supports `--allow-unreleased`. So, I'm closing this as resolved, but please feel free to reopen if necessary.
