### ISSUE TITLE
Support overriding chart from command line

### ISSUE THREAD

**Issue by yujunz** [roboll/helmfile#1690]
We have a use case to build chart on demand and deploy, it would be nice if helmfile can allow overriding chart in command line.

**Comment by itscaro** [comment]
You can use `{{ env "" }}` or `{{.Values}}` with `--state-values-set` or `--state-values-files`

**Comment by yujunz** [comment]
That works but the state file needs to be augmented for each release to have a chart value if I understand correctly.

Proposed a change to override it from args. It has been tested in our environment for weeks and works well so far. Please have a look. @itscaro

**Comment by mumoshu** [comment]
@yujunz Hey! Interested in it but still curious how it works in other cases. For example- how does it work when you have two or more releases to work on? Does `--chart` overrides all the charts for the all the releases?

**Comment by yujunz** [comment]
Yeah, it works the same way as other options to `helmfile template` too. Suppose `--set` `--values` applies for all releases too, right?

If the selector matches multiple releases, all the chart will be overridden. Normally we will choose the selector for the releases are using the same chart when overriding it.

For more context, this is used in argocd content plugin to allow overriding the chart from application parameters managed by argocd. It is quite convenient during fast iteration when it is not ready to persist the chart version to helmfile yet.

**Comment by mumoshu** [comment]
@yujunz Thanks for the response!

First of all, I agree with the usefulness of this feature.

> Suppose --set --values applies for all releases too, right?

That's good point. But FWIW I don't even like the fact that the current `--values` applies to all releases 😇 

> For more context, this is used in argocd content plugin to allow overriding the chart from application parameters managed by argocd. It is quite convenient during fast iteration when it is not ready to persist the chart version to helmfile yet.

That mostly makes sense. Curious, but doesn't it work like what you told when you have two ore more releases? Do you only have one release per helmfile that is triggered from within the ArgoCD content management plugin?

**Comment by mumoshu** [comment]
I wonder if this and `--values` could ideally work with multiple releases by providing a more complex parameter like:

```
helmfile --patch '{"selector": "name=myrelease1", "addValues": ["values1.yaml"]}' --patch '{"selector": "name=myrelease2", "chart": "./generated_chart"}' template
```

**Comment by yujunz** [comment]
> That mostly makes sense. Still curious, but doesn't it work like what you told when you have two ore more releases? Do you only have one release per helmfile that is triggered from within the ArgoCD content management plugin?

We have ~100 releases in one helmfile. The argocd content plugin is a simple shell script to map argocd application name to release.

```
- name: helmfile
  generate:                      # Command to generate manifests YAML
    command: ["/bin/sh", "-c"]
    args:
    - helmfile
      --helm-binary helm2
      --selector name=${HELMFILE_SELECTOR_NAME:-${ARGOCD_APP_NAME}}
      ${HELM_CHART:+--chart ${HELM_CHART}}
      template --skip-deps
      ${HELM_SET_IMAGE:+--set image=${HELM_SET_IMAGE}}
```

**Comment by mumoshu** [comment]
@yujunz So you get one ArgoCD application per each release in helmfile.yaml? Neat! Now your proposed change makes sense a lot. Thanks for clarifying.

**Comment by yujunz** [comment]
Exactly.

helmfile is an ideal complementary to argocd on chart, values and secrets management for helm releases. The missing piece is equivalent UI support as native helm application. Current workaround is to pass arguments as plugin env.
