### ISSUE TITLE
chartify breaks when two or more releases sharing the same chart and the namespace, but kubeContext

### ISSUE THREAD

**Issue by jwitko** [roboll/helmfile#1695]
As a very simple use case take a directory which is just a single k8s manifest for creating a cluster role.  You plan to install this into multiple clusters by iterating over AWS regions, as part of that you jsonPatch the region into the metadata.labels.  If the release name is not dynamic (aka same release name in both clusters) then the jsonPatch for the last iteration will apply to all manifests and they will all get patched with the label of a single region, regardless of where they are actually deploying.

**Comment by mumoshu** [comment]
@jwitko Hey! Thanks for reporting. Could you confirm that you're basically saying that jsonPatches/strategicMergePatches breaks when two or more releases sharing the same chart, even if they have different kubecontexts?

**Comment by jwitko** [comment]
> @jwitko Hey! Thanks for reporting. Could you confirm that you're basically saying that jsonPatches/strategicMergePatches breaks when two or more releases sharing the same chart, even if they have different kubecontexts?

Yes that is correct.  It should be extremely easy to reproduce but if you can't let me know and I'll draw up a full example.

**Comment by mumoshu** [comment]
@jwitko Thanks for confirming! As I have a lot of issues hanging on my desk that are waiting for me to prepare reproduction examples myself, any go-to example provided by the reporter(you) is super helpful and always welcomed 😄

**Comment by mumoshu** [comment]
@jwitko Seems like I've managed to fix it #1799

**Comment by jwitko** [comment]
@mumoshu thank you!  so sorry I did not get a chance to respond with an example.
