### ISSUE TITLE
helmfile diff - file not found

### ISSUE THREAD

**Issue by liamawhite** [roboll/helmfile#17]
When I try to run `helmfile -f charts.yml diff` or `helmfile -f charts.yml diff --sync-repos`  it fails as follows:
```
exec: helm diff mq-demo reg-stage/rabbitmq
exec: helm diff terminator local/terminator
Error: file "local/terminator" not found
Error: plugin "diff" exited with error
Error: file "reg-stage/rabbitmq" not found
Error: plugin "diff" exited with error
err: exit status 1
err: exit status 1
```

with the helmfile:

```
repositories:
  - name: local                         
    url: http://127.0.0.1:8879/charts
  - name: reg-stage
    url: <another-url>

charts:
  - name: terminator                     # helm deployment name
    chart: local/terminator              # chart reference
  - name: mq-demo
    chart: reg-stage/rabbitmq
```

Am I doing something wrong or is this a bug?

**Comment by roboll** [comment]
I don't use the diff plugin, but maybe @jrnt30 who added the diff plugin to helmfile can lend a hand?

**Comment by mumoshu** [comment]
@liamawhite In case you missed it, can you just try installing `helm diff` plugin before running `helmfile diff`?

For me, it was a matter of just running `helm plugin install https://github.com/databus23/helm-diff` and then `helmfile diff --sync-repos ...` to make it work.

Assuming you're using recent version of helm, https://github.com/databus23/helm-diff#using-helm-plugin-manager--23x would help.

**Comment by mumoshu** [comment]
Closing this as "probably" resolved" because the original question is answered anyway, and also due to lack of further activity.
Please feel free to reopen if necessary. Thx!
