### ISSUE TITLE
Testing helmfiles?

### ISSUE THREAD

**Issue by pjotre86** [roboll/helmfile#1708]
Hey!
Just curious: Is anyone running automated tests against their helmfiles to make sure that they behave like they should and you're not breaking them?  
For my helm-charts I'm using [terratest](https://github.com/gruntwork-io/terratest). It has a module for helm which let's you write extensive tests for your charts in golang.  
I'm wondering:  
Is there something similar for helmfile? What creative solutions are you using or did you encounter?   
Thanks in advance for any hints!

**Comment by renehernandez** [comment]
@pjotre86 This may relevant: https://github.com/roboll/helmfile/issues/1713

**Comment by mumoshu** [comment]
@pjotre86 If you're more interested in integration testing helmfile with a live K8s cluster, I'd guess something like `terratest` is the best. For unit testing helmfile-generated heml releases, #1713 should be the way to go.

Regarding `terratest`, I think writing a helmfile adapter for `terratest` like the helm one https://github.com/gruntwork-io/terratest/tree/master/modules/helm wouldn't be too hard

**Comment by pjotre86** [comment]
Thanks for the answer. I'll follow #1713, looks in deed promising and might match my use-case. Will close this.
