### ISSUE TITLE
Not possible to handle different namespace per release entry when CLI --namespace is used

### ISSUE THREAD

**Issue by antaloala** [roboll/helmfile#1718]
I have created a simple helmfile yaml manifest defining two releases. I am setting the namespace field for each as follows:

```
releases[0].namespace: {{ .Namespace }}
releases[1].namespace: {{ requiredEnv "OTHER_NAMESPACE" | quote }}
```
When invoking the ```helmfile apply``` command with the  ```--namespace my_namespace``` option both releases are deployed in the ```my_namespace``` namespace. The same happens if I am setting ```namespace: my_namespace``` at the root of my helmfile manifest (in this case ```--namespace``` is not accepted in CLI).
When running in ```--debug``` mode I can see the rendered helmfile yaml manifest shows different namespace setting for each (```OTHER_NAMESPACE=other_namespace```) but when ```helm upgrade --install``` is finally invoked for each release the exact same namespace is used for both (the one provided through ```--namespace``` or the root namespace field set in the yaml manifest).

NOTE: to be sure it was not related to any issue with the OTHER_NAMESPACE env variable I explictly set (in the helmfile yaml manifest):
```releases[1].namespace: "other_namespace```
But again it was installed in the namespace set with ```--namespace```  even when not setting it to ```{{ .Namespace }}``` for the second release.

If not using the ```--namespace``` option nor defining the root namespace field in the helmfile yaml I get each release being deployed in the desired namespace (of course I had first to update the ```releases[0].namespace: {{ .Namespace }}``` setting to not depend on the Namespace map)

helmfile version v0.138.7

**Comment by mumoshu** [comment]
@antaloala Hey! Thanks for reporting. Honestly speaking it looks working as expected to me. `--namespace` is used to override the namespaces of all the releases in the first place. General recommendation is to avoid using ad-hoc settings like `--namespace` via flags and keep everything declared in your helmfile.yaml, so that it is- declarative.

What was your original goal? Probably a list of use-cases would help.

**Comment by antaloala** [comment]
Thanks @mumoshu for jumping (and for the great work with helmfile).
I initially thought this was the intended behavior ... but as it is possible to set ```namespace: {{ .Namespace }}``` for some releases entries but not for some others (as I did in the state file I am using) I then thought it was making more sense not to overrwrite the ```namespace``` settings for those releases setting a valud different than ```{{ .Namespace }}``` (as in the end you can control where to use the value passed through ```--namespace``` CLI option and where not using that map).

My Use Case: leaving the namespace for almost all releases to be set using the ```--namespace``` CLI option except for some releases entries where I want to use a different one (being hard coded in the state file or got from some environment variable, or even got from some env values)

**Comment by mumoshu** [comment]
@antaloala Hey! Thanks for clarifying. I can see your point, but unlike `.Release.Namespace` in Helm we opted to let it override namespaces regardless of `namespace: {{ .Namespace }}`. And `{{ .Namespace }}` in helmfile.yaml gotmpl is intended to be used for templating other things like values.

For your use-case, would you try using a state value instead?

That is, `helmfile --state-values-set myns=foo` will make `{{ .Values.myns }}` rendered to `foo`

**Comment by antaloala** [comment]
I see now yor point (thanks for clarifying it) 

> 
> For your use-case, would you try using a state value instead?
> 
Yes, I also thought on using that approach (that would also keep the declarative aim, right? ;-)
Thanks a lot for the clarifications.
We can close then.

**Comment by mumoshu** [comment]
> that would also keep the declarative aim when using --state-values-file so I use another manifest for it, right? ;-)

@antaloala Absolutely!

You may already know but you can even define the default value for `myns` by adding this in the beginning of your helmfile.yaml:

```
values:
- myns: mydefaultns

---

releases:
- ...
```

I'm glad to hear I was able to clarify the way you use Helmfile!
This had been a good chance for me to revisit why/for what there are state values.
Please feel free to ask anything you caught on the way towards using it!

**Comment by antaloala** [comment]
@mumoshu Yes, I am actually using the "values" stanza in the state manifest (to set some default values for those namespaces) plus allowing them to be overridden by an optional deployment specific state values manifest.
I am templating the per-releases entry "namespace" field with those state values so

- thanks to the settings in the "values" stanza I can assure I am always able to render the state file
- in case there are deployment specific settings (so --state-values-file CLI option is used) the namespace fields get those

Do you see a better way to handle it? (thanks in advance)

**Comment by mumoshu** [comment]
@antaloala That looks good to me! Just to be extra sure- do you still have any concerns about your current setup?

**Comment by antaloala** [comment]
@mumoshu no, sorry, we do not need to keep any activity in this closed issue. Thanks a lot for your comments/help.
