### ISSUE TITLE
Use helmfile to create a helm chart

### ISSUE THREAD

**Issue by avgKol** [roboll/helmfile#1722]
As I understand, helmfile makes it easier to deploy helm charts across environments .

Is Is it possible to use helmfile to create a helm chart on the fly ?

**Comment by mumoshu** [comment]
@avgKol Hey! I have a similar sentiment and want to compare your idea with mine.

So, helmfile is already able to turn a directory of raw K8s manifest YAML files, or a directory containing [kustomize](https://github.com/kubernetes-sigs/kustomize) `kustomization.yaml` into a Helm chart on-the-fly.

https://github.com/roboll/helmfile/blob/master/docs/advanced-features.md#deploy-kustomizations-with-helmfile

Is that what you would like? Or do you have any other idea in your mind?

**Comment by avgKol** [comment]
> @avgKol Did you have any chance to check my reply? I believe Helmfile already supports your use-case

Helmfile does not seem to help with that. I am using  [move2kube](https://move2kube.konveyor.io) .

**Comment by mumoshu** [comment]
@avgKol Hey! Sorry but I don't fully get it. You need to persist the generated Helm chart for whatever reason? If not, Helmfile is already able to generate a temporary Helm chart "on the fly", which will be enough for managing e.g. a set of K8s manifests with Helmfile.

**Comment by mumoshu** [comment]
Unfortunately, this ended up with me not even understanding what the original goal was.

Helmfile supports various deployment sources, including:

- Remote Helm chart
- Local Helm chart
- A directory of K8s manifest YAML files
- Kustomization (https://github.com/roboll/helmfile/blob/master/docs/advanced-features.md)

You can even leverage the `incubator/raw` chart for to use Helm features while not required to write your own Chart.

Furthermore, you can add ad-hoc changes to the chart and manifests/kustomization using:

- strategicMergePatches
- jsonPatches
- transformers
- forceNamespace

To anyone seeing this issue later, Id' would be helpful to take the above into your consideration.
