### ISSUE TITLE
Installing from AppRegistry

### ISSUE THREAD

**Issue by plumdog** [roboll/helmfile#174]
I found a helm chart that tells me to install it using `helm registry install quay.io/...` rather than `helm install`.

(The specific chart being https://github.com/kubernetes-sigs/aws-alb-ingress-controller/tree/master/alb-ingress-controller-helm)

Is this possible using helmfile?

**Comment by sstarcher** [comment]
I don't believe we have any way to currently support the `helm registry` plugin.

**Comment by plumdog** [comment]
OK, that's fine - I'm happy to just install the chart from local files.
