### ISSUE TITLE
Concatenate in go template

### ISSUE THREAD

**Issue by Xat59** [roboll/helmfile#1747]
Hello guys,

I am trying to create a `values.yaml.gotmpl` that has the following content : 

```
es:
  uri: http://<username>:<password>@<url>:<port>
```

Where `username` and `password` are retrieved from vault and are declared in the same line.

So I tried a lot of combination, such as :
```
es:
  uri: {{ "http://" }}ref+vault://secret/path/to/secret?address={{ env "VAULT_ADDR" }}/#username{{ ":" }}ref+vault://secret/path/to/secret?address={{ env "VAULT_ADDR" }}/#password{{ "@domain.net:80" }}
```

... and a lot of other tests, without any success.

Please can you help ?

Thanks a lot !

**Comment by mumoshu** [comment]
@Xat59 Hey! Try using `print` for concatenating strings and `fetchSecretValue` for fetching secrets. Perhaps yours should be something like `{{ print (fetchSecretValue (print "ref+vault://secret/path/to/secret?address=" (env "VAULT_ADDR") "/#username")) ":" (fetchSecretValue (print "ref+vault://secret/path/to/secret?address=" {{ env "VAULT_ADDR" }} "/#password")) "@domain.net:80" }}`

**Comment by Xat59** [comment]
I have finally succeeded with this syntax : 
```
es.uri: {{ print "http://" }}{{ fetchSecretValue ( print "ref+vault://path/to/secret?address=" (env "VAULT_ADDR") "/#username" ) }}{{ print ":" }}{{ fetchSecretValue ( print "ref+vault://path/to/secret?address=" (env "VAULT_ADDR") "/#password" ) }}{{ print "@domain.net:80" }}
```

Thanks for all the hints.
Regards

**Comment by mumoshu** [comment]
@Xat59 Thanks for sharing! Sorry `{{ env "VAULT_ADDR" }}` in my example was a mistake. As you already have figured out, we need to use `()` as it's already inside a go template expression `{{ }}`.

**Comment by mumoshu** [comment]
That being said you can safely rewrite your solution with:

```
{{ print "http://" (fetchSecretValue ( print "ref+vault://path/to/secret?address=" (requiredEnv "VAULT_ADDR") "/#username" )) ":" (fetchSecretValue ( print "ref+vault://path/to/secret?address=" (requiredEnv "VAULT_ADDR") "/#password" )) "@domain.net:80" }}
```

**Comment by mumoshu** [comment]
Or even:

```
{{ $username := fetchSecretValue ( print "ref+vault://path/to/secret?address=" (requiredEnv "VAULT_ADDR") "/#username" ) -}}
{{ $password := fetchSecretValue ( print "ref+vault://path/to/secret?address=" (requiredEnv "VAULT_ADDR") "/#password" ) -}}
{{ print "http://" $username ":" $password "@domain.net:80" }}
```

**Comment by Xat59** [comment]
> {{ $username := fetchSecretValue ( print "ref+vault://path/to/secret?address=" (requiredEnv "VAULT_ADDR") "/#username" ) -}}
> {{ $password := fetchSecretValue ( print "ref+vault://path/to/secret?address=" (requiredEnv "VAULT_ADDR") "/#password" ) -}}
> {{ print "http://" $username ":" $password "@domain.net:80" }}

It works like a charm ! Thanks a lot @mumoshu
