### ISSUE TITLE
potential bug: namespace creation failing

### ISSUE THREAD

**Issue by naseemkullah** [roboll/helmfile#1748]
Hello, I have the following release to deploy to a non-existant namespace:

```
  - chart: prometheus-community/kube-prometheus-stack
    name: kube-prometheus-stack
    namespace: monitoring
```

But I get:

```
Release "kube-prometheus-stack" does not exist. Installing it now.
Error: create: failed to create: namespaces "monitoring" not found
```

I've tried adding `createNamespace: true` but get:

```
failed to read helmfile.yaml: reading document at index 1: yaml: unmarshal errors:
  line 138: field createNamespace not found in type state.ReleaseSpec
```

Am I doing something wrong? I have the latest versions of helm + helmfile.

thanks!

**Comment by mumoshu** [comment]
@naseemkullah Hey! Out of curiosity, what are the exact version numbers of helmfile and hlem? Running `helmfile version` and `helm version` would help.

**Comment by naseemkullah** [comment]
> @naseemkullah Hey! Out of curiosity, what are the exact version numbers of helmfile and hlem? Running `helmfile version` and `helm version` would help.

Hey @mumoshu. This may be my problem!:

```
$ helmfile --version
helmfile version
$ which helmfile
~/go/bin/helmfile
```

and helm is `3.5.3`

**Comment by naseemkullah** [comment]
My issue was I was using `~/go/bin/helmfile`... everything works perfectly after deleting that binary to force using the `brew` installed helmfile v0.138.7.

Sorry for the bother!
