### ISSUE TITLE
{{ with merge }} logic was breakingly changed in 0.130.2

### ISSUE THREAD

**Issue by sigurdblueface** [roboll/helmfile#1756]
I have a layered deployment which is using gotmpls
Project folder looks this way:
```
mystack:
  app_a:
    values.gotmpl
  app_b:
    values.gotmpl
  app_c:
    values.gotmpl
  helmfile.yaml
  default-values.yaml
mystack-values.yaml
helmfile.yaml # contains "helmfiles" block with link to helmfile and values  
```
gotmpl values templates contain smth like
```
{{with merge .Values .Values.a }}
replicas: {{.replicas}}
hostname: {{.hostname}}
{{end}}

let's say `mystack-values.yaml` contains:

```
a:
  replicas: 1
  hostname: a.test.local
b:
  replicas: 2
  hostname: b.test.local
c:
  replicas: 3
  hostname: c.test.local
```

using helmfile < 0.130.2 everything works fine and every service gets parameters, as set above

using helmfile >= 0.130.2 it seems like values map merges just once, so in result every app gets parameters of a first app by alphabetical order:

```
a:
  replicas: 1
  hostname: a.test.local
b:
  replicas: 1
  hostname: a.test.local
c:
  replicas: 1
  hostname: a.test.local
```

**Comment by mumoshu** [comment]
@sigurdblueface Hey! Thanks for reporting. I was reading [v0.130.2](https://github.com/roboll/helmfile/releases/tag/v0.130.2) changelog but have no clue how it could affect your use-case like that.

Would you mind sharing a small example project with `helmfile.yaml` and other files for reproduction?

**Comment by sigurdblueface** [comment]
sure, [here it is](https://github.com/sigurdblueface/with_merge)

**Comment by mumoshu** [comment]
@sigurdblueface Thanks for sharing! I've managed to reproduce the issue. BUT-

My consequence was: it seems we had to use `mergeOverwrite` instead of `merge` when the destination fields (.Values.hostname and .Values.replicas) are non-empty.

I'm not sure why it worked like we saw for pre-v0.130.1, but from what I can see from merge/mergeOverwrite's implementation, v0.130.2's behaviour is correct. Using `mergeOverwrite` seems to work consistently for both v0.130.1 and v0.130.2 so I'd say we had to use it.

FYI, mergo 0.3.11's `Merge` which is the implementation of `{{ merge }}` explicitly says that:

```
// Merge will fill any empty for value type attributes on the dst struct using corresponding
// src attributes if they themselves are not empty. dst and src must be valid same-type structs
// and dst must be a pointer to struct.
// It won't merge unexported (private) fields and will do recursively any exported field.
func Merge(dst, src interface{}, opts ...func(*Config)) error {
	return merge(dst, src, opts...)
}
```

And `MergeWithOverwrite` which is the impl of `mergeWithOverwride` says:

```
// MergeWithOverwrite will do the same as Merge except that non-empty dst attributes will be overridden by
// non-empty src attribute values.
// Deprecated: use Merge(…) with WithOverride
func MergeWithOverwrite(dst, src interface{}, opts ...func(*Config)) error {
	return merge(dst, src, append(opts, WithOverride)...)
}
```

**Comment by mumoshu** [comment]
@sigurdblueface Here's the changeset I've used for testing: https://github.com/sigurdblueface/with_merge/pull/1

**Comment by sigurdblueface** [comment]
@mumoshu, I can confirm, works like a charm. 
Thanks for your time.

**Comment by mumoshu** [comment]
@sigurdblueface Thanks for reporting/confirming! I've learned the thing.
