### ISSUE TITLE
Support single yaml files?

### ISSUE THREAD

**Issue by GoldenMouse** [roboll/helmfile#1757]
Maybe a silly request but can helmfile support applying just a single manifest file? Sometime we have some extraneous set of yamls that isn't in a chart yet such as CRDs.

**Comment by mlushpenko** [comment]
It is supported if you create a folder for that manifest and then reference it as a chart. See here for more details https://github.com/roboll/helmfile/pull/673

**Comment by GoldenMouse** [comment]
Sweet thank you!

**Comment by mumoshu** [comment]
// Linking #1720 as a related issue

**Comment by FlorianPatzer** [comment]
This does not work using fetch. Is this intended behavior?

Take a simple example:
helmfile.d
    |_test.yaml
manifests
    |_noops.yaml
    
with test.yaml containing:
```yaml
releases:
  - name: manifests
    chart: "../manifests"
```
and noops.yaml containing:
```yaml
kind: ConfigMap
apiVersion: v1
metadata:
  name: test-noop-only
data:
  NOOP: |
```
`docker run --rm --net=host -v "${HOME}/.kube:/helm/.kube" -v "${HOME}/.config/helm:/helm/.config/helm" -v "${PWD}:/wd" --workdir /wd ghcr.io/helmfile/helmfile:v1.0.0-rc.4 helmfile fetch`
```logs
:v1.0.0-rc.4 helmfile fetch
Building dependency release=manifests, chart=../manifests
in helmfile.d/test.yaml: [building dependencies of local chart: command "/usr/local/bin/helm" exited with non-zero status:

PATH:
  /usr/local/bin/helm

ARGS:
  0: helm (4 bytes)
  1: dependency (10 bytes)
  2: build (5 bytes)
  3: ../manifests (12 bytes)

ERROR:
  exit status 1

EXIT STATUS
  1

STDERR:
  Error: Chart.yaml file is missing

COMBINED OUTPUT:
  Error: Chart.yaml file is missing]

```
There is no error when adding `--skip-deps`.

`fetch` seems to skip the chart preparation
