### ISSUE TITLE
Running helmfile as a container failes when helm-secrets is used

### ISSUE THREAD

**Issue by amnk** [roboll/helmfile#176]
Since helmfile offloads actual executions to `helm secrets`, plugin should be installed in the container, otherwise:
```
Error: unknown command "secrets" for "helm"
Run 'helm --help' for usage.
```

**Comment by mumoshu** [comment]
@amnk Ah, good catch! Would you mind adding it [here](https://github.com/roboll/helmfile/blob/master/Dockerfile#L24) and send a PR? So that every docker image released in the future includes the plugin 😉

**Comment by amnk** [comment]
@mumoshu done :)

As a side note: maybe I was doing something wrong, but helmfile inside container is not really useful because it can't authorize to the clouds to do deployments or decrypt secrets. I had to create a [monster image](https://github.com/amnk/gcloudhelm) with google binaries inside to make that work.

**Comment by mumoshu** [comment]
@amnk Thanks :)

> As a side note: maybe I was doing something wrong, but helmfile inside container is not really useful because it can't authorize to the clouds to do deployments or decrypt secrets

I should learn more about GCP but anyway, I was thinking that:

- you probably need the four envvars mentioned in your awesome project's README to allow sops to call gcp-kms and
- A `kubeconfig` file and a `KUBECONFIG` envvar that points to the file

that are properly configured via container volume mounts and envvars (i.e. `docker run -e KUBECONFIG=/host/kube/config -e GOOGLE_APPLICATION_CREDENTIALS=/host/google/credentials.json -v $(pwd)/kube:/host/kube -v $(pwd)/google:/host/google ....`)

In that regard, I'm not yet sure why you had to include google binaries.

**Comment by amnk** [comment]
@mumoshu this is true for local execution. But imagine the same code running in CI - it needs to authenticate to google registry, and to GCP itself.

**Comment by mumoshu** [comment]
@amnk Thanks for the clarification! Makes sense. Probably we should note about that - to use the docker image just as a base image in case it is used in a container-based CI - somewhere in the README?
