### ISSUE TITLE
Make helmfile diff pass namespace to helm-diff 

### ISSUE THREAD

**Issue by foklepoint** [roboll/helmfile#179]
This is related to this issue in helm-diff: https://github.com/databus23/helm-diff/issues/66

Currently when you want to diff a chart via helmfile diff under the following conditions:
- The chart has no previous releases
- There is a namespace specified in helmfile

The diff is inaccurate because `helm upgrade diff --allow-unreleased` hard-codes to [using the default namespace here](https://github.com/databus23/helm-diff/blob/master/cmd/upgrade.go#L112). However, helmfile can actually contain the correct namespace and be other than default. This would require for helm-diff to read in the namespace from the cli, if supplied, and require helmfile to send the the namespace as a flag to helm-diff.

**Comment by mikedmcfarland** [comment]
Curious, how do I install the correct version of helm diff so that the namespace flag exists?
Just used `helm plugin install https://github.com/databus23/helm-diff --version master`
and I'm receiving an error.
```
 helmfile diff
Comparing external-dns stable/external-dns
Error: unknown flag: --namespace
Usage:
  diff upgrade [flags] [RELEASE] [CHART]

Examples:
  helm diff upgrade my-release stable/postgresql --values values.yaml

Flags:
      --allow-unreleased       enables diffing of releases that are not yet deployed via Helm
  -h, --help                   help for upgrade
      --reset-values           reset the values to the ones built into the chart and merge in any new values
      --reuse-values           reuse the last release's values and merge in any new values
      --set stringArray        set values on the command line (can specify multiple or separate values with commas: key1=val1,key2=val2)
      --suppress stringArray   allows suppression of the values listed in the diff output
  -q, --suppress-secrets       suppress secrets in the output
  -f, --values valueFiles      specify values in a YAML file (can specify multiple) (default [])
      --version string         specify the exact chart version to use. If this is not specified, the latest version is used

Global Flags:
      --no-color   remove colors from the output

Error: plugin "diff" exited with error

err: exit status 1
```
