### ISSUE TITLE
chartify issues

### ISSUE THREAD

**Issue by jbadeau** [roboll/helmfile#1790]
Hello,

There are issues and pull-requests pending in https://github.com/variantdev/chartify which we are waiting for. Is there a plan here to merge and release?

**Comment by tomassatka** [comment]
Hi @mumoshu 

I have provided local test docu for : https://github.com/variantdev/chartify/issues/9 on win.
Please let me know if that is sufficient for you.

**Comment by mumoshu** [comment]
Finished merging all the pending prs there! Thanks for your cooperation.

**Comment by jbadeau** [comment]
Coolio
