### ISSUE TITLE
Interactive mode with apply command by default

### ISSUE THREAD

**Issue by iamalryz** [roboll/helmfile#1795]
Is there an ability to force Helmfile to use an interactive mode with `helmfile aply` by default? It would be great if it could be configured at the top of `helmfile.yaml`.

**Comment by mumoshu** [comment]
@iamalryz Hey! Unfortunately no. Also, I dont particularly like writing any operational config/knowledge into helmfile.yaml. That can be considered very similar sentiment as you don't/can't define `-auto-approve` of `terraform apply` in a tf file.

**Comment by mumoshu** [comment]
@iamalryz I think we'd better merge this discussion into #1767
