### ISSUE TITLE
UPGRADE FAILED: ... has no deployed releases

### ISSUE THREAD

**Issue by estahn** [roboll/helmfile#180]
```
exec: helm upgrade --install --reset-values cheeky-chick stable/prometheus-cloudwatch-exporter --version 0.1.2 --namespace devops --values /p/prometheus-cloudwatch-exporter-us-east-1/values.yaml
Error: UPGRADE FAILED: "cheeky-chick" has no deployed releases
err: exit status 1
```

Added a new thing to the helmfile but get the above error.

```
  - name: cheeky-chick
    namespace: devops
    chart: stable/prometheus-cloudwatch-exporter
    version: 0.1.2
    values:
      - devops/prometheus-cloudwatch-exporter-us-east-1/values.yaml
```

**Comment by estahn** [comment]
This is probably more related to helm.

https://github.com/kubernetes/helm/issues/4282

**Comment by bgarcial** [comment]
I've performed 

```
⟩ helm upgrade <my-release-name> ./<path-of-my-helm-chart> --install
```
And I can upgrade my helm chart without the need to perform previously

`helm del --purge <my-release-name>`


```
⟩ helm upgrade <my-release-name> ./<path-of-my-helm-chart> --install
Release "<my-release-name>" has been upgraded. Happy Helming!
LAST DEPLOYED: Thu Feb 21 11:50:03 2019
NAMESPACE: default
STATUS: DEPLOYED

RESOURCES:
==> v1/Service
NAME                        TYPE       CLUSTER-IP    EXTERNAL-IP  PORT(S)  AGE
<my-release-name>  ClusterIP  x.x.x.x                   <none>       80/TCP   5d17h

NOTES:
The “help text” for your chart. This will be displayed to your users when they run helm install.
[I] 
~/workspace/ZCRM365/CD-to-AKS · (Deployments±)
⟩ 
```

**Comment by rafaelfelix** [comment]
I could only overcome this by running `helm del --purge <my-release-name>`, then `helmfile apply`.

```bash
$ helm version
Client: &version.Version{SemVer:"v2.13.1", GitCommit:"618447cbf203d147601b4b9bd7f8c37a5d39fbb4", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.13.1", GitCommit:"618447cbf203d147601b4b9bd7f8c37a5d39fbb4", GitTreeState:"clean"}
```

**Comment by mumoshu** [comment]
Thansk for the info!

If it works after `helm del --purge`, you'd like to set `atomic: true` for your relase in `helmfile.yaml`. See the help for `--atomic` flag that has been added to helm recently for more context.

**Comment by mumoshu** [comment]
And probably we'll make it default #512

**Comment by Morriz** [comment]
I don't know about others, but we deploy from a monorepo and setting `atomic: true` would cause the whole deployment to be reverted. Is there a possibility to have a flag that forces a single chart to be atomic? I am getting tired of this error...

**Comment by mumoshu** [comment]
@Morriz Hm? `atomic: true` does exactly that.

**Comment by mumoshu** [comment]
@Morriz Hey! So what you wanted was making only one sub-chart of your umbrella chart to be atomic? If so, that's impossible, and should be a feature request to helm, not helmfile.

**Comment by Morriz** [comment]
I do not remember if the `atomic` flag can be set on one release only. I think I tried, but am not sure. Will try.
