### ISSUE TITLE
A way to error if incorrect version of Helm is used?

### ISSUE THREAD

**Issue by max-rocket-internet** [roboll/helmfile#1813]
Is there a way I can specify in a helmfile that it must be used with Helm version 3.5.4 and nothing older?

**Comment by max-rocket-internet** [comment]
Or at least to block Helm 2?

**Comment by mumoshu** [comment]
Hey! No. There's no such feature today.

**Comment by max-rocket-internet** [comment]
OK thanks as always @mumoshu
