### ISSUE TITLE
Repos fail to fetch if same repo name is used in multiple release configs

### ISSUE THREAD

**Issue by esvirskiy** [roboll/helmfile#1815]
As discussed on Slack (https://sweetops.slack.com/archives/CE5NGCB9Q/p1619566457313300), when running `helmfile lint/apply` against helmfile.yaml with multiple release configs defined that use the same repo names, helmfile will fail with   ```Error: repo <repo> not found```

**Comment by mumoshu** [comment]
@esvirskiy Thanks for helping me isolating this down to a real bug and writing this up! #1816 fixed the issue for me. The next release is going to be huge :)

**Comment by mumoshu** [comment]
BTW It happened only when you  used the same repo concurrently with both helm 2 and 3 so I updated the issue title accordingly.

**Comment by esvirskiy** [comment]
great! thank you very much!
