### ISSUE TITLE
`helmfile lint` don't stop on error

### ISSUE THREAD

**Issue by FWest98** [roboll/helmfile#1826]
Current behaviour seems like `helmfile lint` stops once one of the `helm lint` commands for a particular chart fails (due to finding errors). This makes it quite hard to lint an entire infra setup, especially if you use some third-party charts that helm trips over.

Would it be possible to add some flag or something to not stop processing after an error output from `helm lint`?

**Comment by mumoshu** [comment]
@FWest98 Hey! This does sound like a good feature request. How about adding `--fail-fast=false` to `helmfile lint` so that it runs lint on all the releases?

**Comment by FWest98** [comment]
Why not make it default behaviour? `helm lint` analyses an entire chart and doesn't stop after finding an error, so I would assume that `helmfile lint` would analyse everything as well.

**Comment by mumoshu** [comment]
@FWest98 Thanks! Yeah maybe? If you think making that the default behaviour won't be received as breaking change by anyone, I'm happy to do so.

**Comment by FWest98** [comment]
I don't think so, but maybe others would think this is breaking? I cannot envision a situation in which it would be, at least.

**Comment by mumoshu** [comment]
@FWest98 Thanks! Let's try.
