### ISSUE TITLE
Add `dig` templating function

### ISSUE THREAD

**Issue by z0rc** [roboll/helmfile#1827]
I need new function [`dig`](https://github.com/Masterminds/sprig/pull/254) which is available since sprig [3.2.0](https://github.com/Masterminds/sprig/releases/tag/v3.2.0). It's already usable in current helm for templating needs, but helmfile is missing it.

Also there might be some implementation specific details, as initial availability in helm had [some issues](https://github.com/helm/helm/issues/9266) with it.

**Comment by mumoshu** [comment]
@z0rc Hey! We have a better variant named `get`. Perhaps you'll find it useful? https://github.com/roboll/helmfile/issues/1866#issuecomment-851360988

**Comment by z0rc** [comment]
Yes helmfile's `get` works very similar to `dig`. Still it might be worth adding `dig` if there is plan to keep feature parity with helm templating.

**Comment by z0rc** [comment]
Closing in favor of https://github.com/roboll/helmfile/issues/1646
