### ISSUE TITLE
Add --skip-diff-on-install to helmfile diff

### ISSUE THREAD

**Issue by dudicoco** [roboll/helmfile#1840]
Currently, only the `helmfile apply` command supports the `--skip-diff-on-install` flag.

We are running `helmfile diff` in our CI during a PR, as i'm sure many others do, and post the output to a GitHub comment. When there are many new releases and the output exceeds the maximum allowed characters in the comment's body we get an error - `'Body is too long (maximum is 65536 characters)'`.

I believe this issue can be solved by adding the `--skip-diff-on-install` flag to `helmfile diff` as well.

**Comment by mumoshu** [comment]
@dudicoco Sounds good! Would you mind submitting a PR for this?
