### ISSUE TITLE
template command does not print triple dash

### ISSUE THREAD

**Issue by Morriz** [roboll/helmfile#1848]
Could it be possible to print `---` underneath every file that is output by the `template` command? If I now pass the output to a tool like kubernetes-score it complains about invalid yaml.

**Comment by mumoshu** [comment]
@Morriz It should have `---` before every entry in the template output and I can see it's working like that.
If it's missing for you, how can I reproduce it?

**Comment by Morriz** [comment]
Hmmm...strange...we are using `0.138.7` and don't see that. I am running plain helmfile command in a docker container. Maybe those triple dashes are going to stderr and maybe that is not captured? Helmfile also decided to log the hooks output to stderr, right?

**Comment by mumoshu** [comment]
Yeah, I think so. Maybe sharing a github repo containing the whole example and steps to reproduce issue would better help.

**Comment by Morriz** [comment]
Closing as I managed to track it down to our poorly written regular expression removing lines with white space and dashes.
