### ISSUE TITLE
Feature request: set default parameters for subcommands

### ISSUE THREAD

**Issue by lemaral** [roboll/helmfile#1853]
It would nice to be able to specify default parameters for each subcommand.
For instance (this is useful if you really want to the diff inside configurations stored as secrets)
diff: --show-secrets
would use this parameter for every call to helmfile diff (instead of having to use helmfile diff --args --show-secrets every time)
It could be in helmDefaults or even maybe per release

Thanks

**Comment by mumoshu** [comment]
@lemaral Hey! Are you trying to use `--args`? Please don't use it. Instead, raise separate feature requests add specific flags to specific helmfile sub-command.

In your case, could it  be `helmfile diff --show-secrets`, which already exists?

If you literally meant a way to configure default subcommand flags in helmfile.yaml- helmfile isn't designed that way. helmfile's motto is letting the user to provide operational concerts via command-line flags, and provide desired state of your helm releases in helmfile.yaml.

**Comment by lemaral** [comment]
Yes, thanks, the helmfile --show-secrets option is more recent than my use of it :) I have upgraded and will use it now.
I understand the philosophy, but it seems less flexible for me, as for instance we will have to wait for a new helmfile version every time there is a change in the upstream (this is the situation which forced me to use diff --args --show-secrets). Anyway, thanks for this great product, and I will look to your terraform provider now :)

**Comment by mumoshu** [comment]
> it seems less flexible for me, as for instance we will have to wait for a new helmfile version every time there is a change in the upstream

@lemaral Thansk for your feedback. That's actually a good point!
