### ISSUE TITLE
Chartify renders objects with incorrect apiVersion

### ISSUE THREAD

**Issue by alexgaganov** [roboll/helmfile#1864]
Hey guys,

Just another issue I've noticed with Chartify and Helmfile: while trying to install `prometheus-community/kube-prometheus-stack` chart with Helmfile and setting `forceNamespace` key in my `helmfile.yaml`, the Ingress object is generated with `apiVersion: networking.k8s.io/v1` which is not supported by our current K8s version. So it seems that the logic in `kube-prometheus-stack.ingress.apiVersion` [helper function](https://github.com/prometheus-community/helm-charts/blob/main/charts/kube-prometheus-stack/templates/_helpers.tpl#L104) is just ignored.

And then, when I'm trying to do, for example, `helmfile diff` I get the following error:
```
error: unable to recognize "/var/folders/km/x2g0dhc17mn7sb5czxsmz3gw0000gp/T/chartify134751137/arn:aws:eks:eu-west-1:XXX:cluster/XXX/monitoring/prometheus-operator-ec2/kube-prometheus-stack/files/templates/prometheus/ingress.yaml": no matches for kind "Ingress" in version "networking.k8s.io/v1"
```

However, once I remove the `forceNamespace`, everything is working just fine.

Could you please assist?

How to reproduce: basically the configurations are the same as I described in #1857, but the cluster version should be the one that doesn't support the `networking.k8s.io/v1` API version yet(in our case it's 1.18, which only supports `networking.k8s.io/v1beta1`).

K8s version: 1.18
Helm version: 3.5.4
Helmfile version: 0.139.7

Thanks a lot,

Alex.

**Comment by mumoshu** [comment]
@alexgaganov Hey! I thought you had to pass `--api-versions` to `helm template` to make that kind of helper to work.

How did you pass API versions to the chart when it worked without `chartify`?

**Comment by alexgaganov** [comment]
@mumoshu hey, and thanks for your help! Actually, I never had to pass the API versions directly, it was always taken care of behind the scenes. But I will try playing with passing the versions explicitly, though maintaining this in the long run might become a real pain.

**Comment by mumoshu** [comment]
@alexgaganov Hey! Thanks. Oh really- so does `helm template` somehow retrieve the available API versions from the live k8s server? Do you have any insight on how it's working usually?

**Comment by alexgaganov** [comment]
@mumoshu I don't think `helm template` is aware of the cluster's K8s version, however, `helmfile diff` is running `helm diff upgrade` under the hood which has to be aware, otherwise, how would it generate the diff. So if I run `helm/helmfile template` the objects are generated with `networking.k8s.io/v1` version, which I think is expected.

Having said that, I've noticed that Helm 3.6.0 introduced a new `--kube-version` flag, which allows to give a hint to Helm about which K8s version should be used. So running `helmfile template` with this flag generates the correct version without Chartify, and incorrect with Chartify.

**Comment by mumoshu** [comment]
@alexgaganov Ah gotcha! Thanks a lot for clarifying.

`chartify` doesn't use `helm upgrade --install --dry-run`, but `helm template`, to render the templates to be included in the temporary chart. The temporary chart contains the rendered files only, which doesn't contain any go template expressions. So running `helm diff` on the temporary chart look like not respecting kube version.

So the only way forward would be to (1) enhance helmfile to somehow pass `kube-version` to `chartify` and (2)enhance chartify to pass `kube-version` to the `helm template`.

> So running helmfile template with this flag generates the correct version without Chartify, and incorrect with Chartify.

You confirmed it by passing kube-version via the `--args` flag of helmfile right?
It's very difficult to parse `--args` to extract only `--kube-version` to be passed to chartify. I'd rather add a dedicated flag to helmfile for that, that can be used like `helmfile --kube-version=$K8S_VER diff`. Does that sound good to you?

**Comment by alexgaganov** [comment]
> You confirmed it by passing kube-version via the --args flag of helmfile right?

Exactly.
> Does that sound good to you?

I think the best way would be to add it under `helmDefaults`, this way the K8s version can be controlled on a per environment basis. Not familiar with the internal workings though, so it might not be feasible.
