### ISSUE TITLE
Cannot use conditional variables in helmfile templating

### ISSUE THREAD

**Issue by dudicoco** [roboll/helmfile#1866]
When using an `{{ if .myVar }}` statement, if `myVar` is not defined, helmfile will fail. 
In helm templating, the same statement will not fail if the variable is not defined.

Example:
```
{{ range $key, $value := .releases }}
- name: {{ .name }}
  chart: {{ .chart }}
  version: {{ .version }}
  installed: {{ .installed }}
  kubeContext: {{ $kubecontext }}
  namespace: {{ $namespace }}
  timeout: {{ .timeout }}
{{ if .needs }}
  needs:
{{ range $item := .needs }}
  - {{ printf "%s/%s" $kubecontext $item }}
{{ end }}
{{ end }}
```

If `needs` is not defined, the above code will fail with `error during helmfile.yaml.part.1 parsing: template: stringTemplate:40:8: executing "stringTemplate" at <.needs>: map has no entry for key "needs"`

A similar code in `helm` would not fail.

What is the correct way to do this in helmfile?

**Comment by dudicoco** [comment]
@mumoshu

**Comment by mumoshu** [comment]
@dudicoco Hey! That's by design, to avoid silently ignoring errors. Could you use `dig` instead?

**Comment by dudicoco** [comment]
@mumoshu looks like the `dig` function is not included: `error during helmfile.yaml.part.1 parsing: template: stringTemplate:38: function "dig" not defined`.

**Comment by mumoshu** [comment]
Sry told you wrong one. Try `get` instead https://github.com/roboll/helmfile/blob/ae942c5288895c84c79171e5446773e4cb41c4ce/pkg/tmpl/get_or_nil_test.go#L15

**Comment by dudicoco** [comment]
@mumoshu it doesn't seem like it's possible to do this with the `get`/`hasKey` functions, as helmfile checks the `if` statement even when it shouldn't.

For example:
```
{{ if hasKey . "myMap") }}
myMap:
  var1: {{ get .myMap "var1") }}
  var1: {{ get .myMap "var2") }}
{{ end }}
```

The above will fail if `myMap` doesn't exist.
Any way to make this work?

**Comment by mumoshu** [comment]
@dudicoco Sorry I don't get it. Could you share the exact error message you're getting?

**Comment by dudicoco** [comment]
Managed to solve this with the following:

```
{{ if hasKey . "myMap") }}
myMap:
  var1: {{ .myMap.var1 }}
  var2: {{ .myMap.var2 }}
{{ end }}
```

Thanks @mumoshu!

**Comment by mumoshu** [comment]
@dudicoco Great! Thanks for sharing. Re `get` you seem to have had wrong ordering of args, it should be `get "var1" .myMap` rather than `get .myMap "var1"`.

**Comment by dudicoco** [comment]
@mumoshu thanks, this seems to be opposite of the sprig documentation: http://masterminds.github.io/sprig/dicts.html

```
get $myDict "key1"
```

**Comment by mumoshu** [comment]
@dudicoco Yup. Spri's is available via `springGet` as written in https://github.com/roboll/helmfile#templating
