### ISSUE TITLE
Support --insecure-skip-tls-verify

### ISSUE THREAD

**Issue by AssafKatz3** [roboll/helmfile#1871]
Hi,

While this option is bad practice, sometime this shortcut is required temporary. Currently I couldn't manage to overcome through helmfile over the error (I used export of GODEBUG as temporary workaround):

`Error: looks like "https://repository.xxx.local/repository/HelmRepository/" is not a valid chart repository or cannot be reached: Get "https://repository.xxx.local/repository/HelmRepository/index.yaml": x509: certificate relies on legacy Common Name field, use SANs or temporarily enable Common Name matching with GODEBUG=x509ignoreCN=0`

Base on example in Read Me I suggest adding such option skipTlsVerify:
```
- name: insecure
   url: https://charts.my-insecure-domain.com
   caFile: optional_ca_crt
   skipTlsVerify: true
```

Thanks

**Comment by AssafKatz3** [comment]
> @AssafKatz3 Hey! This seems like a valid faeture request. I'd prefer `skipTLSVerify`. Would you mind submitting a PR?

Hi,

I don't mind the name. I wouldn't be able to add PR to legal issues.

Thanks

**Comment by mumoshu** [comment]
OK. I wouldn't be able to add it anytime soon due to the lack of spare time, but I'll gladly review it if anyone could submit a PR.

**Comment by andrascz** [comment]
There is another workaround:
1. manually edit the helm repository config (`$HOME/.config/helm/repositories.yaml`) where you can add the `insecure_skip_tls_verify: true` option
1. use `--skip-deps` with helmfile to not update helm repositories
