### ISSUE TITLE
Dynamic helmfile per external information

### ISSUE THREAD

**Issue by AssafKatz3** [roboll/helmfile#1875]
Hi,

Maybe I missed it, but I couldn't understand how to do it. I have dynamic YAML in format of:
```
image-name1: version1
image-name2: version2
```
I want to add this list to helmfile (all other parts of images, like repository are constant) that will run after the constant parts (e.g. global objects).

Per my understand, helmfiles option would allow me to do it but:

1. It is always run before the current helmfile (I can workaround it)
2. It doesn't support gotmpl option (that I would be able to use in order to convert it to real helmfile.yaml that I need)

Did I miss or this is really isn't supported and I will need to find other templating engine for issue 2?

Thanks

**Comment by mumoshu** [comment]
@AssafKatz3 Sorry I don't really understand what you're trying to do. But doesn't something like the below work?

```
{{ $imageSet := readFile "external.yaml" | fromYaml }}

releases:
- name: foo
  chart: charts/foo
  values:
  - image:
      tag: {{ $dict | get "image-name1" }}
- name: bar
  chart: charts/bar
  values:
  - image:
      tag: {{ $dict | get "image-name2" }}
```

**Comment by AssafKatz3** [comment]
@mumoshu The list is dynamic so I can have in one environment for & bar, and in another foo only and still other foo, bar & baz. Moreover I want to support option to add micro service without changing the helmfile. So I need something like:
```
releases:
{{ range $image, $version := readFile "external.yaml" | fromYaml }}
- name: {{ $image }}
  chart: charts/{{ $image }}
  values:
  - image:
      tag: {{ $version }}
{{ end }} 
```

Thanks

**Comment by mumoshu** [comment]
@AssafKatz3 Hey! Thanks for clarifying. I'm still unsure though that what you're asking. Your example looks fine.

> The list is dynamic so I can have in one environment for & bar, and in another foo only and still other foo, bar & baz.

Perhaps you wanted one helmfile environment per `$image`, rather than one release per `$image` as your above example?

**Comment by AssafKatz3** [comment]
> @AssafKatz3 Hey! Thanks for clarifying. I'm still unsure though that what you're asking. Your example looks fine.
> 
> > The list is dynamic so I can have in one environment for & bar, and in another foo only and still other foo, bar & baz.
> 
> Perhaps you wanted one helmfile environment per `$image`, rather than one release per `$image` as your above example?

Hi,

The problem with this idea is that the list is dynamic, the developers needs on same environment different list of micro services (the ones that they are working on them now). Unfortunately, the environment is constant (it contains a lot of other parts), so the definition of environment itself cannot be merged.

I can define helmfile per $image but I still need to include it conditionally so it won't help me too much.

Thanks

**Comment by mumoshu** [comment]
@AssafKatz3 How about this:

```
values:
- project: image-name1

---
{{ $split := split "-" 2 .Environment.Name }}
{{ $env = $split._0 }}
environments:
  {{ $env }}:
    values:
    - environments/{{ $env }}.values.yaml
---
{{ $split := split "-" 2 .Environment.Name }}
{{ $env = $split._0 }}
{{ $targetImage = $split._1 }}
{{ range $image, $version := readFile "external.yaml" | fromYaml }}
{{ if eq $image $targetImage }}
releases:
- name: {{ $image }}
  chart: charts/{{ $image }}
  values:
  - image:
      tag: {{ $version }}
{{ end }}
{{ end }}
```

Then run `helmfile -e prod-image-name1 apply` to deploy only `image-name1` into the `prod` environment.

**Comment by AssafKatz3** [comment]
> @AssafKatz3 How about this:
> 
> ```
> values:
> - project: image-name1
> 
> ---
> {{ $split := split "-" 2 .Environment.Name }}
> {{ $env = $split._0 }}
> environments:
>   {{ $env }}:
>     values:
>     - environments/{{ $env }}.values.yaml
> ---
> {{ $split := split "-" 2 .Environment.Name }}
> {{ $env = $split._0 }}
> {{ $targetImage = $split._1 }}
> {{ range $image, $version := readFile "external.yaml" | fromYaml }}
> {{ if eq $image $targetImage }}
> releases:
> - name: {{ $image }}
>   chart: charts/{{ $image }}
>   values:
>   - image:
>       tag: {{ $version }}
> {{ end }}
> {{ end }}
> ```
> 
> Then run `helmfile -e prod-image-name1 apply` to deploy only `image-name1` into the `prod` environment.

Hi,

I don't understand the suggestion. Where will I put the third part (after second --- )?

Thanks

**Comment by mumoshu** [comment]
@AssafKatz3 You can put everything into a single `helmfile.yaml`. You want to dynamically generate a helmfile.yaml sharing some common setup, and you also want to include only one "targeted" release in the generated helmfile.yaml, right?

**Comment by AssafKatz3** [comment]
> @AssafKatz3 You can put everything into a single `helmfile.yaml`. You want to dynamically generate a helmfile.yaml sharing some common setup, and you also want to include only one "targeted" release in the generated helmfile.yaml, right?

Hi,

This seems good but don't work, I started with code that you put and modify it to match what I need:

```
values:
- project: image-name1
- env: {{ (split "-" .Environment.Name)._0 }}

---
environments:
  prod:
    values:
    - external.yaml
---
releases:
{{ range $image, $version := (readFile "external.yaml" | fromYaml) }}
- name: {{ $image }}
  chart: charts/{{ $image }}
  values:
  - image:
      tag: {{ $version }}
{{ end }}

Then I ran:
`helmfile  -e prod  template`

And got:
`err: no releases found that matches specified selector() and environment(prod), in any helmfile`

I am not sure what is the problem.

Thanks
```

**Comment by mumoshu** [comment]
@AssafKatz3 Run it with `helmfile --debug apply` and see what the rendered helmfile.yaml looks like. Perhaps you've some templating errro that resulted in missing releases

**Comment by AssafKatz3** [comment]
> @AssafKatz3 Run it with `helmfile --debug template` and see what the rendered helmfile.yaml looks like. Perhaps you've some templating error(s) that resulted in missing releases, or `external.yaml` isn't parsed correctly

Hi,

I would probably mentioned it but I got effectively nothing (or maybe just didn't understand :-( ).

For 'helmfile -debug -e prod  template' I got:
```
processing file "helmfile.yaml" in directory "."
first-pass rendering starting for "helmfile.yaml.part.0": inherited=&{prod map[] map[]}, overrode=<nil>
first-pass uses: &{prod map[] map[]}
first-pass rendering output of "helmfile.yaml.part.0":
 0: values:
 1: - project: image-name1
 2: - env: prod 
 3: 

first-pass produced: &{prod map[] map[env:prod project:image-name1]}
first-pass rendering result of "helmfile.yaml.part.0": {prod map[] map[env:prod project:image-name1]}
vals:
map[env:prod project:image-name1]
defaultVals:[map[project:image-name1] map[env:prod]]
second-pass rendering result of "helmfile.yaml.part.0":
 0: values:
 1: - project: image-name1
 2: - env: prod 
 3: 

err: no releases found that matches specified selector() and environment(prod), in any helmfile
```

I worked without environment (up to fictitious chart names), i.e. running 'helmfile -debug   template ' print:
```
processing file "helmfile.yaml" in directory "."
first-pass rendering starting for "helmfile.yaml.part.0": inherited=&{default map[] map[]}, overrode=<nil>
first-pass uses: &{default map[] map[]}
first-pass rendering output of "helmfile.yaml.part.0":
 0: values:
 1: - project: image-name1
 2: - env: default 
 3: 

first-pass produced: &{default map[] map[env:default project:image-name1]}
first-pass rendering result of "helmfile.yaml.part.0": {default map[] map[env:default project:image-name1]}
vals:
map[env:default project:image-name1]
defaultVals:[map[project:image-name1] map[env:default]]
second-pass rendering result of "helmfile.yaml.part.0":
 0: values:
 1: - project: image-name1
 2: - env: default 
 3: 

merged environment: &{default map[] map[env:default project:image-name1]}
first-pass rendering starting for "helmfile.yaml.part.1": inherited=&{default map[] map[env:default project:image-name1]}, overrode=<nil>
first-pass uses: &{default map[] map[env:default project:image-name1]}
first-pass rendering output of "helmfile.yaml.part.1":
 0: environments:
 1:   prod:
 2:     values:
 3:     - external.yaml

first-pass produced: &{default map[] map[env:default project:image-name1]}
first-pass rendering result of "helmfile.yaml.part.1": {default map[] map[env:default project:image-name1]}
vals:
map[env:default project:image-name1]
defaultVals:[]
second-pass rendering result of "helmfile.yaml.part.1":
 0: environments:
 1:   prod:
 2:     values:
 3:     - external.yaml

merged environment: &{default map[] map[env:default project:image-name1]}
first-pass rendering starting for "helmfile.yaml.part.2": inherited=&{default map[] map[env:default project:image-name1]}, overrode=<nil>
first-pass uses: &{default map[] map[env:default project:image-name1]}
first-pass rendering output of "helmfile.yaml.part.2":
 0: releases:
 1: 
 2: 

first-pass produced: &{default map[] map[env:default project:image-name1]}
first-pass rendering result of "helmfile.yaml.part.2": {default map[] map[env:default project:image-name1]}
vals:
map[env:default project:image-name1]
defaultVals:[]
second-pass rendering result of "helmfile.yaml.part.2":
 0: releases:
 1: 
 2: - name: image-name1
 3:   chart: charts/image-name1
 4:   values:
 5:   - image:
 6:       tag: version1
 7: 
 8: - name: image-name2
 9:   chart: charts/image-name2
10:   values:
11:   - image:
12:       tag: version2
13: 
14: 
```

And a lot of errors about missing charts (which are fine...).

Thanks

**Comment by AssafKatz3** [comment]
Hi,

I understood from @mumoshu answers that helmfile,yaml itself is passing through go-template (something that I at least couldn't understand from documentation) and therefore I can use:

releases:
```
{{ range $image, $version := (readFile "external.yaml" | fromYaml) }}
- name: {{ $image }}
  chart: charts/{{ $image }}
  values:
  - image:
      tag: {{ $version }}
{{ end }}

environments:
  prod:
    values:
    - external.yaml
```

And from my point of view, this is valid solution, and I will use it.

Thanks

**Comment by mumoshu** [comment]
Glad to see it worked.

Just my two cents but you'd better have the environments parts separated from the rest of your helmfiel.yaml, to avoid nasty chicken-and-egg problem.

```
environments:
  prod:
    values:
    - external.yaml

---
releases:
{{ range $image, $version := (readFile "external.yaml" | fromYaml) }}
- name: {{ $image }}
  chart: charts/{{ $image }}
  values:
  - image:
      tag: {{ $version }}
{{ end }}
```
