### ISSUE TITLE
Go-getter issue with AWS Secret Manager

### ISSUE THREAD

**Issue by sf-jmarcou** [roboll/helmfile#1888]
Since recent upgrade, the fetchSecretValue function is unable to fetch secret on AWS Secret Manager.

## How to reproduce:

Create the AWS Secret:
```
aws secretsmanager create-secret --name mytestingsecret
aws secretsmanager put-secret-value --secret-id mytestingsecret --secret-string "secret-string"
# tear down with: aws secretsmanager delete-secret --secret-id mytestingsecret
```

Write the helmfile file:
```
# helmfile.yaml
---
environments:
  default:
    values:
      - hello: {{fetchSecretValue "ref+awssecrets:///mytestingsecret" }}
```

## Working command
Execute the template rendering command with working version of helmfile:
```
helmfile_v0.139.0 --allow-no-matching-release template && echo OK || echo KO
awssecrets: successfully retrieved key=mytestingsecret
err: no releases found that matches specified selector() and environment(default), in any helmfile
OK
```
## Non-working command
Execute the template rendering command with non-working version of helmfile:
```
helmfile_v0.139.1 --allow-no-matching-release template && echo OK || echo KO
in ./helmfile.yaml: error during helmfile.yaml.part.0 parsing: template: stringTemplate:5:17: executing "stringTemplate" at <fetchSecretValue "ref+awssecrets:///mytestingsecret">: error calling fetchSecretValue: expand awssecrets:///mytestingsecret: get parameter: ResourceNotFoundException: Secrets Manager can't find the specified secret.
KO
```

Last known working version is v0.139.0.
The bug seems to be introduced in v0.139.1, tested from v0.139.1 to v0.139.9.

**Comment by gugacavalieri** [comment]
Hi @sf-jmarcou ! This worked for me:

Change 
`{{fetchSecretValue "ref+awssecrets:///mytestingsecret" }}`

Into:
`- {{ fetchSecretValue "ref+awssecrets://mytestservice" }}`

Here are the supported formats:
https://github.com/variantdev/vals#aws-secrets-manager

**Comment by sf-jmarcou** [comment]
It works!

Interesting our config was working until v0.139.0 and breaks from v0.139.1.
I guess `variantdev/vals` have implement a breaking change.

We can now just adjust our config accordingly and finally upgrade our helmfile bin.
Closing the issue.

Thank you @gugacavalieri for taking time to comment. :+1:

**Comment by adecchi** [comment]
Hi, I have a helm chart template and I would like to integrate with helmfile to render my secretes.yaml and my deployment.yaml template and complete the secrets from aws secrets manager to then map as environment variable for the POD. 
I could not find any documentation, probably someone can help me to find it or give me some tips.
Kind regards
