### ISSUE TITLE
support --pass-credentials option for helm repositories (introduced in helm 3.6.1)

### ISSUE THREAD

**Issue by andrascz** [roboll/helmfile#1890]
Using helm v3.6.1 might break usage of some private repositories. There is no way at the moment to overcome this through `helmfile`. The workaround mentioned [here](https://github.com/roboll/helmfile/issues/1871#issuecomment-865029230) works though.

See: https://github.com/helm/helm/releases/tag/v3.6.1 and https://github.com/helm/helm/security/advisories/GHSA-56hp-xqp3-w2jf for reference.

**Comment by nerney** [comment]
seeing this issue as well 
using helmfile to authenticate with artifactory
after helm patch, needed pass creds flag for helm repo add command. trying to find workaround for now...

**Comment by anessi** [comment]
That's already implemented with https://github.com/roboll/helmfile/pull/1899, correct?

**Comment by andrascz** [comment]
I suppose yes.
