### ISSUE TITLE
feat. helmfile render

### ISSUE THREAD

**Issue by nhomble** [roboll/helmfile#1930]
I am enjoying some of the advanced features, including referencing other helmfiles with the configuration:
```yml
helmfiles:
  - path: to/other/manifest/syntax
```

akin to `helm template chart/` might do, I would find it helpful for debugging to have a similar subcommand for `helmfile` to print the entire manifest with releases across files combined. Additionally, any templating on the manifest could be done as well at this stage.

**Comment by nhomble** [comment]
or maybe call the subcommand `expand` to take vocab from [source](https://github.com/roboll/helmfile/blob/ccd81de77e0811ccaeaae5ed00164c2299c17654/pkg/state/state.go#L2590)

**Comment by 4c74356b41** [comment]
yeah, definitely. debugging this is a nightmare

**Comment by mumoshu** [comment]
> print the entire manifest with releases across files combined

What do you mean by this? If you literally meant "manifest", you should be able to use `helmfile template` to render all the K8s resources across all the sub-helmfiles.

Otherwise try `helmfile build`.

**Comment by 4c74356b41** [comment]
`build` is perfect, thanks!

**Comment by nhomble** [comment]
sorry @mumoshu you're right `helmfile build` does what I am looking for - I got hung up on `helmfile template` doing more than I needed when pulling in sub-helmfiles.
