### ISSUE TITLE
`helm` and `helmfile` dependency matrix - which versions are compatible?

### ISSUE THREAD

**Issue by gczarnocki** [roboll/helmfile#1953]
Hello `helmfile` community! I have a question because I could not find it in documentation. Is there any dependency matrix between `helm` and `helmfile` when it comes to version compatibility? Which version of `helm` can be used with a particular version of `helmfile`?

From what I know, `helmfile` is calling `helm` as an external command.

In your `Build info` (CircleCI), e.g. for version `v0.139.9`, `helm` version used equals: `2.17.0`.

Can you help with determining version compatibility?

**Comment by gczarnocki** [comment]
I found in `.circle/config.yml` the following lines: https://github.com/roboll/helmfile/blob/master/.circleci/config.yml#L151-L153

```
          matrix:
            parameters:
              helm-version: ["v2.17.0", "v3.4.2", "v3.5.4"]
```

Are those `helm` versions working with latest `helmfile`, right? (e.g. `0.140.0`)?

**Comment by yurrriq** [comment]
We use Helm 3.6.3 with Helmfile 0.140.0.

**Comment by gczarnocki** [comment]
Great, thanks for the input! Closing then.
