### ISSUE TITLE
Proposal: An option to mark chart as not installed.

### ISSUE THREAD

**Issue by jamielennox** [roboll/helmfile#197]
Hey, 

I'd like a way to describe a chart as something that should be deleted by helmfile or something that is not present in an environment. 

So my use case is that I use helmfile to install a consistent set of packages across multiple clusters, so things like external-dns, newrelic-infra, cluster-autoscaler, etc should be installed on staging, prod and any others via CI/CD.

I'd like a way when changing this infrastructure and using a new package to say like 
```
installed: False
```
or some similar property to be able to remove old packages from all the clusters when something has replaced it. 

The extension of that would be that i could then use this to do per environment tests, like: 
```
installed: {{ requiredEnv "ENV_NAME" in ['production'] }}
```
My python is showing through, i need to look up the real syntax. But for example newrelic probably doesn't need to be on staging, but makes sense in production.

Obviously defaults to true and values etc would simply be ignored if installed=False to allow them to still be passed in places that do make sense.

Thanks,

**Comment by osterman** [comment]
What about using a combination of labels and selectors? E.g. add a label for `installed: false` and then use a selector to destroy all releases with that condition.

**Comment by mumoshu** [comment]
@jamielennox Would enclosing the whole optional release inside a `{{ if eq (requiredEnv "ENV_NAME") "production" }}` block be a good-enough workaround for your problem?

Do you have specific reason(s) to prefer `enabled: [true|false]` over that? Any input is welcomed. Thx!

**Comment by jamielennox** [comment]
So the reason i was suggesting `installed:` was that it would actively uninstall a chart that may previously have been installed. I use labels in CI pipelines to select only the things that should be installed there but setting this up so it would remove things that are no longer required is not easy. This adding and removing of releases would better seem to match the command name of `sync`.

Now obviously that's idempotent so in most cases it will have the same actual effect as an `enabled:` switch as it wont find an existing install.

This would give me git history of when things were removed from the cluster as I want this particular tiller install to be entirely managed by helmfile.

**Comment by sstarcher** [comment]
If we wanted something to be entirely managed by helmfile I would think a `helmfile sync --purge` option which would remove anything not in the current helmfile would be the easiest path.

**Comment by jamielennox** [comment]
Having helmfile delete anything that's not in it's list is a big change and will be hard with the helmfile.d layout.

This is why I was thinking i could explicitly mark things to not be installed and they'd be removed. Because it's a new option that would default to installed true it shouldn't need the additional flag.

**Comment by mumoshu** [comment]
Related: https://github.com/roboll/helmfile/issues/240#issuecomment-416797869

**Comment by sstarcher** [comment]
@mumoshu responded over - https://github.com/roboll/helmfile/issues/194#issuecomment-416937228
