### ISSUE TITLE
Comments getting parsed in template

### ISSUE THREAD

**Issue by damobrisbane** [roboll/helmfile#1972]
I am finding variables in comments are getting dereferenced? Problem is can be hard to debug, ie have commented out some code, so dont expect it to cause a problem, but will fail deployments:

```
values:
- key1: {{ .Values.mygoodvar }}
  # key1: {{ .Values.my_non_existent_var }}
 key2: ...
```

will cause "map has no entry for key my_non-existent_var" failure on helmfile apply

**Comment by mumoshu** [comment]
I hear you, but this is by-design. Helmfile renders the whole file as a go template first, and then parse the output as a plain YAML. Any go template expression in your file is parsed in the first phase, hence the error

Technically it can be handled more gracefully IF anyone contributed a reliable "Go template parser that is aware of YAML comments" but I don't think that makes sense outside of Helmfile.

I beileve you'd better use Go template comments. That is, each region that is denoted by a starting `{{/*` and ending  `*/}}` is treat as a comment by Go template. 

https://pkg.go.dev/text/template#hdr-Actions

**Comment by damobrisbane** [comment]
Thanks Mumoshu. It would be nice to put this in the documentation somehow. I searched _comment_ on Readme and doesnt bring up anything. For experienced coders not a problem, but for inexperienced, another issue to unpack. Also, if not done right, then cause of bugs, like:

```
# {{ htpaswd ... ... }}
```

Will generate a state change everytime. Very poor. Would be clearer then to not use "#" at all. Different ways of doing things (two ways to comment), with different behaviour each time, is less than ideal. 

Cheers

**Comment by mumoshu** [comment]
Thanks for the feedback!

I'd appreciate it if you could submit a pull request for that. I just don't understand how I can improve it myself and it's hard for me to decide to spend my own time on it, to keep my mental stability.

I do remember I've answered on this matter several times in the GitHub issues and the slack channel so I thought there should be enough chance to know about it, but apparently not.

While maintaining several open-source projects, I've been asked to answer various questions. One asks without reading the doc. Another one asks without reading issues. Yet another one asks without reading the Slack channel. To be clear that's not anyone's fault. But I just don't know what works 100% yet and what to do for your suggestion.

**Comment by damobrisbane** [comment]
Yeh leave. On reflection I think this is an unsolvable issue, a clash of two paradigms, yaml and go.
