### ISSUE TITLE
String concatenation with helmfile and vals

### ISSUE THREAD

**Issue by habc12** [roboll/helmfile#1984]
I want to use [vals](https://github.com/variantdev/vals) to access values in a terraform state file. 

**values.yaml**
`
   key: ref+tfstate://path/to/some.tfstate/aws_vpc.main.id
`

Then in values.gotmpl.yaml I want to reference this `key`:

**values.gotmpl.yaml**
`arn: {{ .Values.key }}`

I get the expected result of: `arn: 123`. 

However, when I try to concatenate multiple variables  `arn: {{ .Values.key }}-{{ .Values.key }}` I get this unexpected issue where the first bracket gets parsed correctly but everything afterward doesn't 
`arn: 123-ref+tfstate://path/to/some.tfstate/aws_vpc.main.id`.

**The error is:**
`reading value for tfstate://path/to/some.tfstate/aws_vpc.main.id-ref: function not defined: ref/0`

So `-ref+` causes helmfile to fail because it doesn't know what that means.

How can I get access to multiple variables in the same line and concat them?

**Helmfile version**
`helmfile version v0.139.9`

**Comment by habc12** [comment]
> I don't understand your exact issue, but you can try to work around it by trying to put it all in a single expression:
> 
> ```
> {{ printf "%s-%s" .Values.key .Values.key }}
> ```

I get the same error, basically the first expression expands correctly so `123`. But after that the hyphen and the literal value gets added, `123-ref+tfstate://path/to/some.tfstate/aws_vpc.main.id`.

I would like `123-123`.

If there is a way to have my values.yaml file `built` first, for example: 

**values.yaml**
key: ref+tfstate://path/to/some.tfstate/aws_vpc.main.id 

will turn into

**values.yaml**
key: 123

Then this will work for me as well.

Hope this clears things up!

**Comment by bradym** [comment]
@habc12 Have you tried using the `fetchSecretValue` function? It's documented at https://github.com/roboll/helmfile/blob/master/docs/remote-secrets.md#fetching-single-key

Try something like this in your `values.gotmpl.yaml`

```
arn: {{ .Values.key | fetchSecretValue }}-{{ .Values.key | fetchSecretValue }}
```

**Comment by habc12** [comment]
> bradym

Brilliant! This is exactly what I needed, thanks!
