### ISSUE TITLE
Kustomize transformers doesn't work for local charts

### ISSUE THREAD

**Issue by szymonrychu** [roboll/helmfile#1991]
# Affected versions:

all that support kustomize transformers (since `0.135.0`)

# Behaviour:

`jsonPatches` `strategicMergePatches` don't work for local helm charts. Helmfile exits with error:

```
Error: accumulating resources: accumulation err='accumulating resources from 'helmx.1.rendered/ingress-nginx-controller/templates/controller-rolebinding.yaml': evalsymlink failure on '/tmp/chartify313741024/<redacted>-5b78b4c9fd/helmx.1.rendered/ingress-nginx/templates/controller-rolebinding.yaml' : lstat /tmp/chartify313741024/<redacted>-5b78b4c9fd/helmx.1.rendered: no such file or directory': evalsymlink failure on '/tmp/chartify313741024/<redacted>-5b78b4c9fd/helmx.1.rendered/ingress-nginx/templates/controller-rolebinding.yaml' : lstat /tmp/chartify313741024/<redacted>-5b78b4c9fd/helmx.1.rendered: no such file or directory
```

It seems, that files are there- or nearly there- helmfile searches for them in:

`/tmp/chartify313741024/<redacted>-5b78b4c9fd/helmx.1.rendered/ingress-nginx/templates/controller-rolebinding.yaml`

while the files are actually in:
`/tmp/chartify313741024/<redacted>-5b78b4c9fd/ingress-nginx/templates/controller-rolebinding.yaml`

It seems that it might be caused by integration with `helm-x`, maybe the problem is there.

**Comment by tomassatka** [comment]
@szymonrychu i would suggest to look here into variantdev/chartify. 
As last time similar behavior was fixed by following PR: https://github.com/variantdev/chartify/pull/8

You could also check if the buggy behavior is only on win or also on linux

**Comment by tomassatka** [comment]
Found the issue. Fixed and made PR: https://github.com/variantdev/chartify/pull/13

**Comment by mumoshu** [comment]
@szymonrychu @tomassatka This seems to happen only when you created `helmfile.yaml` within the local chart directory.

Let's move the discussion to #2035 for how this can be fixed.
