### ISSUE TITLE
[Question] Is it possible to use AND/OR operators in the if clause?

### ISSUE THREAD

**Issue by talonx** [roboll/helmfile#1994]
My use case is something like this 

```
{{ $platformEnv := env "PLATFORM_ENV" }}
{{- if eq $platformEnv "envB" OR eq $platformEnv "envA" }}
....do something

{{- end }}
```
i.e. I want to use an OR for multiple conditions in the if. Is this possible?

**Comment by bradym** [comment]
Use the `or` function:
```
{{- if or (eq $platformEnv "envB")  (eq $platformEnv "envA") }}
```

The `and` function exists as well:
```
{{- if and (eq $platformEnv "envB")  (eq $platformEnv "envA") }}
```

These are functions built into the go template package: https://pkg.go.dev/text/template#hdr-Functions

**Comment by mumoshu** [comment]
Thanks @bradym!
I'm closing this as answered.
