### ISSUE TITLE
Change Log Level for Unmatched Selectors

### ISSUE THREAD

**Issue by osterman** [roboll/helmfile#200]
## what
* The current log level for `specified selector did not match any releases` is too verbose (IMO)
* Propose moving it to `debug` or `warn` log levels

```
2018/07/26 01:28:44 specified selector did not match any releases in helmfile.d/0610.kubernetes-dashboard.yaml
```

## why
* If you have a directory with a couple dozen helmfiles, selectors might not apply to most files
* The fact that the selector did not match becomes noisy and is alarming to those unfamiliar

**Comment by mumoshu** [comment]
Good catch! I believe `debug` level would be enough, especially given [we still get useful error when the selector did not match any releases in any helmfile](https://github.com/roboll/helmfile/blob/master/main.go#L412).
