### ISSUE TITLE
Debug output for username/password

### ISSUE THREAD

**Issue by InTheCloudDan** [roboll/helmfile#202]
I saw the recent commit of the logging levels which look awesome!! Do you want an additional PR to add logging username/password if the level is set to debug? Along with that the README needs to get updated to remove the WARNING.

**Comment by mumoshu** [comment]
@InTheCloudDan Thanks for catching it! Yeah, I greatly appreciate it 👍

**Comment by InTheCloudDan** [comment]
I looked it up in OWASP and their recommendation is never to log the password: https://www.owasp.org/index.php/Logging_Cheat_Sheet so I'm think we should defer to that and I'm just going to submit a PR to remove the warning in the README

**Comment by mumoshu** [comment]
Note: We have removed the outdated warning message in #206 that corresponds to this issue.
