### ISSUE TITLE
how to add `--post-renderer` into `helm` cli ?

### ISSUE THREAD

**Issue by tanguofu** [roboll/helmfile#2034]
Helm 3.1+ support Post Rendering: https://helm.sh/docs/topics/advanced/#custom-post-renderers , which can manually manipulate, configure, and/or validate rendered manifests before they are installed by Helm.

So how to add this flags to helmfile?

**Comment by mumoshu** [comment]
Unforunately it isn't possible! If you're willing to contribute a new feature for that, I'd be more than welcome to review it! Thanks

**Comment by tanguofu** [comment]
it is same that `helmfile` with  `--args="--post-renderer exec"`  works

**Comment by tanguofu** [comment]
there same to  has a bug:   the  `--post-renderer ` arg will pase into `helm list` but which did not  supported.


```
helmfile  -f k8s/helmfile.yaml   apply --args="--post-renderer=`pwd`/script/rewrite.sh"
```
came into the error:
```
Listing releases matching ^unifiedcsi$
in k8s/helmfile.yaml: in .helmfiles[4]: in storage-module/helmfile.yaml: command "/usr/local/bin/helm" exited with non-zero status:

PATH:
  /usr/local/bin/helm

ARGS:
  0: helm (4 bytes)
  1: list (4 bytes)
  2: --filter (8 bytes)
  3: ^ti-unifiedcsi$ (15 bytes)
  4: --namespace (11 bytes)
  5: ti-inf (6 bytes)
  6: --uninstalling (14 bytes)
  7: --deployed (10 bytes)
  8: --failed (8 bytes)
  9: --pending (9 bytes)
  10: --post-renderer=/home/install/helm-charts/script/rewrite.sh (69 bytes)

ERROR:
  exit status 1

EXIT S
```

i thinks there is two way to fix this:
A: just filter the `--post-renderer ` in  `helm list `function at : https://github.com/roboll/helmfile/blob/9dca4fea5926c2ae4266e4ac1cad3b72ef9afed9/pkg/helmexec/exec.go#L235
B:  add a specail flags  `--post-renderer `  to `helmfile` 

so  which canbe accepted?  i d like to contribe with a PR. 

many thanks.

**Comment by yxxhero** [comment]
@tanguofu https://github.com/roboll/helmfile/issues/2148 please see this.

**Comment by mumoshu** [comment]
`-args` isn't a fully supported feature because we aren't sure which args should be passed to which helm command(s) helmfile is running. I'd welcome your contribution to make it configurable per release in helmfile.yaml (Perhaps `releases[].postRenderer` or `releases[].postRenders[]` if helm supports passing multiple renders to it?
