### ISSUE TITLE
[QUESTION] is there a way (CLI flag?) to apply only single release from a big helmfile?

### ISSUE THREAD

**Issue by Va1** [roboll/helmfile#2038]
hi!

every now and then i'm interested in applying only single release from a large helmfile to save time and i'm wondering whether the only clean way to achieve this would be having smaller focused helmfiles. although having smaller helmfiles that represent a single state is kinda against the very idea of helmfile, i find.

having a CLI flag seems more elegant to me and i was wondering if there is one to achieve this (did not find it myself).

thanks

**Comment by mumoshu** [comment]
@Va1 Hey! Have you tried `helmfile -l name=YOUR_RELEASE_NAME apply`? You can also use arbitrary labels declared in your helmfile.yaml's `releases[]` for as a selector.

```
   --selector value, -l value              Only run using the releases that match labels. Labels can take the form of foo=bar or foo!=bar.
                                           A release must match all labels in a group in order to be used. Multiple groups can be specified at once.
                                           --selector tier=frontend,tier!=proxy --selector tier=backend. Will match all frontend, non-proxy releases AND all backend releases.
                                           The name of a release can be used as a label. --selector name=myrelease
```

**Comment by mumoshu** [comment]
@Va1 Closing this as answered. I hope it worked for you.
