### ISSUE TITLE
helmfile sync --file does not work

### ISSUE THREAD

**Issue by kody-abe** [roboll/helmfile#204]
helmfile sync --file ./helmfile.d/platform-latest.yaml
Incorrect Usage.

NAME:
   helmfile sync - sync all resources from state file (repos, releases and chart deps)

USAGE:
   helmfile sync [command options] [arguments...]

OPTIONS:
   --values value       additional value files to be merged into the command
   --concurrency value  maximum number of concurrent helm processes to run, 0 is unlimited (default: 0)
   --args value         pass args to helm exec

2018/08/01 11:34:28 err: flag provided but not defined: -file

**Comment by Evesy** [comment]
@kody-abe `--file` is a global option so it should work if you specify it before your command argument

i.e. `helmfile --file ./helmfile.d/platform-latest.yaml sync`

**Comment by kody-abe** [comment]
@Evesy Right you are! Thanks!
