### ISSUE TITLE
Missing colors in diff

### ISSUE THREAD

**Issue by z0rc** [roboll/helmfile#2043]
After upgrading `helm-diff` to 3.2.0 or newer, running `helmfile diff` produces output with no colors when running in regular terminal (not CI, `TERM=xterm-256color`). In the same time running `helm diff` in the same terminal produces colors as expected.

My guess is that after https://github.com/databus23/helm-diff/pull/240, there is check https://github.com/databus23/helm-diff/blob/master/cmd/root.go#L47-L50 which always true due to how `helmfile` executes `helm-diff`. `helm-diff`'s stdout is captured/redirected in separate file descriptor which isn't considered as terminal.

I tried passing running `helmfile --no-color=false diff`, but it didn't enable color in diff output. Only way to enforce colors I found was `helmfile diff --args="--no-color=false"`, but it's problematic in way where this arg passed to `helm list` execution and fails there.

**Comment by mumoshu** [comment]
@z0rc Ah good catch. Probably helm-diff should have an option to force enabling color, and external tools like helmfile that calls helm-diff should specify that force-color flag when it detects a terminal. WDYT?

**Comment by z0rc** [comment]
@mumoshu proposed logic look correct, just need to take into account `helmfile`'s own `--no-colors` argument.

**Comment by mumoshu** [comment]
Merged https://github.com/databus23/helm-diff/issues/344 on helm-diff. The next action item would be to enhance helmfile to set HELM_DIFF_COLOR appropriately.

**Comment by evgkrsk** [comment]
Seems like HELM_DIFF_COLOR=true dont working in CICD env (without control terminal) with helm-diff-3.3.2. I tried to "export TERM=xterm256" or alike, but it has no effect.

**Comment by z0rc** [comment]
@evgkrsk `HELM_DIFF_COLOR=true` won't work with helm-diff 3.3.2. Linked changes haven't been released yet.

**Comment by evgkrsk** [comment]
Oops, sorry, my fault. Waiting for helm-diff release...

**Comment by sjentzsch** [comment]
@mumoshu Would it be possible to create a new release on [databus23/helm-diff](https://github.com/databus23/helm-diff) to have colors again? Really appreciated :-)

**Comment by frank-berlin** [comment]
I would prefer that this can be done via helmDefaults.
for consistency in behavior for a team.
see #2060 

there is an updated release [databus23/helm-diff](https://github.com/databus23/helm-diff/releases/tag/v3.4.0)

**Comment by mumoshu** [comment]
@frank-berlin I hear you, but I have never intended to include operational concerns into helmDefaults, so that everything included in helmfile.yaml can be entirely about releases. Probably we'll keep that, until there's any serious design discussion that convinces me.

**Comment by mumoshu** [comment]
As @frank-berlin has kindly shared, the latest helm-diff release should work well with `helmfile --color`.
Closing as resolved but please feel free to reopen if necessary.
Thanks everyone for your cooperation!

**Comment by z0rc** [comment]
> the latest helm-diff release should work well with `helmfile --color`

I don't see this.
```
% helm diff version
3.4.0

% helmfile version
helmfile version v0.143.0
```

Running `helmfile diff` produces output without colors.

Running `helmfile --color diff` produces error `Incorrect Usage. flag provided but not defined: -color` and shows `helmfile` usage help.

Running `helmfile diff --color` produces error `Incorrect Usage. flag provided but not defined: -color` and shows `helmfile diff` usage help.

Running `HELM_DIFF_COLOR=true helmfile diff` produces colored output.

Is this expected resolution?

---
Additionally is it possible to make patch release of helmfile docker image, which includes updated helm-diff?

**Comment by mumoshu** [comment]
Turns out I forgot the fact that it only has `--no-color` but `--color`
https://github.com/roboll/helmfile/blob/debd3c0eeac2cd40c8a1227a3d0424f5944c3b81/pkg/state/state.go#L1710-L1712

That said, `HELM_DIFF_COLOR=true helmfile diff` might be the right way to force color! Thanks for pointing it out.

**Comment by z0rc** [comment]
@mumoshu any chance to restore `helmfile diff` behaviour to emit colors by default when running in regular terminal? Also documentation needs an update too.

**Comment by mumoshu** [comment]
@z0rc I don't have much slack in my life these days to work on it myself, but anyway yeah I'm convinced that we should address this in helmfile side!

Almost certainly we'd need to do the term detection thing that formerly done only in helm-diff:

https://github.com/databus23/helm-diff/blob/916891fac6033c9bf1bb482041ba2066e1341ebb/cmd/root.go#L45-L65

So that helmfile configure `HELM_DIFF_COLOR` appropriately according to the detected terminal.

**Comment by max-rocket-internet** [comment]
Is there any workaround we can use now?

> Running HELM_DIFF_COLOR=true helmfile diff produces colored output.

This does not work for me with helmdiff version `3.3.2`:

```
export HELM_DIFF_COLOR=true
helmfile --file helmfiles/main.yaml --selector app=atlantis diff
<no color output>
```

**Comment by z0rc** [comment]
@max-rocket-internet you need at least https://github.com/databus23/helm-diff/releases/tag/v3.4.0

**Comment by mumoshu** [comment]
Hey everyone!
I don't remember the state-of-the-art of this problem but is this still the issue?
I mean, does Helmfile still needs to be enhanced to do term-detection on its own? https://github.com/roboll/helmfile/issues/2043#issuecomment-1022707227

**Comment by lindhe** [comment]
A colleague complained about this last week, and I think he had the latest version installed. But I didn't double check, so I'm not sure...

**Comment by mumoshu** [comment]
@lindhe Thanks! (Please feel free to submit a PR as always) A known workaround would be to explicitly set `HELM_DIFF_COLOR=true` envvar when running helmfile.

**Comment by z0rc** [comment]
> I mean, does Helmfile still needs to be enhanced to do term-detection on its own? https://github.com/roboll/helmfile/issues/2043#issuecomment-1022707227

Yes, this is still needed.

**Comment by mumoshu** [comment]
Fixed via https://github.com/helmfile/helmfile/pull/24
