### ISSUE TITLE
helmfile set release version inline

### ISSUE THREAD

**Issue by leo191** [roboll/helmfile#2049]
Hi,

I'm using helmfile from roboll.helmfile.
my helmfile.yaml

```
repositories:
- name: privatebin
url: https://privatebin.github.io/helm-chart
releases:
- name: privatebin
chart: privatebin/privatebin
version: v0.7.0

...

```

now I want to overwrite the version inline.

`helmfile --selector name=privatebin -i --file helmfile.yaml apply --set version=v0.10.0`

but this is not working.
I can take version from environment and put something {{ env "VERSION" | default v0.7.0 }} but inline option will be more suitable..

**Comment by mumoshu** [comment]
@leo191 I hear you but your example doesn't make sense to me. `--set` is not for setting arbitrary release fields. It's for setting rendering parameters.

You'd need to explicitly say in helmfile.yaml:

```
version: {{ .Values.version }}
```

to denote that it is being set via the value.

**Comment by leo191** [comment]
@mumoshu ok then how do I pass version via cli? like in helm we use --version.

**Comment by mumoshu** [comment]
@leo191 You need to manually map the state value into a release value like this. There's really no way to directly overwrite a specific release value.

```
releases:
- name: a
  values:
  - version: {{ .Values.a.version }}  
- name: b
  values:
  - version: {{ .Values.b.version }}  
```
