### ISSUE TITLE
Only sync release if there is a difference

### ISSUE THREAD

**Issue by kody-abe** [roboll/helmfile#205]
Any possibility of adding a feature to run the sync for releases in the helmfile that have differences.

With the feature of `helm diff` I would imagine this would be something that would fit?

**Comment by mumoshu** [comment]
@kody-abe Hey! Thanks for the request.

Would you mind clarifying a bit more, on pros of your requested feature over just `helmfile diff && helmfile sync`?

**Comment by kody-abe** [comment]
@mumoshu I guess maybe the terraform style.

Showing all the changes and then asking for confirmation.

Currently, our team will just have a policy to run the diff first verify the changes are as expected and then run sync.

I can see the value in having sync, or another command, run the diff and present it if changes are found, then ask if the command should continue with sync.

**Comment by sstarcher** [comment]
One pro of only doing the updates is not upgrading every release in the helmfile.  If you had a automated system that ran on say a 5 min interval you would end up with thousands of releases, but if it only upgraded on releases that changed it would work cleanly.

**Comment by mumoshu** [comment]
@kody-abe Thanks for the clarification! Just to make it extra clear, you're talking about non-CI use-case, that is, helmfile is run by humans so interactive confirmation makes sense, right?

**Comment by kody-abe** [comment]
@mumoshu Correct!

**Comment by mumoshu** [comment]
@sstarcher Good point! It would be a good enhancement. Just a moment until I come up with something...

**Comment by mumoshu** [comment]
@sstarcher @kody-abe How about adding `helmfile apply`, that runs `helmfile diff` and then `helmfile sync` only when there's any change?

I'm introducing a brand-new command to retain backward-compatibility while giving more terraform-like u/x to helmfile with (from my perspective) a more appropriate name.

// Regarding the last point, I remember that I had once felt a bit ambiguity in the "direction" of `helmfile sync`. That is either helmfile is synchronized to the cluster, or the cluster is synchronized to helmfile. `apply` doesn't have such ambiguity imo.

`helmfile apply` will, by default, prompt the user for confirmation before running `helmfile sync`. The confirmation can be skipped by providing a flag named like `--auto-approve` or `--force`(Which one do you prefer by the way? The former is from terraform, while the latter is a more widely used flag I think).

**Comment by kody-abe** [comment]
@mumoshu Yes, `apply` sounds like a great route. Very good for making it backwards compatible. As for the flag I don't have a preference either way. Thanks for this!

**Comment by mumoshu** [comment]
@kody-abe Thanks a lot for the confirmations 👍

**Comment by sstarcher** [comment]
Sounds good to me, I'm good with either, but due to it seems people being familiar with terraform I would lean toward `-auto-approve`.  Other prior art would be `-y` for yes and `--force` of course.

**Comment by mumoshu** [comment]
Just submitted #263 for this. I've proceeded with `--auto-approve` according to your feedback.
