### ISSUE TITLE
add HELM_DIFF_THREE_WAY_MERGE to helmDefaults

### ISSUE THREAD

**Issue by frank-berlin** [roboll/helmfile#2060]
Please add HELM_DIFF_THREE_WAY_MERGE flag to helmDefaults.
This allow for more consistent deploy behavior in a team.
If people missing  the env var or cli parameter.

**Comment by mumoshu** [comment]
Hey! Same as https://github.com/roboll/helmfile/issues/2043#issuecomment-1019460480, I have never intended to include any operational concerns into helmDefaults.

Maybe it would make sense to be a command-line flag (`helmfile --three-way-merge-diff`). But assuming it can be configured via an envvar already, I don't have a  strong motivation for adding a new flag, too.

If anyone has a strong desire for that and submit a pull request, I'd review it.
Closing this as answered, but please feel free to reopen if necessary. Thanks!

**Comment by frank-berlin** [comment]
HELM_DIFF_THREE_WAY_MERGE has strong impact on deploy via helmfile apply.
Without helmfile would not detect any manual changes via kubectl in cluster. 
With true this changed get detected and helmfile runs helm upgrade. 
This make bring more consistency in releases get deployed, which result also into operations.
By still have the benefit from helmfile apply that only an helm upgrade runs when samething need to change to bring the state and  k8s reality in sync. 

@mumoshu for me doesn't matter where in helmfile.yaml I define this, don't need to be in helmDefaults.
An cli flag don't help, as get forgotten same times (similar with env var).
The main driver to use helmfile is all about make values files dryer and that releases get deployed consistent, because nobody forget a value file or change the order,...
The values defined in helmDefaults like atomic, timeout, wait,... have also strong impact how releases get deployed.
Could be that my wording with operation is misleading
I'm big fan of helmfile and we build all our releases (>200) with it.

**Comment by mumoshu** [comment]
@frank-berlin All your explanations makes sense. To be clear, you can already upgrade helm-diff independently from helmfile and run helmfile like `HELM_DIFF_THREE_WAY_MERGE=true helmfile apply` to let it use `--three-way-merge` today.

What else do you need in helmfile if it isn't something under `helmDefaults`?

**Comment by fc-subutai** [comment]
Allow in helmfile.yaml to set the value for three-way-merge.
That without to change env or cli you can set the three-way-merge usage.

**Comment by frank-berlin** [comment]
I need per release enable/disbale HELM_DIFF_THREE_WAY_MERGE in helmfile.yaml.
In 90% of the cases HELM_DIFF_THREE_WAY_MERGE works with helmfile fine.
But there cases where not, spacial on install of CRD's via separte chart. There I need to disbale it.
like
`  Error: unable to build kubernetes objects from new release manifest: unable to recognize "": no matches for kind "OperatorConfiguration" in version "acid.zalan.do/v1"`

**Comment by mumoshu** [comment]
@frank-berlin I guess it's the first install and it's failing due to the cluster does not have the OperatorConfiguration CRD installed yet, which makes helm-diff fail due to missing CRD. Then what you need is disableValidationOnInstall

```
    # passes --disable-validation to helm 3 diff plugin, this requires diff plugin >= 3.1.2
    # It is useful when any release contains custom resources for CRDs that is not yet installed onto the cluster.
    # https://github.com/roboll/helmfile/pull/1618
    disableValidationOnInstall: false
```
