### ISSUE TITLE
helmfile does not ask before apply

### ISSUE THREAD

**Issue by neogeogre** [roboll/helmfile#2107]
Hi, I have `helm`, `helm diff` and `helmfile`, and when I do `helmfile -l app=my-app apply --context 3` it does not ask me "yes" "no" anymore before applying the template. And I do not manage to reactivate it. 

Someone knows how to activate it again ? Is it an helm diff or helmfile option ?

**Comment by pathob** [comment]
It should also not have asked you before per default. You can find the answer in the help:

```bash
$ helmfile --help
NAME:
   helmfile

# ...

GLOBAL OPTIONS:
   # ...
   --interactive, -i                       Request confirmation before attempting to modify clusters
   # ...
```

So, `--interactive` is what you're looking for.

Please consider closing the issue if your question got answered.

**Comment by neogeogre** [comment]
I missed it somehow in the help, thank you very much !
