### ISSUE TITLE
Trying to delete decrypted files on Windows results in PathError

### ISSUE THREAD

**Issue by philomory** [roboll/helmfile#2127]
Whenever I run `helmfile` on Windows, after it decrypts any files, it fails to remove them, with a log like this:

```
[helm-secrets] Decrypting C:\path\path\path\secrets\test.yaml

[helm-secrets] Decrypting C:\path\path\path\secrets\common.yaml

removing decrypted file secrets\secret986570939.yaml: %!w(*fs.PathError=&{remove secrets\secret986570939.yaml 32})
removing decrypted file secrets\secret058986718.yaml: %!w(*fs.PathError=&{remove secrets\secret058986718.yaml 32})
```

Looking into Go's `os.Remove` and `fs.PathError` a bit (though not being a Go programmer myself), and then looking into Windows syscall errors, error 32 is:

> ERROR_SHARING_VIOLATION
>
>32 (0x20)
>
>The process cannot access the file because it is being used by another process.

The file in question was only just _created_ by `helmfile` (strictly, by `helmfile` calling out to `helm secrets dec`), and I made sure that even without my editor open, the problem still occurs (so it's not the editor holding open a handle to the file which prevents it from being deleted). Fundamentally the root of the problem is that Windows is ridiculous and doesn't allow files to be deleted until all file handles have been closed, but, I can't figure out what process might be holding the file open. It can't be `helmfile` itself directly, since the Windows `DeleteFile` function doesn't error in that case, it just flags the file to be deleted once the handle has closed; it has to be some other process. Whatever process does it also doesn't seem to hold it for _long_, because immediately after the error I'm able to delete the file if I try, even while Helmfile is still running and still using the data it got from the decrypted file (I even compiled a small Go program to delete it using `os.Remove()` to make sure there wasn't anything weird going on where "native" methods of deleting a file got special handling).

Ultimately I don't know if this "counts" as a bug in Helmfile; maybe you'd be within your rights to say, "Windows gonna Windows" and ignore it. But, none of the other tools I use have this problem, so I'm wondering if there isn't _something_ Helmfile could do to address it; possibly deferring deleting decrypted secrets files until later in the execution process on Windows, or even simply not decrypting the files onto disk at all, calling `helm secrets view` (rather `helm secrets dec` followed by `os.ReadFile` followed by `os.Remove`), to get the decrypted contents into memory?

(This is Helmfile v0.142.0, by the way, on Windows 10, running under Powershell)

**Comment by itscaro** [comment]
@philomory I looked into this last year but did not catch the worm. Thanks for encouraging me to have another look at this issue.
