### ISSUE TITLE
How to use the output of `a.yaml.gotmpl` in `b.yaml.gotmpl`?

### ISSUE THREAD

**Issue by fzyzcjy** [roboll/helmfile#2129]
Hi thanks for the lib! I need to use the output of `a.yaml.gotmpl` in `b.yaml.gotmpl`. How can I do that? The "layering" feature seems promising but I fail to use it even for official examples (https://github.com/roboll/helmfile/issues/2128)

**Comment by mumoshu** [comment]
Depends on the kind of gotmpl file! Layering environment values would just work. You seem to have missed specifying the env in #2128. Layering release values isn't supported.

**Comment by fzyzcjy** [comment]
Thanks!
