### ISSUE TITLE
[Question] Is there possibility to render values files?

### ISSUE THREAD

**Issue by andrey-gava** [roboll/helmfile#2156]
Hi!
We use values files that are heavily use requiredEnv function. 
Something like this:
```
gcp:
  enabled: false
  bucket: minio-backups-{{ requiredEnv "CUSTOMER" }}-{{ requiredEnv "SHARED_NAMESPACE" }}
```
After deploy we would like to have such values rendered, so after some time if we like to know what env was used for deploy we can just check the file.
I know that helmfile have "build" command but it render values into one big file, and than sort all top level keys in alphabetic order. Its little bit hard to search for needed key if you use many values files. For example I want to check all the keys from one file, than I need to take keys one by one and search them in this one big rendered file.

Is there possibility to render values files separately as they are presented on filesystem/values block? 
As example, if I have next files:
```
    values:
      - ../environments/gke-dev/common.yaml.gotmpl
      - ../environments/gke-dev/backup.yaml.gotmpl
      - ../environments/gke-dev/shared-users.yaml.gotmpl
      - ../environments/gke-dev/shared-roles.yaml.gotmpl
      - ../environments/gke-dev/shared-resources.yaml.gotmpl
      - ../environments/gke-dev/shared-hosts.yaml.gotmpl
      - ../environments/gke-dev/shared-secrets.yaml.gotmpl
      - ../environments/gke-dev/shared-certs.yaml.gotmpl
```
And after apply/template I want to have them rendered in some folder like this(each one separate as the original):
```
./rendered_files
common.yaml.gotmpl.rendered
backup.yaml.gotmpll.rendered
shared-users.yaml.gotmpll.rendered
shared-roles.yaml.gotmpll.rendered
shared-resources.yaml.gotmpll.rendered
shared-hosts.yaml.gotmpll.rendered
shared-secrets.yaml.gotmpll.rendered
shared-certs.yaml.gotmpll.rendered
```

Maybe this future exist but I cant find it.

**Comment by yxxhero** [comment]
see: https://github.com/roboll/helmfile/issues/2148

**Comment by andrey-gava** [comment]
Move to new repo
