### ISSUE TITLE
line x: mapping key "<<" already defined at line y

### ISSUE THREAD

**Issue by Abdur-rahmaanJ** [roboll/helmfile#2162]
Greetings,

I had a previous helmfile where this worked:

```
releases:
- name: somerelease
  <<: *localChart
  <<: *default
```

Now after updating to `helmfile version 0.149.0` i get this error:

```
in ./helmfile.yaml: failed to read helmfile.yaml: reading document at index 1: yaml: unmarshal errors:
  line x: mapping key "<<" already defined at line y
```

I cannot understand what changed in helmfile causing it to break. Thank you.

**Comment by yxxhero** [comment]
@Abdur-rahmaanJ please post issue on helmfile/helmfile

**Comment by yxxhero** [comment]
<<: [*localChart, *default]
