### ISSUE TITLE
Add useful hook environment variables

### ISSUE THREAD

**Issue by pennytextures** [roboll/helmfile#2184]
It'd be really useful if a few environment variables were exported for hooks

stuff like:

HELM_RELEASE
HELM_CHART
HELM_ENVIRONMENT

It'd be really nice to put a pre-sync hook templated into all your releases, then have that script know where it's being invoked from.

Fwiw, my use case is running some idempotent scripts to upgrade charts which don't run cleanly, right now I just run a bunch of scripts before my sync, updating crds etc. it'd be nice if i could wire this script in as a pre-sync hook, and then only run these migrations before syncing the relevant chart.

**Comment by yxxhero** [comment]
@pennytextures please post issue in helmfile/helmfile. thanks so much.
