### ISSUE TITLE
Using private s3 bucket as repository

### ISSUE THREAD

**Issue by schollii** [roboll/helmfile#220]
Is this possible? Currently we are using helmsman, which supports repository that has s3://bucket-name/repo-name as repo, but we would like to switch to helmfile if helmfile could handle accessing a repo that is hosted in a private s3 bucket (needs access to AWS profile of course).

**Comment by mumoshu** [comment]
@schollii Hey! I haven't tried myself yet due to I have no specific need to use s3 as a repository, but it would be useful, and feasible.

Try installing [helm-s3](https://github.com/hypnoglow/helm-s3) and specify the url that starts with`s3://`:

```
repositories:
  - name: roboll
    url: s3://yourbucket/prefix
```

It should work!

**Comment by schollii** [comment]
Thanks I will try that! I will close this for now.

**Comment by gtaylor** [comment]
We use helmfile with S3 and a custom plugin that is very similar to helm-s3. It is possible and works well!

**Comment by sstarcher** [comment]
@schollii I have been using the `helm-s3` plugin for a while and it's been great.  @schollii mind if I ask what about helmfile brought you to the tool?
