### ISSUE TITLE
feat: Template functions to replace `set`s

### ISSUE THREAD

**Issue by mumoshu** [roboll/helmfile#227]
In #207, I and @sstarcher have discussed about if it is a good idea to leverage `--set`, `--set-string` and `--set-file` flags to make it easy to keep feature parity between helm and helmfile.

Conclusion at the moment is to avoid relying on `sets` as much as possible. Instead, we should enhance #216 originally proposed in #97.

In theory, it is matter of adding following template functions so that we can completely avoid using `set`s:

- `readFile` reads the specified local file and generate a golang string
- `unmarshalYaml` reads a golang string and generates a map
- `setValuleAtPath PATH NEW_VALUE` traverses a golang map, replaces the value at the PATH with NEW_VALUE
  - Originally this was name `set` but renamed as such to avoid conflict with `set` from sprig
- `marshalYaml` marshals a map into a string
   - `unmarshalYaml` and `marshalYaml` were named `yamlToMap` and `mapToYaml` respectively. But renamed to respect the golang's convention to use marshal/unmarshal

Expected use-cases of these functions are:

- Instead of `--set foo[0]={bar,baz}`, write a `values.yaml` containing:

```
{{ readFile "another.values.yaml" | unmarshalYaml | setValuleAtPath "foo[0]" (array "bar", "baz") | marshalYaml }}
```

- Instead of `--set-file foo=path/to/file`, write:

```
foo: |
{{ readFile "path/to/file" | indent 2 }}
```

**Comment by mumoshu** [comment]
Tweaked function names a bit. See comments on why they are named so.

**Comment by mumoshu** [comment]
Btw this should be possible just by implementing these functions, as we already support templated values files via #97 and #216

**Comment by sstarcher** [comment]
Looks good to me, but the `unmarshalYaml` might cause some confusion with helms `toYaml`

**Comment by mumoshu** [comment]
@sstarcher Good point! I'll use `toYaml` along with `fromYaml`. At the time of writing my above proposal, I didn't know that [helm has `fromYaml`](https://github.com/helm/helm/blob/7cad59091a9451b2aa4f95aa882ea27e6b195f98/pkg/engine/engine.go#L80-L81).

**Comment by mumoshu** [comment]
`set:` should be explicitly noted as deprecated in favor of this feature. I'll add some words in README.

Would it also be nice to write docs for example use-cases of templated values fiies?

**Comment by darkn3rd** [comment]
@mumoshu With this:
```
foo: |
{{ readFile "path/to/file" | indent 2 }}
```

How do you handle a multi-line file that is a TLS cert for example.

**Comment by mumoshu** [comment]
@darkn3rd What do you mean by "how"? `indent` indents each line in the input.
