### ISSUE TITLE
Limit the number of concurrent helm calls

### ISSUE THREAD

**Issue by andytom** [roboll/helmfile#23]
I have quite a large helmfile and helm (or tiller) is starting to time out when deploying to my local cluster in minikube. Would it be possible to have an argument to limit the number of concurrent requests being made to helm at a time. Maybe something like `--max-connections=X`, if unset you could leave it as unlimited, but if set `helmfile` should only make at most `X` requests at a time.

**Comment by roboll** [comment]
Seems like a reasonable change. It would need to go [here](https://github.com/roboll/helmfile/blob/master/state/state.go#L91), probably instead of a goroutine per chart, a pool of workers and a work channel.

I'm not going to implement this right now. Feel free to submit a PR.
