### ISSUE TITLE
usage of helm-diff broken due to the addition of a namespace

### ISSUE THREAD

**Issue by sstarcher** [roboll/helmfile#234]
This PR has not been released yet - https://github.com/databus23/helm-diff/pull/41

Anyone using the latest helmfile must also build helm-diff themselves.

**Comment by sstarcher** [comment]
Actually I take it back `helm-diff upgrade` even on master does not have a --namespace flag.

**Comment by mumoshu** [comment]
Sorry for the inconvenience! Forgot to merge https://github.com/databus23/helm-diff/pull/85 beforehand. Just released v2.9.0+3 with that.
