### ISSUE TITLE
values templates break backwards compatibility

### ISSUE THREAD

**Issue by sstarcher** [roboll/helmfile#249]
I just realized after upgrading from 0.22.0 that if I have a values file with something like
```          description: '{{$labels.namespace}}/{{$labels.pod}} restarted {{$value}}```

It will attempt to template it.  So migrating from 0.22.0 to 0.23.0 will cause breakage and I have to update the helmfile and the templates in sync.

**Comment by sstarcher** [comment]
ouch this prometheus config 104 occurances

**Comment by mumoshu** [comment]
How about this?

```
{{`'{{$labels.namespace}}/{{$labels.pod}} restarted {{$value}}`}}
```

**Comment by mumoshu** [comment]
Alternatively, adding helmfile an ability to customize the template expression delimiters per release would be handy.

Requiring a suffix of .tmpl to parse a values file as a template, otherwise treat it a vanilla yaml would also work.

**Comment by sstarcher** [comment]
@mumoshu ya, I was initially not thinking about this issue when I recommend just going with `values.yaml` vs `values.yaml.tmpl`

**Comment by sstarcher** [comment]
Are you ok with the backwards incompatible change of requiring it to be values.yaml.tmpl?

**Comment by mumoshu** [comment]
Yes, as it's a relatively new feature introduced a few days ago!

Also, I slightly prefer `values.yaml.gotmpl` to make it very clear that it is a golang text/template. I see the same file extension is used in other projects like go-swagger.
