### ISSUE TITLE
helmfile lint breaks when local charts are referenced from helmfile.d/

### ISSUE THREAD

**Issue by davidovich** [roboll/helmfile#252]
## Problem

When a local chart is referenced in the state file, `helmfile lint` tries to fetch the chart anyway.

This can be observed by using this simple helmfile (local-chart-helmfile.yaml):

```
releases:
- name: my-release
  namespace: default
  chart: ../local-charts/my-local-chart # this 
```

Here is the file layout to reproduce the problem:

```
root
  | local-charts
  `--| my-local-chart
  | helmfile.d
  `--| local-chart-hemlfile.yaml
```
Other helmfile operations seem to work as expected (I tested sync).

## Analysis

After some investigation, this is probably related to a wrong working directory, for the `LintRelease()` function as `isLocalChart()` (a simple os.Stat() with no root dir decoration) called from [LintReleases()](https://github.com/roboll/helmfile/blob/822cc13e72c560bc8ee989cfcbee7d8f98498a7a/state/state.go#L376) returns false for a relative path. 

If I change the `chart:` path in local-chart-helmfile.yaml to be rooted at the working directory, linting completes without error. But this is not a viable solution because other helmfile operations (sync) treat relative paths relative to the helmfile.yaml (or helmfile.d/).

If I change the working directory to `helmfile.d/` and issue `helmfile -f . lint` this also completes without error, which is a temporary workaround.

Note that `helmfile -f helmfile.d/ sync` works as intended as the chart can be reached relative to manifest file, as stated in the README documentation.

Related issue #246

I think a concept of root dir as determined by the `-f` argument, and propagated to every command would solve this problem.

**Comment by davidovich** [comment]
Thank you @mumoshu !, that was fast :-)

**Comment by Morriz** [comment]
I think this behavior came back in 0.119.1 @mumoshu. helmfile suddenly uses `helm fetch` to get charts with absolute path. We create charts dynamically with pre-hooks in `/tmp/charts/abc` and use those in releases.
