### ISSUE TITLE
Add the ability to do `helm template`

### ISSUE THREAD

**Issue by Stono** [roboll/helmfile#283]
It'd be nice to be able to do helm template on the helmfile (pr incoming).

**Comment by mumoshu** [comment]
Interesting! What do you use it for? Example use-cases are welcomed.

**Comment by Stono** [comment]
Hey @mumoshu - so we use helmfile+helm to do all of our deployments to kubernetes in our org.  It's actually wrapped by our deployment API.

We currently use `helmfile sync` with a `--dry-run` and `--debug` to generate the yaml files to do some basically validation in advance of it being actually deployed, for example:

  - Detect known "gotchas" within our platform.  For example, your ports need to be named `http-*` etc
  - Enforce certain standards (labels, etc)

However, this has some downsides; primarily that it depends on having a network connection to kubernetes available, plus it's a bit slow.

We are perfectly happy doing a helm template and then performing our validation on those results instead, does that make sense?

**Comment by Stono** [comment]
Thinking about it too, it also opens up the opportunity for me to extend https://github.com/Stono/helm-test to work with helmfile too (as it parses and asserts on helm template)

**Comment by mumoshu** [comment]
I'm in favor of your use-case https://github.com/roboll/helmfile/issues/283#issuecomment-418077609. I'd appreciate it if you could contribute a README improvement that covers the topic 👍

**Comment by rplute** [comment]
+1
