### ISSUE TITLE
A sync with multiple releases, never exits!

### ISSUE THREAD

**Issue by Stono** [roboll/helmfile#301]
Hey, 
Big regression since we went from 0.20.0 to 0.32.0 is that a helmfile with multiple releases never exits/completes.  

I have discovered that this is only the case with `--concurrency=1`

Looking at the code, it seems to get stuck:

```
				state.logger.Infof("Here")

				if err != nil {
					results <- syncResult{errors: []*ReleaseError{&ReleaseError{release, err}}}
				} else {
					results <- syncResult{}
				}
				state.logger.Infof("Here Done")
```

I never see the `Here Done` when running `--concurrency=1`

**Comment by Stono** [comment]
Fixed it, PR inc

**Comment by mhulscher** [comment]
This does not seem fixed in either 33.0 or 33.1

**Comment by mumoshu** [comment]
@mhulscher Oh, too bad it worked for me on my machine. How does your logs look like when you enabled debug logging?

**Comment by mhulscher** [comment]
Never mind. This issue is fixed 👍  My deploys did not finish because of a different reason.
