### ISSUE TITLE
helmfile --version does not report version

### ISSUE THREAD

**Issue by davidovich** [roboll/helmfile#304]
I installed helmfile with `go get` (the first recommended installation method), and when I run `helmfile --version`

I get `version` as version.

```
$ helmfile --version
helmfile version
```

**Comment by mumoshu** [comment]
Good catch!

We use ldflags to embed the version number into go binary, so in theory the `go get` command should include ldflasg like `go get -u -ldflags "-X github.com/roboll/helmfile.Version=x.y.z".

However I'm not sure how it should work on master...

**Comment by mumoshu** [comment]
Closing this as resolved by #437.
