### ISSUE TITLE
Allow specifying namespace

### ISSUE THREAD

**Issue by hlascelles** [roboll/helmfile#31]
We would like to deploy the same group of charts to the same cluster in different namespaces (branch environments)

Would there be any desire to see that in helmfile? eg `--kube-namespace`

**Comment by mumoshu** [comment]
Sounds reasonable to me. Would it be a matter of passing the namespace you will specify via `--kube-namespce` to helm commands like `helm upgrade --install --namspace $kube_namespace ...`?

**Comment by mumoshu** [comment]
@hlascelles Would #39 work for you?

**Comment by hlascelles** [comment]
Yes, looks great, thank you! :+1:
