### ISSUE TITLE
Ordering of charts on delete: List should be reversed

### ISSUE THREAD

**Issue by elemental-lf** [roboll/helmfile#312]
When using ``helmfile.d`` and multiple helmfiles they are ordered lexicographically so that user can define a certain installation order. I think this list should be reversed when doing a ``helmfile delete``. The same applies when using glob patterns.

**Comment by mumoshu** [comment]
@elemental-lf Sounds good! Would you mind submitting a PR for that?

**Comment by elemental-lf** [comment]
@mumoshu, sorry, no time for a PR currently. Need to work on the project _using_ helmfile for a change ;)

**Comment by mumoshu** [comment]
No worry! I'll work on it soon.

**Comment by elemental-lf** [comment]
Thanks again.
