### ISSUE TITLE
Use --namespace value within Helmfile template

### ISSUE THREAD

**Issue by witten** [roboll/helmfile#326]
Use case: I want to interpolate the namespace specified on the Helmfile command-line via `--namespace` into the release name in a `helmfile.yaml`. My motivation is that I'm trying to prefix all Helm release names with the name of the namespace that they correspond to, because I've got a global cluster-wide Helm Tiller and `helm list` is kind of useless if I can't tell at a glance which namespace a particular release belongs to. And perhaps more importantly, I want to avoid Helm release name collisions if the same thing is deployed to multiple different namespaces in a cluster.

Here's the sort of syntax I'm imagining:

```
releases:
  - name: {{ .Namespace }}-my-chart
```

Please let me know if this isn't possible for some reason, e.g. the namespace isn't known at release name templating time.

I know that I could use the environment variable feature for this, but that would be duplicative with `--namespace`.

**Comment by mumoshu** [comment]
@witten Hey! It sounds great. Would you mind contributing a PR?

**Comment by witten** [comment]
I don't know Go, but I can maybe give it a shot anyway. How would you prefer the namespace value to appear in the template? `{{ .Namespace }}`? `{{ .Namespace.Name }}`? `{{ env "namespace" }}`?

**Comment by mumoshu** [comment]
Thanks. `{{ .Namespace }}` sounds good 👍

**Comment by witten** [comment]
Thanks, that's exactly the sort of guidance I needed. I've got an initial stab working now.. I'll do some additional testing and then submit it for review.

**Comment by Morriz** [comment]
Why is the namespace not populated when it is specified in a release?

**Comment by hrvolapeter** [comment]
@Morriz its helm problem where helm install and helm template have different output. However maintainers of helm decided to close the issue as won't fix https://github.com/helm/helm/issues/3553

**Comment by mumoshu** [comment]
Yeah it's a helm/helm chart problem.

However, Helmfile has a secret feature called `forceNamespace` to, uh, set metadata.namespace forcefully, as a workaround to the problem. It works by Helmfile running `helm template` to render the manifests and setting `metadata.namespace`, and compiling it as a temporary chart(again). So you can use it when you know what you're doing.

```
releases:
- name: "aws-load-balancer-controller"
  namespace: "kube-system"
  forceNamespace: "kube-system"
```

**Comment by antaloala** [comment]
I have created issue [#1718](https://github.com/roboll/helmfile/issues/1718)  related to a bug I have found (in latest 0.138.7 release) when using this --namespace CLI option.

**Comment by dvarrazzo** [comment]
> However, Helmfile has a secret feature called forceNamespace to, uh, set metadata.namespace forcefully, as a workaround to the problem.

Hello,

this is useful in many situations.

Is there a reason why this is not documented?

**Comment by yxxhero** [comment]
> > However, Helmfile has a secret feature called forceNamespace to, uh, set metadata.namespace forcefully, as a workaround to the problem.
> 
> 
> 
> Hello,
> 
> 
> 
> this is useful in many situations.
> 
> 
> 
> Is there a reason why this is not documented?

Welcome to post PR in helmfile/helmfile.

**Comment by dvarrazzo** [comment]
> Welcome to post PR in helmfile/helmfile.

That's not what I asked. "Is there a reason why it's not documented"? (unstable features, kills your cat, scratches your car) or is this feature deemed complete, stable, usable, no side effect, doesn't pollute the seas?
