### ISSUE TITLE
`helmfile delete` is not purging the release

### ISSUE THREAD

**Issue by mumoshu** [roboll/helmfile#33]
Running `helmfile sync`, `helmfile delete` and then `helmfile sync` again results in https://github.com/kubernetes/helm/issues/3208.
More concretely, you get something like:

```
$ PROJECT=deis/empty-testbed ENV=staging IMAGE=mumoshu/golang-k8s-aws:1.9.1 COMMAND='go' SERVICE_ACCOUNT=default helmfile sync
exec: helm repo add brigade https://azure.github.io/brigade
"brigade" has been added to your repositories
exec: helm repo update
Hang tight while we grab the latest from your chart repositories...
...Skip local chart repository
...Successfully got an update from the "incubator" chart repository
...Successfully got an update from the "kubeherd" chart repository
...Successfully got an update from the "es-operator" chart repository
...Successfully got an update from the "brigade" chart repository
...Successfully got an update from the "stable" chart repository
Update Complete. ⎈ Happy Helming!⎈
exec: helm upgrade --install brigade-project brigade/brigade-project --values myvalues.yaml --set secrets.env=staging,secrets.image=mumoshu/golang-k8s-aws:1.9.1,secrets.command=go,secrets.serviceAccount=default,project=deis/empty-testbed,repository=github.com/deis/empty-testbed,cloneURL=https://github.com/deis/empty-testbed.git
WARNING: Namespace doesn't match with previous. Release will be deployed to kube-system
Error: UPGRADE FAILED: "brigade-project" has no deployed releases
err: exit status 1
```

This seems to prevent us from just re-running `helmfile sync` without changing `charts[].name` in charts.yaml each time you run `helmfile delete`.

Would it be better for helmfile to just purge releases so that we don't need to change `charts[].name` so often?

**Comment by mumoshu** [comment]
I've submitted #34 to fix this.

**Comment by andrewnazarov** [comment]
@mumoshu Is it really fixed? I'm facing the same issue in version v0.43.2. To work around this I had to set helmDefaults.force to true.

**Comment by mumoshu** [comment]
Should be. Would you ming sharing a full output with `--log-level=debug`, from the first `sync`, the subsequent `delete`, and `sync`?
So that I can see whats happening. A github gist would be nice.

**Comment by andrewnazarov** [comment]
@mumoshu, sorry, my fault. I've noticed PR #142 introducing `--purge` flag to helmfile. For some reason, I missed this while reading docs.

**Comment by mumoshu** [comment]
@andrewnazarov Thanks for confirming! Glad it worked for you.
