### ISSUE TITLE
[Question] Are all the value files templatable ?

### ISSUE THREAD

**Issue by davidovich** [roboll/helmfile#334]
I had the impression (from [README.md](https://github.com/roboll/helmfile/blame/master/README.md#L284)) that all value files could be rendered (including `values.yaml`): 

```
You can use go's text/template expressions in helmfile.yaml and values.yaml(helm values files).
```

But this is not currently [the case](https://github.com/roboll/helmfile/blob/master/valuesfile/valuesfile.go#L25-L33). As you see, RenderToBytes, which is used to make the temporary value files to pass to helm, renders only `.gotmpl` extensions.

I think this is actually a good thing, but I believe it is a departure from previous functionality (in which all values.yaml files were rendered). Am I right ?

Should it be the new direction, I can make a PR to fix the README.md, stating that only .gotmpl files get rendered.

**Comment by mumoshu** [comment]
@davidovich Yeah, you're right!

`.gotmpl` is required to enable templating today. I had originally enabled templating even for `.yaml` files, that resulted in an usability issue(#249). Requiring the `.gotmpl` ext. seemed the way with the minimum friction.

> I can make a PR to fix the README.md, stating that only .gotmpl files get rendered.

I appreciate it!
