### ISSUE TITLE
The --auto-approve feature should be removed and replaced with --dry-run

### ISSUE THREAD

**Issue by blissd** [roboll/helmfile#354]
PR #263 added an `--auto-approve` flag to signal some destructive actions should be applied, such as destroying and recreating resources.

I think this is a bad user experience. After all, if just ran a command to `delete` or `sync` resources, then that is what I want the command to do. Don't make me confirm that I really mean it.

An approach I would prefer would be to restore the original behaviour, but add a `--dry-run` flag that would simply print the commands that would execute instead of actually executing them.

**Comment by blissd** [comment]
Both `kubectl` and `helm` support `--dry-run` flags for a number of commands.

**Comment by mumoshu** [comment]
Hi!

Maybe you're talking about removing the flag from `delete`, right? You can use `sync` instead of `apply` in case you aren'j interested in interactivity.

**Comment by mumoshu** [comment]
Also, the point of `apply` is not to print commands being executed but show what's being affected. dry run does'nt help that. Maybe `sync` is what you want and your frustration would be from its name - `apply`. I'm open to suggestions to rename `apply` to something else to not confuse k8s/helm users, but don't expect me to just remove it! There are use-cases and conforming to kubectl/helm is not the only goal at the moment.

Removing interactivity from `delete` might make sense. I'd instead add `destroy` command that works interactively.

Do you actually need --dry-run? Or is it just that you don't like interactivity?

**Comment by mumoshu** [comment]
Okay but I won't just remove it! There're diverging use-cases that shouldn't be thrown away.

I'd appreciate if you could suggest better names for the commands you think wrong but other people think useful, and suggest addition of more low-level commands that will fit your use-cases.

**Comment by blissd** [comment]
No, I don't need `--dry-run`. It was a compromise for those who might like the interactive behaviour to remain.

How we use `helmfile` is for integration testing against minikube locally, and against a real K8S deployment when running on jenkins. Our plans for the future include using it for actual production deployments, too.

However, right now it is only used for integration testing during builds and called from a `Makefile`. We have defined a build lifecycle where tooling runs `make up` to use `helmfile` to deploy resources, then we run integration tests, and then run `make down` to use helmfile to clean up the resources.

It looks something like this, if this is helpful:
```
.PHONY: up
up:
	kubectl --context=${K8S_CONTEXT} create namespace ${K8S_NAMESPACE}
	eval `${DP_DEPLOYMENT_DIR}/bin/kube-env --kube-context ${K8S_CONTEXT} --namespace ${K8S_NAMESPACE}` && \
	helmfile --kube-context ${K8S_CONTEXT} --namespace ${K8S_NAMESPACE} sync --args --wait

.PHONY: down
down:
	eval `${DP_DEPLOYMENT_DIR}/bin/kube-env --kube-context ${K8S_CONTEXT} --namespace ${K8S_NAMESPACE}` && \
	helmfile --kube-context ${K8S_CONTEXT} --namespace ${K8S_NAMESPACE} delete --purge || true
	kubectl --context=${K8S_CONTEXT} delete namespace ${K8S_NAMESPACE} --ignore-not-found || true
```

**Comment by mumoshu** [comment]
@blissd Thanks for sharing your use-case!

Yeah, that's basically how I'm using helmfile. And I was planning to just replace `sync` in your example with `apply --auto-approve`, and add `--auto-approve` to `delete`, when landing the latest helmfile onto my pipeline in near future.

So, it is not that I don't understand your use-case, but there are divergence among us about what good u/x is.

Perhaps you are not going to use `apply`? Then, how about using `apply` and `destroy` for interactive use-cases and `sync` and `delete` for non-interactive use-cases?

If that's ok, what we need is to add a new command `destroy [--auto-approve]`, and remove `--auto-approve` and the confirmation out of `delete`. WDYT?

**Comment by blissd** [comment]
From the docs, `sync` and `apply` mostly sound like the same thing, which is confusing. I'd rather they were more distinct, or merged and their behaviour differentiated by a command line flag.

For the same reason I wouldn't want to see a `destroy` command added. Delete should be enough.

So my suggestion is to have single commands for syncing and deleting, instead of two command with subtly different behaviours.

I'd imagine a CLI something like this:

```sh
# Sync changed releases, as determined by helm diff
$ helmfile sync 

# Sync all releases. Don't use helm diff, just 'helm install --upgrade' everything
$ helmfile sync --full    

# Only print commands that have side-effects, 
# for the use case where changes must be validated first
$ helmfile sync --dry-run    

# Delete all releases right now
$ helmfile delete

# Only print commands that have side-effects,
# for the use case where changes must be validated first
$ helmfile delete --dry-run
```

And then :wink: :
```
$ helmfile apply
No such command 'apply'

$ helmfile destroy
No such command 'destroy
```

**Comment by mumoshu** [comment]
Sounds good, as long as you can accept that `sync --dry-run` also prints a summary of affected releases at last.

**Comment by mumoshu** [comment]
A possible problem in the interactive workflow of running `helmfile sync --dry-run` first and then `helmfile sync` to commit is that, helmfile needs to read the whole tree of helmfie.yaml files twice, involving external commands(`{{ exec " ... " }}`) and files(`{{ readFile "..." }}`), and bunch of those(`helmfiles:`). It wouldn't be a good u/x when the tree is huge.

So, I'd be happy if we could also come up with a nicely named flag, that means you do want confirmation before commit.

I think that I don't have a strong opinion about making confirmation a default behavior, but I do have a strong opinion about that helmfile should works fast and nice when used interactively.

**Comment by blissd** [comment]
If you want to avoid processing many helmfiles twice, then perhaps instead of `--dry-run` add a `-i` or `--interactive` option?

**Comment by davidovich** [comment]
I have thought about this more, and I think that every "possibly cluster altering" command should have a interactive safeguard. I believe that it is easier to add `--auto-approve` in an automation context (which you don't change once introduced), than remembering to type --interactive at each invocation.

We should optimize for the user experience. The machine can receive hard-coded parameters in a source-controlled script. I definitely would prefer the prompt to help me not make mistakes.

@blissd What prevents you to add `--auto-approve` in your Makefile driven tests ?

**Comment by blissd** [comment]
Nothing stops me adding `--auto-approve`, and I will do that. However, it is the opposite of my preference for how command-line tools should work.  Default-on interactive safeguards to CLI tools harken back to those annoying old email client messages that said "do you really want to delete this email?" I like CLI tools to do what they are told, especially when I only use them from scripts. That behaviour would optimize my user experience.

I also don't see why `helmfile` would require an interactive step when the other tooling like `kubectl` and `helm` don't. As I use these tools together to mange different aspects of the same resources I would very much like for them to have consistent behaviours.

Our current use case is managing K8S resources during local testing and testing on CI, both of which are non-interactive. Our future planned use case (perhaps when `helmfile` is a bit nearer 1.0) is to manage production deployments, too, which would be driven by something like Jenkins and also be non-interactive.

None of my use cases are interactive, so being interactive by default is no help to me.

Of course, perhaps my non-interactive use cases aren't the common ones.

In fairness, though, I've destroyed plenty of things by running the wrong command. However, an interactive step like the one in `helmfile` won't stop me doing that. Once you get beyond four or five releases it become too easy to miss something that you don't want affected, or so much noise that it will be ignored.

Should all of these be deleted?

```
Affected releases are:
  app4-test (dp-incubator/dp-kafka-streams-v2)
  app45-test (dp-incubator/dp-kafka-streams-v2)
  app5-test (dp-incubator/dp-kafka-streams-v2)
  app50-test (dp-incubator/dp-kafka-streams-v2)
  app51-test (dp-incubator/dp-kafka-streams-v2)
  app60-test (dp-incubator/dp-kafka-streams-v2)
  app62-test (dp-incubator/dp-kafka-streams-v2)
  app63-test (dp-incubator/dp-kafka-streams-v2)
  app63a-test (dp-incubator/dp-kafka-streams-v2)
  app67-test (dp-incubator/dp-kafka-streams-v2)
  app70-test (dp-incubator/dp-kafka-streams-v2)
  app71-test (dp-incubator/dp-kafka-streams-v2)
  app79-test (dp-incubator/dp-kafka-streams-v2)
  app80-test (dp-incubator/dp-kafka-streams-v2)
  app81-test (dp-incubator/dp-kafka-streams-v2)
  app82-test (dp-incubator/dp-kafka-streams-v2)
  ... lots more...

Do you really want to delete?
  Helmfile will delete all your releases, as shown above.

 [y/n]: 
```

What's the right answer? I don't know because too many things can be altered so I can't really look at it and tell what is correct or not. I can only imagine this will be even less helpful when using `helmfile` with multiple `helmfile.yaml` files.

So for me, I suspect an interactive step won't stop the destruction of anything that shouldn't be destroyed.

I think this exhausts my commentary on the subject.

**Comment by manics** [comment]
Linux CLI tools follow all sorts of conventions. `rm` defaults to not prompting, but many distros alias it to default to interactive. `kubectl` and `helm` don't prompt. `yum` does prompt. `apt` prompts if it needs to do something extra.

If the interactive/non-interactive flag coudl be made a top level flag (not a flag belonging to a subcommand) it would be possible to change the default with a shell alias, e.g `alias helmfile=helmfile --noninteractive`

**Comment by mumoshu** [comment]
@blissd Thanks a lot for taking much time to explain your thoughts!

I now believe helmfile should default to non-interactive. And I'd add `helmfile [-i|--interactive]` and suggest aliasing it, `alias hi='helmfile --interactive'` for interactive use-case and refer to it in docs if necessary.

Thanks also to @davidovich @manics for your feedbacks!

**Comment by mumoshu** [comment]
#368 is the impl for this.
