### ISSUE TITLE
context in root is not respected

### ISSUE THREAD

**Issue by cmeury** [roboll/helmfile#383]
I've just rolled out something to the wrong cluster, no harm done luckily. But the `context: foo` setting in the root level was not respected, it took my currently configured context. Only the new `helmDefaults: { kubeContext: foo }` worked, so we may want to adapt the example in the readme.

**Comment by AnatolyRugalev** [comment]
Same here. I have this issue a couple of weeks already. My helmfile version: v0.36.0

**Comment by The-Loeki** [comment]
same, but specifying `kubeContext` under `helmDefaults` works as intended

**Comment by call** [comment]
Same issue here.

**Comment by AnatolyRugalev** [comment]
I suppose, `context` directive should be deprecated now in favor of `helmDefaults.kubeContext`?
