### ISSUE TITLE
Install instructions

### ISSUE THREAD

**Issue by CalvinRodo** [roboll/helmfile#393]
I ran the go get command but am unsure where the file gets downloaded from, is there some documentation I can reference?

**Comment by emman27** [comment]
`go get` is generally for developers. It actually downloads the source code from github into your go working directory. If you're not a go developer, you're probably better off downloading a binary release.

**Comment by mumoshu** [comment]
Hey! Thanks a lot for your support @emman27.

I remember that there was an another confusion in the past #304. So my best bet in regard to improving the doc is to remove the `go get github.com/roboll/helmfile` instruction from README.

Anyway -

@CalvinRodo You can grab it from the release page and [other locations](https://github.com/roboll/helmfile#installation). Regarding `go get`, it would have `git clone`d the entire repo under your `$GOPATH/src/github.com/roboll/helmfile` and the resulting binary would have been produced to `$GOPATH/bin/helmfile`. Not sure where the reference is though!

**Comment by mumoshu** [comment]
`CONTRIBUTING.md` sounds like a good idea. Thanks!

**Comment by CalvinRodo** [comment]
Awesome, yeah I'm not a go developer so was unfamiliar, and was a bit confused with it, I've used brew for our macs and your release page for our linux machines. 

I agree I was confused since it was under the installation section that this might have been a nice way to install similar to how npm global will install binaries.

I think a contributing.md would be a better fit for it.

**Comment by mumoshu** [comment]
Thanks @CalvinRodo! I've submitted #437 for that.

**Comment by Joannacervantes** [comment]
#1014

**Comment by Joannacervantes** [comment]
[Google Contacts.pdf](https://github.com/roboll/helmfile/files/3954140/Google.Contacts.pdf)
