### ISSUE TITLE
--kube-context flag does not work

### ISSUE THREAD

**Issue by AMeng** [roboll/helmfile#4]
The `--kube-context` CLI flag does not do anything. Passing in different contexts simply uses the default context. Even passing in a bad context name uses the default. The preview execution that is printed out is clearly not what is actually running.

Example command that will use default context:
```
$ helmfile --kube-context BAD_CONTEXT_NAME sync
exec: helm upgrade --install test stable/datadog --kube-context BAD_CONTEXT
...
```

When run manually, helm is able to accept context and apply just like helmfile should:
```
helm upgrade --install test stable/datadog --kube-context staging --file test.yaml
```

As you can see helm errors out if passed in a bad context:
```
$ helm list --kube-context BAD_CONTEXT_NAME
Error: could not get kubernetes config for context 'BAD_CONTEXT_NAME': context "BAD_CONTEXT_NAME" does not exist
```

**Comment by roboll** [comment]
This is fixed in `v0.6`.
