### ISSUE TITLE
--concurrency flag caused problems

### ISSUE THREAD

**Issue by ts4z** [roboll/helmfile#411]
I have a configuration with 24 charts in a helm file that was taking too long. I added a "--concurrency 3 flag".  I believe this caused a couple releases to end up thinking they had no deployed releases.

I wanted to share this feedback, but I realize it's not quite actionable, and I'm not sure how easy this is to reproduce. Ultimately I was able to work this out by splitting up the helmfile into multiple files and run them sequentially (after helm delete --purge .... to clean up the bad helm state).

**Comment by mumoshu** [comment]
@ts4z Hey! Thanks for reporting.
As I've explained in #484, this should have been fixed in recent versions of helmfile.
I'm closing this as already fixed, but please feel free to reopen in case you reproduce it.
