### ISSUE TITLE
bombs when helmfile.yaml is missing

### ISSUE THREAD

**Issue by sstarcher** [roboll/helmfile#42]
2018/03/02 14:34:33 warn: charts.yaml is loaded: charts.yaml is deprecated in favor of helmfile.yaml. See https://github.com/roboll/helmfile/issues/25 for more information
2018/03/02 14:34:33 err: open helmfile.yaml: no such file or directory

**Comment by sstarcher** [comment]
@mumoshu

**Comment by mumoshu** [comment]
@sstarcher Thx! #43 should fix this, but its completely untested because I wrote it from my iPhone 😆
