### ISSUE TITLE
Support for helm tpl function

### ISSUE THREAD

**Issue by astorath** [roboll/helmfile#420]
Hi!

Helm can render a file template with `tpl` function, helmfile has `readFile` option, but it reads file "as is". It would be nice to have `tpl` alternative here. 

Maybe you can:
- render files with `tmpl.RenderTemplateToBuffer` with `readFile` when file has gotmpl extension
- introduce a new function to render file instead of just loading it

**Comment by mumoshu** [comment]
@astorath Hey! Thanks for submitting this.

It sounds interesting, but I'm still unsure what would be exact use-cases.

With `readFile` you usually include any file into `helmfile.yaml` or environment values.yaml file, [values file templates](https://github.com/roboll/helmfile#values-files-templates). The included file contents are injected into the resulting yaml data, so it is true that there's no way to template the external file loaded via `readFile`.

It is just that I have no specific use-case myself and have no idea how I can introduce the feature in our docs. Could you help clarifying? Thanks!

**Comment by mumoshu** [comment]
@astorath I realized that using `tpl` seems like the easiest way when you want to extract a HUGE helm chart value whose part(s) needing to be templated.

So I've authored #504 😄

**Comment by mumoshu** [comment]
So If you got to want writing something like the below, try `tpl` in your `values.yaml.gotmpl`:

```
set:
- name: foo
  # This doesn't work as you might have expected, of course!
  file: hugefile.txt.gotmpl
```

**Comment by astorath** [comment]
@mumoshu thanks, sorry, missed your question in january. My usecase is similar: we use repo with lot's of different configurations for different environments.

If I place all these in helm chart, it exceeds 1Mb limit, so I have to store configs outside and pass as values to the chart.
