### ISSUE TITLE
Relative path in helmfile not relative to file in multi file setup

### ISSUE THREAD

**Issue by stefanthorpe** [roboll/helmfile#431]
I have several helmfiles:

- apps/
  - helmfile_1.yaml
  - filebeat/
    - helmfile_2.yaml

helmfile_1 is super simple:
```bash
environments:
  dev:
  prod:

helmfiles:
  - ./filebeat/helmfile_2.yaml
```
helmfile_2 is super simple:
```bash
environments:
  dev:
  prod:

releases:
- name: my-chart
  chart: .
```

The relative path in the helmfile_2 chart is the problem. This path should be relative to it's self. There is no way I can deploy this on it's own if I have to change the path to be relavent to the parent helmfile.
The docs also state "Relative paths referenced in the Helmfile manifest itself are relative to that manifest".

**Comment by mumoshu** [comment]
@stefanthorpe Thanks for reporting!

Just to clarify, you say that `chart: .` in `helmfile_2.yaml` is resolved relative to `helmfile_1.yaml`, right? That sounds like a bug. The desired behavior is `chart: .` resolved relative to the `helmfile_2` as you said.

**Comment by stefanthorpe** [comment]
Yes that's exactly what I'm saying
