### ISSUE TITLE
helmfile should pass on already set environment variables to helm

### ISSUE THREAD

**Issue by petergardfjall** [roboll/helmfile#438]
For a TLS-enabled Tiller, I'd like to be able to set the usual helm environment variables and have `helmfile` simply pass those on when executing `helm` commands.

```
export HELM_TLS_CA_CERT=...   # ca.pem
export HELM_TLS_CERT=...      # helm.pem
export HELM_TLS_KEY=...       # helm-key.pem
export HELM_TLS_ENABLE=true
```

This does not seem to be the case as I get the following errors with these set:
```
$ helmfile --file helmfile.yaml diff
Comparing kubernetes-dashboard stable/kubernetes-dashboard
Error: transport is closing
Error: plugin "diff" exited with error
...
err: exit status 1
exit status 1
```

Now, I managed to figure out that I _can_ set something similar to this in the `helmfile.yaml`
```
helmDefaults:
   args:
     - --tls
     - --tls-ca-cert={{ requiredEnv "HELM_TLS_CA_CERT" }}
     - --tls-cert={{ requiredEnv "HELM_TLS_CERT" }}
     - --tls-key={{ requiredEnv "HELM_TLS_KEY" }}
```

However, this only works for helm commands supporting those arguments, which for instance breaks down when using `helmfile lint`:
```
$ helmfile --file helmfile.yaml lint
...
Error: unknown flag: --tls

err: exit status 1
exit status 1
```

Of course, setting `--args` on the command-line for each helmfile comand that needs them is also possible but _really_ tedious:

```
helmfile --file helmfile.yaml lint
helmfile --file helmfile.yaml diff --args '--tls --tls-ca-cert=/path/to/ca.pem --tls-cert=/path/to/helm.pem --tls-key=/path/to/helm-key.pem'
helmfile --file helmfile.yaml apply --args '--tls --tls-ca-cert=/path/to/ca.pem --tls-cert=/path/to/helm.pem --tls-key=/path/to/helm-key.pem'
```

So the only reasonable thing I believe is to pass on the `HELM_TLS_*` environment variables if they are set.

**Comment by mumoshu** [comment]
@petergardfjall Hey! Thanks for reporting this.

I'm unsure how I could fix this because helmfile or helm-diff doesn't explicitly "unset" those environment variables.

Unless explicitly unset, all the environment variables should be inherited to sub-processes running helm commands. There's no need to explicitly "pass HELM_TLS_ envvars" aounrd, or am I missing something?

Just curious but what's your helm version? I see an upstream bug like https://github.com/helm/helm/pull/4657 can throw away your envvars on the helm-side.

In such cases we'd just need to bump helm.

**Comment by petergardfjall** [comment]
This is my environment:

```
$ helmfile --version
helmfile version v0.41.0

$ env | grep HELM
HELM_TLS_CERT=/path/to/helm.pem
HELM_TLS_KEY=/path/to/helm-key.pem
HELM_TLS_CA_CERT=/path/to/ca.pem
HELM_TLS_ENABLE=true
```

But as you can see, I get TLS problems trying to use `helmfile diff` or `helmfile apply`:
```
$ helmfile --file ../kubernetes/helmfiles/helmfile.minikube.yaml diff
...
Error: transport is closing
...
Error: plugin "diff" exited with error
....
err: exit status 1
exit status 1
```

However, if I explicitly pass those arguments to `helmfile`/`helm` it works:
```
$ helmfile --file helmfile.yaml diff --args "--tls --tls-ca-cert=${HELM_TLS_CA_CERT} --tls-cert=${HELM_TLS_CERT} --tls-key=${HELM_TLS_KEY}"
```

This seems to imply that these `HELM_TLS_*` variables indeed aren't being forwarded to `helm`.

I don't want the code to do any particular handling of these variables, I just want it to pass the existing environment variables to the subprocess.

**Comment by petergardfjall** [comment]
Is this the code being run when executing `helm`?
https://github.com/roboll/helmfile/blob/master/helmexec/runner.go#L24
```
// Execute a shell command
func (shell ShellRunner) Execute(cmd string, args []string) ([]byte, error) {
	preparedCmd := exec.Command(cmd, args...)
	preparedCmd.Dir = shell.Dir
	return preparedCmd.CombinedOutput()
}
```

Could it be that you explicitly need to pass on the environment to the process?
```
preparedCmd.Env = os.Environ()
```

**Comment by mumoshu** [comment]
Thanks!

Yep, that's why I'm curious on your helm'' version number (not helmfile's).

It's too bad that I don't have a test environment with tls-enabled tiller.

Would you mind running your `helm` directly, with the HELM_ envvars? If it works, the issue might be in helmfile.

**Comment by petergardfjall** [comment]
This helm-diff issue appears to have been fixed in the [latest release](https://github.com/databus23/helm-diff/releases/tag/v2.11.0%2B3). Since I've been running on `2.11.0+2` I presumable have a broken diff plugin, so let me try with the new plugin version and see if that resolves the issue.

**Comment by petergardfjall** [comment]
Indeed it does work now. So, version `2.11.0+3` of the helm-diff plugin does support TLS client-parameters via the `HELM_TLS_*` environment variables.

So this was a false alarm. Since both `helmfile diff` and `helmfile apply` makes use of the helm-diff plugin, the issue appeared to be originating from `helmfille`.
