### ISSUE TITLE
Automatically update repos in diff and sync?

### ISSUE THREAD

**Issue by manics** [roboll/helmfile#452]
Following the discussion on https://github.com/roboll/helmfile/issues/415 where chart dependencies are automatically updated by `diff` and `sync`. Would it also make sense to automatically run `helmfile repos`?

Main motivation is I always forget 😀.

**Comment by mumoshu** [comment]
@manics Hey! Thanks for this.

`helmfile sync` should already be running `helmfile repos`.

Also, `helmfile diff --sync-repos` sync repos before executing diff. However, making `--sync-repos=true` default would be preferable for consistency with `helmfile apply`. `helmfile apply` sync repos by default, and you can opt-out with `--skip-repos`.

Perhaps we should also migrate to `helmfile diff --skip-repos` as well?

**Comment by mumoshu** [comment]
Btw,

> Main motivation is I always forget 😀.

Same here 😄
