### ISSUE TITLE
helmfile apply: hide diff output

### ISSUE THREAD

**Issue by manics** [roboll/helmfile#458]
I've belatedly discovered `helmfile apply`, and it works really nicely! Only issue is it displays the output of `helm diff`, which may include parameters that shouldn't be exposed publicly. `--suppress-secrets` isn't enough since not all values are secrets in the Helm charts I'm using, though that'd make sense as a long term goal for the charts.

`helmfile --log-level warn` shows no output- I'd like to know which charts were updated, either as a summary or the output of `helmfile sync` for the changed charts.

Does that sound like a reasonable feature? If so should it be the default so `helmfile apply` diff output is suppressed unless `--log-level=debug`, or a new `helmfile apply` arg such as `--supress-diff`?

**Comment by davidecg** [comment]
I need this feature as well.

**Comment by skeenan947** [comment]
please!  The logs from our first helmfile install are so huge they're impossible to read

**Comment by mumoshu** [comment]
@skeenan947 Hey! I'm curious - Which parts of helmfile logs do you need in your case?

**Comment by skeenan947** [comment]
@mumoshu I'd like to see what releases were installed.  Optionally, it would be nice to get the values file passed to the chart too, but I definitely prefer to turn off the whole diff on a fresh install.

**Comment by mhyousefi** [comment]
This feature would be much appreciated!
