### ISSUE TITLE
Disable release?

### ISSUE THREAD

**Issue by tonsV2** [roboll/helmfile#461]
Is there a way to disable a specific release? Something like the following would be handy when dealing with multiple environments where a specific release isn't in some of the environments. Eg. something release for testing but not production

    releases:
      - name: some-name
        namespace: some-namespace
        chart: some/thing
        enabled = false

**Comment by sstarcher** [comment]
The current way to do that would be
```
releases:
{{  if eq .Environment.Values.blah "blah" }}
  - name: some-name
    namespace: some-namespace
    chart: some/thing
    enabled = false
{{- end }}
```

**Comment by tonsV2** [comment]
That's going to get messy really fast! But thanks for answering.

**Comment by mumoshu** [comment]
@tonsV2 Hi!

You will be able to write it like #427, once #465 is resolved.

**Comment by mumoshu** [comment]
I think #513 resolves this. Try `installed: {{ .Environment.Values.myapp.installed }}` with a different value for `myapp.installed` for each environment.
