### ISSUE TITLE
Deprecate `getOrNil` and enhance `get` instead

### ISSUE THREAD

**Issue by mumoshu** [roboll/helmfile#465]
`getOrNil` introduced via #357 and #370 was intended to be used with `default` in order to support setting default values for environment values.

However, recently, it turned to not work as expected for bool values as reported in #427. That is, `default` applies defaulting to not only nil but also any empty values.

In #427 I proposed to add `getOrDefault` that would be used like `{{ .Environment.Values.myBoolValue | getOrDefault "a.b.c" true }}`. But it turns out we may use it in combination with `default` like `getOrDefault "a.b.c" "used_instead_of_nil" | default "used_instead_of_empty_str"` which confuses me due to overloading of the term "default".

So, I'd just enhance `get` to accept an optional second parameter as the default value used when the target value was not found(or nil). It would also be nice to produce a nicer error message when `get` is used without the default value.

```
{{ .Environment.Values | get "foo.bar" }}

# BEFORE:
# no value exist for key "foo.bar" in {....}:
#
# AFTER:
# no value exist for key "foo.bar" in {....}: provide the default value via the second parameter of `get` if this isn't a mistake
```

**Comment by royjs** [comment]
Any progress on that? I also need this

**Comment by Morriz** [comment]
Hi @mumoshu, where is this `get` documented? I can't find it

**Comment by mumoshu** [comment]
Hey! I believe this isn't documented. A pr to add some doc around it is always welcomed!

**Comment by Morriz** [comment]
aha, can't you just edit inline in github and just add a line? I am not aware of it's options

**Comment by mumoshu** [comment]
@Morriz I would do when I have some spare time, but I'm always overwhelmed by questions coming into github issues and via slack. That's why I'm asking everyone for help :)
