### ISSUE TITLE
`helmfile diff` always shows changes for CRDs

### ISSUE THREAD

**Issue by andrewnazarov** [roboll/helmfile#468]
`helmfile diff` always shows changes for CRDs, hence `helmfile apply` always upgrades a release containing CRDs.

helmfile version v0.43.2

**Comment by mumoshu** [comment]
@andrewnazarov Thanks for reporting!

This seems like an issue in helm-diff.

Anyway, I'm wondering how the diff looked like. Did helm-diff show unnecessary additions of CRDs?

**Comment by andrewnazarov** [comment]
@mumoshu , oh, I don't know what's happening. I can swear, I've seen this behavior more than ten times in a row, but today everything seems ok. Telling the truth diffs has been working kinda weird for me. I'll try to keep an eye on it. 

Btw, thank you for the great tool!

**Comment by andrewnazarov** [comment]
Gonna close this since I stopped getting this changes in diffs. Probably this was due to some issues with updates of prometheus-operator and cert-manager. Both have CRDs.
