### ISSUE TITLE
Helmfile hangs when decrypting secret with a passphrase-protect key

### ISSUE THREAD

**Issue by michaelgeorgeattard** [roboll/helmfile#479]
If passphrase cache is cleared using:

`echo RELOADAGENT | gpg-connect-agent`

`helmfile` stalls and eventually times out when decrypting secret file.

Also, `helm secrets` is also sometimes stalling when decrypting; passphrase prompt does not always appear.

**Comment by michaelgeorgeattard** [comment]
https://github.com/mozilla/sops/issues/429

**Comment by mumoshu** [comment]
@michaelgeorgeattard Hey! Thanks for the report. Just confirming, but did [your workaround](https://github.com/mozilla/sops/issues/429#issuecomment-466425954) solved this?

**Comment by michaelgeorgeattard** [comment]
Hi @mumoshu, yes the workaround solved the issue.

I assume the problem is a glitch from `sops` end, closing this issue for now.
