### ISSUE TITLE
Proposal: Flag to force deleting each releases

### ISSUE THREAD

**Issue by aslafy-z** [roboll/helmfile#481]
It would be handful to be able to delete all the target releases even if some of them fails / doesn't exists. 
Eventually this feature can use a flag (`force` or `all`?) to prevent breaking change.

Here's a pseudo-helmfile:
```
releases:
- name: not-installed
- name: already-installed
```

If I run
```
helmfile delete --purge
```
it fails at the first release and does not process the other.

```
receiving result 0
worker 1/1 started
Deleting not-installed
exec: helm delete not-installed --purge
Error: release: "not-installed" not found

sending result for release: not-installed

sent result for release: not-installed

worker 1/1 finished
received result for 0
err: release "not-installed" failed: exit status 1
changing working directory back to "/home/zadkiel/x"
failed processing /home/zadkiel/work/x/helmfile.yaml: release "not-installed" failed: exit status 1
 ```

**Comment by mumoshu** [comment]
@aslafy-z Good catch!

I believe we can just make helmfile NOT to stop on the first error. Unlike other helmfile commands, it sounds like a more natural behavior for the delete command.

**Comment by mumoshu** [comment]
.. Or maybe to handle the specific case that a missing release stops the whole deletion process, we can enhance helmfile to run `helm delete --purge` only on available releases, which eventually removes the error.

**Comment by sgandon** [comment]
to follow up on this, Is it possible to specify the "--purge" flag inside the helmfile definition cause whenever I forget to add it to the `delete` command (and this happens often) I always endup with a failure when re-instaling a helmfile.
Actually I never understood why you would not purge everything upon delete. the ideal would be to default the delete to --purge and add a flag to not purge it accasionnaly if required.

**Comment by mumoshu** [comment]
Sounds like a good feature req! Would you mind opening a dedicated issue to
track it?
2019年3月28日(木) 19:04 sgandon <notifications@github.com>:
