### ISSUE TITLE
Multiple tillers managed by helmfile ?

### ISSUE THREAD

**Issue by drimailorr** [roboll/helmfile#486]
Hi

I'm having use case when I have two tillers installations (one is managed by dev team and another by devops team). One tiller is tls enabled and managed by Devops team. Another tiller installation isn't tls enabled and managed by Dev team. They both belong to one environment.
Is it possible to specify multiple tiller arguments (tls/no-tls) and releases in single helmfile ?

Just to summarize it seems like parameters "args=--tls" and "tillerNamespace" aren't working per release scope.

```
failed to read helmfile.yaml: reading document at index 1: yaml: unmarshal errors:
  line 60: field args not found in type state.ReleaseSpec
  line 62: field tillerNamespace not found in type state.ReleaseSpec
```

**Comment by sstarcher** [comment]
It will make your life significantly better if you use a single parent helmfile and 2 children helmfiles or use a helmfile directory.

**Comment by drimailorr** [comment]
Hello Shane
Thank you for your input. Indeed it's manageble with 2 helmfiles, I was just wondering if it can be done with one.

**Comment by mumoshu** [comment]
@drimailorr Glad to see an advanced use-case like yours!

If you want something that works today, @sstarcher's suggestion would be the best.

But I think this is a valid feature request. What If we added `tillerNamespace` and other tiller-related settings per release. Would it be useful to you?

**Comment by orbiran88** [comment]
I'm just got into this issue... I will wait for that @mumoshu, thanks!

**Comment by drimailorr** [comment]
Hello @mumoshu

Certainly, per release helmDefaults settings will be useful.
Maybe per environment as well if it's not too much trouble.

**Comment by mumoshu** [comment]
@drimailorr Got it, thx!

> Maybe per environment as well if it's not too much trouble.

I think you'd prefer templating `tillerNamespace` and other per-release settings than, enhancing helmfile for that! Like `tillerNamespace: {{ .Environment.Values.tillerNsNameBase}}-myapp`.

**Comment by drimailorr** [comment]
Thanks a lot
