### ISSUE TITLE
Absolute paths to helmfiles do not work

### ISSUE THREAD

**Issue by Nuru** [roboll/helmfile#488]
Despite #475, absolute paths do not work when including helmfiles in `helmfile` version v0.45.3. Given a `helmfile.yaml` of
```
helmfiles:
  - "/path/to/file.yaml"
  - "/path/to/otherfile.yaml"
```
`helmfile sync` does not correctly find the files and instead outputs
```
err: no releases found that matches specified selector() and environment(default), in any helmfile
```
It appears `helmfile` treats absolute paths as if they were relative to the current working directory.

**Comment by mumoshu** [comment]
@Nuru Hey! Thanks for the report.

Honestly saying, I'm trying my best not to rely on absolute paths while using helmfile in my job, for reproducibility of helmfile deployments. But as I've been asked several times regarding the use-cases of using abs paths in various places of helmfile.yaml, I'm not opposed to fix this!

So #498 is that. Would you mind testing it once released?
