### ISSUE TITLE
FR: sync --if-diff-only ?

### ISSUE THREAD

**Issue by johnmarcou** [roboll/helmfile#489]
Hi,

I would like to use the `helmfiles` feature (glob way) to sync multiple helmfile deployments, in GitOps model, which would run every `x minutes` and on push to the infra-git-repo.

The bash equivalent script, from the doc, seems to resync only if the definition have changed:
```
for d in apps/*; do helmfile -f $d diff; if [ $? -eq 2 ]; then helmfile -f $d sync; fi; done
```

But, `helmfile sync` on the parent folder is not doing this. This result in `revision` of the release (on the tiller side) bumps every time we resync.

Would it be possible to implement an option to resync only if detected diff?

Thank you.

**Comment by manics** [comment]
Does `helmfile apply` do what you want? Be aware that unlike `helmfile sync` it [always prints out the diff which might include sensitive information](https://github.com/roboll/helmfile/issues/458)

**Comment by sstarcher** [comment]
Yes, I would recommend using apply for this case.  We could add a flag to apply to not print out the diff.

**Comment by johnmarcou** [comment]
John... RTM
`apply     apply all resources from state file only when there are changes`

Thanks what I was after, thank you guys!
