### ISSUE TITLE
Diff and installed: false

### ISSUE THREAD

**Issue by goruha** [roboll/helmfile#499]
## Steps to reproduce

* Install a release with helmfile
* Set for the release `installed: false`
* Run `helmfile diff`

## Expects 
* Get diff with `-` for all resources from the release

## Exits
* No changes

## How to fix
* Check this https://github.com/roboll/helmfile/blob/master/state/state.go#L550
 and https://github.com/roboll/helmfile/blob/master/state/state.go#L255

**Comment by mumoshu** [comment]
@goruha Good catch! I think we need a special handling for this case as helm-diff doesn't support this by its design. Maybe enhance helmfile to print its own `-` diffs for the to-be-deleted releases?

**Comment by andrewnazarov** [comment]
Any plans for this?
We are using terraform-provider-helmfile, and in case of switching from `installed: true` to `installed: false` it can't see the changes.

**Comment by mumoshu** [comment]
@andrewnazarov Unfortunately nothing planned on this. If anyone could help me implementing this, I'm more than happy to support in terms of reviews, design advice, etc.

**Comment by mumoshu** [comment]
The first issue to be addressed would be that helm-diff, which helmfile uses under the hood, doesn't support showing diff on delete.

**Comment by andrewnazarov** [comment]
Probably this issue could be closed in favour of https://github.com/roboll/helmfile/issues/1072
Or vice versa.

**Comment by mumoshu** [comment]
Ah thanks! Yes you're absolutely correct. I should have linked this issue from #1072 but was unable to remember this one
