### ISSUE TITLE
Support yml as a file suffix

### ISSUE THREAD

**Issue by RobWin** [roboll/helmfile#5]
Hi,

first of all: Awesome idea and library. Thank you.

Many tools and libraries use `yml` as a file suffix for YAML files. I intuitively created a file called `charts.yml`.
Do you think you can support both file suffixes: `yaml`  and `yml`?

**Comment by roboll** [comment]
Thanks for the feedback, glad to hear it. 😄 

I don't have a strong preference between the two file extensions, but I would not want to break existing setups. If you want to put in a PR to first try `.yaml`, and then `.yml`, I would merge it.

You can also use `charts.yml` by using the `-f` flag - `helmfile -f charts.yml`.

**Comment by roboll** [comment]
Going to close this, the workaround is there and if you feel strongly feel free to submit a PR.
