### ISSUE TITLE
Following logs, optionally until the job/pod completes

### ISSUE THREAD

**Issue by mumoshu** [roboll/helmfile#50]
Extracted from https://github.com/roboll/helmfile/issues/49#issuecomment-371848711

This still seems like a scope-creep regarding what helmfile do today, yet I find nowhere to do this cleanly outside of helmfile.

**Comment by gtaylor** [comment]
This does seem like we're probably creeping scope a bit. Hate to see helmfile get to be too hairy/complex.

Might this be more the province of something more heavy-duty like Spinnaker.

**Comment by mumoshu** [comment]
@gtaylor Thank you very much for the feedback!
It really helps shape helmfile's direction and scope.

Honestly saying, I won't agree with calling out Spinnaker just for tailing logs, but I do agree that you would certainly use an another tool for tailing logs like `stern`!

Perhaps just running `stern` until the pod/job finishes would do the job today.
Let's close this and keep us concentrated on what helmfile would clearly do.

Thanks again for your feedback 👍
