### ISSUE TITLE
chart version not displayed when doing sync

### ISSUE THREAD

**Issue by sgandon** [roboll/helmfile#502]
When running `helmfile sync`  we don't know which chart version was used especially if some semver constraint was used .
That would be useful to display the version installed.

**Comment by mumoshu** [comment]
@sgandon Thanks! Your suggestion sounds so nice.

Should this be a feature request to `helm` as helmfile just calls `helm upgrade install` that that's `helm` who decides the exact version?

Or do we have anything feasible in helmfile?

**Comment by mumoshu** [comment]
`helm list | grep YOUR_RELEASE` should include the exact chart version number helm decided to use. Does it help, or can helmfile produce a nicer `helmfile apply` output based on outputs from the `helm list`?

**Comment by sgandon** [comment]
indeed that is what I use to check on the release version but that would be nice to have in displayed in helm file logs.
I have tryied to create a hook on cleanup to launch this command without success.
This is strange in fact. I have this error on a yaml that does not even have an environment node.
```>helmfile -f local-hybrid.helmfile.yaml sync
could not deduce `environment:` block, configuring only .Environment.Name. error: failed to read local-hybrid.helmfile.yaml: reading document at index 1: yaml: line 21: did not find expected node content
failed to read local-hybrid.helmfile.yaml: reading document at index 1: yaml: line 21: did not find expected node content```


here is my yaml file
```releases:
- name: test-infra
  namespace: test
  chart: talend/talend-infrastructure
  version: ~2.0.0
  values:
    - tags:
        talend-redis: true
  hooks:
  - events: ["cleanup"]
    command: "helm"
    args: ["list ", "|", "grep", , "{{`{{.Release.Name}}`}}"]
```

**Comment by sgandon** [comment]
Shall I file a bug ?

**Comment by mumoshu** [comment]
Not sure if that's the root cause, but you can't write pipes in args!
Try 'bash' as the command, and put your script in args like ["-c", "helm
list | grep ...."]
2019年3月26日(火) 21:44 sgandon <notifications@github.com>:

**Comment by sgandon** [comment]
Ok. I managed to make the hook kind of working cause it does not displaying anything if I am not using the `--log-level debug`.
here is the hook
```
  hooks:
  - events: ["cleanup"]
    command: "sh"
    args: ["-c","helm list | grep {{`{{ .Release.Name }}`}}"]
```

**Comment by sgandon** [comment]
it seems that the output of the hook command is not displayed in the helmfile ouput.
So I guess that could also be another feature request to have hook output on the helmfile output or it might also be considered as a bug.

**Comment by sgandon** [comment]
I'll propose a PR for this with a complete summary of releases that where upgraded, deleted and in error.
