### ISSUE TITLE
helmfile sync/apply output error when 'installed: false' is set and the release does not exist.

### ISSUE THREAD

**Issue by naseemkullah** [roboll/helmfile#507]
continuing in the spirit of https://github.com/roboll/helmfile/issues/423 ..

I understand that the intended behaviour for this is to simply uninstall a release if it is already installed. but could it be possible to do so AND if it is not released, not output any error? or at the very least just a Warning?? FWIW it does not error our (command still exits with `0` despite the various e.g. `Error: getting deployed release "jaeger": release: "jaeger" not found`

Reason is I am using this as a way to decide on which env (which correspond to kube contexts in my case) to install charts on, rather than have 1 helmfile per env, i've decided to create 1 helm file per namespace with all possible charts in each namespace, but explicitly setting which envs need those charts with installed values such as:

  `installed: {{ eq .Environment.Name "dev" "staging" "production" }}`
  `installed: {{ eq .Environment.Name "dev"  }}`
  `installed: {{ eq .Environment.Name "qa" "staging" "production" }}`
  `installed: {{ eq .Environment.Name "production" }}`

etc.

Many thanks!

**Comment by mumoshu** [comment]
Good catch! This should definitely be fixed, and I submitted #508

**Comment by naseemkullah** [comment]
Thank you @mumoshu !
