### ISSUE TITLE
Bake releases

### ISSUE THREAD

**Issue by willejs** [roboll/helmfile#51]
Maybe use goreleaser in the CI to do so?

I can make a PR, but can a maintainer help by adding the githb auth token and getting it working?

**Comment by mumoshu** [comment]
Hi @willejs! Good suggestion. Would an envvar named `GITHUB_TOKEN` work?

@roboll Would you mind setting the envvar with the [encrypted variables feature](https://docs.travis-ci.com/user/environment-variables/#Defining-encrypted-variables-in-.travis.yml)?
@willejs and I could do all the remaining work to start releasing per a new tag automatically.

**Comment by willejs** [comment]
@mumoshu yep all we need is the `GITHUB_TOKEN` with permissions to push new releases and tags. 👍

**Comment by sstarcher** [comment]
ya, a release would be great as it's been a while and has some new features cut.

**Comment by roboll** [comment]
I will set something up tonight.

**Comment by afirth** [comment]
anything i can do to get the container builds happening too?

**Comment by mumoshu** [comment]
@roboll Oh, hey, you seem to have already implemented the automatic release job before! https://github.com/roboll/helmfile/blob/master/circle.yml#L33

**Comment by sstarcher** [comment]
According to that we only need to create a tag that starts with v

**Comment by roboll** [comment]
Yes! I was just coming here to set it up and checked, and it should be working.

All you need to do is create a tag and it should automatically create a release.

**Comment by roboll** [comment]
`v0.10` is released
