### ISSUE TITLE
failing to load values file in environment

### ISSUE THREAD

**Issue by sgandon** [roboll/helmfile#518]
I am trying to load a values file in the default environment but get an unmarshal error.
helmfile
```
environments:
  default:
    values:
    - default.yaml
```
default.yaml
```
version: 12
```
and the error I get is
```
>helmfile -f test apply
failed to read default.yaml: reading document at index 1: yaml: unmarshal errors:
  line 1: field version not found in type state.HelmState
```
What am I doing wrong ?

**Comment by sgandon** [comment]
helmfile version v0.47.0

**Comment by sgandon** [comment]
I think I found the reason, 
I have a folder called `test` in which I have those 2 files (helmfile.yaml and default.yaml)
and when I cd outside of the folder and do a `helmfile -f test` it tries to read both files as if they where helmfile templates.
On solution is to move the default.yaml in a subfolder or to change the extension.

**Comment by mumoshu** [comment]
Thanks for reporting!

Makes sense. helmfile does treat all the yaml files under the directory
specified with `-f` as helmfiles, not values.yaml files. That's by-design.

If you don't want to change the dir structure, just specify the file, like
`helmfile -f test/helmfile.yaml`.
2019年3月30日(土) 2:48 sgandon <notifications@github.com>:
