### ISSUE TITLE
sync brew formula and current release

### ISSUE THREAD

**Issue by naseemkullah** [roboll/helmfile#532]
Hi,
would it be possible to keep release and brew formula in sync? https://formulae.brew.sh/formula/helmfile

Thanks!
Naseem

**Comment by mumoshu** [comment]
@naseemkullah Thanks for suggestion! Although I do believe the brew formula for helmfile is useful and important, unfortunately, I have no bandwidth to manually create a PR on each new helmfile release. It's so frequent!

So, would you be possible to open a PR to the formulas repo when you think you need an update?

**Comment by naseemkullah** [comment]
Yes of course, thanks @mumoshu!
