### ISSUE TITLE
destroy killed wrong services

### ISSUE THREAD

**Issue by sstarcher** [roboll/helmfile#534]
I have services called a,b,c that are installed into 2 different tillers.
I can `-l namespace=dev destroy` which picked up a,b,c that were installed, but it destroyed them from the default tiller and not the tiller in the helmfile.

**Comment by mumoshu** [comment]
Thanks for reporting! Perhaps helmfile is missing tiller-related flags while calling helm, in certain cases.
I'll take a look into the code-base.

**Comment by mumoshu** [comment]
So it turned out "list", "diff", "status", "delete", "destroy" were not taking tiller-related args into account(terrible!

**Comment by mumoshu** [comment]
#536 fixes this
