### ISSUE TITLE
helmfile destroy does not delete helm releases in status : PENDING_INSTALL 

### ISSUE THREAD

**Issue by sgandon** [roboll/helmfile#539]
the `wait` feature is sometime causing problems cause if all the pods are not started the helm release is in a PENDING_INSTALL status.
And if you want to delete everything during that time, the `helmfile destroy` fails to delete those pending releases.

**Comment by mumoshu** [comment]
Thanks for reporting!

How helmfile destroy is faling? Is it ignoring pending releases in the
first place, or trys to delete and fails complete it?

If that's former, do you think `helmfile destroy` should delete pending
releases as well?
2019年4月5日(金) 0:43 sgandon <notifications@github.com>:

**Comment by sgandon** [comment]
it is just ignoring them, it looks like there is a check on the release status.
And yes when you say destroy you want everything destroyed even pending ones.

**Comment by mumoshu** [comment]
I'll take a look! Thx. I was assuming that every release destroyable is
shown when we run `helm list`. But it isn't true as helmfile is ignoring
them.
2019年4月5日(金) 0:54 sgandon <notifications@github.com>:

**Comment by sgandon** [comment]
when you run `helm list -a` you'll see all of them whatever the status.

**Comment by mumoshu** [comment]
That info does help! Thx for your support
2019年4月5日(金) 1:08 sgandon <notifications@github.com>:

**Comment by dududko** [comment]
Noticing the same problem, helmfile can not destory the release which has the status `PENDING_INSTALL`. To purge the release I need to call `helm delete --purge <release name>` manually.

helmfile version: 0.92.1

@sgandon is right, it seems like the only thing is needed is to pass `-a` flag to the `helm list` call.

**Comment by dududko** [comment]
@mumoshu could you please have a look on this issue one more time ?
