### ISSUE TITLE
helmfile exits with an error when user chooses to not install a helmfile

### ISSUE THREAD

**Issue by sgandon** [roboll/helmfile#543]
launch an `helmfile apply` and say no when you are asked for applying the changes.
then the command exits with many errors and I should not expect any.
```
Do you really want to apply?
  Helmfile will apply all your changes, as shown above.

 [y/n]: n
err: exit status 2
err: exit status 2
err: exit status 2
err: exit status 2
err: exit status 2
changing working directory back to "/Users/sgandon/git-repos/helm-charts/platform-services/helmfile"
exit status 2
```
we are calling helmfile from another tool and we would not want this choice exits as an error.

**Comment by mumoshu** [comment]
I personally see two problems here, one is noisy `err` messages, one is the exit status.

For the latter, can you just disable interactivity(omit `--interactive`) and use some bash to treat 2 as one of expected statuses?

```
helmfile apply
status=$?
if [[ $status -eq 0 -r $status -eq 2 ]; then
  # expected code
else
  fail
fi
```

**Comment by sgandon** [comment]
omit interactive mode is not an option if you really want it and also we are hidding helmfile into another tool. 
And then why would it exits as an error when it is a user choice and not an error that happend ?
(The noisy error message is anoying but not that important).

**Comment by mumoshu** [comment]
I see. That's to allow you to

**Comment by mumoshu** [comment]
Ah, and I now understand that you're asking why you would need the errorneous exit code when in the interactive mode.

Definitely we don't need it :)

I'll just change it to return 0 when you typed `n` in the interactive mode.
Is that okay? Just wanted to make sure.

**Comment by mumoshu** [comment]
@sgandon Forgot to mention you!

**Comment by sgandon** [comment]
that is perfect thanks.

**Comment by mumoshu** [comment]
So say the user sees helmfile is going to affect releases `A` and `B`, typed `n`, then `helmfile` asks the user whether they want to apply `A` or `B`?

**Comment by sgandon** [comment]
nope, this is in case of multiple sub-helmfile, the first subhelm file will ask you if you want to update and you say "no", then the `apply` shall continue and if the second helmfile has changes you are also asked if you want to apply the changes and can say yes and only the second helmfile releases will be installed.

**Comment by mumoshu** [comment]
Ahh, that makes sense! Thanks for clarifying. I'd like helmfile to work like that.

**Comment by mumoshu** [comment]
@sgandon Hey! #586 would reduce confusing error messages AND allows you to interactively apply sub-helmfiles one by one. PTAL
