### ISSUE TITLE
Template subcommand is "invalid"

### ISSUE THREAD

**Issue by johnmarcou** [roboll/helmfile#551]
Hi all,

The `template` command is printing more than templates. The command print information message:
```
helmfile template | grep Decrypting
Decrypting secret [REDACTED]/prod/secrets.yaml
Decrypting [REDACTED]/prod/secrets.yaml
```

This result in invalid kubernetes templates:
```
helmfile template | kubectl diff -f -
error: unable to decode "STDIN": json: cannot unmarshal string into Go value of type unstructured.detector
```

This can be easily fix with `grep -v -e '^Decrypting .*'` workaround, but I would suggest to adapt this.

EDIT: the `--log-level=warn` make both "Decrypting" message and rendered template disappearing. It's like the template is part of the info-log. IMO it should be a standard print.

Thank you.

**Comment by johnmarcou** [comment]
Same issue with the dependencies:

```
# helmfile template
Building dependency ....
Hang tight while we grab the latest from your chart repositories...
...Successfully got an update from the "asci" chart repository
...Successfully got an update from the "incubator" chart repository
...Successfully got an update from the "monocular" chart repository
...Successfully got an update from the "kiwigrid" chart repository
...Successfully got an update from the "gitlab" chart repository
...Successfully got an update from the "stable" chart repository
...Successfully got an update from the "bitnami" chart repository
Update Complete. ⎈Happy Helming!⎈
Saving 1 charts
Downloading postgresql from repo https://charts.bitnami.com/bitnami
Deleting outdated charts
....
[RENDERED MANIFESTS]
```

**Comment by mumoshu** [comment]
@johnmarcou Thanks for the report!

Yeah this isn't desirable at all..
Can we just turn all the log messages to be printed to STDERR, so that only kubernetes manifests are printed to STDOUT?

**Comment by johnmarcou** [comment]
Hi @mumoshu, 

No worries, thank you for helmfile!
If printing messages to `stderr` and templates to `stdout` is easier, I guess that would work.
But this means, for application management (like ArgoCD), the rendering command would be: `helmfile template &2>/dev/null`, which is a bit less elegant than `helmfile template`.

I would say that all messages (update repo, update dep, decrypting secrets, etc) should be in `DEBUG` log level, and `template` subcommand should set the default log level at `ERROR`.
Rendered manifests should be not logging but just printing. That's my opinion. :)

**Comment by mumoshu** [comment]
@johnmarcou Hey! Thanks for the response. I also read your issue in `tilt` and got surprised tilt can be used with helmfile :) Great job.

> the rendering command would be: helmfile template &2>/dev/null, which is a bit less elegant than helmfile template.

Just wanted to confirm but I was in the impression that you don't need `&2 >/dev/null` in that case, as my friend is using basically `helmfile template | sed -e '1,/---/d'` as the argocd config management plugin.

**Comment by mumoshu** [comment]
Just read https://github.com/windmilleng/tilt/issues/1517 and this has been a major gotcha for other use-cases like `tilt`.

**Comment by johnmarcou** [comment]
My bad, you are actually right.

Kubectl actually doesn't read stderr as this test confirm it:
```
k apply -f - < <(echo)
error: no objects passed to apply
```

```
k apply -f - < <(echo ; echo NOERROR > /dev/stdout)
error: error validating "STDIN": error validating data: invalid object to validate; if you choose to ignore these errors, turn validation off with --validate=false
```

```
k apply -f - < <(echo ; echo NOERROR > /dev/stderr)
NOERROR
error: no objects passed to apply
```

Even though, I still think it's a bit dangerous to print warnings on the templates command, for example if we have to redirect the output to a file, or something.

**Comment by mumoshu** [comment]
@johnmarcou Thanks for confirming!

> Even though, I still think it's a bit dangerous to print warnings on the templates command, for example if we have to redirect the output to a file, or something.

I completely agree about that 👍 

I'll shortly turn almost all the log messages to go STDERR by default, still "print"ing useful outputs like ones from `helm template` to STDOUT.

And we address the log-level changes later, in another issue, so that we can this this issue sooner.

Does it make sense to you?

**Comment by johnmarcou** [comment]
Sounds good to me.

Thank you for your support!
