### ISSUE TITLE
Helm apply not deleting releases

### ISSUE THREAD

**Issue by acaire** [roboll/helmfile#554]
Hi, starting at #526, release deletion is broken in apply.

Here's the output of `helmfile --log-level debug apply`:

```
processing file "helmfile.yaml" in directory "."
second-pass rendering result of "helmfile.yaml":
 0: helmDefaults:
 1:   tillerNamespace: kube-system
 2: releases:
 3: - chart: stable/redis
 4:   force: false
 5:   installed: false
 6:   labels:
 7:     app: redis
 8:   name: redis
 9:   namespace: default
10:   values: []
11:

worker 1/1 started
worker 1/1 finished
worker 1/1 started
worker 1/1 finished
Listing releases matching ^redis$
exec: helm list ^redis$
NAME 	REVISION	UPDATED                 	STATUS  	CHART      	APP VERSION	NAMESPACE
redis	1       	Fri Apr 12 21:37:42 2019	DEPLOYED	redis-6.4.4	4.0.14     	default

worker 1/1 started
worker 1/1 finished
worker 1/1 started
worker 1/1 finished
```

Expected this (working fine in the commit before - 3edc7d6f331ded66499eaac4a0dbe4f83d371412):
```
processing file "helmfile.yaml" in directory "."
second-pass rendering result of "helmfile.yaml":
 0: helmDefaults:
 1:   tillerNamespace: kube-system
 2: releases:
 3: - chart: stable/redis
 4:   force: false
 5:   installed: false
 6:   labels:
 7:     app: redis
 8:   name: redis
 9:   namespace: default
10:   values: []
11:

worker 1/1 started
worker 1/1 finished
worker 1/1 started
worker 1/1 finished
Listing releases matching ^redis$
exec: helm list ^redis$
NAME 	REVISION	UPDATED                 	STATUS  	CHART      	APP VERSION	NAMESPACE
redis	1       	Fri Apr 12 21:37:42 2019	DEPLOYED	redis-6.4.4	4.0.14     	default

worker 1/1 started
worker 1/1 finished
worker 1/1 started
Listing releases matching ^redis$
exec: helm list ^redis$
NAME 	REVISION	UPDATED                 	STATUS  	CHART      	APP VERSION	NAMESPACE
redis	1       	Fri Apr 12 21:37:42 2019	DEPLOYED	redis-6.4.4	4.0.14     	default

Deleting redis
exec: helm delete redis --purge
release "redis" deleted

worker 1/1 finished
```

**Comment by andrewnazarov** [comment]
Facing the same issue.

**Comment by aegershman** [comment]
If it means anything, still seeing this bug on macOS helmfile version v0.54.2

**Comment by nullbyte61** [comment]
> If it means anything, still seeing this bug on macOS helmfile version v0.54.2

Same on Linux v0.54.2, seems it wasn't included in that release.

**Comment by mumoshu** [comment]
Thanks for your reports!
Can we say that this affects `helmfile apply` only, and `helmfile sync` does work as expected - uninstall the releases moved from `installed: true` to `installed: false`, right?

**Comment by mumoshu** [comment]
@nullbyte61 

> Same on Linux v0.54.2, seems it wasn't included in that release.

Thanks for the info! I just checked it and saw https://github.com/roboll/helmfile/commit/04a9ea1d2a80b4d746c0b441e85416acafb5a6fb should be included since v0.54.1(although v0.54.1 had no binary available due to failures in the release script)

Probably something's wrong in our implementation

**Comment by mumoshu** [comment]
FWIW, I'm unable to reproduce this in v0.55.0. What I did is basically run `helmfile sync` and `helmfile apply` with the following `helmfile.yaml`, manually changing `installed: true` to `installed: false` and vice versa, and it just worked as expected.

```
repositories:
- name: stable
  url: https://kubernetes-charts.storage.googleapis.com

releases:
- name: envoy
  chart: stable/envoy
  installed: true
```

What am I missing..?

**Comment by nullbyte61** [comment]
> @nullbyte61
> 
> > Same on Linux v0.54.2, seems it wasn't included in that release.
> 
> Thanks for the info! I just checked it and saw [04a9ea1](https://github.com/roboll/helmfile/commit/04a9ea1d2a80b4d746c0b441e85416acafb5a6fb) should be included since v0.54.1(although v0.54.1 had no binary available due to failures in the release script)
> 
> Probably something's wrong in our implementation

I just checked and there was a mistake on one of my automation scripts (The script downloads an older release). Thank you

**Comment by mumoshu** [comment]
@nullbyte61 Great! Glad it worked for you. Thanks for reporting back 😄

**Comment by mumoshu** [comment]
@aegershman Did it work for you?

@acaire Thanks for taking your time on revisiting this ☺️
