### ISSUE TITLE
Feature Request: make helmfile to understand .yml

### ISSUE THREAD

**Issue by afoninsky** [roboll/helmfile#565]
There are bunch of tools which generates `yml` extension instead of `yaml`. For example I'm able to create `helmfile.d/*.yml` files using `kapitan` tool, but unable to create `helmfile.d/*.yaml` as extension is hardcoded. In this case it's hard to do `helmfile diff` out of the box ... this makes me sad.

Is it possible to support both? Thx.
https://stackoverflow.com/questions/21059124/is-it-yaml-or-yml/21059164

**Comment by mumoshu** [comment]
@afoninsky Hey! Thanks for the feature request. That makes sense, and implementation would be simple as adding a `yml` glob after the one for `yaml` in https://github.com/roboll/helmfile/blob/fa95e0dd920fa953cb1c7eea245b2dbf6a735c15/pkg/app/app.go#L287-L290.

I'd greatly appreciate it if you could submit a PR!

**Comment by afoninsky** [comment]
Sure, thank you fo pointing it. I've not found tests according to extensions, feel free to tell me if you need some.

**Comment by afoninsky** [comment]
Sure, thanks for pointing to it. I've not noticed tests which verificate extensions, I guess they are not needed? Indicate if I missed them or eed to create them, thx again :)

**Comment by mumoshu** [comment]
@afoninsky We currently don't have one for the file extension. I'd appreciate it if you could add test cases for that ☺️
