### ISSUE TITLE
helmDefaults not interpreted when defined in separate file

### ISSUE THREAD

**Issue by msutter** [roboll/helmfile#568]
I use helmfile.d for my releases and a helm-default.yaml file to define global values.
After upgrading to v 0.54.2, the defaults are no longer interpreted in the releases definitions.

I have to workaround this with a dirty inclusion of the helm default file in my release definitions like this:

```
{{ readFile "000-helm-defaults.yaml" }}
---
releases:
- name: myrelease1
....

```

The helmDefaults in separated file was working with version 0.45.3

**Comment by mumoshu** [comment]
@msutter Hey! Thanks for reporting.

I think you've found an interesting use of `helmfile.d`.
Honestly saying, I have no idea how `helm-default.yaml`'s `helmDefaults` settings have been propagated/replicated to another helmfiles under the same `helmfile.d`, without explicitly referring to it(if that's what you meant).

I'll try to see what was going on, but in a certain case you need to wait until the addition of `bases` which has proposed in https://github.com/roboll/helmfile/issues/388#issuecomment-478007910.

Out of curiosity, would `bases` help your use-case, too?

**Comment by sonjasutter** [comment]
Hi @mumoshu,

Yes sure, bases(includes) would definitively help us to define global vars

**Comment by mumoshu** [comment]
After #587, you can use `bases: ["000-helm-defaults.yaml"]` as well. Also, the original workaround of using `readFile` remains possible.

**Comment by mumoshu** [comment]
`bases` will be enabled since helmfile v0.60.0
