### ISSUE TITLE
Understanding `apply`

### ISSUE THREAD

**Issue by naseemkullah** [roboll/helmfile#570]
Hello, I would like to confirm if this is expected behaviour:

1) I run helmfile apply, my chart has a certian value for a deployment which is `.Values.foo = bar`

2) It is deployed. I now manually edit the value in the deployment (`kubectl edit deployment`) and change the value `bar` to `qaz`

3) I re-run the helmfile apply command, my helmfile still has `.Values.foo = bar`

Expected behaviour: `helmfile apply` compares what is running to what is desired, and changes `qaz` back to `bar` in the deployment.
Actual behaviour:` helmfile apply` does not notice that there has been a manual tweak to that value.

Worth noting: If instead of manually editing the deployment to change `bar` to `qaz`, i edit `.Values.foo` in my helmfile to equal `qaz`, `helmfile apply` would indeed detect this change, of course.

Hope this made sense, if anything is unclear or further details are required please let me know.

**Comment by sgandon** [comment]
I believe this comes from the 'helm diff' plugin behavior that will check between what you want to deploy and what you have deployed and not what is the current state in the cluster.
When you deploy with helm, helm stores all the release manifests and values inside a configmap.
You can find it out by doing `helm get <release_name>`. So my guess is the `helm diff` plugin compares the release you want to deploy with the helm release it gets from this command. So whatever you have changed in the cluster will no be seen here.

**Comment by sgandon** [comment]
so to answer your question, yes this is an expected behaviour.

**Comment by naseemkullah** [comment]
Thank you very much!

**Comment by sgandon** [comment]
Just to add some more tips if you really want to 'apply' or come back to what was deployed initially after you have changed something in the cluster like deleting some deployments.
I suggest you use `helm sync` that will force the install of everything.

**Comment by naseemkullah** [comment]
Thanks @sgandon, that's a good point. I was choosing `apply` over `sync` to not have super high  values for `REVISION` when running `helm ls` (as the `helmfile` command in question runs via a CI system that is triggered quite frequently). But it is kind of a non-issue I guess!
