### ISSUE TITLE
Add "required" function identical to helm's

### ISSUE THREAD

**Issue by Nuru** [roboll/helmfile#572]
Feature Request:

`helm` has a `required` template function documented [here](https://github.com/helm/helm/blob/master/docs/charts_tips_and_tricks.md#know-your-template-functions). This is similar to, but more powerful than, `requiredEnv`. I would like `helmfile` to support the same function.

My use case is that I am writing releases where a value can come from multiple environment variables (as a way of implementing layers of configuration), so I cannot use `requiredEnv`, but I want to mark a value as required and provide a useful error message. For example:
```
dnsZone: {{ required "Either DNS_ZONE or CLUSTER_NAME required" (coalesce (env "DNS_ZONE") (env "CLUSTER_NAME")) }}
```

**Comment by mumoshu** [comment]
This would be a good addition to helmfile!
