### ISSUE TITLE
Feature Request: Add new event hook `presync` for mutating operations

### ISSUE THREAD

**Issue by rajiteh** [roboll/helmfile#579]
Background:

IMO, the event hook system in helmfile is a very useful feature and something that is missing from helm right now. However, as described in #552 , the `prepare` hook will always run regardless of the helmfile operation type that is being performed. This is due to the fact that the design goal of `prepare` hook is to prepare a chart (eg: kustomize, helmify, etc)

However, if you had specified a hook action that mutates the cluster state, you will end up inadvertently affecting the cluster state your shell kubectl is pointed at even when performing read-only operations like `helmfile lint` or `helmfile diff`

Therefore, I propose

- A new event hook `presync` which will be executed during install/upgrade scenarios and will be ignored for read-only invocations like `lint` or `diff`.
- Update to the documentation that describes the distinction between hooks and their intended purposes.

**Comment by rajiteh** [comment]
I have proposed a PR for this issue at #580

**Comment by mumoshu** [comment]
Closing this as #580 has been merged. Thanks for your contribution @rajiteh!
