### ISSUE TITLE
Add a validate command to validate the syntax of helmfiles

### ISSUE THREAD

**Issue by cmeury** [roboll/helmfile#58]
## helmfile validate

Examines helmfiles for possible issues.

### Synopsis
The  command validates the syntax of the default or specified helmfile(s) and runs a series of tests to verify that they are well-formed.

If the linter encounters things that will cause the chart to fail installation, it will emit [ERROR] messages. If it encounters issues that break with convention or recommendation, it will emit [WARNING] messages (linting).

The following could be reported:

- invalid YAML syntax
- wrong format namespace value, chart names, versions, env var declarations, repository URLs, ..
- same release, value fileor repository declared multiple times
- interpolation used in places where it's unsupported
- missing value for a variable (if enabled)

```
helm validate [flags]
```

### Suggested Options

```
      --strict               Fail on lint warnings
      --file valueFiles      Specify helmfile (can specify multiple) (default `helmfile.yaml`)
      --follow-values        check syntax of specified values files
      -e, --env              Set environment variables
      --env-file             Read in a file of environment variables
      --check-variables=true Check whether all required variables have been specified. (default `true`)
```

### Reference

Inspired by [helm lint](https://docs.helm.sh/helm/#helm-lint), [terraform validate](https://www.terraform.io/docs/commands/validate.html) and [docker run](https://docs.docker.com/engine/reference/commandline/run/#set-environment-variables--e---env---env-file).

**Comment by cmeury** [comment]
Seems fine with me!

**Comment by mumoshu** [comment]
@cmeury WDYT about #162? Can we safely close this as resolved via that?

**Comment by cmeury** [comment]
I think so, yes.

**Comment by mumoshu** [comment]
Closing this as resolved via #162

**Comment by abdennour** [comment]
not resolved.

**Comment by mumoshu** [comment]
@abdennour `helmfile lint` succeeds only when your `helmfile.yaml` syntax is correct and all the `helm list` runs against the contained releases succeeds.

Wouldn't it solve your issue? Then, would u mind sharing what's missing? Thanks!

**Comment by matin25553** [comment]
how to check helmfile is install and is working or not using Linux
