### ISSUE TITLE
feat: auto-chartify kustomize apps

### ISSUE THREAD

**Issue by mumoshu** [roboll/helmfile#588]
You as an infrastructure engineer wants to manage the whole environment with a single helmfile.yaml. But one of your apps managed by your app-engineer colleague, and they wants to write his own app with `kustomize`.

You have no clue how you can mix it without shell scripting. Yet you don't want to force your colleague to use helm charts, or even want them to notice the entire env is managed by helm/helmfile, so that there's less things to remember which means easier on-boarding for app engineers.

How helmfile can help?

**Shameless plug:** Adding [helm-x](https://github.com/mumoshu/helm-x) integration to helmfile would allow you to transparently use your kustomizations as helm charts.

That is, put your kustomization.yaml to the directory where a local helm chart should be:

```yaml
releases:
- name: myapp
   chart: kustomizations/myapp
   # version is required because it isn't provided by kustomization by its nature!
   version: 1.2.3
```

`helmfile diff` prints the diff even though the desired state is defined by the kustomization rather than a helm chart!

Even `helmfile test` is possible once you mix `templates/tests`, as you would do for a regular helm chart, to your kustomization.

This is superior to regular kustomizations, as it allows you to use leverage helm's release management, release testing, diffing and so on even for apps not written as a chart.

This is an enhancement even from helmfile's perspective - helmfile already has support for kustomizations via hooks as documented in https://github.com/roboll/helmfile#helmfile--kustomize. The proposed feature doesn't need hooks.

**Comment by mumoshu** [comment]
#673 has added this. cc/ @manics

**Comment by alexppg** [comment]
@mumoshu Hi! Why is this not documented? It seems nicer than using a bash script.
