### ISSUE TITLE
feature request: optional ability to exit zero when no releases match the selector

### ISSUE THREAD

**Issue by rajiteh** [roboll/helmfile#597]
Right now helmfile will exit with code 2 when the selectors don't match helmfiles. 

I would like the ability to have a special argument that will disable this behaviour as sometimes not having any releases that match a specific selector is not necessarily an error condition.

My use case:
- I have multiple dirs that have independent helmfiles.
- In each helmfile, I define labels for each release to indicate the deployment order (`stage: pre`, `stage: my-app`, `stage: post`)
- I have a CI script that will go to each dir, and execute `helmfile` commands with the  selectors in order (first run `-l stage=pre`, second run `-l stage=my-app`, third `-l stage=post`)
- However, not all of my helmfiles require staged deployments with `pre` or `post` selectors, so these helmfiles will return the "not matching" error due to the CI script runs.
- I am resorting to ignore exit code 2 to get around this issue. However, certain legitimate errors like go SIGSEGV panics also exit with code 2, and I fail to capture those.

If this sounds like a good idea, I can propose a MR for it.

**Comment by mumoshu** [comment]
@rajiteh Hey! Thanks for the detailed explanation of your use-case and the issue.

I was thinking about changing the exit code to be returned in this case to `3`, as `2` also collide with the status returned by `helmfile diff --detailed-exitcode`.

Does it sound good to you? Or do you think we still need a flag like `--allow-no-matching-release` that instructs helmfile to return `0` when no matching releases found?

**Comment by mumoshu** [comment]
Btw it should be a matter of changing the number in this line if that's just changing `2` to `3` in the specific case https://github.com/roboll/helmfile/blob/4f83e69bf68fdc0e94b5c3c410cdcc4cf2aa84a4/cmd/cmd.go#L86

**Comment by rajiteh** [comment]
Thanks for your insights again @mumoshu!

Yes, I think exiting with `3` would solve my immediate issue as we would remove the ambiguity with go panics and `diff` commands) -- however, I would love an option to simply ignore it as an error altogether. I could think that we can add the `cli.Context` as an argument to `toCliError` and determine the exit code to be either `0` or `3` by inspecting if a specific flag is present?

Let me know your thoughts on my suggestion. Thanks!
