### ISSUE TITLE
Feature request: support glob notation in environments.values.

### ISSUE THREAD

**Issue by skaji** [roboll/helmfile#606]
I would like helmfile to support glob notation in environments.values.

## Example

Let's say we have the following directories and files:

```
❯ cat helmfile.yaml
environments:
  dev:
    values:
      - env/dev/*.yaml

releases:
  - name: redis
    chart: stable/redis

❯ tree .
.
├── env
│   └── dev
│       ├── main.yaml
│       ├── sub1.yaml
│       └── sub2.yaml
└── helmfile.yaml
```

Currently when we execute `helmfile -e dev template`, then we get
```
❯ helmfile -e dev template
could not deduce `environment:` block, configuring only .Environment.Name. error: failed to read helmfile.yaml.part.0: failed to load environment values file "env/dev/*.yaml": failed to load [env/dev/*.yaml]: open env/dev/*.yaml: no such file or directory
in ./helmfile.yaml: failed to read helmfile.yaml: failed to load environment values file "env/dev/*.yaml": failed to load [env/dev/*.yaml]: open env/dev/*.yaml: no such file or directory
```

I would like helmfile to support glob notation in environments.values.
Thanks.

**Comment by mumoshu** [comment]
@skaji Hey! Thanks, this seems like a great addition to helmfile.

One thing I would consider is how to make it deterministic.
Can we just sort all the yaml files matching `env/dev/*.yaml` alphabetically(like we do for sub-helmfiles and `./helmfile.d`), and merge latter files to former ones?

**Comment by skaji** [comment]
> Can we just sort all the yaml files matching env/dev/*.yaml alphabetically(like we do for sub-helmfiles and ./helmfile.d), and merge latter files to former ones?

For my use case, it's totally fine.

**Comment by skaji** [comment]
@mumoshu Thank you!!
