### ISSUE TITLE
Version range constraints

### ISSUE THREAD

**Issue by sstarcher** [roboll/helmfile#61]
Thoughts on allowing version constraints to be specified.

* Currently we support version and when not specified it will install the latest version
* Support for semver range constraints to allow users to say `~2.2.0` to get the latest version of the 2.2.x

**Comment by cmeury** [comment]
@sstarcher Are you sure this does not work? Looking at the [code](https://github.com/roboll/helmfile/blob/master/state/state.go#L348), we just append the version to the Helm command-line. And Helm seems to use [semantic versions](https://github.com/kubernetes/helm/blob/master/docs/chart_best_practices/conventions.md#version-numbers). I just tested it with `version: ~1.24.1` and it seems to work.
Could you give this a test?

**Comment by sstarcher** [comment]
@cmeury I should of probably of thought more about it :)  You are correct
