### ISSUE TITLE
Regression: complain on missing values files for undesired releases

### ISSUE THREAD

**Issue by naseemkullah** [roboll/helmfile#616]
There seems to be a regression from fix https://github.com/roboll/helmfile/pull/526

perhaps re introduced https://github.com/roboll/helmfile/pull/555/files

not sure.

But helmfile sync complains if a values files does not exist for an "undesired" release.

in other words https://github.com/roboll/helmfile/issues/519 is occurring again.

**Comment by naseemkullah** [comment]
I confirm that helmfile 0.54.0 behaves correctly in terms of not producing unwanted error msg. but 0.64.1 does not behave as wanted.

**Comment by naseemkullah** [comment]
I can confirm that the unwanted behaviour was re introduced somewhere between `0.54.0` and  `0.55.0`

**Comment by mumoshu** [comment]
@naseemkullah Thanks to your detailed report, I was able to quickly isolate the cause, add test cases to prevent further regressions, and implemented the fix in #617 ☺️

**Comment by naseemkullah** [comment]
Thanks @mumoshu!
