### ISSUE TITLE
Misleading help text for charts command

### ISSUE THREAD

**Issue by cmeury** [roboll/helmfile#62]
The help text for the charts command [currently is](https://github.com/roboll/helmfile/blob/master/main.go#L78):

> helm repo upgrade --install

Shouldn't it be:

> helm upgrade --install

**Comment by mumoshu** [comment]
@cmeury Thx for the good catch! Would you mind submitting a PR for that?

**Comment by cmeury** [comment]
Yeah, I might do some work, also for other suggestions (not yet filed).
