### ISSUE TITLE
0.68.1:  executing "stringTemplate" at <.Environment.Values.parent>: wrong type for value; expected string; got map[string]interface {}

### ISSUE THREAD

**Issue by bitsofinfo** [roboll/helmfile#628]
The #624 issue still exists with the scenario described on the original ticket with 0.68.1

```
helmfile version v0.68.1

err: error during deployments.yaml.part.2 parsing: template: stringTemplate:4:29: executing "stringTemplate" at <.Environment.Values.parent>: wrong type for value; expected string; got map[string]interface {}
in ./deployments.yaml: error during deployments.yaml.part.2 parsing: template: stringTemplate:4:29: executing "stringTemplate" at <.Environment.Values.parent>: wrong type for value; expected string; got map[string]interface {}
```

**Comment by mumoshu** [comment]
Thanks for reporting! Seems like my fix wasn't complete and it isn't working for some nest level. I'll take a look asap.

**Comment by mumoshu** [comment]
@bitsofinfo This should be due to a misusage of `getOrNil`.

You have `{{ if getOrNil .Environment.Values.parent "child1" }}`. However, the first arg for getOrNil should be a path, in this case it's "child".

Would you mind trying `{{ if getOrNil "child1" .Environment.Values.parent }}` intead?

**Comment by bitsofinfo** [comment]
my bad

**Comment by mumoshu** [comment]
I'm glad if it worked! Thanks for confirming 👍
