### ISSUE TITLE
0.68.1: is Sprig 'values' dict function supported?  function "values" not defined

### ISSUE THREAD

**Issue by bitsofinfo** [roboll/helmfile#630]
Will provide more details in a bit:

Getting 
```
err: error during deployments.helmfile.yaml.part.2 parsing: template: stringTemplate:8: function "values" not defined
in ./deployments.helmfile.yaml: error during deployments.helmfile.yaml.part.2 parsing: template: stringTemplate:8: function "values" not defined
```

Is the sprig `values` function available? http://masterminds.github.io/sprig/dicts.html

**Comment by mumoshu** [comment]
@bitsofinfo Good catch!

Seems like helmfile is currently using a version of sprig (2.15.0) that is one-minor-ver-earlier than the version added `values` (2.16.0+, https://github.com/Masterminds/sprig/commit/df393122472a0abccc1046e2cf05173b14a00535).

Bump `sprig` in `go.mod` and `values` should be available.
