### ISSUE TITLE
It is not clear for which release an upgrade failed

### ISSUE THREAD

**Issue by cmeury** [roboll/helmfile#66]
In the case of an error, the error message is printed without any indication of the affected release. For example, in the middle of two successful releases, I found the following error for third one. But I had to manually go through the helmfile to find out which one it might have been.

```
Error: UPGRADE FAILED: failed to create patch: failed to get versionedObject: unable to convert unstructured object to apps/v1beta1, Kind=StatefulSet: cannot restore struct from: string
```

**Comment by mumoshu** [comment]
@cmeury Good point! I believe we should prepend the affected release name before error-exiting helmfile.

**Comment by mumoshu** [comment]
@cmeury #223 adds an error message like `err: release "grafana" in "helmfile.yaml" failed: exit status 1` at last. In combination with the error message that you've shared, which seems to have been emitted by helm, it will help you to locate where the issue was.
