### ISSUE TITLE
Wrong versions in the summary output

### ISSUE THREAD

**Issue by andrewnazarov** [roboll/helmfile#665]
I've noticed strange values of the version fields in the summary output when versions are parametrized:

```
RELEASE              CHART                      VERSION
printing-alpha       chartmuseum/printing         alpha
...
# a bunch of other releases with the same output
...

List of updated releases :
```

In helmfile the version of the chart looks the following: `version: {{ .Environment.Values.printing.chartVersion }}`. When the version is a plain string (like 0.1.0) the output looks ok.

This is the underlying helm command installing the release (note that version 0.5.0 is passed):
```
exec: helm tiller run my-tiller -- helm upgrade --install --reset-values printing-alpha chartmuseum/printing --version 0.5.0 --timeout 300 --force --namespace shared-alpha --values /tmp/values158934177 --kube-context=gke_XXXX_europe-west1-b_XXXX-cluster-global
```

My version of helmfile: v.0.69.0

**Comment by sgandon** [comment]
Can you do a `helm list -a` command and let us know what is the output please ?

**Comment by andrewnazarov** [comment]
```
NAME                 	REVISION	UPDATED                 	STATUS  	CHART                     	APP VERSION                 	NAMESPACE
printing-alpha       	1       	Sun Jun  9 01:48:47 2019	DEPLOYED	printing-0.5.0            	1.0                         	shared-alpha       
```

**Comment by sgandon** [comment]
I believe this is a bug from this regexp : https://github.com/roboll/helmfile/blob/34c793d87e75ecf479c74239c99614c8b2dac475/pkg/state/state.go#L437
