### ISSUE TITLE
feat: Experimental Helm v3 mode

### ISSUE THREAD

**Issue by mumoshu** [roboll/helmfile#668]
Extracted from https://github.com/roboll/helmfile/issues/122#issuecomment-499310848

I believe we need it to start real-world testing with helm 3.

**Comment by jdolitsky** [comment]
Would love to see. @mumoshu how involved is this to implement?

**Comment by olivierboudet** [comment]
I guess you already know but beta.2 is available :)

**Comment by costimuraru** [comment]
beta.3 available

**Comment by mumoshu** [comment]
#841 is the first implementation for this!

Assuming you have helm v3 binary `~/bin/helm3b3`, try it like:

```
HELMFILE_HELM3=1 helmfile --log-level=debug --helm-binary ~/bin/helm3b3 sync
```

// You don't need `--helm-binary ~/bin/helm3b3` if you've fully migrated to helm v3 i.e. just running `helm` runs helm 3.

**Comment by mumoshu** [comment]
#841 has been released as v0.83.0

**Comment by mumoshu** [comment]
helm-3.0.0-beta.3 has a regression that makes `helm diff upgrade --detailed-exitcode` unable to work correctly https://github.com/helm/helm/issues/6384

**Comment by mumoshu** [comment]
The minimal change on `helm-diff` is at https://github.com/databus23/helm-diff/pull/149. Clone it and run `HELM_HOME=$HOME/Library/helm make install` in the project root for testing with helm3 and #841.

**Comment by mumoshu** [comment]
Probably we may need to set api version in the temporary `Chart.yaml` generated in `helmfile deps` to `v1` once helm v3 becomes generally available: https://github.com/helm/helm/issues/5907

**Comment by mumoshu** [comment]
`helmfile deps` should work w/ helm 3 after #842

**Comment by costimuraru** [comment]
I appreciate the great work you're doing, @mumoshu! Will definitely give this a try, given that we're currently using helmfile in tillerless mode, but we experience occasional freezes (timeouts when doing a sync)... probably has something to do with the helm-tiller plugin. We hope helmv3 will prove to be more robust over the time. 

By the way, I wrote an article with our experience in using helmfile (we're using it at Adobe for a few projects) and the feedback has been great (both internally and externally). Hope it leads to an increased adoption of helmfile so keep up the good work. The article is on medium of you're curious - https://itnext.io/setup-your-kubernetes-cluster-with-helmfile-809828bc0a9f

**Comment by cdunford** [comment]
What is the current status of helm 3 support?

**Comment by mumoshu** [comment]
@cdunford It's fully supported by default. Just provide a `helm` binary of v3 and it should just work. Please note though that some charts are broken in terms of helm v3 compatibility as revealed in #1000

**Comment by viroos** [comment]
> @cdunford It's fully supported by default. Just provide a `helm` binary of v3 and it should just work. Please note though that some charts are broken in terms of helm v3 compatibility as revealed in #1000

how about things like tiller namespace in helmfile? could you provide a working example of helmfile for helm 3, please?

**Comment by smeierhofer** [comment]
Lots of example Helm Charts in the official Helm Chart repo at (https://github.com/helm/charts/tree/master/stable).

**Comment by viroos** [comment]
from readme:
`#default values to set for args along with dedicated keys that can be set by contributers, cli args take precedence over these
helmDefaults:
  tillerNamespace: tiller-namespace  #dedicated default key for tiller-namespace
  tillerless: false                  #dedicated default key for tillerless`

is it also valid for helm3?

**Comment by smeierhofer** [comment]
Tiller doesn't exist in Helm 3 so probably don't use any of these if you are using Helm 3.

**Comment by mumoshu** [comment]
Thanks! Yes, that's correct. tiller-namespace is ignored for Helmfile + Helm 3.
