### ISSUE TITLE
helmfile destroy fails, needs concurrency flag

### ISSUE THREAD

**Issue by Morriz** [roboll/helmfile#690]
A global `helmfile destroy` gives errors for some charts. If I destroy them one after the other with `helmfile -l name=$release destroy` I see no errors.

I suspect something is conflicting because of the attempted concurrency, and therefor I would like the destroy command to also honour `--concurrency=1`.

**Comment by mumoshu** [comment]
@Morriz Hey! Mind sharing the error message you saw?

**Comment by Morriz** [comment]
Yeah, this is what I get (not revealing anything):
```
err: release "ingress" failed: helm exited with status 143:
  /Users/Morriz/.helm/plugins/helm-tiller/scripts/tiller.sh: line 114: 88849 Terminated: 15          [[ "${HELM_TILLER_SILENT}" == "false" ]]
  Error: plugin "tiller" exited with error
err: release "external-dns" failed: helm exited with status 143:
  Error: transport is closing
  /Users/Morriz/.helm/plugins/helm-tiller/scripts/tiller.sh: line 128: 88799 Terminated: 15          ./bin/tiller --storage=secret --listen=127.0.0.1:${HELM_TILLER_PORT}  (wd: ~/.helm/plugins/helm-tiller)
  /Users/Morriz/.helm/plugins/helm-tiller/scripts/tiller.sh: line 114: 88851 Terminated: 15          [[ "${HELM_TILLER_SILENT}" == "false" ]]
  Error: plugin "tiller" exited with error
err: release "ingress-merge" failed: helm exited with status 1:
  Error: transport is closing
  Error: plugin "tiller" exited with error
changing working directory back to "/Users/Morriz/Documents/Workspace/essent/k8s-stacks"
in helmfile.d/helmfile-ingress.yaml: 3 errors:
err 0: release "ingress" failed: helm exited with status 143:
  /Users/Morriz/.helm/plugins/helm-tiller/scripts/tiller.sh: line 114: 88849 Terminated: 15          [[ "${HELM_TILLER_SILENT}" == "false" ]]
  Error: plugin "tiller" exited with error
err 1: release "external-dns" failed: helm exited with status 143:
  Error: transport is closing
  /Users/Morriz/.helm/plugins/helm-tiller/scripts/tiller.sh: line 128: 88799 Terminated: 15          ./bin/tiller --storage=secret --listen=127.0.0.1:${HELM_TILLER_PORT}  (wd: ~/.helm/plugins/helm-tiller)
  /Users/Morriz/.helm/plugins/helm-tiller/scripts/tiller.sh: line 114: 88851 Terminated: 15          [[ "${HELM_TILLER_SILENT}" == "false" ]]
  Error: plugin "tiller" exited with error
err 2: release "ingress-merge" failed: helm exited with status 1:
  Error: transport is closing
  Error: plugin "tiller" exited with error
```

**Comment by Morriz** [comment]
I don't see what is going wrong in the tiller-plugin on that line 114 or 128

**Comment by Morriz** [comment]
Yeah, it seems the plugin tries to stop the local tiller but others processes are using it of course.

**Comment by Morriz** [comment]
so please add `--concurrency` flag ;)

**Comment by mumoshu** [comment]
@Morriz Ah, that seems like the current restriction of the helm-tiller integration #449 

Tiller needs two or three ports to bind, grpc, metrics, and optionally trace ports. The error seems to be due to that grpc and metrics ports are conflicting across tiller instances. So yes, the shortterm solution would be to add `--concurrency` :) Ok

**Comment by Morriz** [comment]
tnx....it would be nicer if the plugin would allow for concurrency...I will create a request for that

**Comment by mumoshu** [comment]
@Morriz Please try #691!

**Comment by Morriz** [comment]
I would love to, but where can I find the master binary?

**Comment by mumoshu** [comment]
Just grab the latest binary from github releases.

**Comment by Morriz** [comment]
0.77 works great now...mega tnx for the quick update!

**Comment by mumoshu** [comment]
Glad to help! Thanks for your confirmation
