### ISSUE TITLE
0.76.2: "set":  wrong type for value; expected map[string]interface {}; got state.EnvironmentTemplateData

### ISSUE THREAD

**Issue by bitsofinfo** [roboll/helmfile#707]
```
  {{- $cluster := "something" }}
  {{ $_ := set . "cluster" $cluster }}
  {{ .cluster }}
```

```
parsing: template: stringTemplate:10:15: executing "stringTemplate" at <.>: wrong
type for value; expected map[string]interface {}; got state.EnvironmentTemplateData
```

This kind of thing works in Helm natively, would be cool if could do it in helmfile

**Comment by mumoshu** [comment]
Yeah... but are you trying to mutate the template data?! I don't think it's a good idea.

**Comment by bitsofinfo** [comment]
yes I do things like generate "names" for things based on constructing from other top level values, and I need these generated variables available when I pass to `{{ tpl .Values.valueWithRefernceInIt . }}`

**Comment by bitsofinfo** [comment]
where 

```
values:
  someothervalue: "dog"
  valueWithRferenceInIt: ".Values.someothervalue}}"
```

**Comment by mumoshu** [comment]
Can't you use `dict` and `merge` functions to generate `$cluster` without mutating the template data, which seems safer to me?

**Comment by bitsofinfo** [comment]
see my last comment, don't follow

**Comment by mumoshu** [comment]
I'm not yet sure what you wanted to say, but perhaps `$cluster := set (merge (dist) .) "generated" $generated` doesn't work as well, so we need to make the template data `map[string]interface{}` regardless of you use mutation or not?

**Comment by bitsofinfo** [comment]
a bit lost, what is `(dist)`?

**Comment by mumoshu** [comment]
Sorry I meant `dict`!

**Comment by bitsofinfo** [comment]
closed via other solutions, in any case what I was trying to do now works.

**Comment by bendevcat** [comment]
> closed via other solutions, in any case what I was trying to do now works.

Can you please share your solution ? :)

**Comment by dudicoco** [comment]
@bitsofinfo how did you solve this issue?

**Comment by bitsofinfo** [comment]
@bendevcat @dudicoco sorry, honestly I can't even recall the specific thing I was working on at the time. I can tell you however that the solution is likely in one of these two files as this was the project i was working on when this ticket was created. I do all sorts of things w/ dynamic vars etc related to what this issue is talking about. Perhaps its was just fixed as a by product of one of the many fixes hemfile patched last summer

https://github.com/bitsofinfo/helmfile-deploy/blob/master/deployments.helmfile.yaml

https://github.com/bitsofinfo/helmfile-deploy/blob/master/conduits.helmfile.yaml

**Comment by dudicoco** [comment]
@bitsofinfo how did you solve this issue?

**Comment by bitsofinfo** [comment]
@dudicoco read my previous comment

**Comment by dudicoco** [comment]
Thanks @bitsofinfo, sorry for the double comment, accident.
