### ISSUE TITLE
Installation gives error "bus.go:98:30: undefined: strings.ReplaceAll"

### ISSUE THREAD

**Issue by max-rocket-internet** [roboll/helmfile#710]
Example:

```
$ go get -u github.com/roboll/helmfile
# github.com/roboll/helmfile/pkg/event
../../../go/src/github.com/roboll/helmfile/pkg/event/bus.go:98:30: undefined: strings.ReplaceAll
```

**Comment by max-rocket-internet** [comment]
Updating golang to version `1.12.6` fixed it for me but perhaps the version should be checked when installing?

**Comment by mumoshu** [comment]
Unfortunately `go get` has no such ability!

Never try to use `go get` just for installing helmfile. It's almost for go devs and that's why our README doesn't list `go get` as one of installation methods: https://github.com/roboll/helmfile#installation

**Comment by max-rocket-internet** [comment]
OK but in the readme it states:

> CAUTION: This documentation is for the development version of Helmfile. If you are looking for the documentation for any of releases, please switch to the corresponding release tag like v0.31.0.

Then that link goes to tag `v0.31.0` which then lists the install method as `go get ...` 😅

**Comment by max-rocket-internet** [comment]
Shall I make a PR to update link in README to point to a later release?

**Comment by mumoshu** [comment]
I'd appreciate it if you could do so!
