### ISSUE TITLE
Version does not display

### ISSUE THREAD

**Issue by max-rocket-internet** [roboll/helmfile#711]
```
$ helmfile -v
helmfile version
$ helmfile --version
helmfile version
```

I've seen https://github.com/roboll/helmfile/issues/304 but it was closed with comment:

> Closing this as resolved by #437. It isn't actually resolved

🤔

**Comment by mumoshu** [comment]
Hmm? How did you install the helmfile command?

**Comment by mumoshu** [comment]
Please use one of recommended installation methods as per https://github.com/roboll/helmfile/issues/710#issuecomment-503937988

`go get` isn't a package manager!

**Comment by max-rocket-internet** [comment]
OK but in the readme it states:

> CAUTION: This documentation is for the development version of Helmfile. If you are looking for the documentation for any of releases, please switch to the corresponding release tag like v0.31.0.

Then that link goes to tag `v0.31.0` which then lists the install method as `go get ...` 😅
