### ISSUE TITLE
Absolute paths for -f not working on Windows

### ISSUE THREAD

**Issue by bastianeicher** [roboll/helmfile#718]
This worked up until 0.73.3 and stopped working in 0.74.0

**Comment by bastianeicher** [comment]
This works:

    helmfile -f somedir\helmfile.yaml sync

This fails:

    helmfile -f C:\somedir\helmfile.yaml sync

The error message is:

    locate: invalid src format: it must be `[<getter>::]<scheme>://<host>/<path/to/dir>@<path/to/file>?key1=val1&key2=val2: got D:\_Sources\Axoom\MyAxoom\PortalService\charts\portalservice\helmfile.repos.yaml

**Comment by bastianeicher** [comment]
I suppose this issue was introduced by #670.

**Comment by mumoshu** [comment]
Thanks for reporting! I'll take a look asap

**Comment by mumoshu** [comment]
@bastianeicher I have no windows machine for testing, but #721 should fix this. Would you mind testing it out?

**Comment by bastianeicher** [comment]
@mumoshu I just gave v0.79.3 a try and it works.

Thank you for the super fast fix! :)

**Comment by mumoshu** [comment]
@bastianeicher Glad to help! Thanks for your lightning first report 😄
