### ISSUE TITLE
Allow files to be optionally included

### ISSUE THREAD

**Issue by MPLew-is** [roboll/helmfile#730]
Currently, if you try to include an external file in any of `values`, `set`, `environments`, or `bases` and that file does not exist, helmfile stops processing, with no way that I've found to continue. I'd like to be able to use a file to optionally override some defaults if present, which requires the ability to somehow mark a file as optional and its values to be read in if it is present, but otherwise to ignore it.

Currently, I've built a workaround in the form of using `exec` in a `.gotmpl` file to run a shell script that checks for the existence of a file and `cat`s it if it is present, but it would be nice to have better support for this particular use case.

This could probably be accomplished with glob matching as requested #414, but it may also be a separate fix, so I'm filing this issue separately.

**Comment by jradtilbrook** [comment]
I would also like this functionality

**Comment by MPLew-is** [comment]
Looks like this already possible in `environments`, and this issue is a duplicate of #548.
