### ISSUE TITLE
Cannot use absolute chart path

### ISSUE THREAD

**Issue by BenBlaisdell** [roboll/helmfile#743]
When I use an absolute chart path (starting with `/`) helmfile drops the starting slash and treats it as a relative path

```
Building dependency Users/my-user/charts/my-chart
in /Users/my-user/my-helmfiles/helmfile.yaml: in .helmfiles[1]: in releases/env/helmfile.yaml: helm exited with status 1:
  Error: could not find Users/my-user/charts/my-chart: stat Users/my-user/charts/my-chart: no such file or directory
```

**Comment by bitsofinfo** [comment]
agree would be great if we could reference non-relative resources

**Comment by BenBlaisdell** [comment]
I probably should have mentioned that this is a regression in my initial post. My org **did** use absolute paths (referencing charts in a local directory passed by environment variable). I noticed that this no longer works after upgrading to a newer helmfile version (although I'm not sure which version caused the regression).

**Comment by mumoshu** [comment]
Thanks for reporting! I'll take a look and add a regression test for it as well.

**Comment by osterman** [comment]
@mumoshu I think we're having this problem as well. @maximmi will confirm.

**Comment by mumoshu** [comment]
#753 should fix this and it's included since v0.80.1. Would you mind trying, and report back if the problem still persist?

**Comment by BenBlaisdell** [comment]
Problem's fixed; thanks for the quick response!

**Comment by mumoshu** [comment]
Wow! Thanks a lot for your quick confirmation 😄
