### ISSUE TITLE
Helm diff output is misleading

### ISSUE THREAD

**Issue by madAndroid** [roboll/helmfile#749]
Hi,

This is related to #540 - when we run `helmfile diff`, the output is misleading:

```
identified at least one change, exiting with non-zero exit code (detailed-exitcode parameter enabled)
in helmfiles/dev.yaml: failed processing release prometheus: helm exited with status 2:
  Error: identified at least one change, exiting with non-zero exit code (detailed-exitcode parameter enabled)
  Error: plugin "diff" exited with error
```

This is confusing, as the `Error` output leads the user to believe the run has failed, whereas it's only picked up a change - the exit code is correct, but the output isn't, IMO

In particular "failed processing" is alarming, as the run hasn't actually failed ... we've managed to handle this using a wrapper script, which checks the exit code, and handles that more gracefully, but we cannot effectively suppress the output here to be more consistent with the change that's being picked up.

Thanks :)

**Comment by mumoshu** [comment]
@madAndroid Thanks a lot for the feedback!

What if it was just:

```
identified at least one change, exiting with non-zero exit code (detailed-exitcode parameter enabled)
in helmfiles/dev.yaml: detected changes for release prometheus
```

Would it make things less confusing?

**Comment by madAndroid** [comment]
@mumoshu - yes, absolutely! that would be significantly better :)

**Comment by mumoshu** [comment]
I'm finally shipping this: #1174
