### ISSUE TITLE
Allow use of requiredEnv in .Environment.Values path

### ISSUE THREAD

**Issue by gorzek** [roboll/helmfile#755]
It's quite possible this can already be done, but after beating on it for a while we have been unable to figure it out.

We're using environment secrets, exposed under `.Environment.Values`, however the path we need is dynamic at runtime. For instance, we might need to find:

`.Environment.Values.foo.bar.MYVALUE`

...where `foo` and `bar` are sourced from environment variables. So, something like this:

`{{ .Environment.Values.{{ requiredEnv "VAR1" }}.{{ requiredEnv "VAR2" }}.MYVALUE }}`

We've tried many permutations and approaches for this and nothing will render. We suspect the problem is that the requiredEnv calls need to be parsed first, in order to produce a valid .Environment.Values path (down to MYVALUE). Just having a lot of trouble determining how to do this, and have looked through usages of `get` and other functions to find a solution.

We'd appreciate any assistance we can get with this, including having this fixed as a bug or added as a feature if the functionality we're looking for doesn't exist yet.

**Comment by mumoshu** [comment]
@gorzek Hey! Try this:

```
{{ index .Environment.Values (requiredEnv "VAR1") (requiredEnv "VAR2") "MYVALUE" }}
```

**Comment by gorzek** [comment]
Thanks so much! I'll try that and get back to you. Haven't used the "index" feature before.

**Comment by gorzek** [comment]
Works great! Much appreciated.
