### ISSUE TITLE
exec not using native binary

### ISSUE THREAD

**Issue by Morriz** [roboll/helmfile#772]
on osx I get `exec format error`...can I do something to make helmfile use local exec?

**Comment by mumoshu** [comment]
@Morriz What do you mean by "local exec"?

**Comment by Morriz** [comment]
it seems the included `exec` is a binary built for another platform...that is what the error means imo

**Comment by mumoshu** [comment]
@Morriz What platform(CPU arch and os) are you on, and which hemlfile binary did you get?

Helmfile has binaries for both amd64 and 386. I think using the one that matches your CPU arch resolves the issue.

**Comment by Morriz** [comment]
I am very sorry, but I think I used it wrongly before, as I now can use it well. Thanks again for your assistance :)
