### ISSUE TITLE
bug: 0.80.0 --state-values-set not setting more than first child in nested paths

### ISSUE THREAD

**Issue by bitsofinfo** [roboll/helmfile#773]
See: https://github.com/bitsofinfo/helmfile-statevalue-key1

Doing this:
```
./helmfile --log-level debug \
  --state-values-set top.middle.x='x1' \
  --state-values-set top.middle.y='y1' \
  --file helmfile.works.yaml template
```

then `.Values.top.middle.y` has no value... only `.Values.top.middle.x`. Both should be populated

https://github.com/bitsofinfo/helmfile-statevalue-key1

**Comment by mumoshu** [comment]
@bitsofinfo We had an interesting bug that caused it. #774 should be the fix.

Thanks as always for your support 😄

**Comment by bitsofinfo** [comment]
thanks man!
