### ISSUE TITLE
deps fails on missing globbed files

### ISSUE THREAD

**Issue by sstarcher** [roboll/helmfile#778]
We have a root helmfile similar to 
```
helmfiles:
- helm/account/helmfile.yaml
- helm/account/{{ .Environment.Name }}/services/*/helmfile.yaml
- helm/account/{{ .Environment.Name }}/teams/*/helmfile.yaml
```

In some environments some of the above may not exist.  This works fine with helmfile sync, diff, apply etc, but fails for helmfile deps.

```
Running helmfile from helm/account/prod
in ./helmfile.yaml: no file matching helm/account/prod/teams/*/helmfile.yaml found
```

**Comment by mumoshu** [comment]
Seems like a bug. I'll take a look asap. Thanks for reporting!

**Comment by mumoshu** [comment]
@sstarcher Sry I misunderstood this issue. Shouldn't we add `missingFileHandler` like `environments`, `values` and `secrets` but for `helmfiles` this time so that it aligns well with the existing behavior of Helmfile?
