### ISSUE TITLE
not clear if destroy orders files lexically reversed

### ISSUE THREAD

**Issue by Morriz** [roboll/helmfile#797]
I am not sure it works that way, and I could write a test for it of course, but wouldn't it be nice to see it in the documentation.

**Comment by mumoshu** [comment]
@Morriz Hey! I agree that it should be documented.

FYI, in any command other than `delete` and `destroy`, Helmfile processes sub-helmfiles and releases in each helmfile.yaml in the order of definitions, not lexical order. Files under a `helmfile.d/` is processed in lexical order though.

For `delete` and `destroy`, the order is reversed.

**Comment by Morriz** [comment]
Sounds good, so I can safely rely on resources being removed in the opposite order they were created...awesome

**Comment by chaliy** [comment]
Is reverse order for processing helmfiles for destroy is still a case?

Have folder structure:
helmfile.d:
001-a.yaml
002-b.yaml

helmfile apply, process 001-a.yaml and then 002-b.yaml
helmfile destroy, deletes releases from 001-a.yaml first and then from 002-b.yaml

helmfile  v0.100.1

**Comment by mumoshu** [comment]
@chaliy Thanks for reporting! Just that the reverse ordering wasn't working within a directory.
In other words, `releases` and `helmfiles` are reversed as intended, but files loaded from a directory specified under `helmfiles:` wasn't reversed. #1119 fixes it.

**Comment by mumoshu** [comment]
Fixed via #1119
