### ISSUE TITLE
Helmfile installs non-existent release version

### ISSUE THREAD

**Issue by Nuru** [roboll/helmfile#815]
### Bug in helmfile version v0.81.0

At the time of this writing, the latest release of `cloudposse/helmfiles` is 0.58.0. There is no 0.59.0 release. However, this happened:
```
$ helmfiles ⨠ helmfile -f 'git::https://github.com/cloudposse/helmfiles.git@releases/prometheus-pushgateway.yaml?ref=0.59.0' apply 
locate: get: error downloading 'https://github.com/cloudposse/helmfiles.git?ref=0.59.0': /usr/bin/git exited with 1: error: pathspec '0.59.0' did not match any file(s) known to git
$ helmfiles ⨠ helmfile -f 'git::https://github.com/cloudposse/helmfiles.git@releases/prometheus-pushgateway.yaml?ref=0.59.0' apply 
Adding repo stable https://kubernetes-charts.storage.googleapis.com
"stable" has been added to your repositories
...
```

In other words, the first time I tried to install the non-existent release, it failed, as it should. However, `helmfile` apparently created a `.helmfile/cache/https_github_com_cloudposse_helmfiles_git.ref=0.59.0` directory and populated it with the latest release or current master branch (they are currently the same commit) of the repo. Then the second time I ran the command, `helmfile` found the cache and went ahead an installed it.  

This lead to the wrong version of helmfiles being installed without warning. 

Please fix this. If the tag does not exist, then the cache directory should not be created and populated, or at least it should be deleted when the error is detected.

**Comment by mumoshu** [comment]
@Nuru Good catch! It does sound like a bug.

If you could have some time to work on this, would you try adding some code to remove the directory at `cacheDirPath`(while recursively removing the files in int) before returning an error here?

https://github.com/roboll/helmfile/blob/a584aeab2e2ae31e0d68e93d50867d1597c38b50/pkg/remote/remote.go#L220

Perhaps that's the only thing needed to fix it.

**Comment by mumoshu** [comment]
something like this should work:

```
rmerr := os.RemoveAll(cacheDirPath)
if rmerr != nil {
  // some log to tell the user that helmfile was unable to remove the dir for whatever reason
}
return "", err
```

**Comment by Nuru** [comment]
Sorry, @mumoshu, I don't have a golang build environment to build and test with.

**Comment by mumoshu** [comment]
@Nuru Got it 👍I just reproduced this myself. Will fix it asap.
