### ISSUE TITLE
helmfile 0.82.0 brew upgrade issue

### ISSUE THREAD

**Issue by chenrui333** [roboll/helmfile#834]
relates to https://github.com/Homebrew/homebrew-core/pull/43728
https://jenkins.brew.sh/job/Homebrew%20Core%20Pull%20Requests/47572/version=mojave/console

error
```
	fatal: unable to access 'https://git.apache.org/thrift.git/': Failed to connect to git.apache.org port 443: Operation timed out
go: error loading module requirements
```

**Comment by mumoshu** [comment]
Hey! Thanks for reporting.

`thrift` moved to github for hosting the go pkg. Maybe the old host finally stopped working?

Would you mind adding `replace git.apache.org/thrift.git => github.com/apache/thrift v0.12.0` to `go.mod` of `helmfile` and see if it builds correctly?

**Comment by mumoshu** [comment]
Also see for some background:

https://github.com/mozilla/sops/issues/443#issuecomment-474209549
https://stackoverflow.com/questions/49678711/go-get-thrift-package-failed-with-repo-not-found

**Comment by chenrui333** [comment]
> Would you mind adding `replace git.apache.org/thrift.git => github.com/apache/thrift v0.12.0` to `go.mod` of `helmfile` and see if it builds correctly?

that is totally what I am going to do.

**Comment by chenrui333** [comment]
As homebrew works now, I filed a PR to fix the apache-thrift git location change.
