### ISSUE TITLE
HELMv3 support

### ISSUE THREAD

**Issue by ivanilves** [roboll/helmfile#838]
First, thanks for this awesome software!

Second: 
Do you have any plans to support Helm version 3 (currently **beta**) ?

It has slightly different command line syntax for a few operations and, also, does not use configMaps for store release information, which makes it not usable with `helmfile` 😄 as far as I can see.

**Comment by manics** [comment]
There are two issues to track the Helm 3 work:
- https://github.com/roboll/helmfile/issues/122#issuecomment-499310848
- https://github.com/roboll/helmfile/issues/668

**Comment by ivanilves** [comment]
Thank you @manics !

Closing this 😄
