### ISSUE TITLE
Timeout issue with Helm v3 mode

### ISSUE THREAD

**Issue by zen4ever** [roboll/helmfile#863]
in Helm v3 `--timeout` option in `upgrade` command has a type of duration, i.e. `60s` or `5m`

```
--timeout duration         time to wait for any individual Kubernetes operation (like Jobs for hooks) (default 5m0s)
```

helmfile expects it to be an integer.

So declaring `timeout: 60` doesn't work

```bash
in ./helmfile.yaml: failed processing release ingx: helm exited with status 1:
  Error: invalid argument "60" for "--timeout" flag: time: missing unit in duration 60
```

If I declare `timeout: 60s` helmfile fails with a different error

```bash
could not deduce `environment:` block, configuring only .Environment.Name. error: failed to read helmfile.yaml.part.0: reading document at index 1: yaml: unmarshal errors:
  line 10: cannot unmarshal !!str `60s` into int
in ./helmfile.yaml: failed to read helmfile.yaml: reading document at index 1: yaml: unmarshal errors:
  line 10: cannot unmarshal !!str `60s` into int
```

**Comment by mumoshu** [comment]
@zen4ever Hey! Thanks a lot for the detailed report. It does seem like a bug, which is being fixed via #864.

I'll push the next helmfile release with the fix soon. Would you mind testing it and report back if still don't work after that?

**Comment by zen4ever** [comment]
No problem, I can test it as soon as the new release is out

**Comment by mumoshu** [comment]
Thanks! v0.85.2 is out with the fix

**Comment by zen4ever** [comment]
It works with Helm v3 mode on.

**Comment by mumoshu** [comment]
Nice. Thanks for confirming ☺️

**Comment by Emixam23-FCMS** [comment]
So what's the concrete format? It's not clearly indicated in the doc at https://helm.sh/docs/helm/helm_upgrade/
