### ISSUE TITLE
"helmfile -f helmfile.d/ diff --detailed-exitcode" output incomplete

### ISSUE THREAD

**Issue by Pharb** [roboll/helmfile#874]
Hello,

I have this annoying behaviour with `helmfile diff --detailed-exitcode` which might be a bug:

`helmfile -f helmfile.d/ diff` shows the full diff of all changes in different Helmfiles within the Helmfile-directory as expected.

`helmfile -f helmfile.d/ diff --detailed-exitcode` exits early with

```
identified at least one change, exiting with non-zero exit code (detailed-exitcode parameter enabled)

in helmfile.d/0-common.yaml: failed processing release cluster-autoscaler: helm exited with status 2:
  Error: identified at least one change, exiting with non-zero exit code (detailed-exitcode parameter enabled)
  Error: plugin "diff" exited with error
```
stopping after the diff of the first Helmfile in the directory with changes.
Any diffs in further Helmfiles are then not processed.

I would guess the problem might be how the Helmfile-directory is treated? The exit should probably be deferred until all Helmfiles have been processed?

It would be great if you could clarify the expected behaviour here.

`helmfile version v0.85.2`

Thanks for all your work on Helmfile 👍

**Comment by mumoshu** [comment]
@Pharb Hey! Thanks for reporting.

> stopping after the diff of the first Helmfile in the directory with changes.

Good catch! I think this isn't an expected behavior. It should just match how it behaves without `--detailed-exitcode`

Labeling this as a bug.
