### ISSUE TITLE
env in 'set' does not interpolate unless quoted

### ISSUE THREAD

**Issue by maratoid** [roboll/helmfile#88]
this works:

```
set:
      - name: vault.replicas 
        value: "{{ env \"NUM_REPLICAS\" }}"
```

This does not:

```
set:
      - name: vault.replicas 
        value: {{ env "NUM_REPLICAS" }}
```

second example results in:

```
exec: helm upgrade --install vault ... --namespace mynamespace --values .../vault.yaml --values .../secrets.yaml.dec --set vault.replicas=
```

**Comment by cmeury** [comment]
`{` and `}` have a special meaning in the YAML format, see here: http://yaml.org/spec/1.2/spec.html#id2790832

So, your second example without quotes seems to be invalid YAML (checked with a [YAML validator](https://codebeautify.org/yaml-validator)).

**Comment by maratoid** [comment]
Fair enough. In that case the readme's should be fixed up. Also, first example should probably result in error (as described in the 'configuration syntax' section of the readme).

As is helmfile accepts the input and just sets the relevant key to nothing.

**Comment by cmeury** [comment]
> first example should probably result in error

I assume you mean the second example?

Yeah, agreed, that should be handled more robustly.

**Comment by maratoid** [comment]
yes, my apologies. edited.

**Comment by mumoshu** [comment]
@maratoid Thanks for the feedback and the report 👍 

Oh, I have never realized that the second example doesn't result in any error!
It should definitely error out.
Would you mind submitting a PR or an dedicated github issue for that?

**Comment by maratoid** [comment]
@mumoshu I'll try my best, thanks :)
