### ISSUE TITLE
Allow indicating runtime dependencies

### ISSUE THREAD

**Issue by entropitor** [roboll/helmfile#887]
E.g. the Kong helm chart introduces some new Custom Resource Definitions. I've built other charts on top of those CRDs but given I only want 1 kong instance but many charts declaring CRDs for this 1 kong instance, helmfile fails when I try to run it on a new cluster because it cannot find the CRD that one of the charts is declaring. It could be cool if we could say something like `depends_on: ['kong']` or `declares_crd: true`

**Comment by mumoshu** [comment]
@entropitor Hey! Thanks for trying Helmfile. I think we already have an issue for this: #715 

We'll have something like `depends_on`(perhaps `needs: ['namespace:release']`).

In the meantime, you can try sub-helmfiles as they are processed in the order of declaration.
