### ISSUE TITLE
--state-values-set for array or key with dot

### ISSUE THREAD

**Issue by eddycharly** [roboll/helmfile#899]
@mumoshu is this possible to pass a key containing a dot in its name to --state-values-set ?
also, does it support array access ?
i'm trying to do something like this :
```
    --state-values-set stacks.monitoring.prometheus.alertmanagerFiles.alertmanager\.yml.receivers[0].email_configs[0].auth_password=${MONITORING_SES_SECRET_KEY} \
    --state-values-set stacks.monitoring.prometheus.alertmanagerFiles.alertmanager\.yml.receivers[0].email_configs[0].auth_username=${MONITORING_SES_ACCESS_KEY} \
    --state-values-set stacks.monitoring.prometheus.alertmanagerFiles.alertmanager\.yml.receivers[0].email_configs[0].smarthost=${MONITORING_SES_ENDPOINT} \
```

**Comment by mumoshu** [comment]
@eddycharly Hey!

I believe that it isn't implemented. It would be a great feature request though!

**Comment by eddycharly** [comment]
@mumoshu I'm looking at implementing it.
From what is saw, helmfile is using urfave to parse the command line arguments.
Such a parsing does not seem to be natively supported by urfave, then i guess i could write a new flag parser for urfave.
Do you think it is the correct approach ?
Any hints on how to implement the feature welcome ;)

**Comment by mumoshu** [comment]
@eddycharly Hey! Yes, that sounds like a correct approach.

Regarding the implementation, you'd need to implement something to handle index access to arrays in https://github.com/roboll/helmfile/blob/4294a5de0604226e3434b19c850df3db95a8dacf/main.go#L486-L489

We currently support only paths that are composed of dot-separated nested keys there. The enhancement should include a recursive loop to descend into the keys one by one, and a if-else to handle it according to that it's a regular scalar access (e.g. `.afield`) or array index access(e.g. `ary[0]`)

**Comment by junpostrado** [comment]
--state-values-set stacks.monitoring.prometheus.alertmanagerFiles.alertmanager\.yml.receivers[0].email_configs[0].auth_password=${MONITORING_SES_SECRET_KEY} \
    --state-values-set stacks.monitoring.prometheus.alertmanagerFiles.alertmanager\.yml.receivers[0].email_configs[0].auth_username=${MONITORING_SES_ACCESS_KEY} \
    --state-values-set stacks.monitoring.prometheus.alertmanagerFiles.alertmanager\.yml.receivers[0].email_configs[0].smarthost=${MONITORING_SES_ENDPOINT} \

**Comment by tahmid11328** [comment]
Write a program where a number is given. At first find the alternate digit of a
given number from first digit, then from second digit, and multiply the digits, then you can get
two different number. 
(needs to be solved in emu 8086) someone please help

**Comment by rxell** [comment]
uncvar

**Comment by zhengboyan** [comment]
it souds diffult

**Comment by tahmid11328** [comment]
It is .... i have no idea how to do this

**Comment by eddycharly** [comment]
?
@mumoshu too much things to do lately but i didn't forget it, i will have a look to it this afternoon hopefully ;)

**Comment by qinwentian-cpu** [comment]
!
