### ISSUE TITLE
Charts successfully installed but helmfile apply returns errors.

### ISSUE THREAD

**Issue by mojochao** [roboll/helmfile#902]
I have a helmfile installing several charts.  When I apply them, they appear to be successfully installed, but `helmfile apply` command returns errors.

    identified at least one change, exiting with non-zero exit code (detailed-exitcode parameter enabled)

    Upgrading release=cluster-autoscaler, chart=stable/cluster-autoscaler
    Release "cluster-autoscaler" does not exist. Installing it now.

    in ./helmfile.yaml: in .helmfiles[0]: in helmfiles/cluster-utils.yaml: failed processing release cluster-autoscaler: helm exited with status 1:
      Error: unsupported format

There is nothing exotic in my chart values, and this used to work fine.  Things that I've observed:
- if I generate the manifests with `helmfile template` and I apply them with `kubectl` everything succeeds
- if I install with `helmfile apply` the charts seem to be installed and apps running properly, yet I see the error above

Is there any way to get more detailed information out of `helm` or `helmfile` to aid in diagnosis of the error?

My environment is:

    $ sw_vers
    ProductName:	Mac OS X
    ProductVersion:	10.14.6
    BuildVersion:	18G103

    $ helm version
    Client: &version.Version{SemVer:"v2.15.0", GitCommit:"c2440264ca6c078a06e088a838b0476d2fc14750", GitTreeState:"clean"}
    Server: &version.Version{SemVer:"v2.15.0", GitCommit:"c2440264ca6c078a06e088a838b0476d2fc14750", GitTreeState:"clean"}

    $ helmfile -v
    helmfile version v0.87.0

My cluster is an AWS EKS cluster running Kubernetes 1.14.  I am also running tiller-less helm.

Any help or suggestions is greatly appreciated.

Many thanks in advance!

**Comment by mojochao** [comment]
I tried this with another chart that requires no values, and observed that `helm` seems to operating correctly.

    # Define additional repositories containing charts to install.
    repositories:
    - name: traefik2
        url: git+https://github.com/containous/traefik-helm-chart@?ref=master

    # Define helm chart releases to install in this environment.
    releases:
    - chart: traefik2/traefik
        name: traefik
        namespace: kube-system

`helmfile apply` fails as indicated previously:

    identified at least one change, exiting with non-zero exit code (detailed-exitcode parameter enabled)

    Upgrading release=traefik, chart=traefik2/traefik
    Release "traefik" does not exist. Installing it now.

    in ./helmfile.yaml: in .helmfiles[0]: in helmfiles/cluster-utils.yaml: failed processing release traefik: helm exited with status 1:
    Error: unsupported format

Just installing with `helm` succeeds:

    $ helm install traefik2/traefik --name traefik --namespace kube-system
    NAME:   traefik
    LAST DEPLOYED: Mon Oct 21 18:15:51 2019
    NAMESPACE: kube-system
    STATUS: DEPLOYED

    RESOURCES:
    ==> v1/ClusterRole
    NAME     AGE
    traefik  2s

    ==> v1/ClusterRoleBinding
    NAME     AGE
    traefik  2s

    ==> v1/Deployment
    NAME     READY  UP-TO-DATE  AVAILABLE  AGE
    traefik  0/1    1           0          1s

    ==> v1/Pod(related)
    NAME                     READY  STATUS             RESTARTS  AGE
    traefik-b696d668b-x75r5  0/1    ContainerCreating  0         1s

    ==> v1/Service
    NAME               TYPE          CLUSTER-IP      EXTERNAL-IP       PORT(S)                     AGE
    traefik            LoadBalancer  10.100.250.206  aba39634bf458...  80:32137/TCP,443:31424/TCP  1s
    traefik-dashboard  ClusterIP     10.100.159.100  <none>            80/TCP                      1s

    ==> v1/ServiceAccount
    NAME     SECRETS  AGE
    traefik  1        2s

    ==> v1beta1/CustomResourceDefinition
    NAME                                  AGE
    ingressroutes.traefik.containo.us     2s
    ingressroutetcps.traefik.containo.us  2s
    middlewares.traefik.containo.us       2s
    tlsoptions.traefik.containo.us        2s

**Comment by mojochao** [comment]
Here is a minimal self-contained `helmfile` illustrating the problem:

    # minimal helmfile illustrating https://github.com/roboll/helmfile/issues/902
    helmDefaults:
    wait: true

    repositories:
    - name: traefik2
        url: git+https://github.com/containous/traefik-helm-chart@?ref=master

    releases:
    - chart: traefik2/traefik
        name: traefik
        namespace: kube-system

Error output as above:

    # minimal helmfile illustrating https://github.com/roboll/helmfile/issues/902
    helmDefaults:
    wait: true

    repositories:
    - name: traefik2
        url: git+https://github.com/containous/traefik-helm-chart@?ref=master

    releases:
    - chart: traefik2/traefik
        name: traefik
        namespace: kube-system


    $ helmfile apply
    ...

    Upgrading release=traefik, chart=traefik2/traefik
    Release "traefik" does not exist. Installing it now.

    in ./helmfile.yaml: failed processing release traefik: helm exited with status 1:
    Error: unsupported format

After failure it still seems to be deployed:

    $ helm list
    NAME   	REVISION	UPDATED                 	STATUS  	CHART        	APP VERSION	NAMESPACE
    traefik	1       	Mon Oct 21 19:10:37 2019	DEPLOYED	traefik-2.0.0	2.0.0      	kube-system

**Comment by Skaronator** [comment]
I've noticed the same issue. Turns out that downgrading Helm to v2.14.3 fixed this issue.

**Comment by mojochao** [comment]
So this is a bug, then?  I feel that helmfile should work with latest Helm release. Working around by pinning my Helm version to v2.14.3.  Thanks for the confirmation and workaround advice, @Skaronator.

**Comment by mumoshu** [comment]
@mojochao @Skaronator Thanks for reporting!

It seems like an upstream bug 🤔 

`helm upgrade --install`, which is used extensively by helmfile, seems to fail consistently on any chart with any flags:

```
$ helm215 upgrade --install myapp stable/mysql
Release "myapp" does not exist. Installing it now.
Error: unsupported format

$ echo $?
1
```

**Comment by mojochao** [comment]
Looks like a fix was pushed yesterday.  https://github.com/helm/helm/issues/6718

**Comment by Skaronator** [comment]
2.15.1 has been tagged but no changelog or bins yet.
https://github.com/helm/helm/releases

**Comment by mojochao** [comment]
Helm 2.15.1 has been released.  I've checked and this is no longer an issue. Closing.

**Comment by mumoshu** [comment]
Glad to hear it worked. Thanks for reporting ☺️
