### ISSUE TITLE
CircleCI job "deployment" might not work

### ISSUE THREAD

**Issue by cmeury** [roboll/helmfile#91]
In PR #81 we left out the `deployment` job in `.circleci/config.yml`. It is neither included in the `jobs` section nor is it contained in a [workflow](https://circleci.com/docs/2.0/workflows/). I suspect the command will currently not work. We need to test this and potentially correct this.

https://github.com/roboll/helmfile/blob/master/.circleci/config.yml#L76

**Comment by mumoshu** [comment]
@cmeury Yes. It must be ignored by CircleCI as unsupported according to [the CircleCI doc](https://circleci.com/docs/2.0/deployment-integrations/)!

**Comment by mumoshu** [comment]
@cmeury Submitted #100 for this.
