### ISSUE TITLE
JSON output

### ISSUE THREAD

**Issue by czuares** [roboll/helmfile#913]
We recently had a need to parse the output of `helmfile list`. It would be ideal if we could utilize an `--output json` flag (like `helm` allows) to return structured json output.

**Comment by osterman** [comment]
Just adding some context from [slack](https://slack.sweetops.com)

![image](https://user-images.githubusercontent.com/52489/73893583-f091bd80-482e-11ea-9531-d176138ef857.png)


Related ask.
