### ISSUE TITLE
Automatically enable Helm v3 mode

### ISSUE THREAD

**Issue by mumoshu** [roboll/helmfile#923]
Currently `HELMFILE_HELM3` must be set to a non-empty value to enable the v3 mode. It works but not intuitive. Can't we do better?

My quick idea is that Helmfile could run `helm version -c`(`-c` is the shorthand for `--client` which skips contacting Tiller for the version number. It's v2 only) to detect the major version of the helm binary being used?

That is, if `helm version -c` returns 0 it should be v2 and if 1 and the error message was `Error: unknown shorthand flag: 'c' in -c` it should be v3.

```
$ helm version -c
Client: &version.Version{SemVer:"v2.14.3", GitCommit:"0e7f3b6637f7af8fcfddb3d2941fcc7cbebb0085", GitTreeState:"clean"}
$ echo $?
0
$ helm3b5 version -c
Error: unknown shorthand flag: 'c' in -c
$ echo $?
```

**Comment by scottrigby** [comment]
Cross-posting: https://github.com/helm/helm/issues/6322

**Comment by drakedevel** [comment]
@mumoshu Helm 3.0 released today and supports `helm version -c` without complaint (via https://github.com/helm/helm/pull/6868), so this should be unblocked for a non-hacky solution:

```
$ helm version -c --short
v3.0.0+ge29ce2a
```

Let me know if you'd like me to submit a PR, I'd be happy to throw one together.

**Comment by mumoshu** [comment]
@drakedevel That's super helpful! Thanks for sharing.

I'd definitely appreciate your PR!

Implementation-wise, a gotcha is that we have multiple places to pass the mode detected by calling `helm version -c`. Code search for `isHelm3()` for more on that.
