### ISSUE TITLE
More control over log verbosity

### ISSUE THREAD

**Issue by manics** [roboll/helmfile#93]
Follow-up from https://github.com/roboll/helmfile/issues/79#issuecomment-378544353
The use case in that comment could be solved by defining and hiding secret variables, but @mumoshu suggested more control over logging such as `trace`, `debug`, `info`, `warn`, `error` would be useful.

For example, when creating or troubleshooting a helmfile having more verbose output is useful. In contrast if you're deploying a large production system with many charts you might prefer reduced output to summarise the deployment status of each chart.

At present there are two logging levels, normal which prints the helm command and all output, and `quiet` which hides everything including the output of helm.

**Comment by osterman** [comment]
Yes, this is an issue for me too. I need to pass `--quiet`, otherwise, all secrets are output in the logs due to the output of `exec: ....` with `--set` parameters.  But what I really want is to see the output from `helm` without the `exec`.  Thus, I support some sort of `--log-level` argument of which the `exec: ...` should be `debug`.

**Comment by manics** [comment]
I've looked into possible libraries for this. [glog](https://github.com/golang/glog) seems overly focussed on low-level logging, for example it defaults to logging to a file and there's no way to send logs to stdout, only stderr.

[go.uber.org/zap](https://github.com/uber-go/zap) looked more promising, you can configure stdout or stderr logs, and it provides an optional global logger `zap.S().Info(...)`. See https://github.com/manics/helmfile/commit/a515de458171757d866bdc7a3503664f8ddd2847 for my an initial example.

**Comment by manics** [comment]
@mumoshu in principle does using go.uber.org/zap sound OK to you? If so I'll do more investigation/coding.

**Comment by mumoshu** [comment]
@manics Sorry for the delayed response! Yes, I'm fine with any logger as long as it is "leveled", and I have no desire to introduce loggers with rich sets of outputs(like logrus). That being said, I'm fine with zap.
