### ISSUE TITLE
怎么开启 MAMP PRO 版本为5.6.37 的Redis扩展？

### ISSUE THREAD

**Issue by baiqiongyu** [roboll/helmfile#949]
![71D398C9-9C26-41EA-B8DB-F38D6E14C4CB](https://user-images.githubusercontent.com/43636784/68520835-13671100-02d6-11ea-89d9-60585ebc949a.png)
![E64D06B0-0C51-43FC-8FF7-AABF5D410DDC](https://user-images.githubusercontent.com/43636784/68520837-1cf07900-02d6-11ea-97b4-0658dce0098a.png)

**Comment by drakedevel** [comment]
@baiqiongyu You should contact MAMP support, this repository has nothing to do with MAMP (or Redis).
