### ISSUE TITLE
Add possibility to set helm executable in helm3 mode

### ISSUE THREAD

**Issue by pavdmyt** [roboll/helmfile#956]
I'm using both `helm2` and `helm3` for managing different environments. For production clusters `helm2` is used and we've started experimenting with `helm3` for our new clusters.

At my laptop I'm having `helm` pointing to _helm2_ binary and `helm3` pointing to _helm3_ binary. Running `helmfile` with `HELMFILE_HELM3="1"`, there are following errors:

```
$ helmfile -f cert-manager.yaml diff                                                                                                              
Adding repo jetstack https://charts.jetstack.io
"jetstack" has been added to your repositories

Updating repo
Hang tight while we grab the latest from your chart repositories...
...Successfully got an update from the "jetstack" chart repository
...Successfully got an update from the "stable" chart repository
Update Complete.

Comparing release=cert-manager, chart=jetstack/cert-manager
in ./cert-manager.yaml: 2 errors:
err 0: failed processing release cert-manager: helm exited with status 1:
  Error: could not find tiller
```

Under the hood `helmfile` executes commands using `helm` and it seems there is no way to specify which binary to use. Is it possible to add e.g. env variable to specify this?

I've fixed the issue by renaming `helm` binary to `helm2` and creating symlink: `helm -> helm3`. But it's not very convenient.

**Comment by mumoshu** [comment]
@pavdmyt Hey! Are you looking for the `--helm-binary` flag that exists today, or
anything else?

**Comment by pavdmyt** [comment]
@mumoshu this is exactly what I need 😃 

I've been searching through the codebase for appropriate env var not thinking about flag.

**Comment by mumoshu** [comment]
We need to do better job surfacing this feature. Anyways, thanks for using Helmfile ☺️
