### ISSUE TITLE
got error like "getting deployed release version failed:Failed to get the version for:xxx" when using helmfile sync with Helm3

### ISSUE THREAD

**Issue by hmwenchen** [roboll/helmfile#962]
Hi, 
I am trying to use the command "helmfile sync" with Helm3 to install my services, but failed. The command I use is as follows:
`HELMFILE_HELM3=1 /path/to/helmfile_linux_amd64 --log-level=debug --helm-binary=/usr/local/bin/helm sync`

The error messages are as follows:
`getting deployed release version failed:Failed to get the version for:zookeeper
Upgrading release=kafka, chart=../helm_charts/kafka
exec: /usr/local/bin/helm tiller run tiller-namespace -- /usr/local/bin/helm upgrade --install --reset-values kafka ../helm_charts/kafka --verify --wait --timeout 600s --force --recreate-pods --atomic --values /tmp/values635527329
exec: /usr/local/bin/helm tiller run tiller-namespace -- /usr/local/bin/helm upgrade --install --reset-values kafka ../helm_charts/kafka --verify --wait --timeout 600s --force --recreate-pods --atomic --values /tmp/values635527329: The Kubernetes package manager`

How should I use "helmfile sync" with Helm3 correctly?
Thank you!

**Comment by mumoshu** [comment]
@hmwenchen Hey! Seeing `/usr/local/bin/helm tiller run tiller-namespace -- `, aren't you running it with helm-tiller? Could you remove `tillerless: true` from your helmfile.yaml?

**Comment by mumoshu** [comment]
To be clear, helm-tiller is for helm 2 and it won't work with helm3.

**Comment by hmwenchen** [comment]
Yeah! It works after removing "tillerNamespace" and "tillerless" from "helmDefaults" of my helmfile.
Thanks a lot for quick response!
