### ISSUE TITLE
Proposal: Template values files

### ISSUE THREAD

**Issue by sstarcher** [roboll/helmfile#97]
To limit the need to duplicate values it would be helpful to be able to template the values files.

**Comment by osterman** [comment]
Also, just want to throw this out there: https://github.com/hairyhenderson/gomplate

`gomplate > sprig`

richer library of functions. pretty much everything sprig can do, but more! =)

**Comment by mumoshu** [comment]
@osterman Thx for the info! gomplate looks promising :)

Just to sync up with you, it looks like there is a momentum to let helmfile close to helm's spec/behavior.
sprig sounded a good idea at the time we introduced it in that regard, but practically saying there can be more options. 

That being said, I'm eager to providing options to use an alternative template engine like gomplate as long as it doesn't lock helmfile to single template engine, and the implementation is not so hard.

Actually, I prefer jsonnet as suggested in #92 [here](https://github.com/roboll/helmfile/issues/92#issuecomment-379231253) but it is attracted to no one 🤣 

WDYT? Any input is welcomed!

**Comment by sstarcher** [comment]
Overall I would tend to stick with sprig unless we supported both.

**Comment by mumoshu** [comment]
@sstarcher I was considering to support this simply like:

```yaml
releases:
- name: myrelease
   values:
   - myvalues.yaml
```

This configuration would just instruct helmfile to render a temporary yaml file from `./myvalues.yaml`. The extension can be anything. So, even if it is `.yaml`, it's considered a sprig template. To be extra clear, it can be a standard yaml if the yaml doesn't include any golang text/template expressions in it.

An alternative to the above is:

```yaml
releases:
- name: myrelease
   values:
   - template: myvalues.yaml.tmpl
```

This looks more explicit which I personally prefer, but I guess the momentum in helmfile community is not make it too explicit like that, similar to helm's own template(no .tmpl extension, no distinction between template vs regular yaml file).

WDYT?

**Comment by sstarcher** [comment]
I would transparently support it s in your first example.  Run the templates across all values files.

**Comment by mumoshu** [comment]
@sstarcher Thx. Sounds good. I've posted an enhanced example in https://github.com/roboll/helmfile/issues/119#issuecomment-384830608.

**Comment by mumoshu** [comment]
Just submitted #216 for this
