### ISSUE TITLE
feat: Allow more characters in release labels

### ISSUE THREAD

**Issue by bitsofinfo** [roboll/helmfile#970]
I have a release label

```
version: x.y.z
```

and helmfile cmd w/ `--selector whatever=dog,version=x.y.z`

```
Malformed label: version=x.y.z. Expected label in form k=v or k!=v in ...[mytemplate.yaml]...
```

Looking at:

https://github.com/roboll/helmfile/blob/c68fc5bc50ea80f5782381f1f4a1ce975ad98e06/pkg/state/release_filters.go#L51

Why are there any character restrictions on helmfile release selectors/labels anyway? They just are used to control what releases helmfile processes, and are not necessarily labels that end up in k8s so I don't see the need to comply with a specific character restriction format?

**Comment by mumoshu** [comment]
@bitsofinfo Good point! Yeah maybe we can loosen this restriction, assuming you won't use helmfile labels for propagating to k8s resources somehow.

But to be extra sure - why are you trying label releases with version numbers? Maybe we can focus on your specific use-case and the goal first, so that we may come up with a good solution anyway.

**Comment by bitsofinfo** [comment]
thats just one use case i have, a helm release per distinct app artifact version, they rotate through quite frequently, the helmfile can generate many releases and I have an upstream deployment tool that invokes helmfile, where I only want to force helmfile to process one of N releases and not all.

**Comment by sshishov** [comment]
Hello here, our organization is using labels with prefixes like `org.com/label-name: value`.
Therefore we just cannot reference this label.

**Comment by adamski52** [comment]
Our organization is also using labels with prefixes to help prevent collisions on generic terms likely to be in different charts, like "name".  We use the same reverse domain notation as sshishov and get the same error about malformed label.

Easy way to test/reproduce is with something like `helmfile -l com.example/name=something status`

If we need to change the format on our end from dot.notation to camelCase or something, I suppose that would work too but gets a little messy.

**Comment by sshishov** [comment]
@mumoshu I can try to fix the issue, if you want and create PR. Please let me know as I am not professional in `go` but you added label that it is good issue for newcomers 🤣

**Comment by mumoshu** [comment]
@sshishov Yes, I'd appreciate it if you could do so!
