### ISSUE TITLE
Fully support helm 3 in docker image (helm diff)

### ISSUE THREAD

**Issue by entropitor** [roboll/helmfile#980]
~Is it possible to add helm 3 to the docker image of helmfile? So we can just use the helmfile docker image in CI/CD without needing to install helm3.~

Things to do:
- [x] Update helm diff plugin to version `v3.0.0-rc.7` to support helmfile diff

**Comment by entropitor** [comment]
Ah, I just saw there is a `helm3-v0.92.1` tag :D Thanks! Sorry for the ticket

**Comment by entropitor** [comment]
There is still an error though when using `helm diff`, I'm guessing the wrong version is installed. There is a rc that's available for helm 3 as the one from master fails

**Comment by mumoshu** [comment]
@entropitor Hi! Which error did you see exactly?

**Comment by jurgenweber** [comment]
I am seeing this:
```
$ helm plugin list
NAME   	VERSION   	DESCRIPTION
diff   	3.0.0-rc.7	Preview helm upgrade changes as a diff
secrets	2.0.2     	This plugin provides secrets values encryption for Helm charts secure storing
$ helmfile --version
helmfile version v0.92.1
$ helm version
version.BuildInfo{Version:"v3.0.0", GitCommit:"e29ce2a54e96cd02ccfce88bee4f58bb6e2a28b6", GitTreeState:"clean", GoVersion:"go1.13.4"}
```
in ./helmfile.yaml: in .helmfiles[2]: in helmfile/bases.yaml: 4 errors:
err 0: failed processing release ecr-access: helm exited with status 1:
  Error: Couldn't load repositories file (repository/repositories.yaml).
  You might need to run `helm init` (or `helm init --client-only` if tiller is already installed)
  Error: plugin "diff" exited with error
```

**Comment by mumoshu** [comment]
@jurgenweber Thanks!

Could you please remove `tillerless: true` from the config? It forces `helm-tiller` to be used, which in turn calls helm 2. `You might need to run `helm init` is coming from helm 2.

**Comment by jurgenweber** [comment]
I removed all traces of helm2 from my machine, as I don't need it.
I removed `tillerless: true` but I still get the same error with diff.

```
in ./helmfile.yaml: in .helmfiles[2]: in helmfile/bases.yaml: 6 errors:
err 0: failed processing release ecr-access: helm exited with status 1:
  Error: Couldn't load repositories file (repository/repositories.yaml).
  You might need to run `helm init` (or `helm init --client-only` if tiller is already installed)
  Error: plugin "diff" exited with error
```

I can run a sync no problems but this does not seem to be idempotent. Once it is run once, some charts fail with immutable object errors.

**Comment by mumoshu** [comment]
@jurgenweber Thanks! Ohhh... I thought helm-diff `3.0.0-rc.7` does support helm v3. We actually have an integration test to verify that on CircleCI. But maybe we're missing something here?

If you reinstall `helm-diff` and it still doesn't work, defintely something is broken...

**Comment by jurgenweber** [comment]
it looks to me like it does; https://github.com/databus23/helm-diff/releases.
I `rm -rf ~/.helm` and reinstalled it all from scratch.

**Comment by mumoshu** [comment]
@jurgenweber Thanks for confirming. Could you share full helmfile logs with `helmfile --log-level=debug` via a DM in Slack?

**Comment by jurgenweber** [comment]
with a little talking on slack we worked out that
> you had plugin.yaml that cloned from 3.0.0-rc.7, but the latest 2.x binary installed from install-binary.sh contained in 3.0.0-rc.7...

the solution was 
```
helm plugin uninstall diff
helm plugin install https://github.com/databus23/helm-diff --version v3.0.0-rc.7
```

**Comment by entropitor** [comment]
I also had to apply the solution above. Otherwise I get an error which also happens when the v3.0.0 branch is not installed 

```
...
Couldn't load repositories file (repository/repositories.yaml).
You might need to run `helm init` (or `helm init --client-only` if tiller is already installed)

context deadline exceeded

context deadline exceeded

in ./helmfile.yaml: 3 errors:
err 0: failed processing release ingress-proxy: helm exited with status 1:
  Error: Couldn't load repositories file (repository/repositories.yaml).
  You might need to run `helm init` (or `helm init --client-only` if tiller is already installed)
  Error: plugin "diff" exited with error
err 1: failed processing release my-release: helm exited with status 1:
  Error: context deadline exceeded
  Error: plugin "diff" exited with error
err 2: failed processing release my-other-release: helm exited with status 1:
  Error: context deadline exceeded
  Error: plugin "diff" exited with error
make: *** [Makefile:61: diff] Error 1
Exited with code 2
```

**Comment by mumoshu** [comment]
Thanks everyone for your support. This should now be resolved via #984 thanks to @shikhar7 :tada: Please try v0.92.2 which is being available via quay soon!

**Comment by entropitor** [comment]
It's working. Thanks!

**Comment by tinyzimmer** [comment]
This issue appears to have come back on the latest helmfile image

**Comment by mumoshu** [comment]
@tinyzimmer Could you share me the exact steps you've done to reproduce it? Thanks!

**Comment by tinyzimmer** [comment]
I just realized it was because I wasn't running as root. And the plugins are only installed for root in the image.

**Comment by mumoshu** [comment]
@tinyzimmer Thanks! That makes sense. Maybe we'd better have a documentation for non-root usage(with the current image, the only way would be to installing the plugin as the non-root user before running helmfile), or maybe have an another docker image with non-root user as the default? WDYT?

**Comment by tinyzimmer** [comment]
Thats a good question. I'm wondering almost if it warrants a custom entry point, but that seems overly complicated. I really wish diff was a built-in to helm :stuck_out_tongue: . 

I dunno how you would reliably have a non-root image. In my use case I usually am passing it from a Makefile with something like `--user $(shell id -u)`. I don't know off hand what that turns `HOME` into by default, but that's another thing you have to take into account. I usually overwrite that too when I'm doing this. 

Another idea would be a less complicated entrypoint if helm would let you dynamically set that plugin path via a global file or something, but that does not appear to be the case either.

**Comment by mumoshu** [comment]
> diff was a built-in to helm 😛 

@tinyzimmer Sounds great 😄 I haven't realized about that benefit of merging diff into helm core. I can suggest adding your 👍 to https://github.com/databus23/helm-diff/issues/211 about that

> Another idea would be a less complicated entrypoint if helm would let you dynamically set that plugin path via a global file or something, but that does not appear to be the case either.

I think this is technically possible using custom entrypoint, or a wrapper around helm. Probably the wrapper could read $HOME and copy the prepopulated helm-diff plugin installation directory to the actual plugins path under current $HOME, or just run `helm plugin install` on demand.
