### ISSUE TITLE
--concurrency=1 is running in alphabetically order in latest version of helmfile.

### ISSUE THREAD

**Issue by shikhar7** [roboll/helmfile#988]
Earliar --concurrency=1 used to run charts sequentially in the order defined.Because of that i have added hooks to the various charts, and as of now various charts are running alphabetically so now the hook one is running one and others are running afterwards.Moreover i saw `needs` tag in helmfile but that also is not suitable as that wants the dependency and our structure is such that we will ask user what to deploy and will deploy according based on the hierarchy.

**Comment by shikhar7** [comment]
#784

**Comment by mumoshu** [comment]
@shikhar7 Thanks! This should be fixed in v0.93.1.
