### ISSUE TITLE
Label syntax for missing values

### ISSUE THREAD

**Issue by sstarcher** [roboll/helmfile#99]
Lets say I have 10 charts.  1 chart has a label `stage: pre` and another has the label `stage: post`

When I do
`helmfile -l stage=pre sync`  I get the expected 1 chart from pre and the same for post.

When I do
`helmfile -l stage!=pre,stage!=post sync` I would expect to get the other 8 charts, but I get 0 charts as the charts without the label are not selectable.

When I do 
`helmfile -l stage!='' sync` I would expect to also get the other 8 charts, but I get an error.
```
2018/04/07 16:45:35 Malformed label: stage!=. Expected label in form k=v or k!=v
```

**Comment by mumoshu** [comment]
@sstarcher Good point! Your expectation sounds very valid. It would also follow the same semantics as `kubectl`, which is good.

**Comment by sstarcher** [comment]
This seems to be working fine in master.
