### ISSUE TITLE
Why would a successfully installed chart release be ignored by a subsequent helmfile diff command?

### ISSUE THREAD

**Issue by mojochao** [roboll/helmfile#997]
I have a situation where one chart, prometheus-operator, is successfully installed with `helmfile apply`, yet when a `helmfile diff` command is executed after the install it presents a diff showing what appears at first glance to be all the resources that were previously installed.  I imagine that `helmfile` defers to the installed `helm-diff` plugin and that it is, for some reason, returning new versions of the previously installed manifests.  For all of my other chart installs, they properly report no diff needing to be applied.

This started happening during migration to helm 3 use.  I never saw this happen when using helm 2.  My environment is:

```shell
$ helm version
version.BuildInfo{Version:"v3.0.0", GitCommit:"e29ce2a54e96cd02ccfce88bee4f58bb6e2a28b6", GitTreeState:"clean", GoVersion:"go1.13.4"}

$ helm plugin list
NAME    	VERSION   	DESCRIPTION
2to3    	0.2.0     	migrate and cleanup Helm v2 configuration and releases in-place to Helm v3
diff    	3.0.0-rc.7	Preview helm upgrade changes as a diff
helm-git	0.5.0     	Get non-packaged Charts directly from Git.
registry	0.7.0     	This plugin provides app-registry client to Helm.
        	          	usage:
        	          	  $ helm registr...

$ helmfile --version
helmfile version v0.93.1

$ uname -a
Darwin aus-allengooch-osx 18.7.0 Darwin Kernel Version 18.7.0: Sat Oct 12 00:02:19 PDT 2019; root:xnu-4903.278.12~1/RELEASE_X86_64 x86_64
```

If the problem is strictly within the `helm-diff` plugin, I'll go ahead and add an issue in its repo.  Is there any possibility of it also being caused, at least in part, by `helm` or `helmfile` commands?

Many thanks!

**Comment by mumoshu** [comment]
Hey! Thanks for reporting.

> Is there any possibility of it also being caused, at least in part, by helm or helmfile commands?

I beieve, no.
Are you able to reproduce it by running `helm diff` alone?

**Comment by mojochao** [comment]
I ran a `helm -n monitoring diff upgrade prometheus-operator stable/prometheus-operator --reuse-values` command and got the same diff output, so the problem seems to be there.  I assume helmfile is passing in the namespace option necessary now that releases are namespace scoped with helm 3.  

I'll go ahead and add an issue in the helm-diff repo.
